- crypto/bls.go
- crypto/bls_test.go
- crypto/ecdsa.go
- crypto/sign_test_utils.go
Check the length of signature in ECDSA in double the length of the group order.
> Crypto: check ECDSA signature length in verification

- network/gossip/libp2p/connManager.go
- network/gossip/libp2p/discovery.go
- network/gossip/libp2p/libp2pNode.go
- network/gossip/libp2p/libp2pNode_test.go
This PR adds the ability to disconnect from a peer by closing the connection. This is needed for evicting nodes and when a collection node moves over from one cluster to another thus changing it's peers.
> adding RemovePeer method to libp2pNode to disconnect from a node

- README.md
I ran into the following error when switching repos. 
```
ERRO Running error: buildssa: analysis skipped: errors in package: [/Users/leo/onflow-go/model/encodable/keys.go:11:2: could not import github.com/onflow/flow-go/crypto (/Users/leo/onflow-go/crypto/bls.go:31:8: could not import C (cgo preprocessing failed)) /Users/leo/onflow-go/model/encodable/keys.go:24:26: pub.Encode undefined (type NetworkPubKey has no field or method Encode) /Users/leo/onflow-go/model/encodable/keys.go:52:27: priv.Encode undefined (type NetworkPrivKey has no field or method Encode) /Users/leo/onflow-go/model/encodable/keys.go:78:26: pub.Encode undefined (type StakingPubKey has no field or method Encode) /Users/leo/onflow-go/model/encodable/keys.go:106:27: priv.Encode undefined (type StakingPrivKey has no field …
```
> update README to force build relic

- model/flow/account_encoder.go
- model/flow/account_encoder_test.go
After the most recent spork, account keys are stored with a new `Revoked` field that indicates whether the key has been removed from the account. 
The problem is, any account keys stored _before the spork_ do not include a `Revoked` value in their RLP-encoded representation. The RLP decoder throws an error because it cannot read a field that does not exist.
For context, this bug has currently stalled testnet 😬 
@Kay-Zee and I discussed a few options, but since we are likely to refactor account keys in the near future to be stored as Cadence resources, we didn't want to over-engineer a solution.
This solution implements an optimistic decoding that first tries to decode with the `Revoked` field, then tries again without the field (legacy format). Whenever a legacy account key is used as a …
> Update account key decoder to tolerate keys stored without a "Revoked" field

- engine/common/rpc/convert/convert.go
- engine/common/rpc/convert/convert_test.go
Noticed the `Revoked` field wasn't being pass to the client. Found that it was missing from one of the conversion steps.
Added it, and added a test, which explicitly tests the conversion and propagation of the Revoked field
> Propagate Revoked

- cmd/bootstrap/README.md
- cmd/bootstrap/cmd/constraints.go
- cmd/bootstrap/example_files/node-config.json
This PR some documentation/example updates for bootstrapping, and fixes a bug in the Byzantine constraint checking during the bootstrap process.
* update `README` example command to include new required flag and add a missing `\`
* update example `node-config.json` file to be compatible with the command in the `README`
* fix a bug in the total collector count, where a cluster count was used instead of the total count
> Bootstrapping bug fix and documentation update

- cmd/bootstrap/run/result.go
- cmd/bootstrap/run/seal.go
- engine/consensus/matching/engine.go
- engine/execution/execution_test.go
- engine/execution/ingestion/engine.go
- engine/execution/provider/engine.go
- engine/verification/match/engine.go
- engine/verification/test/helper.go
- engine/verification/utils/fixtures.go
- integration/tests/common/receipt_state.go
- integration/tests/common/testnet_state_tracker.go
- integration/tests/consensus/sealing_test.go
- integration/tests/execution/chunk_data_pack_test.go
- integration/tests/execution/failing_tx_reverted_test.go
- integration/tests/execution/state_sync_test.go
- model/chunks/chunks.go
- model/flow/executionResult.go
- state/protocol/badger/mutator_test.go
- utils/unittest/fixtures.go
- Refactor `FinalStateCommit` to method to return last chunk's `EndState`
- Added check for empty chunks in `ExecutionResult.FinalStateCommit()`
- Fixed tests and captures unhappy path 
The `FinalStateCommit` method in `ExecutionResult` now takes the following signature
```go
// FinalStateCommitment gets the final state of the result and returns false
// if the number of chunks is 0 (used as a sanity check)
func (er ExecutionResult) FinalStateCommitment() (StateCommitment, bool) {
if er.Chunks.Len() == 0 {
return nil, false
}
return er.Chunks[er.Chunks.Len()-1].EndState, true
}
```
> Refactor FinalStateCommit in Execution Result

- cmd/collection/main.go
- cmd/consensus/main.go
- cmd/scaffold.go
- consensus/integration/nodes_test.go
- engine/collection/epochmgr/factories/builder.go
- engine/collection/epochmgr/factories/cluster_state.go
- engine/testutil/nodes.go
- integration/tests/collection/suite_test.go
- module/builder/collection/builder.go
- module/builder/collection/builder_test.go
- module/builder/consensus/builder.go
- module/builder/consensus/builder_test.go
- module/finalizer/collection/finalizer_test.go
- module/trace/constants.go
- state/cluster/badger/mutator.go
- state/cluster/badger/mutator_test.go
- state/cluster/badger/snapshot_test.go
- state/cluster/badger/state.go
- state/protocol/badger/mutator.go
- state/protocol/badger/mutator_test.go
- state/protocol/badger/state.go
- state/protocol/util/testing.go
Adds tracing to the following methods:
* `BuildOn` for consensus node
* `mutator.Extend` (for protocol state and cluster state)
* `mutator.HeaderExtend`
* `mutator.Finalize`
> Add tracing to protocol state and consensus block builder

- integration/localnet/Makefile
- integration/localnet/docker-compose.logs.yml
- integration/localnet/docker-compose.metrics.yml
The default integration localnet starts containers for log search, for instance elastic search, grafana etc.
Those containers use a lot of machine resource, and might impact the real performance of the nodes that we wanted to test.
Making them option to start when running `make start` to start the localnet.
Now the localnet will only run the nodes and metrics.
> Run localnet without running log search

- engine/collection/proposal/engine.go
- engine/consensus/compliance/engine.go
When we get these pending child errors, they often form such deep trees that the actual root cause gets omitted in logs. This flattens out the multierror so that only root cause errors are included.
> Flatten errors when processing pending children

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Fixes dapperlabs/flow-go#4894
[Cadence v0.9.2](https://github.com/onflow/cadence/releases/tag/v0.9.2) now panics with a dedicated error for out-of-bounds array accesses. Previously it relied on Go's bounds check, i.e. the error was a Go runtime error.
Non-Go runtime errors are bubbled to the host environment, as they indicate an implementation error, non-Go (Cadence) errors are returned as errors: https://github.com/onflow/cadence/blob/0a889feb15fb738b83924d372677cf8720cb8706/runtime/interpreter/interpreter.go#L855-L870
This means that nothing else needs to be done in flow-go, other than updating to the latest version.
> Update to Cadence v0.9.2

- cmd/execution/main.go
- cmd/scaffold.go
- cmd/verification/main.go
This was already the case, but was being done manually before each Spork.
That was error prone, so adding into code.
> Remove Testnet  Restrictions

- network/gossip/libp2p/network.go
I'm seeing a lot of logs like this that doesn't seem to be useful.
```
{"level":"debug","node_role":"execution","node_id":"11597a5379b82c0e223f0e21753ed22cdc07f3f82c7f9a714ece8d549d6821d2","time":"2020-10-14T17:53:19Z","message":"message successfully unicasted"}
```
The application will probably log when a message has been successfully unicasted, and is able to log more details as it knows the structure of the message. However, the network layer doesn't have as much context as application layer, having logs there doesn't seem to be useful.
We could just remove it.
> [Network] Remove network unicast log

- state/protocol/events/distributor.go
Reference: https://github.com/dapperlabs/flow-go/issues/4931
Protocol events distributor was incorrectly deferring `Lock` rather than `Unlock`.
> Fix deadlock in protocol state events

- engine/execution/ingestion/engine.go
Fix https://github.com/dapperlabs/flow-go/issues/4962
One of the fatal errors in execution ingestion engine was not actually a fatal error. This PR remove that non-fatal error. 
For the fatal error, which is an actual fatal error, I added more comment to explain the case.
> [Execution] Remove non-fatal error

- integration/tests/collection/tx_ingress_test.go
The test assumed that transaction properties were validated in a particular order, which changed as part of implementing epochs. This commit changes the test's assertion to be less specific (merely that an error occurred), since the actual error that is returned is not directly related to the failure condition we are testing, it is instead a side effect of the failure condition we are testing.
> Fix error equality checking in collector test

- engine/execution/ingestion/engine.go
- storage/badger/receipts.go
- storage/badger/receipts_test.go
- storage/badger/results.go
- storage/badger/results_test.go
[Execution node will re-execute a block on startup](https://github.com/onflow/flow-go/blob/master/engine/execution/ingestion/engine.go#L305-L308), however the storage layer will reject the call to store the execution results again, which will cause the block execution to halt on startup.
The behavior I've seen on testnet is that after a restart, only one block is executed. That's because the storage layer hit an `KeyAlreadyExist` error and cause the ingestion engine stop from executing the next block.
Logs:
```
Nov 05 15:33:41 execution-002 docker[56349]: {"level":"error","node_role":"execution","node_id":"639d905053cc36aa80a0c249ae659db8ec58946f1c6a0b2d9b67195646a7f6df","engine":"ingestion","error":"could not save execution results: could not persist execution result: could not store …
```
> [Execution] allow re-executing blocks

- cmd/execution/main.go
Since state syncing is optional, disabling by default for now.
> disable state syncing

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
There was [a regression in v0.10.0](https://github.com/onflow/cadence/issues/445). 
Update to v0.10.1 which [fixes it](https://github.com/onflow/cadence/pull/446).
> Update to Cadence v0.10.1

- cmd/bootstrap/run/key.go
- cmd/bootstrap/run/staking_transaction.go
- cmd/util/cmd/remove-execution-results/cmd.go
- engine/execution/state/mock/execution_state.go
- engine/execution/state/state.go
- storage/badger/commits.go
- storage/badger/commits_test.go
- storage/badger/operation/commits.go
- storage/badger/operation/modifiers.go
- storage/badger/operation/receipts.go
- storage/badger/operation/results.go
- storage/badger/operation/transaction_results.go
- storage/badger/receipts.go
- storage/badger/receipts_test.go
- storage/badger/results.go
- storage/badger/results_test.go
- storage/badger/transaction_results.go
- storage/badger/transaction_results_test.go
- storage/commits.go
- storage/mock/commits.go
- storage/mock/execution_receipts.go
- storage/mock/execution_results.go
- storage/mock/transaction_results.go
- storage/mocks/storage.go
- storage/receipts.go
- storage/results.go
- storage/transaction_results.go
For #https://github.com/dapperlabs/flow-go/issues/5023
This PR added a tool for remove execution results. It's branched out from v0.10.3, and will NOT merge to `master`, since the remove methods are not safe.
Tests are added
> cmd remove execution results

- engine/testutil/mock/nodes.go
The following test case has been flakey. 
```
--- FAIL: TestExecutionStateSyncMultipleExecutionNodes (10.36s)
hub.go:57: 
Error Trace:	hub.go:57
hub.go:46
execution_test.go:349
Error:      	Condition never satisfied
Test:       	TestExecutionStateSyncMultipleExecutionNodes
FAIL
```
It's because we didn't wait until the engine is ready and send the block too early
> fix execution tests

- module/builder/collection/config.go
[We've increased the limit on transaction size](https://github.com/onflow/flow-go/commit/c88e4e950cc341536d88928c17c9009582a0912b#diff-0b6b63ad3693b4a15a89df18ea07d931dcef6ef167cd785ed6bf4dfb6dde87afR23), we also need to increase the size of the collection, otherwise, the tx would still be oversized to be included in a collection.
> increase collection size

- .github/workflows/ci.yml
GitHub Actions [deprecated the use of `set-env`](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) a few months ago and it seems like they have fully removed support in the last few days. This PR updates  `ssh-agent` and `golangci-lint` to versions that have a workaround for this.
> update ssh-agent step to fix deprecated set-env

- engine/consensus/dkg/dkg_controller.go
- engine/consensus/dkg/dkg_controller_test.go
- engine/consensus/dkg/dkg_message.go
- engine/consensus/dkg/errors.go
- engine/consensus/dkg/state.go
Implement DKG controller to start the DKG protocol, listen for incoming messages in the background, and trigger transitions from one phase to another. 
Incoming DKG messages (private and public) are received through a go channel. The responsibility of populating the channel with valid messages is left to the consumer.
Transitions from one phase to another are triggered by function calls, and it is left to the consumer to implement a mechansism to decide when to transition.
> Add DKG controller

- cmd/bootstrap/cmd/keygen.go
PR fixes the default output file name of the `keygen` command
> Fix `keygen` command default output file name

- cmd/bootstrap/cmd/util.go
This PR fixes a bug in bootstrapping script when `--partner-dir` is specified with a folder that doesn't exists, it hits the following panic error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1092bff]
```
> Check dir exists before checking files exists

- cmd/bootstrap/cmd/keygen.go
- cmd/bootstrap/cmd/keys.go
- model/bootstrap/filenames.go
This UP updates the keygen command line to save the public info for the generated node infos.
The public info will be the input for the sporking script
> save node pub info when running keygen

- README.md
- model/encodable/keys.go
- model/encodable/keys_test.go
This PR changes the key encoding to be `hex` instead of the `base64`, which is the default for `[]byte`
Before this PR, the key generation will produce networking key and staking keys in base64 , for instance:
```
go run -tags relic ./cmd/bootstrap key --address "example.com:3569" --role "consensus" -o ./bootstrap/partner-node-infos
```
will produce :
Note the NetworkPubKey and StakingPubKey are both in `base64`
```
{
"Role": "consensus",
"Address": "example.com:3569",
"NodeID": "f1c2f6590da364793f8515712855dae00b135d53de646a4f17f381b28a0cbd2b",
"Stake": 0,
"NetworkPubKey": "1b24gbD5zmVgj7r1texoptzoaMZSw1iixRZsvByShLIzyEzKvJP5seTr5U9xF4q7HLrNduc0QaVCqTYsZsSWmQ==",
"StakingPubKey": "l6Xy4gEisi+kBSocoNdt1P1a+mdzLkOLPS6kXGYDFDFIw24bhBZYOIIz+tZ/QmBxByyByHS0ZurB3SjwOplBz7CVEtm5Fwx4Sk2l16s7izGSE …
```
> Change the key encoding from base64 to hex

- cmd/util/ledger/migrations/multiple_contract_migration.go
- cmd/util/ledger/migrations/multiple_contract_migration_test.go
Cadence optimizes dictionaries where the value type is a resource: In this case, the values are not stored in the dictionary value, but in separate registers.
As the state migration for multiple contracts per account migrates contract values, we also must migrate potentially deferred registers of the contract value.
> Migrate deferred values of contract values

- model/flow/incorporated_result.go
This PR addresses issue [#5067](https://github.com/dapperlabs/flow-go/issues/5067)
> Add locks around aggregatedSignatures in IncorporatedResult

- consensus/hotstuff/committees/consensus_committee.go
- consensus/hotstuff/committees/leader/leader_selection.go
This PR addresses a TODO from https://github.com/onflow/flow-go/pull/157 to use `uint16` rather than `int` for storing leader indices. Saves either 50% (for 32-bit) or 75% (for 64-bit) of memory usage used by pre-computed leader selection.
> Use 16-bit leader indices

- consensus/hotstuff/committees/consensus_committee.go
- consensus/hotstuff/committees/consensus_committee_test.go
- consensus/hotstuff/committees/leader/leader_selection.go
- consensus/hotstuff/committees/leader/leader_selection_test.go
This PR addresses a TODO from https://github.com/onflow/flow-go/pull/157 to remove old epochs such that we only ever store at most 2 epochs worth of leader selection.
> Remove old epochs leader selection from memory

- engine/consensus/matching/engine_test.go
Mocks out the Assigner before adding results to the mempool mock to guarantee the Assigner mock is ready before it is called by the engine.
I believe there was a race condition here where the engine could call `sealableResults` after the result was added to the mempool but before the `Assigner` was mocked out, causing https://github.com/dapperlabs/flow-go/issues/5107. 
Like @arrivets I haven't been able to reproduce this issue locally (only on CI), so have not confirmed this fix.
> Re-order mocking of subgraph fixtures in matching engine

- access/validator.go
- cmd/collection/main.go
- engine/collection/ingest/engine_test.go
- module/builder/collection/config.go
This PR 
- allows any limit for transactions with service account as payer 
- increase the collection total gas limit to 10M from 1M
> V0.12 Patch increase gas limit for service account txs

- fvm/state/accounts.go
- fvm/state/accounts_test.go
- Don't check existence of ledger key by comparing with `nil`
- Remove unnecessary check 
- Reuse `GetPublicKeyCount` in `GetPublicKeys`
- Add tests. Check both register values, an allocated byte slice `[]byte{}`, and `nil`
> Fix accounts

- integration/testnet/container.go
This PR addresses a bug with the integration tests, whereby they were using the wrong docker images: https://github.com/dapperlabs/flow-go/issues/5117
> Change default registry in testnet container.go

- cmd/execution/main.go
- engine/execution/rpc/engine.go
This PR adds a `scripts-enabled` flag to the execution node that can be toggled to disabled calls to the `ExecuteScriptAtBlockID` and `GetAccountAtBlockID` RPC methods.
> Add flag to disable script executions on EN

- engine/consensus/matching/engine.go
- integration/testnet/container.go
- model/flow/incorporated_result.go
- model/flow/incorporated_result_test.go
- module/builder/consensus/builder.go
- module/builder/consensus/builder_test.go
- module/trace/constants.go
- module/validation/receipt_validator_test.go
- state/protocol/badger/mutator.go
- state/protocol/badger/mutator_test.go
- state/protocol/badger/state.go
- utils/unittest/seals.go
Linked to issues [5085](https://github.com/dapperlabs/flow-go/issues/5085) and [5126](https://github.com/dapperlabs/flow-go/issues/5126)
* Builder: test excluding receipts for blocks that have seal in fork in
finalized or pending blocks
* Builder: test including receipts for blocks that have seal in a separate fork
* Builder: test maxSealLimit
* Builder: test excluding seals for blocks that already have seals on the fork
* Mutator: test rejecting duplicate receipts within payload
* Mutator: test inserting a receipt for a block that is sealed on another fork
> Additional tests for phase 2

- cmd/util/cmd/remove-execution-fork/cmd/execution-fork.go
- cmd/util/cmd/remove-execution-fork/cmd/root.go
- cmd/util/cmd/remove-execution-fork/main.go
v0.13 will introduce [the change to stop the consensus node if it detects conflicting seals](https://github.com/onflow/flow-go/pull/178)
In order to recover, we need the tool to remove the conflicting seals. 
This PR implements the tool, I called it `remove-execution-fork`.
> add tool to remove execution fork

- fvm/state/accounts.go
- fvm/transaction.go
This PR
- Renames the ERROR to something more distinct as Stackdriver's text query is not case sensitive. 
- Extends the current check to be about any tx check fails. 
- Adds some temporary logs for when we fetch code for a contract. (this will help us track down to see if this is an error with ledger or cadence)
> extend the safetyErrorCheck on fvm

- engine/execution/ingestion/engine.go
Looking at the network metrics, it seems the execution halt problem is not because of missing collection, the root cause is that the execution node is still broadcasting those old results, which causes the verification node to respond back with a chunk data request. And the network queue quickly filled up by these requests, and grew to a point that no more collection can be forwarded to the ingestion engine, and case the execution to halt. 
This PR changes to not broadcast result for sealed blocks, since the block has already been sealed, there is no value in broadcasting it.
> [Execution] Not broadcast sealed ER

- integration/tests/execution/state_sync_test.go
ref: https://github.com/dapperlabs/flow-go/issues/5131
State sync will be disabled by: https://github.com/onflow/flow-go/pull/240 
And these tests are flakey, so no need to run for now.
> Disable state sync test for now

- cmd/Dockerfile
A recent look at https://github.com/GoogleContainerTools/distroless shows they are now recommending `distroless/base-debian10`. This should come with security updates, with minimal change.
> Upgrade to Debian 10 - Buster

- cmd/Dockerfile
Following https://github.com/golang/go/issues/30310#issuecomment-471669125, decided to use `netgo` which should resolve the docker 20 issues.
> Docker 20 compatibility

- fvm/env.go
1. Scripts may attempt to emit events from scripts. This currently causes a crash, because the current implementation of `EmitEvent` assumes a transaction environment exists. Instead, disable event emission from scripts by returning an error
2. Improve the error returns from the FVM host environment, and make sure all errors that are caused by unavailability are user errors (i.e. don't panic, but return an error)
> Disable event emission for non-transactions and improve FVM errors

- model/flow/epoch.go
- model/flow/service_event.go
- model/flow/service_event_test.go
- state/protocol/badger/state.go
- state/protocol/badger/state_test.go
- Fixed a bug that causes the node unable to restart
- Added test case to verify a bootstrapped protocol state can be opened again (see `TestBootstrapOpen`)
> Fix Node Restart

- fvm/transaction.go
- fvm/transaction_test.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Improve the error safety check in the FVM: When a deployed contract is imported and it fails to parse or check, then log an extended error with all source programs, both in source code form and their ASTs.
The use of spew to dump all information in the error caused an infinite recursion in some cases.
JSON-serializing source codes and ASTs is fine, and what we are actually interested in.
This is a fix for the bug I discovered while updating the core contracts to Cadence v0.12.
> FVM: Improve parsing/checking safety check

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to the latest version of the Go SDK. It fixes a bug with decoding Flow event type IDs
> Update to Go SDK v0.14.1

- go.mod
- go.sum
- integration/go.sum
Use the latest released version instead of an untagged commit
> Update to core contracts v0.7.1

- module/builder/consensus/builder.go
- module/builder/consensus/builder_test.go
- module/builder/consensus/config.go
This PR addresses issue [5202](https://github.com/dapperlabs/flow-go/issues/5202)
It adds a limit to the number of receipts that can be included in a block.
The limit is set to 200 by default
> Enforce maxReceiptCount in block builder

- cmd/consensus/main.go
- engine/consensus/matching/engine.go
- engine/consensus/matching/engine_test.go
- engine/testutil/nodes.go
- module/validation/seal_validator_test.go
- utils/unittest/chain_suite.go
This PR includes:
- implementation of emergency sealing
- cmd argument support, [issue](https://github.com/dapperlabs/flow-go/issues/5199)
> [Sealing] Yurii/5198 emergency sealing

- engine/consensus/matching/engine.go
- engine/consensus/matching/engine_test.go
This PR addresses issue [#5196](https://github.com/dapperlabs/flow-go/issues/5196)
Only send requests to verifiers from which we haven't received an approval yet.
> Only request approvals from missing verifiers

- engine/consensus/matching/engine_test.go
- module/validation/receipt_validator.go
- Add implementation for looking up receipt in payload
> [Sealing] Validation of multiple receipts in payload

- engine/consensus/matching/engine.go
On benchnet, we have a high frequency of these log messages, as they are logged even if no receipts are top be requested: https://console.cloud.google.com/logs/query;query=jsonPayload.instance.name%20:%20%22consensus%22%20%0AAND%20jsonPayload.message%20:%20%22%5C%22requesting%20receipts%5C%22%22;timeRange=2021-01-28T18:34:00.000Z%2F2021-01-28T19:05:00.000Z?project=flow-benchmark&query=%0A
> reduced logging of re-requesting receipts

- cmd/scaffold.go
- engine/execution/computation/computer/computer.go
- fvm/bootstrap.go
- fvm/context.go
- fvm/env.go
Separates out the contract upgrade flag from the deployment flag, allowing us to configure updates differently than deployments.
> FVM flag update - Contract Upgrade Enable

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update from Cadence v0.10.4 to v0.10.6.
Release notes:
- https://github.com/onflow/cadence/releases/tag/v0.10.5
- https://github.com/onflow/cadence/releases/tag/v0.10.6
> Update v0.13 to Cadence v0.10.6

- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- cmd/util/ledger/migrations/storage_reporter.go
Running the test would create a `cmd/util/cmd/execution-state-extract/storage_report_*.csv` file. This was produced by the storage reporter.
By changing the output dir of the storage reporter to the output dir of the migrated root checkpoint (which is more sensible as well) the tests produce the `storage_report_*.csv` in a temp folder (along with the other outputs).
> Storage reporter output directory fix

- go.mod
- go.sum
Revert #347. Instead, apply a minimal improvement: 
https://github.com/onflow/cadence/compare/v0.10.4...v0.10.4-hamt-update
See https://axiomzen.slack.com/archives/CEXKUH74G/p1612129623255100
> Revert update of v0.13 to Cadence v0.10.6, update to a minimal improvement

- .gitignore
- cmd/util/cmd/read-badger/cmd/blocks.go
- cmd/util/cmd/read-badger/cmd/chunk_data_pack.go
- cmd/util/cmd/read-badger/cmd/cluster_blocks.go
- cmd/util/cmd/read-badger/cmd/collections.go
- cmd/util/cmd/read-badger/cmd/commits.go
- cmd/util/cmd/read-badger/cmd/epoch_commit.go
- cmd/util/cmd/read-badger/cmd/epoch_statuses.go
- cmd/util/cmd/read-badger/cmd/events.go
- cmd/util/cmd/read-badger/cmd/guarantees.go
- cmd/util/cmd/read-badger/cmd/receipts.go
- cmd/util/cmd/read-badger/cmd/results.go
- cmd/util/cmd/read-badger/cmd/seals.go
- cmd/util/cmd/read-badger/cmd/storages.go
- cmd/util/cmd/read-badger/cmd/transaction_results.go
- cmd/util/cmd/read-badger/cmd/transactions.go
- go.mod
The read-badger tool didn't close the database after finish executing the commands. 
This results a dirty way of leaving the database open. It is fine if we re-execute the commandline again, because we truncate the log. However, the node software have truncate log option as `false` by default, which causes the node software unable to start up.
This PR fixes the badger related tools to close database properly
> Close database when using badger cli

- module/metrics.go
- module/metrics/network.go
- module/metrics/noop.go
- module/mock/network_metrics.go
- network/p2p/network.go
This PR implements adding a _counter_ metric named `network_queue_inbound_message_process_time` which captures the _total_ time queue workers are blocked for an engine for processing the incoming messages. The metric defines a time series with different labels one for each channel (i.e., topic). Hence, `network_queue_inbound_message_process_time_X` represents the total time queue workers blocked for engines on channel `X` processing their incoming messages.
> NET: Yahya/5258-engine-processing-time

- cmd/util/ledger/migrations/multiple_contract_migration.go
- fvm/astCache.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to the latest version
- [Cadence v0.12.6](https://github.com/onflow/cadence/releases/v0.12.6)
- [Go SDK v0.14.3](https://github.com/onflow/flow-go-sdk/releases/tag/v0.14.3)
> Update to Cadence v0.12.6 and Go SDK v0.14.3

- engine/consensus/matching/engine.go
This PR contains a temporary fix, which hopefully increases stability of block production. It contains two parts:
When the matching engine does not require _any_ approvals for seal construction (i.e. `requiredApprovalsForSealConstruction == 0`), the matching engine drops the approvals without acquiring the engine lock
We expect a lot more Approvals compared to blocks or receipts. However, the level of information only changes significantly with new blocks or new receipts. We used to kick off the sealing check after every approval and receipt. In cases where the sealing check takes a lot more time than processing the actual messages (which we assume for the current implementation), we incur a large overhead as we check a lot of conditions, which only change with new blocks or new receipts. …
> revised scheduling of sealing check

- fvm/errors.go
- fvm/fvm.go
- fvm/transaction.go
- go.mod
- go.sum
Cadence might panic when failing to encode an unsupported value. 
For now, gracefully handle these errors and abort the execution, e.g. revert a transaction.
> Handle encoding errors gracefully

- fvm/env.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- Update to Cadence v0.12.8, which includes https://github.com/onflow/cadence/pull/584
- Implement the new debug log function (debug logs by the Cadence implementation, not logs from Cadence programs / user code)
> Update to Cadence v0.12.8, implement debug log function

- engine/testutil/mock/nodes.go
- engine/testutil/nodes.go
- engine/verification/utils/fixtures.go
This PR fixes the inconsistency of block ID in the chunks of `CompleteExecutionResult` test fixture.
> VER: Yahya/5270 fix block ids fixture

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to Cadence v0.12.9, which fixes the debug logging of encoding prepare calls
> Update to Cadence v0.12.9

- cmd/verification/main.go
- engine/verification/match/engine.go
On my localnet, if I restart execution node, the sealing will be halt.
And the reason it halts is because the consensus didn’t receive approvals.
Why? because during the EN down time, VN has received the ER, and sent the chunk data pack request, but didn’t receive the response. And VN has a config to only retry 2 times, after which it will give up, and then the consensus will never receive approval, so sealing halts.
This PR
- increased the retry attempts from 2 times to 10000000 (last for 115 days)
- remove pending chunks from mempool if the executed block is below sealed height. So that we won't keep sending chunk data pack request for them. 
Tested locally, it worked
> [Verification] increase verification retry attempts

- cmd/bootstrap/cmd/genconfig.go
- engine/consensus/compliance/engine.go
- engine/consensus/matching/engine.go
- engine/consensus/matching/engine_test.go
- engine/consensus/matching/next_unsealed_results.go
- integration/localnet/bootstrap.go
- module/builder/consensus/builder.go
- utils/unittest/chain_suite.go
This PR improves the logging in match engine for debugging potential sealing halt issue. See [Issue](https://github.com/dapperlabs/flow-go/issues/5247)
- Log whether the consensus match engine has received an incorporated result for the next unsealed block
- Log whether the consensus match engine has received enough approvals for the next unsealed block, if not, which chunk index hasn't received enough approval.
> [Consensus] Logging information about next unsealed block

- engine/execution/computation/computer/computer.go
- engine/execution/state/bootstrap/bootstrap_test.go
- fvm/env.go
- fvm/errors.go
- fvm/fvm.go
- fvm/transaction.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- utils/unittest/execution_state.go
Cherry-pick the patches applied to `v0.14` also to `master`, namely these PRs:
- Debug log execution of transaction #368
- Handle encoding errors gracefully #369 
- Update to Cadence v0.12.8, implement debug log function #370 
- Update to Cadence v0.12.9 #371 
- Update to Cadence v0.12.10 #375 
- Update to Cadence v0.12.11 #379
> Update to Cadence v0.12.11, port patches to v0.14

- engine/consensus/compliance/engine.go
- engine/consensus/compliance/engine_test.go
- module/trace/constants.go
modularization improvement to address [downstreamed complications](https://github.com/onflow/flow-go/pull/366#discussion_r573459578) 
* We now have a single function that implements the recursion `processBlockAndDescendants` and calls itself (which makes the reclusive design very apparent)
* `processBlockProposal` is now only concerned with processing a single block is
> Compliance Engine recursion revision

- fvm/context.go
- fvm/state/state.go
increasing the limits for now, until we optimize event storage and improve ledger trie balance.
Note that event limits are not enforced for tx paid by the service account (for epoch switch operations)
> [Execution] increase the event size limit and ledger interaction limit

- fvm/metrics.go
Currently, there are two problems with time tracking for parsing, checking and interpreting a transaction:
- the Metric is constructed in the context (shared for all collections in a block) 
- metric calls by the cadence runtime have overlaps. 
This patch will change the logic to only capture the time spend by tx itself. in the following PR to the master, we revisit the whole structure.
> [Execution] fix time tracking for tracing tx execution

- engine/consensus/matching/engine.go
consensus nodes will only generate a candidate seal, if there are multiple _consistent_ results
> Consensus HOTFIX: wait for multiple receipts before seal

- engine/consensus/matching/engine.go
Revert the change that requiring sealing a block with 2 receipts.
now we will seal block with one receipt
> [Consensus] V0.14 seal with 1 receipt

- cmd/execution/main.go
- engine/consensus/matching/engine.go
- engine/execution/checker/engine.go
- engine/execution/ingestion/engine.go
- engine/testutil/nodes.go
This PR adds a check on block finalized, to check if a sealed block has been executed, if it has, it checks whether the sealed result is consistent with the executed block. 
If a node is falling behind, then the last sealed block might not be executed yet. But in this case, the receipt won't be broadcasted, when the execution node eventually catch up, it will crash and the bad receipt won't be broadcasted.
Tested on localnet, worked.
> [Execution] crash on detected execution fork

- cmd/consensus/main.go
- engine/common/requester/engine.go
- engine/consensus/matching/engine.go
- engine/consensus/matching/engine_test.go
- utils/unittest/chain_suite.go
*  polished logic for requiring two receipts from _different_ ENs before sealing;
* fixed logic for re-requesting second receipt (as a single one is insufficient now)
* added unit tests
> MAINNET FIX v0.14: require multiple receipts to seal V3

- engine/verification/match/engine.go
- engine/verification/verifier/engine.go
- model/flow/chunk.go
- model/flow/chunk_test.go
- utils/unittest/fixtures.go
To have more visibility on tracing the journey of chunks in the verification node, this PR improves the logging in the match and finder engines of the verification node by adding the following details to the logs wherever needed:
- List of assigned chunk indices. 
- Chunk index, and id
> [Verification] Yahya/5343-improve-verification-logging

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to [Cadence v0.13.1](https://github.com/onflow/cadence/releases/tag/v0.13.1)
> Update to Cadence v0.13.1

- cmd/collection/main.go
- engine/collection/ingest/config.go
- collection nodes filter out transactions with account indices larger than a constant
- this PR bumps the constant from 1M to 10M.
> [Collection] increase the address index limit

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to Cadence v0.13.1-no-contract-validation, which contains onflow/cadence#647, which disables the contract update validation for now, and adds an option to enable it again eventually.
> Disable contract update validation

- engine/execution/computation/computer/computer_test.go
- fvm/transaction_test.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update `master` to Cadence v0.13.3 
Changes:
- [Cadence v0.13.1](https://github.com/onflow/cadence/releases/tag/v0.13.1) (was already on Flow Go v0.14)
- [Cadence v0.13.2](https://github.com/onflow/cadence/releases/tag/v0.13.2)
- [Cadence v0.13.3](https://github.com/onflow/cadence/releases/tag/v0.13.3)
> Update to Cadence v0.13.3

- cmd/execution/main.go
- engine/execution/state/state.go
- module/metrics/labels.go
- storage/badger/cache.go
- storage/badger/my_receipts.go
- storage/badger/operation/prefix.go
- storage/badger/operation/receipts.go
- storage/badger/receipts.go
- storage/receipts.go
draft for separating Receipts (from all Execution Nodes) from receipts that a specific execution Node stored as "mine"
> draft for separating Receipts storage Layer

- engine/consensus/dkg/messaging_engine.go
- engine/consensus/dkg/messaging_engine_test.go
- engine/consensus/dkg/reactor_engine.go
- engine/consensus/dkg/reactor_engine_test.go
- engine/execution/utils/hasher.go
- model/encoding/signing_tags.go
- model/messages/dkg.go
- module/dkg.go
- module/dkg/broker.go
- module/dkg/broker_test.go
- module/dkg/controller.go
- module/dkg/controller_factory.go
- module/dkg/controller_test.go
- module/dkg/doc.go
- module/dkg/tunnel.go
- module/local/me.go
- module/mock/dkg_broker.go
- module/mock/dkg_contract_client.go
- module/mock/dkg_controller.go
- module/mock/dkg_controller_factory.go
- utils/hasher/hasher.go
- utils/unittest/fixtures.go
This PR addresses issue [4465](https://github.com/dapperlabs/flow-go/issues/4465) to sign and verify DKG broadcast messages with a node's staking key.
The main changes are in the [DKG broker](https://github.com/onflow/flow-go/blob/549dff03ec7faf75295be11ba10eb1e72c73297f/module/dkg/broker.go#L206-L240) , but the PR also contains some refactoring that is not directly related to the issue.
> Sign and verify DKG broadcast messages with node staking key

- fvm/crypto.go
- fvm/fvm_test.go
Closes dapperlabs/flow-go#5375
Don't rely on the crypto library's constants, but ensure the constants used in the Crypto contract are supported.
Extend the tests to test all combinations.
> Fix Crypto.ECDSA_Secp256k1

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Changes from v0.13.5-no-id-caching to v0.13.7: https://github.com/onflow/cadence/compare/v0.13.5-no-id-caching..v0.13.7
> Update to Cadence v0.13.7

- module/metrics/collection.go
- module/metrics/compliance.go
- module/metrics/labels.go
Including the proposer in finalized block count metric lets us see which nodes are successfully proposing blocks, which should correspond to health, up-to-date nodes. This graph shows how we can see which node is down:
> Add proposer to finalized block count metric

- engine/access/access_test.go
- engine/access/rpc/backend/backend.go
- engine/access/rpc/backend/backend_accounts.go
- engine/access/rpc/backend/backend_events.go
- engine/access/rpc/backend/backend_scripts.go
- engine/access/rpc/backend/backend_test.go
- engine/access/rpc/backend/backend_transactions.go
- engine/access/rpc/logging_interceptor.go
access node change to consider the execution receipts which have the most common execution result
Original PR: https://github.com/onflow/flow-go/pull/428
Cherry-picked commit: https://github.com/onflow/flow-go/commit/99a851570808b99d15b74149db2103d58454ae32
> Porting the change on v0.14 to access node to consider at least 2 matching ER

- module/validation/receipt_validator.go
- module/validation/receipt_validator_test.go
I have added two tests:
1. https://github.com/onflow/flow-go/blob/68cc1497f309b9c92787af24550997dfe0bdccb8/module/validation/receipt_validator_test.go#L582-L591
2. https://github.com/onflow/flow-go/blob/68cc1497f309b9c92787af24550997dfe0bdccb8/module/validation/receipt_validator_test.go#L509-L527  
**Test 1 can be used to demonstrate that the order of block traversal is critical for correctness of algorithm:** https://github.com/onflow/flow-go/blob/68cc1497f309b9c92787af24550997dfe0bdccb8/module/validation/receipt_validator.go#L251-L253
* the difference between `forkCrawler` and `topDownCrawler` is the order in which the process the blocks
* I added `topDownCrawler` in this PR to demonstrate that the order matters
> extended tests

- module/trace/noop.go
This caused a panic on `Done` method
> Remove unused closer from noop tracer

- cmd/execution/main.go
- cmd/util/cmd/exec-data-json-export/event_exporter.go
- engine/execution/state/state.go
- engine/testutil/nodes.go
- storage/badger/all.go
- storage/badger/batch.go
- storage/badger/cache.go
- storage/badger/chunkDataPacks.go
- storage/badger/cluster_payloads.go
- storage/badger/commits.go
- storage/badger/events.go
- storage/badger/events_test.go
- storage/badger/headers.go
- storage/badger/operation/max.go
- storage/badger/results.go
- storage/badger/transaction_results.go
- storage/badger/transaction_results_test.go
- storage/badger/transactions.go
- storage/batch.go
- storage/events.go
- storage/transaction_results.go
This PR caches the transaction results, events for the blocks with a LRU cache.
Also fixed an issue that the badger events instance was used before initialized, wasn't an issue before because it was stateless. Now with caching it's stateful.
Address https://github.com/dapperlabs/flow-go/issues/5370
> Cache Transaction Results

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to [Cadence v0.13.9](https://github.com/onflow/cadence/releases/tag/v0.13.9).
Diff: https://github.com/onflow/cadence/compare/v0.13.8...v0.13.9
> Update to Cadence v0.13.9

- fvm/env.go
- fvm/handler/programs.go
This PR updates the cache handler to cover an edge case that a cadence runtime calls get and the cache is empty and it never calls set. This is necessary for smart contract update transactions.
> [FVM] Updating program cache handler to always clean up state stack

- fvm/handler/programs.go
- fvm/handler/programs_test.go
we need to reset the active state back to the initial state on clean up. this impacts after clean up updates like commit smart contract updates.
> [FVM] program cache patch 2

- fvm/errors.go
- fvm/transaction.go
This PR adds an extra health check for the state holder during the execution of transactions. 
If the state holder state doesn't match the initial state of the transaction, a state child merge has been missing somewhere, while this situation should never happen, this safety check makes sure we fail on those transactions gracefully.
> [FVM] adding an extra health check on the state holder

- engine/verification/assigner/blockconsumer/consumer_test.go
Fixing the flakey tests with the following error:
```
=== RUN   TestProduceConsume/pushing_100_blocks_concurrently,_non-blocking,_receives_100
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa7026a]
goroutine 14770 [running]:
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
/home/m4ks/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/skl/skl.go:86
github.com/dgraph-io/badger/v2.(*DB).getMemTables(0xc00057c000, 0x0, 0x0, 0x0, 0x0)
/home/m4ks/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:578 +0xea
github.com/dgraph-io/badger/v2.(*DB).get(0xc00057c000, 0xc0147f8720, 0x2f, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/m4ks/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:610 +0x66 …
```
> Fix flaky tests

- engine/verification/finder/concurrency_test.go
- engine/verification/finder/engine_test.go
- engine/verification/test/helper.go
- engine/verification/test/verification_test.go
- engine/verification/utils/fixtures.go
The `CompleteExecutionReceipt` is one of our test helper `struct` in the Verification Domain that represents a container block accompanied with all data required to verify its execution receipts.
At this moment that we are in transition between software architectures of verification node, `CompleteExecutionReceipt` should support both the `finder` engine (from old architecture) and `assigner` engine (from new architecture). However, these two engines behave quite differently. The former expects to receive receipts from the network while the latter reads receipts from the payload of blocks. 
The `CompleteExecutionReceipt` was mainly developed with the new `assigner` engine in mind. Hence, to imitate the old `finder` engine receives a block from the network, we needed to iterate over the …
> [Verification] Yahya/5421-adds-receipts-to-complete-execution-receipt-fixture

- cmd/access/main.go
- engine/access/access_test.go
- engine/access/rpc/backend/backend.go
- engine/access/rpc/backend/backend_events.go
- engine/access/rpc/backend/backend_test.go
- engine/access/rpc/backend/historical_access_test.go
- engine/access/rpc/backend/retry_test.go
- engine/access/rpc/engine.go
* Add configurable maximum size for range requests
* Retrieve headers rather than full blocks from storage while fulfilling GetEvents requests
* Really we only need to ID, but are retrieving the entire block + payload. Changing to retrieve the header is quite simple, we could also enhance this to just lookup the height->ID index, which is happening anywhere here under the hood
> Access RPC: GetEvents Performance Improvements (v0.14)

- engine/execution/computation/computer/computer_test.go
- fvm/account.go
- fvm/context.go
- fvm/crypto.go
- fvm/env.go
- fvm/errors/errors.go
- fvm/fvm.go
- fvm/fvm_test.go
- fvm/script.go
- fvm/state/accounts.go
- fvm/transaction.go
- fvm/transactionAccountFrozen.go
- fvm/transactionSequenceNum.go
- fvm/transactionStorageLimiter.go
- fvm/transactionVerifier.go
- fvm/transaction_processor_test.go
- module/chunks/chunkVerifier_test.go
Main reason was that `AccountFrozenError` was not a `fvm.Error` which means it's not handled properly by `VirtualMachine`.
However, to properly make this error a good implementation of `fvm.Error` I had to move `fvm/errors` to separate package to avoid circular dependencies.
Also, removed wrapping of this error in handler.
Added tests which reproduce the problem.
There is upcoming complete re-work of errors handling in FVM, so this solution is semi-temporary I think
> Fix frozen account crashing FVM

- engine/access/rpc/backend/backend_events.go
- engine/access/rpc/backend/backend_test.go
Previously the range maximum check was _after_ reading headers from storage but before sending a request to the EN. This moves the check to before the DB read as well. 
Also tweaked the tests to avoid double-mocking the same mock objects with the same inputs.
> Fix range check location

- cmd/verification/main.go
- engine/verification/fetcher/engine.go
- engine/verification/match/engine.go
* do not send CHDP requests in `match` or `fetcher` engine
* change retry interval to 30s from 1s
> Skip sending chunk data pack requests

- engine/verification/match/engine_test.go
- engine/verification/test/verification_test.go
This PR skips tests that are failing after the [hotfix](https://github.com/onflow/flow-go/commit/737460252e62554eded51715a4c1ba0a1afbbb5c) on the `match` engine, which disables it requesting chunk data packs. Hence, fixing CI on this branch.
> skips failing tests that require match engine requesting chunks

- engine/access/rpc/backend/backend.go
- engine/access/rpc/backend/backend_test.go
Currently, the default behaviour of ANs is that if no Preferred and Fix ENs are provided, it will ALWAYS ask only the default EN. This is undesirable behaviour, as we want the default case to be that the AN will talk to ALL ENs if they happen to be one of the first ENs to produce the result.
This changes the default behaviour so that if no filters are provided, instead of returning an empty list, we return the non-filtered list.
> Update Access Nodes' EN selection logic for the default case

- engine/access/rpc/backend/backend.go
- engine/access/rpc/backend/backend_test.go
* If no preferred nodes are provided, don't filter
* Update tests to match new behaviour
> Update Access Nodes' EN selection logic for the default case (#623)

- cmd/verification/main.go
- engine/verification/match/engine.go
- engine/verification/match/engine_test.go
The PR implements minor optimizations on verification nodes for requesting chunk data from execution nodes. The changes are:
- Verification node only asking chunk data from _original_ executor of the chunk. 
- Bumping up the request intervals from `1s` to `5s` to account for transactions burst at the execution node.
- Limiting the maximum number of retries from literally indefinitely to a day (in case the execution node is failed or down for a long time).
> [Verification] Chunk data request optimization

- cmd/bootstrap/cmd/finalize.go
- engine/execution/state/bootstrap/bootstrap_test.go
- fvm/bootstrap.go
- fvm/fvm_test.go
- integration/testnet/network.go
- utils/unittest/execution_state.go
Change the storage parameters defaults to what was originally deployed.
- minimum account balance        =  0.001 FLOW
- Storage megabytes per FLOW  =  10.0
Also made it possible to set any `Storage megabytes per FLOW` on the bootstrap level.
> Change storage defaults

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.14.5..v0.14.5-patch.1
> Update to Cadence v0.14.5-patch.1

- module/metrics/labels.go
- storage/badger/approvals.go
- storage/badger/cache.go
- storage/badger/chunkDataPacks.go
- storage/badger/cluster_payloads.go
- storage/badger/commits.go
- storage/badger/epoch_commits.go
- storage/badger/epoch_setups.go
- storage/badger/epoch_statuses.go
- storage/badger/events.go
- storage/badger/guarantees.go
- storage/badger/headers.go
- storage/badger/index.go
- storage/badger/my_receipts.go
- storage/badger/receipts.go
- storage/badger/results.go
- storage/badger/seals.go
- storage/badger/transaction_results.go
- storage/badger/transactions.go
We rather need a name for every cache instance, so make it mandatory
> Require resource name to create cache

- .github/workflows/ci.yml
- cmd/collection/main.go
- integration/epochs/epoch_qc_test.go
- module/dkg/client.go
- module/dkg/client_test.go
- module/epochs/base_client.go
- module/epochs/base_contract_client.go
- module/epochs/qc_client.go
This PR adds logging to both the Epoch QC and DKG contract clients. 
- Also moves common methods and fields for any contract client to `epochs/base_client`.
- All `SendTransaction` are logged. Also logs attempts at waiting for transaction to be sealed along with the time elapsed since the parent method was invoked.
- The check to verify that the `AccountKeyIndex` is valid has been moved to 
```BaseClient.GetAccount(ctx) (*sdk.Account, error)```
> Improve Logging within DKG & Epoch QC Clients

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
This PR fixes the cyclic import bug discovered on Testnet
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.14.5-patch.1..v0.14.5-patch.2
> Update to Cadence v0.14.5 patch.2

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.14.5-patch.2..v0.14.5-patch.3
> Update to Cadence v0.14.5-patch.3

- .gitignore
- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- cmd/util/ledger/migrations/storage_v4.go
Closes dapperlabs/flow-go#5422
The next Cadence release will introduce a new storage format, which means the whole execution state needs to be migrated from an old format (there are multiple older versions) to the new format.
Implement a state migration function which decodes all Cadence values using the old decoder and encodes them using the new encoder. 
As a sanity check, the newly encoded data is re-decoded, and the resulting value is compared to the value which was initially decoded from the original data using the old decoder.
> Add state migration for new Cadence storage format v4

- cmd/util/cmd/read-execution-state/list-tries/cmd.go
- ledger/complete/mtrie/forest.go
- ledger/complete/mtrie/trie/trie.go
- ledger/partial/ledger.go
- ledger/partial/ptrie/partialTrie.go
* forest's LRU cache working directly with rootHashes
*  `partial.ledger`:  removed unnecessary conversions of `ledger.Path` to `string` for map lookup
* `ptrie.PSMT`: removed unnecessary conversions of `ledger.Path` to `string` for map lookup
> suggested revisions Pt 2

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/d38523af2...v0.15.1-patch.1
(d38523af2 is v0.15.1, but that tag is missing in the internal repo)
> Update to Cadence v0.15.1-patch.1

- engine/consensus/sealing/core.go
This PR fix an issue that when there is error processing a receipt, the error is overwritten by json encoding error, which we don't care.
> [Consensus] Avoid overwritten error

- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- cmd/util/ledger/migrations/prune_migration.go
- fvm/state/state.go
- fvm/state/state_test.go
Currently, we don't prune tries on delete operations, instead, Cadence sets an empty value for those keys, this migration prunes those keys so the output trie at spork will be pruned.
Why this is safe to do:
Existence methods have always been based on the size of returned value and trie always returns empty slice for non-existence keys:
- `func (a *Accounts) Exists(address flow.Address)`
- `func (e *hostEnv) ValueExists(owner, key []byte)`
StorageUsed never considered any usage for registered with the value of length zero (RegisterSize returns zero for registers with empty) 
`storage_used` and `frozen` values are checked by length. frozen is considered false if register not exists, storage_used checks the size of what is returned. 
Account keys are never removed physically from the state …
> [Ledger] Adding a migration to prune the trie on sporks

- cmd/util/cmd/execution-state-extract/cmd.go
- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
For cadence-aware migrations, we need less-randomized tests, otherwise, we might fail because of cases that are not valid cadence values.
> [cmd] update exec state extract test to skip migrations

- cmd/util/ledger/migrations/storage_v4.go
- ledger/complete/ledger.go
The `TokenForwarding.Forwarder` resource's `recipient` field's type changed from a reference to a capability: https://github.com/onflow/flow-ft/pull/24/files#diff-f88272564fea81ead391ca2c9380749209bf7ed5219a1980aafac775df172fa8L29-R29
However, (some of) these resources were not migrated.
Detect `TokenForwarding.Forwarder` resources, and rewrite the `recipient` field from a storage referene value to a capability value.
Also, recalculate the expected payload size for the next migration, to avoid spurious warnings for a payload size mismatch caused by a previous migration
> Migrate TokenForwarding.Forwarder recipient storage references to capabilities

- go.mod
- integration/go.mod
For downstream dependencies, like the Emulator, the replace statement is not used, so the actual dependency statement is used. However, it incorrectly refers to a non-existent tag.
> Fix Cadence dependency

- model/flow/identity.go
- model/flow/identity_test.go
- state/protocol/inmem/encodable_test.go
This PR adds custom RLP encoding for `flow.Identity` which addresses a problem where different underlying implementations of `crypto.PublicKey` in the `StakingPubKey` and `NetworkingPubKey` fields of `Identity` resulted in different RLP encodings for the same key.
This PR adds a test for result ID consistency after an encode/decode cycle for the entire snapshot, using differing `PublicKey` implementations. There is also [this proof-of-concept which focusses only on the keys](https://github.com/onflow/flow-go/compare/jordan/5430-inconsistent-snapshot-poc). 
💡  More details in https://github.com/dapperlabs/flow-go/issues/5430#issuecomment-828792960
> Fix inconsistent RLP encoding for Identity

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.15.1-patch.1..v0.15.1-patch.2
> Update to Cadence v0.15.1-patch.2

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Includes:
- https://github.com/dapperlabs/cadence-internal/pull/11
- https://github.com/dapperlabs/cadence-internal/pull/12
- https://github.com/dapperlabs/cadence-internal/pull/13
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.15.1-patch.2..v0.15.1-patch.4
> Update to Cadence v0.15.1-patch.4

- cmd/scaffold.go
- network/message/ping.proto
- network/mocknetwork/ping_info_provider.go
- network/p2p/libp2pNode_test.go
- network/p2p/ping.go
- network/test/testUtil.go
In an earlier change, I added the finalized block height as an additional field to the ping response. However, I realized that it should have been the sealed block height and not the finalized height.
> switching finalized block height to sealed block height in ping metric reporting

- Makefile
updating grep regex to cover for newer version of go
> update go version check to support up 1.13-1.16

- engine/collection/ingest/engine_test.go
- utils/unittest/fixtures.go
Identities are no longer stored in block payloads directly, so this was unused.
> Remove unused identities parameter from GenesisFixture

- module/chunks/chunkVerifier.go
Missing register should not return generic error back to FVM, since we consider undefined errors at FVM fatal. The idea is we always return empty slice but capture the missing call and use it for challenge creation later.
> [Verification] fix the logic that handles missing registers

- fvm/fvm.go
- fvm/fvm_test.go
The e2e tests found that tx fee deduction in meta-transactions fails. https://github.com/onflow/flow-e2e-tests/runs/2623252271?check_suite_focus=true
TX fee deduction should not happen in meta transactions.
This PR:
- fixes the fee tests to actually create an account with the same context as the test will use (previously the account was created with fees disabled, that is why the tests didn't catch this issue). Adding this fix I got the same error as the e2e tests
- disables fee deduction in meta transactions (this makes the tests pass again)
- also disabled limiting account storage in meta transactions (this is more of an optimization)
> Remove fee deduction in meta-transactions

- module/epochs/epoch_config.go
The cluster QC model changed slightly after this encoding method was introduced in https://github.com/onflow/flow-go/pull/685. This PR adds the new `voterIDs` field to the encoded QC.
> Update EncodeClusterQCs Method

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to [Cadence v0.16.1](https://github.com/onflow/cadence/releases/tag/v0.16.1)
Diff: https://github.com/onflow/cadence/compare/v0.16.0..v0.16.1
> Update to Cadence v0.16.1

- ledger/common/hash/copy_generic.go
Fix a typo in the for loop definition.
> [Ledger] Fix a typo in copy function

- cmd/bootstrap/cmd/qc.go
- cmd/bootstrap/run/qc.go
- model/bootstrap/node_info.go
the internal node list and all node list was inconsistent because the
full node list had the canonical ordering applied (and this affected the
internal node list because they shared a backing array).
this changes the sorting of node infos to return a copy and updates the
dkg participant data generation
> V0.17: Fix QC generation in bootstrap when non-internal nodes are present

- engine/execution/provider/engine.go
https://github.com/dapperlabs/flow-go/issues/5532#issuecomment-849214263
Based on the assumption, the execution hiccup could potentially fixed by making the chunk data pack response delivery async
> Delivery chunk data pack response async

- engine/access/ping/engine.go
- module/metrics.go
- module/metrics/ping.go
Fixing the issue with the Mainnet Partner Node Availability Grafana dashboard -
Earlier I had added `nodeversion` to the Ping metric and to the `network_gossip_sealed_height` metric.
The metrics now show up accordingly as (using Staked Collection node as an example):
> network_gossip_node_reachable{nodeaddress="flow-0.staked.cloud:3569",nodeid="fcb55c2d1fb2737b159704b5a30b194b8a8ddfb4691d55692af597ac6e236201",nodeinfo="Staked",noderole="collection",**nodeversion="v0.17.4_without_netgo"**} 16
and
> network_gossip_sealed_height{nodeaddress="flow-0.staked.cloud:3569",nodeid="fcb55c2d1fb2737b159704b5a30b194b8a8ddfb4691d55692af597ac6e236201",nodeinfo="Staked",noderole="collection",**nodeversion="v0.17.4_without_netgo"**} 1.4931077e+07
However, initially when a node is not pingable, the Ping …
> removing node version from ping metric

- ledger/common/hash/copy_generic.go
`git cherry-pick 1473631201f7b194fb508aee5ae3efdff14c5512`
https://github.com/onflow/flow-go/pull/748
> fix a typo in copy function

- engine/access/ping/engine.go
- module/metrics.go
- module/metrics/ping.go
Cherry-picking commit from [PR](https://github.com/onflow/flow-go/pull/759)
This change is currently on Access Node 3 on mainnet-9 and is working as expected.
> removing node version from ping metric (#759)

- state/protocol/badger/mutator.go
- state/protocol/badger/mutator_test.go
- state/protocol/badger/validity.go
- state/protocol/events.go
This PR addresses [issue 5560](https://github.com/dapperlabs/flow-go/issues/5560)
> Fix the off-by-one error in the emission of epoch phase change events

- engine/consensus/approvals/aggregated_signatures.go
- engine/consensus/approvals/approval_collector.go
- engine/consensus/approvals/approvals_cache.go
- engine/consensus/approvals/assignment_collector.go
- engine/consensus/approvals/assignment_collector_tree.go
- engine/consensus/matching/core.go
- engine/consensus/sealing/engine.go
- engine/consensus/sealing/engine_test.go
- module/mempool/consensus/execution_tree.go
* minor revisions of goDoc and inline comments
* renamed method `AggregatedSignatures.CollectChunksWithMissingApprovals` to `ChunksWithoutAggregatedSignature()`
* shifted the location of a few lines of code
* renamed internal variable in `matching.Core` to be more specific: the executed block is now called `executedBlock`  
* `AssignmentCollector` now checks _first_ whether an approval is already cached and drops duplicates, _before_ doing expensive crypto verifications
* `ApprovalCollector`
- added logic for sealing right away if no approvals are required
- using consistently  `uint64` to refer to chunk indices and related quantities;
* `sealing.Engine`: 
- separated logic for creating inbound queues for trusted inputs from message handler for untrusted inputs
- removed struct field …
> PR 736: suggestions pt4

- cmd/consensus/main.go
- consensus/integration/nodes_test.go
- engine/consensus/approvals/incorporated_result_seals.go
- integration/tests/execution/failing_tx_reverted_test.go
I think the problem with the integration test is:
* Access nodes now wait until they know _two_ consistent receipts before reporting any state values
* With out updated logic, consensus nodes seal right away (without waiting for _two_ consistent receipts)
* The failing `TestExecutionFailingTxReverted` test waited for the seal and then queried the access node about state values, which declined the request with the error
```
insufficient execution receipts found (1) for block ID ...
```
Previously, we also had the consensus node wait for 2 consistent receipts before sealing. But this logic is now no longer present. Hence, problems arise in the integration test, when 1 Exec node is behind. 
* The `consensus.Builder` waits until 2 consistent receipts are known before including the seal in the …
> Integration test fix for PR 736

- engine/consensus/sealing/core.go
- engine/consensus/sealing/core_test.go
- engine/consensus/sealing/engine.go
[dapperlabs/flow-go/issues/5216](https://github.com/dapperlabs/flow-go/issues/5216)
This PR implements repopulating of assignment collectors tree. 
Issue description is a bit outdated, based on new architecture of `sealing.Core` it's now implemented as part of core and repopulates collectors tree instead of `IncorporatedResults` mempool.
> [Consensus] Repopulating of assignment collectors tree

- fvm/accounts_test.go
- fvm/crypto/crypto.go
- fvm/crypto/hash.go
- fvm/crypto/hash_test.go
- fvm/fvm_test.go
- fvm/handler/accountKey.go
- move `AddAccountKey` to `accountKey.go` as it is more about accounts than crypto.
- restrict account keys to ECDSA and SHA2/SHA3 256 only.
- introduce prefixed hashers to put more emphasis on customized hashing required by domain separated signatures.
- use padded tags till 32 bytes. 
- disable prefixing with tags if an empty tag is used ( to accommodate the way the crypto contract is written today: `hash(data) = haswWithTag("", data)` )
- restrict ECDSA signatures to hashers with SHA2/SHA3 256 only.
> [FVM] prefixed hashers and a few changes

- network/p2p/libp2pUtils.go
- network/p2p/middleware.go
- network/p2p/readConnection.go
To help debug the stream reset issue, I have made some minor logging changes.
> adding logging around libp2p one-to-one stream management

- network/p2p/libp2pConnector.go
- network/p2p/libp2pNode.go
- network/p2p/libp2pUtils.go
- network/p2p/ping.go
- network/p2p/protocol.go
Earlier during the investigation of [5556](https://github.com/dapperlabs/flow-go/issues/5556), a lot of `stream reset` were observed. The root cause of that the connection pruning logic which kicks in every one minute, prunes all connection a node has which are not part of its 1-to-k PubSub topology. This also severs connection on which there is ongoing one-to-one traffic such as `ChunkDataResponse`, `Collection consensus vote` etc. When the connection is closed while there is ongoing one-to-one traffic it leads to a stream reset.
The fix is to skip closing the connection when there is a stream created for one-to-one traffic. Such streams can be easily identified by their Protocol ID which all begin with the `/flow` prefix (the pubsub streams use an entirely different protocol id …
> skipping pruning of connections which have ongoing one-to-one traffic

- cmd/util/ledger/migrations/storage_v4.go
- fvm/accounts_test.go
- fvm/transactionInvocator.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
[Cadence v0.17.0 release notes](https://github.com/onflow/cadence/releases/tag/v0.17.0)
> Update to Cadence v0.17.0

- .github/workflows/ci.yml
References: https://github.com/onflow/cadence/pull/981
The auto create Cadence update PR in cadence will create branches prefixed by `auto-cadence-upgrade/` it will also base the PR on the latest created `auto-cadence-upgrade/` branch (or `master` if there is none). 
This is a suggestion to add `auto-cadence-upgrade/` to the CI. This will mean that CI will run all auto updates, not only the one based on `master`.
> Add auto-cadence-upgrade branch to CI

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
References: https://github.com/onflow/cadence/pull/998
> Auto Cadence Update: Fix AST walk for transaction declaration

- Makefile
Thanks to @zhangchiqing for helping finding the issue and the correct command for the fix.
> Improve tagging logic if commit has more than 1 tag

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
References: https://github.com/onflow/cadence/pull/1004
> Auto Cadence Update: Embed markdown templates to docgen tool at compile time

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Release notes: https://github.com/onflow/cadence/releases/tag/v0.18.0
> Update to Cadence v0.18.0

- engine/verification/fetcher/engine.go
- engine/verification/fetcher/engine_test.go
This issue fixes a bug that the fetcher engine notifies the chunk consumer based on the chunk ID on sealed blocks. However, the chunk consumer would expect the chunk _locator_ ids, which results in a liveness issue on the fetcher engine in one event of fast forwarding.
> [Verification] Fixing notifier id at fetcher

- engine/verification/assigner/engine.go
- engine/verification/fetcher/engine.go
- model/verification/chunkStatus.go
This PR adds block height to the logs on the processing pipeline of chunks in the verification node.
> [Verification] Logging block height on chunk processing pipeline

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.16.1-patch.1..v0.16.1-patch.2
> Update to Cadence v0.16.1-patch.2

- cmd/execution/main.go
- engine/execution/ingestion/engine.go
- engine/execution/ingestion/engine_test.go
- engine/testutil/nodes.go
Adding a flag `pause-execution` to execution node to pause the execution and allow the node to serve queries only
> [Execution] Add pause execution flag

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
dapperlabs/cadence-internal#22 ported to Cadence v0.18
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.18.0-patch.1..v0.18.0-patch.2
This was already applied as a hotfix to Flow Go v0.17 in #860
> Update to Cadence v0.18.0-patch.2

- engine/consensus/sealing/core.go
In case we don't want to require approvals for sealing, simply merge this PR.
The emergency-sealing-active could be `true` doesn't need to be changed, because it will never be triggered.
> [Consensus] v0.18 not require approval for sealing

- engine/verification/verifier/engine.go
- engine/verification/verifier/engine_test.go
- model/chunks/chunkFaults.go
- module/chunks/chunkVerifier.go
This change would let verification nodes to gracefully handle a very special edge case of missing some register touches until the root cause of this edge case is identified and patched.
> [Verification] gracefully handle the missing register case

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.18.0-patch.2..v0.18.0-patch.3
> Update to Cadence v0.18.0 patch.3

- access/errors.go
- access/validator.go
- engine/collection/ingest/engine_test.go
- fvm/fvm_test.go
- fvm/transactionVerifier.go
- fvm/transactionVerifier_test.go
- fvm/transaction_test.go
- integration/go.sum
- integration/tests/common/util.go
- model/flow/transaction.go
- module/builder/collection/builder_test.go
- module/mock/job_consumer.go
- utils/unittest/fixtures.go
this backports #884
It rejects duplicated signatures both on access/collection level and FVM level
> Reject duplicated signatures

- cmd/bootstrap/cmd/finalize.go
- cmd/bootstrap/cmd/keygen.go
- cmd/bootstrap/cmd/keys.go
- cmd/bootstrap/cmd/seal.go
- cmd/bootstrap/run/key_generation.go
- cmd/bootstrap/run/key_generation_test.go
- go.mod
- go.sum
- integration/go.sum
- integration/testnet/network.go
- model/bootstrap/node_info.go
- utils/unittest/fixtures.go
This PR adds additional flags to some commands in the bootstrapping utility to support running epochs on `benchnet`. 
* Adds epoch length flags to `bootstrap finalize` and pass through to execution state generation
* Adds flag to generate machine account files for a default fresh execution state
> Support for epoch files & execution state options to bootstrapping script

- crypto/relic_build.sh
Detect if we're compiling on an ARM and drop the unsupported `-march=native` there.
Fixes #809
> [crypto] Fix relic build script for ARM

- module/mock/verification_metrics.go
[PR 831](https://github.com/onflow/flow-go/commit/a276ede0bfcafa99d6e5be40a1dc55c430584a0c) Touched on the mocks generation.
This records the output of that change: The PR was generated by `make ci` + committing the resulting diff.
> [chore, easy, verification] Tidy up after #831

- integration/dkg/dkg_emulator_suite.go
- integration/dkg/dkg_whiteboard_test.go
- module/dkg/broker.go
- module/dkg/broker_test.go
This PR addresses issue [5607](https://github.com/dapperlabs/flow-go/issues/5607) with log hooks
> Add log hooks to catch warnings from DKGProcessor in integration tests

- engine/common/synchronization/engine.go
- module/synchronization/core.go
- storage/badger/blocks.go
- storage/badger/headers.go
* It would be great to fix this performance bottleneck: https://github.com/onflow/flow-go/blob/5fd2ff27a74127c0cd23fdfaa96d69fb7a9716c6/engine/common/synchronization/engine.go#L489
- In contrast to `badger.Headers`, which has a cache for heights, `badger.blocks` does not have such a cache and instead _always_ hits the data base. 
* I think we could inline method https://github.com/onflow/flow-go/blob/5fd2ff27a74127c0cd23fdfaa96d69fb7a9716c6/engine/common/synchronization/engine.go#L581-L596 as it is only used once. 
* We might be able to reduce lock congestion in [`Core. HandleHeight `](https://github.com/onflow/flow-go/blob/5fd2ff27a74127c0cd23fdfaa96d69fb7a9716c6/module/synchronization/core.go#L98):
* we always lock right away, but on the happy path when the node is up to date, this code …
> suggestions for PR 910

- Makefile
At present, the unit tests run as part of every CI build, but they do not run with with -race parameter which may be used to detect [data races](https://golang.org/doc/articles/race_detector).
Since data races may lead to instability and crashes, it's beneficial to ensure that we prevent data races from being introduced where possible. This runs unit tests with an explicit list of modules (rather than the recursive catch-all) and turns on `-race` for those that pass the build today, hoping others will join the list in the future.
To determine which modules "pass" with `-race` enabled, I've run `go test -race` in a loop and moved any directories that had a test failing because of a race condition move to the Makefile line (part of the unittest goal) without race detection.
[The cost of …
> [CI / build] Activate race-detection for those modules that are passing it

- module/metrics/execution.go
This PR
- closes #5648
- updates `blockExecutionTime`, `collectionExecutionTime`, `transactionExecutionTime`, `scriptExecutionTime` to be reported in milliseconds 
- adds proper histogram buckets to these metrics `blockExecutionTime`, `collectionExecutionTime`, `transactionExecutionTime`, `scriptExecutionTime`, `blockComputationUsed`, `collectionComputationUsed`, `transactionComputationUsed`, `scriptComputationUsed`,
> [Execution] update execution metrics setup with proper histogram buckets 

- engine/access/rpc/backend/backend_events.go
The formatting for the errors returned by this function should be more consistent. The error messages don't need to have an extra space in front, and we should use `status.Errorf` instead of `fmt.Errorf`.
> Update error codes in GetEventsForHeightRange

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.18.0-patch.4..v0.18.0-patch.5
> Update to Cadence v0.18.0-patch.5

- .github/workflows/ci.yml
... when `auto-cadence-upgrade/` is the base branch.
If it does it will make it easier to tell which cadence updates are ready to merge.
> Fix cadence auto update CI not running

- engine/execution/convert.go
- engine/verification/utils/unittest/fixture.go
- module/chunks/chunkVerifier.go
This PR : 
- patches the test logic to create fixtures for integration tests
- fixes the issue in the chunk verifier on what tx index to use for system chunk transaction
> [VER] Patch verification integration code

- crypto/bls.go
- crypto/bls12381_utils.c
- crypto/bls12381_utils.h
- crypto/bls_multisig.go
- crypto/build_dependency.sh
- crypto/dkg_feldmanvss.go
- crypto/dkg_feldmanvssq.go
- crypto/dkg_jointfeldman.go
- crypto/relic_build.sh
- crypto/thresholdsign.go
The diff contains:
- a lot of changes that concern parts of the library we don't use (other curves a la BN, BLS24-X, BLS12-383 ...), integer protocols (ETRS), field extension machinery ...
- otherwise irrelevant changes, e.g. CI/CD
- some memory bug fixing
[Formatted Log](https://gist.githubusercontent.com/huitseeker/e8bbd3f0475ebe93277bdfd46d9424de/raw/385a3dba9fc927b76f1c04e4e96474bff99cab7c/gistfile1.txt)
[Full Changeset](https://github.com/relic-toolkit/relic/compare/7a9bba7f..9206ae5)
**Benchmark Diff:**
`benchstat ~/old_relic.txt ~/new_relic.txt `
```
name                           old time/op  new time/op  delta
ScalarMult/G1-8                 144µs ± 0%   142µs ± 0%   ~     (p=1.000 n=1+1)
ScalarMult/G2-8                 329µs ± 0%   326µs ± 0%   ~     (p=1.000 n=1+1)
HashToG1-8 …
```
> [crypto] Update relic to 9206ae5

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
This is to have the next canary use the same version of cadence as current mainnet, with all the patches we've applied
> Update to same cadence version as currently on mainnet

- module/metrics.go
- module/metrics/compliance.go
- module/metrics/noop.go
- module/mock/compliance_metrics.go
- state/protocol/badger/mutator.go
- state/protocol/badger/mutator_test.go
- state/protocol/badger/state.go
- state/protocol/badger/state_test.go
Resolves https://github.com/dapperlabs/flow-go/issues/5587.
- Adds and sets `consensus_compliance_current_epoch_counter` metric on opening the state, bootstrapping the state and on an epoch boundary
- Adds and sets `consensus_compliance_current_epoch_phase` metric on opening the state, bootstrapping the state and also on phase transitions
- Adds tests for metric calls
> Add metric to track Current Epoch Phase and Counter

- Makefile
Check it matches the script crypto/build_dependency.sh
Add that check to CI (tidy)
- avoids accidental relic updates,
- avoids forgetting to update the script when updating the submodule
> [crypto] Add a Makefile target that checks the relic submodule version

- .github/workflows/ci.yml
There was one more mistake after https://github.com/onflow/flow-go/pull/941: the pattern matching does not account for `/` which it should.
see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet:
> `*`: Matches zero or more characters, but does not match the `/` character. For example, `Octo*` matches `Octocat`
> `**`: Matches zero or more of any character.
> Fix cadence auto update CI not running 2

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.18.0-patch.5..v0.18.0-patch.6
> Update v0.19 to Cadence v0.18.0-patch.6

- .github/workflows/ci.yml
9ae7a18c949d2eb7507459b3ecb8e72b7fb42f2c introduced changes to dependencies and mocks. 
This PR ~~adjusts~~ adjusted for them as they make some of our makefile targets fail on go 1.16
This PR's first 2 commits ~~is~~ was exactly the result of checking out master and running `make ci` on go 1.16.
the last commit runs CI in parallel on go 1.16
> Run CI in parallel on go 1.16

- go.mod
1. We run CI on go 1.15, 1.16
2. Security updates are pushed for the last two released go versions, as per [the security policy](https://golang.org/security), so 1.13 and 1.14 are no longer supported,
3. Our compilation on a go 1.13 fails with the following messages: https://gist.github.com/huitseeker/760c98621531ff226bb4afdb8ef8ec22
4. Cadence already [requires 1.15](https://github.com/onflow/cadence/blob/cd7a7a4830000172119e34c2005aebac21415828/go.mod#L3)
> Update the min go version to 1.15

- engine/consensus/sealing/core.go
- module/chunks/chunk_assigner.go
Since we are in the second phase, we can update the default to be `1`, and keep the option to set as `0` using flag
> require construction seal with at least 1 approval by default

- cmd/bootstrap/cmd/util.go
Adds exported funcs that wrap seed generation util funcs. This is needed to use key generation util funcs in other projects.
> add exported wrapper funcs for random seed util

- network/test/middleware_test.go
> cd network
> go test -v   -race -timeout 60s -run TestMiddlewareTestSuit  ./...
Output:
> github.com/onflow/flow-go/network       [no test files]
> ?       github.com/onflow/flow-go/network/codec/json    [no test files]
> ?       github.com/onflow/flow-go/network/message       [no test files]
> ?       github.com/onflow/flow-go/network/mocknetwork   [no test files]
> testing: warning: no tests to run
> PASS
> ok      github.com/onflow/flow-go/network/p2p   (cached) [no tests to run]
> testing: warning: no tests to run
> PASS
> ok      github.com/onflow/flow-go/network/queue (cached) [no tests to run]
> ?       github.com/onflow/flow-go/network/stub  [no test files]
> === RUN   TestMiddlewareTestSuit
> === RUN   TestMiddlewareTestSuit/**TestEcho**
> 
> WARNING: DATA RACE
> Write at …
> fixing race conditions in middleware_test unit test

- engine/common/synchronization/engine.go
- engine/consensus/ingestion/engine.go
- engine/consensus/sealing/engine.go
- engine/enqueue.go
- engine/enqueue_test.go
- engine/errors.go
This PR is a suggestion for amending PR https://github.com/onflow/flow-go/pull/1001
At the moment, the `synchronization.Engine` bubbles up any networking errors from failed sends. Hence, they eventually crash the engine: https://github.com/onflow/flow-go/blob/538637074415a3ec41c76f78f395d4bec7583ca6/engine/common/synchronization/engine.go#L349-L352
[Best practise for the Flow protocol implementation](https://www.notion.so/dapperlabs/Technical-Product-Meeting-with-Dete-054824f0be334392806e1e39641afe48#43f0a2f00be541b48ba880c0855e078c) is to consistently distinguish between 
* expected errors as part of normal protocol → log error 
* unexpected errors in protocol logic (bug; potential security exploit) → crash node
Current situation:
* The `synchronization.Engine` has recently been …
> proposal for handling networking errors in `synchronization.Engine`

- module/common.go
This PR updates the Godoc for `ReadyDoneAware` to more clearly define the conventions for its implementation. There are many different implementations in the code base which interpret the `Ready` and `Done` methods to mean different things (see https://github.com/dapperlabs/flow-go/issues/5702). 
In particular, the implementations are inconsistent regarding the concurrency-safety and idempotency of these methods. It is also not clear by looking at the interface whether the `Ready` / `Done` methods actually provide the mechanism to start / stop the module, or simply return channels that are closed when the module is started / stopped via some other means (in the latter case, how does one start / stop the module?).
Documenting the interface will hopefully lessen the confusion, and encourage …
> Update Godoc for ReadyDoneAware

- .github/workflows/ci.yml
- .golangci.yml
- cmd/bootstrap/transit/cmd/crypto_test.go
- cmd/bootstrap/transit/cmd/pull.go
- cmd/bootstrap/transit/cmd/utils.go
- engine/execution/state/delta/delta.go
- utils/grpc/grpc.go
This impacts the check of the `rootsnapshot` file: CLI users would have to run the `sha256sum` command-line utility on it instead of `md5sum`
> Clean up DefaultServerTLSConfig & an unnecessary md5

- network/middleware.go
- network/mocknetwork/middleware.go
- network/p2p/libp2pNode.go
- network/p2p/libp2pNode_test.go
- network/p2p/middleware.go
Forks a couple straightforward fixes discovered while working on libp2p peer discovery:
- removes a long-deprecated middleware method
- the interaction between the `allowList` flag in the libp2pNode constructor and `UpdateAllowList` can create a crasher, this fixes it
> [network, easy] Chores & small bugs in middleware / p2p

- engine/execution/computation/computer/computer.go
- fvm/blueprints/system.go
- module/chunks/chunkVerifier.go
The system chunk assumed the FlowEpoch contract was deployed to the service account, which for some networks is not true, including canary.
> Fix import in system chunk

- cmd/scaffold.go
A couple of points here:
* Since this `Ready` and `Done` will likely be exposed to external callers (DPS), it is even more important than ever that we guarantee idempotency and concurrency-safety. Hence, we should use `LifecycleManager` here.
* `engine.unit` was originally intended for use by engines, so it doesn't really fit for this usecase anyways. `LifecycleManager` is more generally intended for use by `ReadyDoneAware` modules.
* Since we are already checking the timeout in `Run`, we don't have to do so in `handleComponent` and `handleDoneObject`. Note that we don't need to check the timeout in `Ready` or `Done`, since the caller of those methods will receive a channel and they can implement any timeout they want themselves.
> Use lifecycle manager instead of engine unit

- cmd/node_builder.go
- cmd/scaffold.go
First set of change to run the unstaked AN as a library instead of a standalone node -
1. Currently, the `NodeBuilder.Run()` method starts all modules and components and then blocks till a SIGINT is received. However, for the unstaked AN to run as a library, its lifecycle will be managed by the caller (DPS). This PR makes the NodeBuilder `ReadyDoneAware` so that it can be started and stopped on-demand. The `Run()` in turn now calls `Ready` and `Done`.
2. All the calls to `os.Exit` have been restricted to the `Run()` method.
> making scaffold ReadyDoneAware

- integration/loader/main.go
Fixes the chain ID of the `loader` as the mitigation to the following crash-loop on `benchnet1`:
```
calling get account for service account client: rpc error: code = InvalidArgument desc = address 8c5303eaa26202d6 is invalid for chain flow-benchnet"
Jul 30 23:12:39 loader-001 systemd[1]: flow-loader.service: Main process exited, code=exited, status=1/FAILURE
```
> [Integration] Fixes loader chain ID 

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.18.0-patch.5..v0.18.0-patch.6
> Update v0.18 to Cadence v0.18.0-patch.6

- ledger/common/encoding/encoding.go
- ledger/common/encoding/encoding_test.go
- ledger/common/hash/hash_test.go
- ledger/common/utils/testutils.go
- ledger/complete/ledger.go
- ledger/complete/ledger_test.go
- ledger/complete/mtrie/forest.go
- ledger/complete/wal/compactor.go
- ledger/complete/wal/compactor_test.go
- ledger/ledger.go
- ledger/trie.go
- module/observable/observable.go
- module/observable/observer.go
found while trying to read about / dig into the WAL:
- removes unneeded byte conversions,
- removes unused, untested functions either in test utils or for which there's a good alternative,
- makes `Test_Compactor/Compactor_creates_checkpoints_eventually` asynchronous but deterministic,
(introduces a minimalistic `Observable` interface that I know I'll reuse elsewhere, though not in this PR, see #1020 )
- Simplifies Compactor's start / stop slightly, thanks to @smnzhu 's LifeCycleManager
> [ledger] Ledger cleanups + make a test async

- module/metrics/compliance.go
- state/protocol/badger/mutator.go
- state/protocol/badger/mutator_test.go
This PR addresses the following problems:
* the counter metric was being set incorrectly in `CurrentEpochPhase`
* the phase transition from committed to staking was not captured in the metrics
Metrics results over several epochs on localnet:
> [v0.20] Fix bugs with epoch phase & counter metrics

- network/p2p/connManager.go
- network/p2p/libp2pNode.go
- network/p2p/sporking_test.go
- network/test/echoengine_test.go
- network/test/epochtransition_test.go
- network/test/meshengine.go
- network/test/meshengine_test.go
- network/test/middleware_test.go
- network/test/testUtil.go
- network/topology/topology_test.go
The network tests in `TestMeshNetTestSuite` and `TestMiddlewareTestSuit/TestUnsubscribe` depend on waiting for mesh formation between libp2p nodes, and use `time.Sleep` for that, and are therefore flaky (see [issue](https://github.com/dapperlabs/flow-go/issues/5710)). 
The present PR:
- defines a customized `ConnManager` in `testUtils` that captures the *tagged* `Protect` events generated by gossipsub at the establishment of a PubSub mesh, using the `observable.Observable` interface,
- injects it in test suite setup,
- registers an `observable.Observer` instance that waits for the correct number of such events to notice the establishment of the mesh,
- thereby replacing the `time.Sleep` instances,
- does some cleanup (removes one minor race in a mock, quiet down the logs in a test). …
> [network] Makes mesh-dependent network tests asynchronous

- crypto/bls.go
- crypto/bls12381_utils.go
- crypto/bls_multisig.go
- crypto/bls_test.go
Adds a function to return an invalid BLS signature that fails verification early under any message and public key.
> add a function to return an invalid BLS function

- Makefile
upgrade to the latest to fix errors from `make lint` in local
> upgrade golangci-lint

- crypto/bls_test.go
The rapid rng has sometimes problematic behavior.
See:
https://github.com/onflow/flow-go/pull/1085/checks?check_run_id=3285304328#step:4:2132
https://github.com/onflow/flow-go/runs/3293037063
we also detected a bad interaction with require.NoError in the past
The grouping of the rapid checks in a single go unit test makes it difficult to pinpoint where things
could have gone wrong -> this splits each rapid test in their go test.
> [crypto, testonly] split rapid tests in go tests

- consensus/hotstuff/sig_validator.go
- consensus/hotstuff/sigvalidator/combined_qc_validator.go
- consensus/hotstuff/sigvalidator/single_qc_validator.go
- consensus/hotstuff/v2/validator/validator.go
This PR adds QC Validator interfaces for consensus voting.
Now we have a few Validators, here are the difference:
1. `Validator` it's used by EventHandler and VoteCollector to validate block and vote. The rules to check are hotstuff specific, but it doesn't check vote/block's signature. The Validator can perform checks statelessly. It uses QCValidator to validate `Block.QC`
2. `SigValidator` is used by VoteCollector to check Vote or Block's signature. Since the signature validation is stateful. The SigValidator is stateful. 
3. `QCValidator` is used by EventHandler to validate block's QC. Validation on QC's signature can be done stateless, so this module is stateless.
> [Consensus Voting] add QC validator interface

- network/p2p/libp2pNode.go
Canary network nodes are currently down because of the following error:
> Aug 13 17:20:29 execution-001 docker[916872]: {"level":"fatal","node_role":"execution","node_id":"4beb93e69d8f3de3771336881b589330b1e1be7b0256467a36a1870855a2d828","error":"could not update approved peer list: could not generate address info: could not get translate identity to networking info 80514ec67dcd19a1000000000000000000000000000000000000000000000001: could not parse address ddba41333a7f7605ff0a5cd2d2966819c2c2aba71728826b5b10478dd49feec804a0eb063c3ffc2c55f76318f3f2386a181cbefbfb49495de2297bf5937a05ad: address ddba41333a7f7605ff0a5cd2d2966819c2c2aba71728826b5b10478dd49feec804a0eb063c3ffc2c55f76318f3f2386a181cbefbfb49495de2297bf5937a05ad: missing port in address","time":"2021-08-13T17:20:29Z","message":"failed …
> skip returning error is an identity address on chain cannot be parsed

- access/legacy/convert/convert.go
- cmd/bootstrap/run/block.go
- cmd/util/cmd/exec-data-json-export/block_exporter.go
- consensus/hotstuff/blockproducer/block_producer.go
- consensus/hotstuff/model/block.go
- consensus/hotstuff/model/proposal.go
- engine/common/rpc/convert/convert.go
- model/flow/header.go
- model/flow/header_test.go
- module/builder/consensus/builder.go
- module/finalizer/collection/finalizer.go
- module/finalizer/collection/finalizer_test.go
- network/codec/roundTripHeader_test.go
- state/cluster/root_block.go
- state/protocol/badger/snapshot.go
- state/protocol/badger/snapshot_test.go
- storage/badger/operation/headers_test.go
- utils/unittest/fixtures.go
This PR 
- updated the signature field for header.
- renamed the `ParentVoterSig` field to `ParentVoterSigData`
- renamed the `ProposerSig` field to `ProposerSigData`
Since the signer signature could be a combination of multiple signature, it makes more sense to be `[]byte` type than `crypto.Signature`.
> Update header's signature field

- consensus/hotstuff/voteaggregator/vote_collectors.go
- consensus/hotstuff/votecollector/collection_base.go
- consensus/hotstuff/votecollector/collection_cluster_vote_collector.go
- consensus/hotstuff/votecollector/combined_aggregator.go
- consensus/hotstuff/votecollector/consensus_verifying_vote_collector.go
- consensus/hotstuff/votecollector/random_beacon_reconstructor.go
The problem with linting is that all of remaining errors are due to unused variables/functions. We can't simply fix it, need to write code, disable linting or comment it out.
> [Consensus] Disabled linting for unused symbols in new implementation

- cmd/bootstrap/transit/cmd/pull.go
- network/p2p/libp2pNode.go
T-systems ran into an issue in mainnet-8 spork where the transit script key timing out when trying to download root.checkpoint. `root.checkpoint` can be upwards of 18GB and may take more than 30 seconds to download.
Hence bumping up the timeout value for `transit pull`
> increasing timeout of transit pull command to accommodate the download of the root.checkpoint

- crypto/bls_crossBLST_test.go
The blst keygen is unstable on 1.15 (in ways that are hard to reproduce), leading to CI failures. https://github.com/onflow/flow-go/pull/1119 disabled the use of the blst keygen in generating valid slices of scalar bytes for cross-testing bls.go with BLST, this completes the job in de-activating the use of the keygen for creating siganture material.
We leave the auxiliary functions in place for future upgrades (the blst keygen is stable on go 1.16 and some architectures on go 1.15)
> [crypto] Unplug ValidSignatureBytesBLST

- crypto/bls.go
- crypto/ecdsa.go
- crypto/ecdsa_test.go
- crypto/sign.go
- crypto/sign_test_utils.go
- network/p2p/keyTranslator.go
- network/p2p/keyTranslator_test.go
- network/p2p/libp2pNode.go
- network/p2p/libp2pUtils.go
- network/p2p/libp2pUtils_test.go
- network/test/middleware_test.go
- utils/grpc/grpc.go
- utils/grpc/grpc_test.go
This:
- implements compressed (32/33 bytes instead of 64) (de)serialization for `crypto.PublicKey`. 
+ This is something we want to work on transitioning to more widely next cycle,
+ it's a milestone towards [#5739](https://github.com/dapperlabs/flow-go/issues/5739)
- re-activates message signing and verification, closes [#5634](https://github.com/dapperlabs/flow-go/issues/5634)
- ~~checks the OriginID contained in a message with respect to the (now cryptographically-verified) libp2p source, closes #1115~~
Edit: Splitting this in 2 PRs, to work on the concurrency issues w/ @vishalchangrani : this is the straightwforward crypto PR that will go easier
> [network, crypto] Compressed serialization, key conversions and message signing

- go.mod
- go.sum
- network/p2p/unstaked_translator.go
- network/p2p/unstaked_translator_test.go
This shows we need to use Secp256k1 on the bootstrap key generation for unstaked Access nodes (and positive keys at that), which I'll add in a further PR. 
Unit-tests and validates the ID translation for unstaked network.
> [network] Validate Unstaked ID translation

- .github/workflows/ci.yml
- Makefile
- crypto/Makefile
This PR:
- removes the race detector in default CI tests, please refer to [individual commit message](https://github.com/onflow/flow-go/pull/1166/commits/d5c9face67cbfa88084f4e506e6f4ee9b33be591) for details on the reasoning.
- fixes a few CI issues left over after #1160 
You can find a successful [run with the new CI here](https://github.com/onflow/flow-go/runs/3364889475?check_suite_focus=true).
> [CI] Fix blst cross-tests & remove race in CI

- network/p2p/middleware.go
- network/p2p/readConnection.go
- network/test/middleware_test.go
Follow-up to #1163.
This closes #1115 (finally) by adding anti-spoofing to `SendDirect` connections as well.
> [network] Check the originID in sendDirect too

- network/p2p/middleware.go
- network/p2p/readConnection.go
- network/p2p/readSubscription.go
- network/test/middleware_test.go
Contributes to #1115.
Follow-up of #1129.
Edit: there was no problem with the integration tests, 🤦 
However, TestMiddlewareTestSuit/TestUnsubscribe is still flaky based on the delay in the last step (sending the message once a mesh has formed). But it is problematic on master, see [[1]](https://github.com/onflow/flow-go/runs/3357056741) [[2]](https://github.com/onflow/flow-go/runs/3356508175), so this is not relevant to this PR per se.
> [network] Check the OriginID of a libp2p message corresponds to its authenticated source

- engine/execution/state/bootstrap/bootstrap_test.go
- fvm/blueprints/epochs.go
- fvm/bootstrap.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- utils/unittest/execution_state.go
This PR updates the `flow-core-contracts` version to `v0.7.7` from `v.0.7.6`. This includes changes made during the last spork cycle.
> Update `core-contracts` to `v0.7.7`

- cmd/bootstrap/utils/key_generation.go
- cmd/bootstrap/utils/key_generation_test.go
This introduces a generator for the unstaked Access Nodes, which by convention only have positive secp256k1 keys.
The keys in question have a specific format (positive ECDSA Secp256k1 keys) because:
- they are meant to serve ephemeral nodes,
- allow a bijection between flow.NodeID, flow.NetworkPublicKey, libp2p.PeerID, libp2p.PublicKey
- hence allowing us to only retain the minimum amount of information for these nodes.
For this bijection, see #1165 and #1129.
This is to be used in a bootstrap of the unstaked Access Node post #1133. 
For now, having this in master allows the direct bootstrapping of network in tests by creating suitable libp2p peers.
> [bootstrap] Key Generation for Unstaked Access Nodes

- fvm/transactionStorageLimiter.go
This relates to: https://github.com/onflow/flow-go/pull/1175
In https://github.com/onflow/flow-go/pull/1175 two separate things were done to fix iterating (and exiting early) over a random list:
1. order the list
2. don't exit early and use multierror to aggregate the errors if there is more then one.
Only one of these measures is actually required to solve the problem. Since number 2 introduces new error semantics it is better to remove that part from the v0.20 branch, and just go with number 1 for any patches.
Number 2. can go into the next spork the usual way.
This PR reverts number 2 from v0.20.
> Remove storage multierror from v0.20

- module/signature/threshold_non_relic.go
Previously, this was inconsistent with the `relic` version of the file, so that builds not using `relic` importing this package failed to compile.
> Use the correct type in NewThresholdSigner

- .github/workflows/ci.yml
The Go bindings for BLST run with unconditional [-D__ADX__ flag](https://en.wikipedia.org/wiki/Intel_ADX). While that is fine for newer
machines, GH Actions run tests on a variety of underlying architectures, some of which do not have
those CPU extensions. See:
https://docs.microsoft.com/en-ca/azure/virtual-machines/dv2-dsv2-series#dsv2-series
As a consequence, this runs detection before setting CGO compilation flags approaprately.
> [ci, crypto] Detect CPU arch and feed that info to blst

- .github/workflows/ci.yml
We're developing several significant features using branches these days: unstaked AN, Epochs, Consensus V2 ...
This activates CI runs on branches named `feature/XXX`, on PRs targeting them and on pushes. 
Of course those branches cannot be created publicly.
Hopefully we'll thereby get CI signal on those big feature branches.
> [CI] Activate CI for branches

- engine/common/synchronization/finalized_snapshot.go
This fixes a bug introduced in https://github.com/onflow/flow-go/pull/1068 that breaks range requests for the sync engine.
> Fix sync engine bug

- cmd/access/node_builder/staked_access_node_builder.go
- cmd/access/node_builder/unstaked_access_node_builder.go
- cmd/node_builder.go
- cmd/scaffold.go
- network/p2p/dht_test.go
- network/p2p/dns/cache.go
- network/p2p/libp2pNode.go
This PR rolls DNS caching for LibP2P into production and makes its TTL configurable through a flag. Note that this is the first version of our DNS caching implementation, which is synchronized. We have an asynchronized implementation coming soon!
> [Networking] Rolls in DNS caching

- engine/execution/computation/computer/computer.go
- engine/execution/computation/computer/computer_test.go
(cherry picked from commit 9bb35401c675e524b82a3df397cffd29cf887f0b)
> Backport of https://github.com/onflow/flow-go/pull/1272

- engine/common/synchronization/engine_test.go
- engine/common/synchronization/request_handler.go
closes #https://github.com/dapperlabs/flow-go/issues/5836
> clamping sync requests

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Includes the fixes: https://github.com/onflow/cadence/compare/v0.19.0...v0.19.1
> Update to Cadence v0.19.1

- cmd/access/node_builder/access_node_builder.go
- cmd/access/node_builder/staked_access_node_builder.go
- cmd/access/node_builder/unstaked_access_node_builder.go
* Fix a few error conditions where the fatal error was never thrown because `Msg()` was not called.
* Update Module and Component blocks to return the error instead of throwing since the handlers will do that automatically. This makes them more consistent with other uses in the codebase.
> Improve error handling in access node

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
References: https://github.com/onflow/cadence/pull/1033
> Auto Cadence Update: Add type inferring for func-args when there are no generics

- engine/unit.go
- engine/unit_test.go
- network/p2p/peerManager.go
We are observing synchronized goroutine spikes causing consensus finalization issues on large committees on benchnet, with the same period as this peer update process. 
This PR:
* Adds a uniform random delay to the initial launch of the peer update requesting routine, so that peer updates are not synchronized across the network
* Updates `engine.Unit` to exit goroutines launched with `LaunchPeriodically` immediately, even if they are waiting for the initial delay period when the unit is torn down
Run on Benchnet without this fix:
With this fix:
> Add random delay to periodic peer update thread

- module/builder/consensus/builder.go
- module/builder/consensus/builder_test.go
- module/chunks.go
- module/chunks/chunk_assigner.go
- module/validation/seal_validator.go
- state/protocol/badger/snapshot.go
If consensus nodes are far behind and catching up on _finalized_ block, it can happen that they fail to validate a block and therefore get stuck. This is caused by a subtle edge case in the builder logic. See [incident report](https://www.notion.so/dapperlabs/Incident-Name-09-15-2021-e1c979212c54451abdb8200982b26b27) (notion doc) for details.
This PR implements _step 1._ described in [#5857](https://github.com/dapperlabs/flow-go/issues/5857). 
* reverted [emergency-fix](https://github.com/onflow/flow-go/pull/1300) that was deployed to recover mainnet
* the [`consensus.Builder`](https://github.com/onflow/flow-go/blob/alex/5857_mainnet_quick-fix/module/builder/consensus/builder.go) logic is patched in a bit more of a hacky way
* refactored builder tests according to account for the updated …
> Mainnet quick fix fo address problems of nodes failing to catch up

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
References: https://github.com/onflow/cadence/pull/1138
> Auto Cadence Update: Add limit on call stack depth

- module/validation/seal_validator.go
interim version that enforces a gap (forwards-compatible) but still trusts the block proposer with the verifier assignment (backwards compatible)
> interim version

- cmd/util/cmd/execution-state-extract/execution_state_extract.go
In order to re-spork testnet with the same version, we need to disable the migrations that we have already applied.
> Disable unnecessary migrations

- cmd/util/ledger/migrations/storage_v5.go
Reducing the log level to reduce the clutter of logs printed on the console. Can enable them by enabling debug level logs.
Fatal/Error levels are also reduced to Warn/Debug because such logs are not end-of-world for the tool, even though they hint something wrong in the decoded value.
> Reduce log level in migration tool

- network/p2p/libp2pNode.go
Let's print out the errors encountered so far.
> [Network] improve error logging

- cmd/scaffold.go
Port of https://github.com/onflow/flow-go/pull/1360 to v0.22.
> Port to v0.22: Enable transaction fees on mainnet

- cmd/scaffold.go
- network/p2p/libp2pNode.go
Previously, this was disabled on everything except localnet. 
Instead, we can probably only disable it for ghost nodes.
> [Network] enable subscription filter except ghost node

- module/synchronization/core.go
- module/synchronization/core_rapid_test.go
- module/synchronization/status.go
I highly suggest looking at individual commits (code AND messages) to review.
When receiving a block (`HandleBlock`), we test its status in existing tables to see if it was already received. 
If a `Received` status is in the height table, we reject the block, without checking if the block we are receiving is different than the one we've already received at the same height.
Moreover, this logic applies even if all blocks involved are requested and received by blockID only.
This:
- makes sure we report a request status upon block reception (`getRequestStatus`) favoring requests by ID,
- adds basic property testing, which exercises the bug from on a forest of blocks which includes forks,
- does not change anything to the pattern or volume of requested heights.
Fixes …
> [consensus, synchronization] Fix forks preventing reception of blocks at same height

- cmd/bootstrap/transit/cmd/pull_root_block.go
operator ran into this error-
> flow@flow--testnetv2--consensus-2:~/testnetv2/bin$ boot-tools/transit pull-root-block -t consensus-test -b /home/flow/bootstrap
> <nil> INF downloading root block
> <nil> INF downloading root block file from transit servers dest=/home/flow/bootstrap/public-root-information/root-block.json source=public-root-information/root-block.json
> <nil> FTL could not download google bucket file error="error creating GCS object reader: storage: object doesn't exist"
The source `source=public-root-information/root-block.json` is incorrect and does not mention the bucket name
> fixing the rootblock.json download path

- module/synchronization/core.go
See https://github.com/onflow/flow-go/pull/1377#discussion_r718934777 for context.
Note that `RequestHeight` api is currently not being used anywhere in the code. Shall we just delete this method?
> [Synchronization] update HandleHeight logic

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Includes https://github.com/onflow/cadence/commit/5ecf81d832c92d6032e853b6bd347ec6d189c02d
> Update v0.22 to Cadence v0.20.0-beta6

- cmd/scaffold.go
Fees will get turned on on mainnet soon. Currently they are both disabled and set to `0.0`. They need to be enabled (with this PR) during a spork. After that they can be set to non `0.0` when desired.
I verified that:
- mainnet tx fees are really set to `0.0`
- having tx fees on and set to `0.0` doesn't lead to any unexpected problems (on the emulator)
- having tx fees on and set to `0.0` doesn't emit fee deduction events (see the [contract](https://github.com/onflow/flow-core-contracts/blob/51b4191ee4367dc33e868b91a32e9cdab98fd519/contracts/FlowServiceAccount.cdc#L65))
> Enable transaction fees on mainnet

- engine/unit.go
- network/p2p/peerManager.go
- network/p2p/peerManager_test.go
The flaky test in question is `TestPeerManagerTestSuite/TestPeriodicPeerUpdate`, but the actual issue is in the implementation of `PeerManager` and `engine.Unit`.
The root cause is described in comments below.
Before the change, `go test -race -count 10 -tags relic -run TestPeerManagerTestSuite -testify.m TestPeriodicPeerUpdate` almost always has at least one failure
After the change, never fails.
> [Flaky test] peer manager flakiness fix

- engine/consensus/approvals/tracker/record.go
Lint error:
> engine/consensus/approvals/tracker/record.go:41:17: SA4010: this result of append is never used, except maybe in other appends (staticcheck)
>                         chunksInfo = append(chunksInfo, chunk)
> fixing lint error

- cmd/collection/main.go
- cmd/consensus/main.go
- integration/localnet/Makefile
`ValidateFlags` needs to be called before `Initialize()`.
> [Consensus] fix startup time

- engine/verification/fetcher/engine.go
Backports https://github.com/onflow/flow-go/pull/1416 against `v0.22`
> [v0.22] backports fixing verification crash loop

- consensus/hotstuff/model/errors.go
- consensus/hotstuff/votecollector/statemachine.go
I think the following code is vulnerable to wrapped errors: https://github.com/onflow/flow-go/blob/da30152b02bc18f9941463f720f176fb110dafc6/consensus/hotstuff/votecollector/statemachine.go#L84-L85
* we check that `err` is a (potentially wrapped) `DoubleVoteError`
* we directly cast to `DoubleVoteError`, which I think would fail for wrapped errors. 
At the moment, the `VotesCache` returns the pure `DoubleVoteError` without any wrapping: https://github.com/onflow/flow-go/blob/da30152b02bc18f9941463f720f176fb110dafc6/consensus/hotstuff/votecollector/vote_cache.go#L77
Therefore, the code works as is. Though the code is brittle, because it is easily broken during future maintenance. I think the consuming code should also tolerate a wrapped error
> Fix for error wrapping problem

- engine/common/synchronization/finalized_snapshot.go
- integration/tests/access/unstaked_node_test.go
Closes https://github.com/dapperlabs/flow-internal/issues/1614
These tests were disabled due to flakiness. See [this example failure](https://github.com/onflow/flow-go/runs/3974629291?check_suite_focus=true#step:6:4707)
The issue stemmed from indicating that the `FinalizedHeaderCache` component had finished shutting down by closing its `Done` channel without waiting for the actual worker routine to stop. This resulted in the node thinking all of the components were completely shut down and proceeding to close badger DB. Depending on the timing of the shutdown signals and new block headers, `FinalizedHeaderCache` may not be finished writing new data resulting in a segfault.
Fixed by explicitly waiting for the worker routine to finish before closing the `Done` channel.
> Fix flaky TestUnstakedAccessSuite/TestReceiveBlocks tests

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
This patches cadence to handle some type checking cases with user error.
> update cadence to use beta8-patch2

- consensus/recovery/recover.go
- consensus/recovery/recover_test.go
This PR fixes a bug that when hitting an invalid block during recovery, it should continue recover other blocks rather than stop
> [Consensus] Continue recover block when hitting invalid block

- engine/execution/state_synchronization/state_diff_storer.go
- engine/execution/state_synchronization/state_diff_storer_test.go
- go.mod
- go.sum
- integration/go.sum
- model/encoding/cbor/codec.go
- model/encoding/codec.go
- model/encoding/json/codec.go
- model/encoding/rlp/codec.go
- model/fingerprint/fingerprint.go
- model/flow/collection_test.go
- model/flow/event.go
- model/flow/event_test.go
- model/flow/header_test.go
- module/chunks/chunk_assigner.go
- network/compressor/lz4Compressor.go
- network/stub/hash.go
- network/test/block_exchange_test.go
- network/test/testUtil.go
- network/topology/topology_utils.go
The entire test run for a ~360 MB state diff takes ~26 seconds, of which the most time consuming is the assertion at the very end to check that there is no discrepancy between the stored and loaded state diff.
The time needed to actually store / load the state diff to / from disk is minimal (~2.5 and ~1.5 seconds, respectively). Note however that the blockstore used in this test is a dummy blockstore which simply writes files directly to the filesystem. Performance may vary with the eventual production blockstore, which will probably be using Badger.
```bash
smnzhu@Simons-MacBook-Pro ~/Documents/GitHub/flow-go % ls -la ~/Downloads/8aeb01b08a446434ea4746aaaec1c458fd24922e26a13e94842bafb74e681670.cbor
-rw-r--r--@ 1 smnzhu  staff  359949597 Oct  8 11:55 
smnzhu@Simons-MacBook-Pro …
```
> [State Sync Engine] state serialization module

- ledger/complete/ledger.go
- ledger/complete/mtrie/README.md
- ledger/complete/mtrie/flattener/forest.go
- ledger/complete/mtrie/flattener/iterator_test.go
- ledger/complete/mtrie/flattener/trie_test.go
- ledger/complete/mtrie/forest.go
- ledger/complete/mtrie/forest_test.go
- ledger/complete/mtrie/node/node.go
- ledger/complete/mtrie/node/node_test.go
- ledger/complete/mtrie/trie/trie.go
- ledger/complete/mtrie/trie/trie_test.go
Backport of PR https://github.com/onflow/flow-go/pull/1507 to master
> [Execution node] Trie pruning (backport to master)

- fvm/handler/programs.go
This is a rare edge case, when we hit the ledger interaction limit on loading a contract, while long term we should adjust the program handler to properly return an error, in this patch we only panic on fatal errors and ignore the rest.
> [Execution] patch ledger interaction limit error when hit on programs

- engine/collection/compliance/engine.go
- engine/collection/compliance/engine_test.go
- engine/collection/synchronization/engine.go
- engine/collection/synchronization/engine_test.go
- engine/collection/synchronization/request_handler.go
- engine/common/synchronization/engine.go
- engine/common/synchronization/engine_test.go
- engine/common/synchronization/request_handler.go
- engine/consensus/compliance/engine.go
- engine/consensus/compliance/engine_test.go
- engine/consensus/ingestion/engine.go
- engine/consensus/ingestion/engine_test.go
- engine/consensus/matching/engine.go
- engine/consensus/matching/engine_test.go
- engine/consensus/sealing/engine.go
- engine/consensus/sealing/engine_test.go
- engine/errors.go
This PR unifies error handling and they way we process message delivered from network layer or other components.
In nutshell:
- `Process/Submit` never returns `IncompatibleInputTypeError` since it expected byzantine inputs
- `ProcessLocal/SubmitLocal` doesn't tolerate `IncompatibleInputTypeError` and will propagate error to caller since input is trusted and it's unexpected. 
This PR has lots of boilerplate logic, I am trying to condense it into reusable component something like `engineBase` or `engineManager`. On other hand this can wait till we refactor `network.Engine` in favor of `network.MessageProcessor `
> [BFT] Error handling for engines

- model/flow/chunk.go
- model/flow/entity.go
This PR was originally meant to optimize the `Less` method of `ChunkList` with respect to `ID` method invocations (see this issue https://github.com/dapperlabs/flow-go/issues/5946). `Less` method of `ChunkList` was introduced earlier [by me](https://github.com/onflow/flow-go/commit/2a14fd5e92b8f28e6e3bb8ea6c52f33795720900) at the time we develop the very first version of the verification node. At that time, the purpose was to make the `ChunkList` implement the `sort` interface, hence, being sortable. 
However, after reviewing the use cases of `ChunkList` in our current codebase, we no longer require such sorting capability. This is also supported by the fact that chunks are uniquely addressed by their index within an execution result, so there is no longer a need for sorting them based on …
> [Verification] Removes less and swap methods of chunk list

- module/dkg/client.go
- module/epochs/qc_client.go
In cases where sealing is behind, using the latest sealed block can result in generating immediately-expired transactions. It is safe to use the latest finalized block for the purposes of the tx reference block.
> Use latest finalized (not sealed) reference block

- consensus/hotstuff/signature/type_encoder.go
- consensus/hotstuff/votecollector/combined_vote_processor_v2_test.go
This PR replaces `48` by the crypto constant for BLS signature length (the constant should not be assumed to be always 48).
> [voting V2] Use the crypto package constant for signature length

- consensus/hotstuff/signature/weighted_signature_aggregator.go
- consensus/hotstuff/signature/weighted_signature_aggregator_test.go
- consensus/hotstuff/votecollector/combined_vote_processor_v2.go
- consensus/hotstuff/votecollector/combined_vote_processor_v3.go
- consensus/hotstuff/votecollector/staking_vote_processor.go
There is a mistake in the current `NewWeightedSignatureAggregator` interface: it takes node identifiers as inputs and uses their staking keys as the low level verification keys. This is not correct because `WeightedSignatureAggregator` should also be used for random beacon keys. 
The PR updates the interface of `NewWeightedSignatureAggregator` to accept public keys as inputs.
> [consensus V3] update weighted aggregator interface

- fvm/fvm_test.go
This PR complements the existing tests for :
- BLS PoP verify
- BLS aggregate signatures
- BLS aggregate keys
It updates the handling of non-BLS algorithms and hashing algorithms. It also adds a full happy path test combining the 2 aggregating functions.
> [FVM BLS] add more tests

- SECURITY.md
For some reason this file has Non-Breaking-Spaces (U+00A0) instead of normal spaces:
```
00000190: 6964 656c 696e 6573 c2a0 466f 72c2 a052  idelines..For..R
000001a0: 6573 706f 6e73 6962 6c65 c2a0 4469 7363  esponsible..Disc
000001b0: 6c6f 7375 7265 2a2a 0a0a 5765 c2a0 6173  losure**..We..as
000001c0: 6bc2 a074 6861 74c2 a061 6c6c c2a0 7265  k..that..all..re
000001d0: 7365 6172 6368 6572 73c2 a061 6468 6572  searchers..adher
000001e0: 65c2 a074 6fc2 a074 6865 7365 c2a0 6775  e..to..these..gu
```
(Note all these `c2a0` instead of `0x20`)
PS. Also note that a subset of links on https://docs.onflow.org/bounties/responsible-disclosure/ are currently broken.
> security: replace nbsp with normal spaces

- module/metrics/example/execution/main.go
I would suspect that `^` here ment exponentiation.  No functional changes except for the magnitude of random values.
> Metrics: fix randomness in execution's example

- CODEOWNERS
"Observation" was renamed to "Access" early last year.
PS. Assigned to @vishalchangrani based on the renaming work in 654bfa76a074242495c183d8fa016c4fd09b69ac (#3170).  Feel free to re-aasign.
> github: fix code ownership for access

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Cadence v0.20.0-beta10 was a success and got re-tagged as v0.20.0.
v0.20.1 fixes a build/dependency error.
> Update to Cadence v0.20.1

- go.mod
- integration/go.mod
`flow-go` currently does not build when using it as a dependency:
```
../../../go/pkg/mod/github.com/onflow/flow-go@v0.23.2-0.20211125190211-7b31c986316e/model/flow/identifier.go:115:2: undefined: "github.com/onflow/flow-go/crypto/hash".ComputeSHA3_256
../../../go/pkg/mod/github.com/onflow/flow-go@v0.23.2-0.20211125190211-7b31c986316e/model/flow/identifier.go:124:2: undefined: "github.com/onflow/flow-go/crypto/hash".ComputeSHA3_256
```
Update the `flow-go/crypto` dependency to the latest version. This is effectively the same as if the `replace` statement would be effective.
Also see https://axiomzen.slack.com/archives/C015G65HR2P/p1637867663058600
> Update to latest flow-go/crypto, 7b31c98

- consensus/hotstuff/forks/forkchoice/forks_test.go
- consensus/hotstuff/forks/forks.go
- consensus/hotstuff/notifications/log_consumer.go
- consensus/hotstuff/notifications/noop_consumer.go
- consensus/hotstuff/notifications/pubsub/distributor.go
- consensus/hotstuff/notifications/pubsub/finalization_distributor.go
- consensus/hotstuff/signature/randombeacon_reconstructor.go
- consensus/hotstuff/signature/weighted_signature_aggregator.go
- consensus/hotstuff/voteaggregator/vote_aggregator_v2.go
- consensus/hotstuff/voteaggregator/vote_collectors.go
- consensus/hotstuff/votecollector/combined_vote_processor_v2.go
- consensus/hotstuff/votecollector/combined_vote_processor_v3.go
- consensus/hotstuff/votecollector/factory.go
- consensus/hotstuff/votecollector/statemachine.go
batch update from:
```
var _ YYY = &XXX{}
```
to
```
var _ YYY = (*XXX)(nil)
```
in order to verify the implementation of interface without allocating memory
> use nil to verify implementation

- cmd/access/node_builder/staked_access_node_builder.go
- cmd/access/node_builder/unstaked_access_node_builder.go
- cmd/scaffold.go
This PR updates the usages of [p2p.NewMiddleware](https://github.com/onflow/flow-go/blob/923546c75a80e6078283d8adf6ef78dbb03b651a/network/p2p/middleware.go#L114) to use SporkID() not RootBlockID
> update AN builders and scaffold to use spork id for mw

- fvm/crypto/bls_wrapper_relic.go
- fvm/crypto/crypto.go
- fvm/crypto/crypto_test.go
This PR updates the crypto FVM error handling:
- user errors are returned to Cadence along with the unset default value
- non-user errors panic
> FVM errors suggestions

- engine/access/rest/collections.go
- engine/access/rest/collections_test.go
- engine/access/rest/converter.go
- engine/access/rest/converter_test.go
- engine/access/rest/generated/model_collection.go
- engine/access/rest/generated/model_transaction.go
- engine/access/rest/generated/model_transaction__expandable.go
- engine/access/rest/generated/model_transaction_result.go
- engine/access/rest/link_generator.go
- engine/access/rest/scripts.go
- engine/access/rest/scripts_test.go
- engine/access/rest/transactions.go
- engine/access/rest/transactions_test.go
- go.sum
This PR implements handlers for expand fields and adding more tests. Converter tests were added with implementing expendables and links as part of that functionality which allows us to test different combinations of response generation without handlers.
> REST: Add improvements and tests to handlers

- engine/access/ingestion/engine.go
- engine/access/ingestion/engine_test.go
Fixes: https://github.com/onflow/flow-go/issues/1623
> Adding a block height threshold to re-request missing collections 

- .github/workflows/bench.yml
Bench tests were being run grouped. Given test A and B with shuffle on and count 3 they would either run like this AAA BBB or like this BBB AAA.
This fix changes the use of the -count flag into a for loop. Which means all test are ran once in a shuffled order, and then this repeats N times.
This tweak causes the uncertainty in the results to go up, which in turn causes the prediction of how much the performance changes to be more conservative.
Example:
```
name                                                                old time/op  new time/op  delta
RuntimeTransaction/reference_tx-8                                   25.0ms ± 9%  23.9ms ± 1%   ~     (p=0.905 n=5+4)
RuntimeTransaction/convert_int_to_string-8                          25.5ms ± 3%  26.6ms ± 5%   ~     (p=0.310 n=5+5) …
```
> Tweak FVM bench to be more stable

- cmd/execution/main.go
closes: https://github.com/dapperlabs/flow-go/issues/5999
This change logs the epoch number from the FlowEpoch smart contract and from the protocol state on execution node startup.
Excerpt from the logs:
```json
[
{
"level": "info",
"node_role": "execution",
"node_id": "385341c8b20cd5ad80c84092693279185cb0144465a4af56b2ea43990a780a8a",
"component": "provider engine",
"contractEpochCounter": 0,
"protocolStateEpochCounter": 0,
"flowEpochAddress": "0xf8d6e0586b0a20c7",
"time": "2021-12-06T15:57:10Z",
"message": "Fetched epoch counter from the FlowEpoch smart contract"
},
{
"level": "info",
"node_role": "execution",
"node_id": "385341c8b20cd5ad80c84092693279185cb0144465a4af56b2ea43990a780a8a",
"component": "provider engine",
"time": "2021-12-06T15:57:10Z",
"message": "component initialization …
```
> Log epoch number on execution node startup

- cmd/consensus/main.go
- crypto/dkg.go
- engine/consensus/dkg/reactor_engine.go
- engine/consensus/dkg/reactor_engine_test.go
- integration/dkg/dkg_emulator_suite.go
- integration/dkg/dkg_emulator_test.go
- integration/dkg/dkg_whiteboard_test.go
- integration/dkg/node.go
- module/dkg/state.go
- module/metrics/labels.go
- module/signature/signer_store.go
- module/signature/signer_store_test.go
- storage/badger/dkg_state.go
- storage/badger/dkg_state_test.go
- storage/dkg.go
- utils/unittest/fixtures.go
This PR is Pt. II of an update to DKG state storage.
* updates components using DKG state storage to use `DKGState` and `SafeBeaconKeys`
⚠️ Depends on #1720
Pt III (https://github.com/onflow/flow-go/pull/1732) updates the beacon key checking to occur atomically with the transition to `EpochCommitted` phase.
> DKG Storage Pt II: Update components using `DKGState` storage

- engine/execution/computation/computer/computer.go
- fvm/errors/execution.go
- fvm/fvm_test.go
- fvm/state/accounts.go
- fvm/state/state.go
- fvm/state/state_holder.go
- fvm/state/state_test.go
- fvm/transaction.go
- fvm/transactionInvoker.go
This PR:
- disables ledger interaction limits when a transaction is signed by the service account. this enables the network to support operations like end-epoch to be applicable even when node counts are growing. 
- let the service chunk uses more ledger interaction and available space on chunk data pack size since it would be the only transaction inside that chunk.
> Relaxing ledger interaction limit for service and system transactions

- consensus/follower_test.go
- consensus/hotstuff/integration/instance_test.go
- consensus/hotstuff/mocks/verifier.go
- consensus/hotstuff/validator/validator.go
- consensus/hotstuff/validator/validator_test.go
- consensus/hotstuff/verification/combined_signer_v2_test.go
- consensus/hotstuff/verification/combined_signer_v3_test.go
- consensus/hotstuff/verification/combined_verifier_v2.go
- consensus/hotstuff/verification/combined_verifier_v3.go
- consensus/hotstuff/verification/staking_signer_test.go
- consensus/hotstuff/verification/staking_verifier.go
- consensus/hotstuff/verifier.go
- consensus/integration/signer_test.go
- engine/testutil/nodes.go
Before VerifyVote returns a bool to indicate whether the vote is valid, however, when the vote is invalid, the returned `bool` value can't carry details of why the vote is invalid. 
After changing to use sentinal error to indicate invalid vote, we could include details like the vote is invalid because the staking sig is invalid.
> [Consensus Voting] refactor VerifyVote

- cmd/Dockerfile
Updates both the base and build docker containers to debian 11 (bullseye)
> Use debian 11 (bullseye)

- model/flow/identifier.go
- storage/merkle/node.go
- storage/merkle/tree.go
_This PR targets branch [`kan/identifier-merkle-root-fix`](https://github.com/onflow/flow-go/tree/kan/identifier-merkle-root-fix) and is an amendment to [PR #1580](https://github.com/onflow/flow-go/pull/1580/)_
Fundamentally, the `Tree` implements cryptographic commitment scheme to a _set_ of key-value pairs. 
1. Currently, the values are not included in the cryptographic hash of the tree: https://github.com/onflow/flow-go/blob/4bf22f6bb2f6568005a6fd965a5b4a5dbd4a920a/storage/merkle/tree.go#L414-L416
2. The current implementation is vulnerable to a hash-collision attacks: It is possible to replace a full node with a short node. Therefore, the current implementation is not safe for providing inclusion or non-inclusion proofs. The current `Tree` is safe to verify cryptographic integrity …
> Suggested refactorings for Merkle Patricia Tree

- go.mod
- go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.20.2-patch.1..v0.20.2-patch.2
Should be rolled out to Canary and tested first, it's a rather large diff
> Add changes needed to build using private cadence repo

- fvm/fvm_test.go
- fvm/transaction.go
- fvm/transactionContractFunctionInvocator.go
- fvm/transactionInvoker.go
Interaction limit was reached during storage limit check producing this call stack:
```
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/onflow/flow-go/fvm.(*TransactionProcedure).Run.func1()
/app/fvm/transaction.go:51 +0xcf
panic({0x1a9e060, 0xfadbe17b60})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/onflow/cadence/runtime.(*Storage).readStorable(0xfadbdd09c0, {{0xe4, 0x67, 0xb9, 0xdd, 0x11, 0xfa, 0x0, 0xdf}, {0xfd962e84e0, ...}})
/go/pkg/mod/github.com/dapperlabs/cadence-internal@v0.20.2-patch.1/runtime/storage.go:156 +0x389
github.com/onflow/cadence/runtime.(*Storage).ReadValue(0x5, 0xfb7bb23cd0, {0xe4, 0x67, 0xb9, 0xdd, 0x11, 0xfa, 0x0, 0xdf}, ...)
/go/pkg/mod/github.com/dapperlabs/cadence-internal@v0.20.2-patch.1/runtime/storage.go:126 …
```
> Recover interaction limit panic earlier - V0.23

- engine/collection/epochmgr/factories/epoch.go
- engine/collection/epochmgr/factories/hotstuff.go
Uses the same hotstuff metrics instance for all components of a given epoch. Previously we would instantiate two of the same instances separately, which isn't allowed by `promauto`
> Avoid double-instantiating hotstuff cluster metrics

- consensus/hotstuff/packer/packer.go
- consensus/hotstuff/votecollector/combined_vote_processor_v2.go
- consensus/hotstuff/votecollector/combined_vote_processor_v2_test.go
- state/protocol/seed/seed.go
Adding a test to check the integration between the protocol state and combined vote processor. 
The combined vote processor packs the block sig data type into QC's sigData field, and protocol state's `Seed` method unpacks QC's sigData. This test case verifies the pair of Pack and Unpack methods used in the two difference places are integrated well.
Also added some comments for future clean up and moving to V3.
> [Consensus Voting] Test QC pack and unpack

- integration/tests/epochs/epoch_test.go
Adds skip unless TEST_RESOURCE_INTENSIVE to epochs AN integration tests.
> add intensive resources flag to AN tests

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to the latest patch version of the `v0.20` release which is equivalent to the internal `v0.20.2-patch.2`
> Update to Cadence v0.20.3

- ledger/common/pathfinder/pathfinder.go
- ledger/complete/mtrie/forest.go
- ledger/complete/wal/encoding.go
- ledger/ledger.go
- ledger/partial/ledger.go
- ledger/partial/ptrie/partialTrie.go
- ledger/trie.go
Closes #1820 
Preallocate some of the slices used in mtrie in order to reduce allocs.
This PR was kept simple and limited so it can be merged before more complex optimizations.  Additional optimizations for mtrie serialization will be provided in a separate PR.
> Preallocate slices in mtrie

- consensus/hotstuff/committees/cluster_committee.go
- consensus/hotstuff/committees/cluster_committee_test.go
HotStuff committees should ensure committee members have [non-zero weight and are not ejected](https://github.com/dapperlabs/flow-go/blob/2aa2e402d8adc0d921605a17d4abaffc2017e9d0/consensus/hotstuff/committee.go#L23). This PR adds these constraints to the cluster committee.
> Enforce weight/ejection requirements in cluster committee

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Release both `v0.20.3-patch.1` + `v0.20.3-patch.2`
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.20.2-patch.2..v0.20.3-patch.2
> Cadence v0.20.3 patch.2

- Makefile
- integration/loader/Dockerfile
- integration/utils/batchLoadGenerator.go
- integration/utils/contLoadGenerator.go
Fix the following issue by reducing from 100 to 50:
```
Jan 14 19:19:07 loader-001 docker[873237]: 7:19PM INF created 0 accounts
Jan 14 19:19:07 loader-001 docker[873237]: 7:19PM INF creating and funding 100 accounts...
Jan 14 19:19:16 loader-001 docker[873237]: 7:19PM ERR account creation tx failed error="[Error Code: 1106] max interaction with storage has exceeded the limit (used: 20000000, limit 20000000)"
Jan 14 19:19:16 loader-001 docker[873237]: 7:19PM INF created 0 accounts
Jan 14 19:19:16 loader-001 docker[873237]: 7:19PM INF creating and funding 100 accounts...
Jan 14 19:19:23 loader-001 docker[873237]: 7:19PM ERR account creation tx failed error="[Error Code: 1106] max interaction with storage has exceeded the limit (used: 20000000, limit 20000000)"
```
Also fix an issue that …
> Fix loader 0.23.6

- cmd/util/cmd/epochs/cmd/deploy.go
- cmd/util/cmd/epochs/cmd/flags.go
- engine/execution/state/bootstrap/bootstrap_test.go
- fvm/bootstrap.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- utils/unittest/execution_state.go
Pin the commit from https://github.com/onflow/flow-core-contracts/pull/267 which adds FlowFees to FlowEpoch and create a commit to pin from test code of `core-contracts` which updates usages of `contracts.FlowEpoch`. 
After we merge this we can update the pin on `core-contracts`, merge https://github.com/onflow/flow-core-contracts/pull/267, and make a release for auto-rewards.
> update `deployEpoch` for new FlowEpoch function

- cmd/bootstrap/cmd/finalize.go
- cmd/bootstrap/cmd/finalize_test.go
- state/protocol/badger/state.go
- state/protocol/badger/validity.go
This PR adds the validation on the saved root snapshot to add extra safety, as this validation is what all nodes will perform when they receive the finalized root snapshot and try to bootstrap with it.
> Validate the saved root snapshot

- crypto/random/rand_test.go
- statistic tests need a high number of samples
- I have reduced the sampling recently to optimize for the test time
- I bumped the sampling again to make sure there is flakiness
> Crypto: fix flakiness in randomness test

- cmd/node_builder.go
- cmd/scaffold.go
- integration/testnet/network.go
- integration/tests/epochs/suite.go
- network/topology/factory.go
- network/topology/fixedListTopology.go
- network/topology/fullyConnectedTopology.go
- network/topology/randomizedTopology.go
- network/topology/topicBasedTopology.go
> [Integration] Topology Factory

- engine/access/rpc/backend/backend_accounts.go
- engine/access/rpc/backend/backend_events.go
- engine/access/rpc/backend/backend_scripts.go
- engine/access/rpc/backend/backend_transactions.go
- engine/access/rpc/engine.go
- The engine seems to pass the `loggingInterceptor` correctly, I have removed the conditional check and included it last to ensure it is the innermost wrapper to the gRPC call. based on [this example](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/880c1749170035e5a54794546dbfe0d45d10a11d/providers/zerolog/examples_test.go#L78-L105)
- I wasn't sure how to test the interceptor but saw that the backends pass around the log object that the interceptor wraps, so I added more naive error logging to all paths that make downstream calls, in case it still doesn't work
> Add naive error logging for Access node downstream calls

- engine/execution/computation/computer/computer.go
- engine/execution/ingestion/engine.go
- fvm/transactionInvoker.go
This PR updates the logs for tracing transaction execution, such that:
- We log one entry when start executing a tx, and log another entry after executing the tx with the result indicating succeeded or not. It did not increase the number of logs, since it was logging twice before after executing a tx.
- Ensure tx ID and block height are included in the log (including failed tx), so that it's easier to fetch them by the next executed block height for debugging purpose.
- Indicate whether a tx is a system chunk tx.
The log before the change for a tx:
```
{"level":"info","node_role":"execution","node_id":"b462c11e771b1ce51b808d3efdc57a75f9a1785213f0d8fdabe297423607bd66","engine":"computation","component":"block_computer","txHash":"33f84536f30f37c3df1f5ce9b5fbd7ec526b43852e3218790ca61f14b0769b …
```
> [Execution] Improve transaction execution log

- ledger/complete/wal/checkpointer.go
- ledger/complete/wal/compactor.go
- ledger/complete/wal/wal.go
Updates #1884 #1750
Changes include:
Add more logs during checkpoint file creation.  Use INFO instead of DEBUG given the limited frequency and quantity of logs for checkpoint file creation.
These logs can be useful for detecting issues related to checkpoint creation.  E.g. the checkpoint duration log can be used by log monitoring programs to alert us if it exceeds a threshold.
> Add logs for MTrie checkpoint file creation

- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- ledger/complete/ledger.go
Address https://github.com/dapperlabs/flow-go/issues/6062
In order to print the state commitment earlier, this PR
- defer writing the checkpoint file to disk
- defer the report generations, like account reports, storage reports, etc.
> [Sporking] Improve state extraction

- Makefile
- cmd/Dockerfile
- integration/localnet/bootstrap.go
This PR updates the `make docker-build-*` commands to override the `GOARCH` when running on an `arm64` CPU (Apple M1). It also makes this change when building localnet containers.
This should provide transparent support for building and testing on `arm64` base machines.
> Support arm64 when building flow docker containers and localnet

- crypto/hash/xor_generic.go
After https://github.com/onflow/flow-go/pull/1865 was merged, we started seeing the following error while building flow on arm64 machines:
```
=> ERROR [build-production 2/3] RUN --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build     GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build --tags "relic,netg  0.6s
------
> [build-production 2/3] RUN --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build     GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build --tags "relic,netgo" -ldflags "-extldflags -static     -X 'github.com/onflow/flow-go/cmd/build.commit=cedf6df37c81c5c82a199cd640aa0b503c5b96b7' -X  'github.com/onflow/flow-go/cmd/build.semver=v0.23.1-1557-gcedf6'"     -o ./app ./cmd/collection:
#21 0.593 # …
```
> Fix undefined: sha3State errors when building on arm64

- cmd/node_builder.go
- cmd/scaffold.go
- cmd/scaffold_test.go
Add a new method to scaffold that allows registering custom shutdown handlers to run after all components have stopped.
> Allow registering custom node shutdown handlers

- cmd/scaffold.go
- integration/utils/contLoadGenerator.go
- integration/utils/scripts.go
references: https://github.com/onflow/flow-go/issues/1931
Changes made:
- reduced ledger heavy interaction size because it was hitting the gas limit
- removed restricted contract deployment from the localnet
- added returning an error if the contract used for load testing fails to deploy
> Fix ledger-heavy load generator

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.21.0...v0.21.1-patch.1
v0.21.1-patch.1 is v0.21.1, which is v0.21.0 + https://github.com/onflow/cadence/pull/1395, and the security fixes from v0.20
> Update to Cadence v0.21.1-patch.1

- crypto/thresholdsign.go
The cli build failed when building for different architectures that the current one.
I am not sure why this fixes it, but it does.
> Fix flow-go failing to cross compile

- cmd/Dockerfile
- crypto/Dockerfile
- crypto/build_dependency.sh
- crypto_setup.sh
- integration/loader/Dockerfile
- Remove `sudo` when using `chmod` to grant permissions to write under the `GOPATH`.
- update Docker images to drop `sudo`.
> remove sudo from crypto setup

- engine/execution/computation/manager.go
Adding a pre/post-script execution logs helps to debug in case a bad script is sent.
> [Execution] Adding a pre and post script execution log

- README.md
- engine/common/synchronization/engine.go
- module/synchronization/core.go
Limits requesting blocks rages to 2*max range size from latest finalized - this prevents spamming large amounts of requests for very distant blocks. Limit grows naturally with finalization spreading the load.
> Limit range queries for sync engine

- engine/access/rest/models/model_transaction_result.go
- engine/access/rest/models/transaction.go
- engine/access/rest/transactions_test.go
closes: https://github.com/dapperlabs/flow-go/issues/6133
Corresponding change to the Open API spec: https://github.com/onflow/flow/pull/802
> adding status_code to transaction result response in the REST API

- cmd/access/main.go
- cmd/access/node_builder/access_node_builder.go
- cmd/node_builder.go
- cmd/scaffold.go
Porting over commits from this [PR](https://github.com/onflow/flow-go/pull/1966/commits) for tomorrow's mainnet spork
git cherry-pick 214e723349760dede23b61a0a572431550c1fe13
git cherry-pick 5fc5ced08a0d2c48e3a0039546f298089f0158a8
> Porting over PR - fix flag validation for access nodes #1966

- cmd/scaffold.go
ref: https://github.com/onflow/flow-go/issues/1931
During fix https://github.com/onflow/flow-go/pull/1933 I have forgotten that bench-net is a separate network. Permissionless contract deployment needs to be enabled there too.
> Allow bench-net permissionless contract deployment

- cmd/bootstrap/cmd/clusters.go
- cmd/bootstrap/run/cluster_qc.go
- cmd/bootstrap/run/cluster_qc_test.go
- engine/collection/test/cluster_switchover_test.go
- integration/testnet/network.go
Previously we passed in only node infos for which we had private keys (internal nodes) to generate the cluster QCs. The previous logic would make use of all nodes to produce a QC.
With changes in Consensus V2, this logic now only uses 2/3 of these node votes (assuming the passed in list is the full cluster committee), which causes QC generation failure in the presence of partners.
This commit separately provides the cluster signers and the full cluster committee.
> Fix bootstrap cluster qc generation

- cmd/bootstrap/cmd/finalize.go
- cmd/bootstrap/cmd/finalize_test.go
- cmd/bootstrap/run/qc.go
Adding logs so that when we receive invalid vote, we know the signer from the error log
> log vote's signer and block when vote is invalid

- engine/collection/epochmgr/engine.go
- engine/collection/epochmgr/engine_test.go
There is a race in `epochmgr` when responding to epoch transition events, because the event handler used `state.Final` rather than `state.AtBlockID` with the block ID in the event. More details in [testing doc](https://www.notion.so/dapperlabs/Test-21-Dynamic-Startup-Collection-Node-d0bf044632fe4ab78e5c814b78d853b1#8fa9538d5c094ea089ac57dd99814d66)
> Fix race in epoch switchover handling

- fvm/handler/contract.go
- fvm/handler/contract_test.go
`h.draftUpdates` is a dictionary.
It was possible that in the for loop an error was hit, which topped the for loop. This could produce a non-deterministic error.
this PR changes the iteration to an ordered list.
> Make ContractHandler Commit produce deterministic errors

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Includes:
- https://github.com/dapperlabs/cadence-internal/pull/60
- https://github.com/dapperlabs/cadence-internal/pull/64
Diff: https://github.com/dapperlabs/cadence-internal/compare/074f3b0e50acec58c8c24c3e50bc1158a22ad680..v0.21.2-patch.1
> Update to Cadence v0.21.2-patch.1

- engine/consensus/matching/core.go
- engine/execution/computation/computer/computer.go
- engine/execution/ingestion/engine.go
add log for execution data id
Also removes transaction error message truncation, since cadence will be changing to only return first error.
> Log Execution Data IDs

- cmd/access/main.go
- cmd/access/node_builder/access_node_builder.go
- cmd/access/node_builder/unstaked_access_node_builder.go
This PR adds support for running an observer as a standalone process using the standard Access Node image.
Example usage:
```
docker run -p 9000:9000 -p 3569:3569 -p 8080:8080  -p 8000:8000 \
-v /tmp/observer/bootstrap:/bootstrap \
-v /tmp/observer/data:/data \
"gcr.io/flow-container-registry/access:latest" \
--staked=false \
--bootstrapdir=/bootstrap \
--datadir=/data/protocol \
--secretsdir=/data/secret \
--loglevel=DEBUG \
--rpc-addr=0.0.0.0:9000 \
--secure-rpc-addr=0.0.0.0:9001 \
--http-addr=0.0.0.0:8000 \
--collection-ingress-port=9000 \
--log-tx-time-to-finalized \
--log-tx-time-to-executed \
--log-tx-time-to-finalized-executed \
--bind 0.0.0.0:0 \
--bootstrap-node-addresses=access-007.mainnet16.nodes.onflow.org:3570 \
--bootstrap-node-public-keys=28a0d9edd0de3f15866dfe4aea1560c4504f …
```
> [Observer] Support running observer standalone using standard AN image

- cmd/access/node_builder/unstaked_access_node_builder.go
- cmd/node_builder.go
- cmd/scaffold.go
- follower/consensus_follower.go
- module/metrics/server.go
Looks like we don't use flag to enable/disable metrics for AN, they are always on for staked AN, so I made it consistent.
> Enable metrics for unstaked access node

- fvm/contract_function_invokers.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Uses the https://github.com/onflow/cadence/tree/secure-cadence-m1 tag
> Update Cadence version to secure-cadence-m1

- cmd/execution/main.go
Mitigations for SPECTRE-V2, SPECTRE-BHB, etc. can affect performance, so log microcode revision, kernel version, etc. at startup.  
Also log Go version because performance can differ between Go 1.16 and 1.17.
Changes include:
- Add CPU microcode revision
- Add OS, Platform, PlatformVersion, KernelVersion, Uptime
- Add Go version, GOMAXPROCS, NumCPU
- rename `logHardware()` to `logSysInfo()`
- rename "hardare specs" (logging) module to "system specs"
Closes #2178 #2183
> Add logs with more system specs

- storage/transaction_results.go
Leftover, unused method - probably some merge artifacts. Prevents compilation, and its not used anywhere
> Remove unused method

- .github/workflows/bench.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Makefile
- cmd/Dockerfile
- crypto/Makefile
- crypto/ecdsa_test.go
- tools/flaky_test_monitor/run-tests.sh
- tools/flaky_test_monitor/test-setup.sh
- add `!relic` from non-relic test files to make sure they are not run when `tags=relic` is added (avoids running tests twice in the flakey-test monitor)
- refactor crypto tests under relic tests and non-relic tests
- update `crypto/relic/build` target misleading name: the target updates the `GOPATH` and not the `crypto/relic/build` folder. Add a new target `crypto_setup` that actually updates `crypto/relic/build`.
- remove one call to `make crypto setup` since the setup is called during `make crypto test` later anyway.
> [Crypto] make test cleanup

- fvm/fvm_test.go
- fvm/meter/basic/meter.go
- fvm/meter/basic/meter_test.go
- fvm/meter/meter.go
- fvm/meter/noop/meter.go
- fvm/meter/weighted/meter.go
- fvm/meter/weighted/meter_test.go
- fvm/state/state.go
- fvm/transactionEnv.go
- fvm/transactionInvoker.go
[master](https://github.com/onflow/flow-go/pull/2217) version
This fixes three things:
1. During testing with the emulator, I discovered that the metering "limit reached" error text did not include the correct limit. The error used the limit at the meters internal precision, instead of the actual limit. (now covered in the weighted meter tests)
2. When testing I noticed that setting a gas limit of 999 I was only able to get a transaction to 941 execution effort before it failed. This was due to the limit enforcement happening after the fee deduction which added computation and potentially failed the transaction.
3. When the transaction failed, the fee deduction code also failed due to `meter.MergeMeter` still emitting an error even though limit enforcement was off.
The new …
> [FVM] Fix metering limits - v0.25

- admin/README.md
- admin/commands/common/get_identity.go
- cmd/scaffold.go
new command to get identity info by flow ID or libp2p peer ID.
> [Admin] GetIdentity command

- cmd/execution/main.go
Reduce checkpoint distance flag to trigger creation of checkpoints more frequently.
Prior to #1944 checkpoint creation took 11-15+ hours so it wasn't feasible to run checkpoints more frequently.
This change will cause fewer WAL segments to trigger checkpoint creation, which will speedup EN startup by having fewer WALs to replay during startup.
On benchnet, replaying 20 WALs is 3.5 minutes faster than replaying 40 WALs.
This change will also speedup checkpoint file creation by the same duration because that also requires replaying WALs.
closes #2207 
updates https://github.com/dapperlabs/flow-go/issues/6114
> Reduce default checkpoint distance flag from 40 to 20 to speedup EN startup

- fvm/fvm_test.go
- fvm/meter/basic/meter.go
- fvm/meter/basic/meter_test.go
- fvm/meter/meter.go
- fvm/meter/noop/meter.go
- fvm/meter/weighted/meter.go
- fvm/meter/weighted/meter_test.go
- fvm/state/state.go
- fvm/transactionEnv.go
- fvm/transactionInvoker.go
[v0.25](https://github.com/onflow/flow-go/pull/2216) version
This fixes three things:
1. During testing with the emulator, I discovered that the metering "limit reached" error text did not include the correct limit. The error used the limit at the meters internal precision, instead of the actual limit. (now covered in the weighted meter tests)
2. When testing I noticed that setting a gas limit of 999 I was only able to get a transaction to 941 execution effort before it failed. This was due to the limit enforcement happening after the fee deduction which added computation and potentially failed the transaction.
3. When the transaction failed, the fee deduction code also failed due to `meter.MergeMeter` still emitting an error even though limit enforcement was off.
The new …
> [FVM] Fix metering limits

- fvm/transactionInvoker.go
This PR moves the execution intensities debug logging to before the fee deduction and storage limit checks.
The reasoning behind this is that:
- payer is only limited on the execution that happens before this point
- payer (or rather the transaction) cannot affect the fee deduction or storage limit checks
- payer is only charged for the execution that happens before this point
This only changes logging so it is safe to port to v0.25, which is something I would like to do, after this is merged to master.
> [FVM] Move execution intensities debug logging

- cmd/execution/main.go
Cherry picked from commit 156e906b8fde3dfa02a7eb27ce159ca5ad232128
> Reduce default checkpoint-distance flag from 40 to 20

- fvm/blueprints/fees.go
- fvm/bootstrap.go
- fvm/fvm_test.go
Port of [[FVM] Execution effort weights option for bootstrap](https://github.com/onflow/flow-go/pull/2228)
This PR introduces a `WithExecutionEffortWeights` option for the bootstrapping procedure, which allows setting the Execution effort weights during bootstrapping.
This option makes testing setup easier but more importantly, it makes the needed Emulator change easier.
This does not change any transaction code and is safe to be ported to v0.25.
> [FVM] Execution effort weights option for bootstrap - v0.25

- fvm/transactionInvoker.go
This is a port of [[FVM] Move execution intensities debug logging](https://github.com/onflow/flow-go/pull/2229)
This PR moves the execution intensities debug logging to before the fee deduction and storage limit checks.
The reasoning behind this is that:
- payer is only limited on the execution that happens before this point
- payer (or rather the transaction) cannot affect the fee deduction or storage limit checks
- payer is only charged for the execution that happens before this point
This only changes logging so it is safe to port to v0.25.
> [FVM] Move execution intensities debug logging - v0.25

- cmd/util/ledger/reporters/fungible_token_tracker_test.go
The progress bar messes up the test output when running tests in JSON mode:
```
{"Time":"2022-03-30T23:50:56.76655-07:00","Action":"run","Package":"github.com/onflow/flow-go/cmd/util/ledger/reporters","Test":"TestFungibleTokenTracker"}
{"Time":"2022-03-30T23:50:56.768101-07:00","Action":"output","Package":"github.com/onflow/flow-go/cmd/util/ledger/reporters","Test":"TestFungibleTokenTracker","Output":"=== RUN   TestFungibleTokenTracker\n"}
{"Time":"2022-03-30T23:50:56.961114-07:00","Action":"output","Package":"github.com/onflow/flow-go/cmd/util/ledger/reporters","Test":"TestFungibleTokenTracker","Output":"\r\r\rProcessing: 100% |██████████████████████████████████| (5/5, 18045 it/s)\n"}
{"Time":"2022-03-30T23:50:56.962618-07:00","Action":"output","Package":"github.com/onflow/flow-go/cmd/uti …
```
> Fix output of fungible token tracker test

- cmd/util/ledger/reporters/fungible_token_tracker_test.go
- network/test/epochtransition_test.go
When a test is skipped, we must still retain the call to `suite.Run`, otherwise it defeats the purpose of skipping it.
Also, added a comment as followup to https://github.com/onflow/flow-go/pull/2237
> Fix incorrectly skipped test

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update to [Cadence v0.23.3](https://github.com/onflow/cadence/releases/tag/v0.23.3), which includes a bugfix which should ideally be deployed as part of the upcoming TN/MN sporks.
> Update to Cadence v0.23.3

- cmd/util/cmd/execution-state-extract/execution_state_extract.go
Undo changes from https://github.com/onflow/flow-go/pull/2195
Migrations had to be removed, because they were already applied on canary during the first canary spork.
They have to be re-added before the testnet and mainnet sporks, as they have not been run there yet.
⚠️ DO NOT MERGE BEFORE THE CANARY SPORK IS OVER
> Add migrations back to v0.25

- .github/workflows/ci.yml
- consensus/hotstuff/integration/integration_test.go
- engine/execution/ingestion/engine_test.go
- integration/dkg/dkg_emulator_test.go
- integration/tests/epochs/epoch_join_and_leave_an_test.go
- integration/tests/epochs/epoch_join_and_leave_vn_test.go
- integration/tests/execution/chunk_data_pack_test.go
- integration/tests/execution/failing_tx_reverted_test.go
- integration/tests/network/network_test.go
- network/test/epochtransition_test.go
Update skip reasons according to flaky test metrics for the past week.
Tests which are unskipped have been passing 100%, so they are not actually flaky.
Tests which have are changed to `TEST_TODO` are completely broken, they have 0% pass rate.
> unskip unflaky tests and update skip reason for broken tests

- network/p2p/middleware.go
We are seeing the repetition of the logs below mostly for execution nodes on the mainnet when trying to respond a chunk data pack:
```
{"level":"warn","node_role":"execution","node_id":"4ab025ab974e7ad7f344fbd16e5fbcb17fb8769fc8849b9d241ae518787695bd","engine":"receipts","origin_id":"f7422f2d3296ede4d1efb36ec55e3fd93702c061f7ee627881f0b3007beff2ed","chunk_id":"e724ed277c5fc8e9f8ff53caa36780d52a051e83e5b392fc6edee6003af43629","sinceProcess":0.1542,"since_deliver":1075.988751,"error":"failed to send message to f7422f2d3296ede4d1efb36ec55e3fd93702c061f7ee627881f0b3007beff2ed: failed to send message to f7422f2d3296ede4d1efb36ec55e3fd93702c061f7ee627881f0b3007beff2ed: i/o deadline reached","time":"2022-04-06T23:11:32Z","message":"could not send requested chunk data pack to origin ID"}
```
This …
> [Networking] Fixes unicast timeout value for chunk data packs

- cmd/bootstrap/cmd/partner_infos.go
- cmd/collection/main.go
- cmd/consensus/main.go
- cmd/dynamic_startup.go
- cmd/util/cmd/common/flow_client.go
- integration/dkg/dkg_emulator_suite.go
- integration/epochs/epoch_qc_test.go
- module/dkg/client.go
- module/dkg/client_test.go
- module/epochs/qc_client.go
This PR updates the DKG and QC contract client logger initialization to include the node ID of the AN that the flow client being used is connecting to.
> Improve DKG & QC contract logging

- cmd/util/cmd/checkpoint-list-tries/cmd.go
- ledger/complete/ledger.go
- ledger/complete/wal/checkpointer.go
- ledger/complete/wal/checkpointer_test.go
- ledger/complete/wal/checkpointer_versioning_test.go
- ledger/complete/wal/syncrename.go
Backport https://github.com/onflow/flow-go/pull/2280 into v0.25
NOTE: the CI Lint error also occurs in prior backports to v0.25 and can be ignored.
> Drop checkpoint files from OS file cache to prevent file cache growing to hundreds of GB

- engine/access/ingestion/engine.go
- engine/access/ingestion/engine_test.go
* move execution result indexing logic to finalized block handler
* modify tests for new storage path
* add simple storage logic test
closes  #2250
> Fix er indexing on finalization

- engine/collection/ingest/engine_test.go
There is a race in the `ComponentManager` where `Done` may be closed before `ShutdownSignal`. This fixes the test case (not the race) by making it wait on the same channel as the function being tested. 
Issue to address the race: https://github.com/dapperlabs/flow-go/issues/6220
> Fix flakey test: `TestComponentShutdown`

- engine/access/ingestion/engine.go
index against the block id in the seal, rather than the current block ID
> Use block ID from seal

- state/cluster/badger/mutator.go
Insertion of cluster blocks was not wrapped in conflict handling, which can cause a collection node to crash.
> Retry on conflict inserting cluster blocks

- engine/access/rpc/backend/backend.go
- engine/access/rpc/backend/backend_test.go
Add logic to lookup random execution nodes on insufficient receipts instead of a blank list/custom error
> [Access node] Add random en lookup on receipt lookup failure

- cmd/bootstrap/cmd/constraints.go
- integration/go.mod
- integration/go.sum
- integration/localnet/Makefile
- integration/localnet/bootstrap.go
**Add Observer Support to Localnet**
Adds Observer support to integration/localnet such that setting the OBSERVER variable in localnet/Makefile will define and bootstrap the specified number of Observers with `make init`, and run them within the localnet Docker network upon a subsequent `make start`.  Once running, these observers will follow consensus from the Flow network running within localnet. 
**`make init` will now:**
- Create a self-contained, self-connected Flow network that includes zero or more functional Observers
- Create the required Observer private keys, needed to follow consensus from the localnet Flow network
- Display a libp2p public networking key that can be used to optionally connect an _external_, _standalone_ Observer that can be used to follow consensus from the …
> Add observer support to localnet

- engine/execution/testutil/fixtures.go
The removeKey function is gone now. This function, `CreateRemoveAccountKeyTransaction` isn't used anywhere but uses the removeKey function. It's easier to just remove it than update it.
> remove unused test util

- integration/localnet/bootstrap.go
https://github.com/onflow/flow-go/pull/2308 updated the dockerfile to accept a path instead of a command name as the `TARGET`.
This PR adds the corresponding change for localnet
> Update localnet TARGET paths after recent dockerfile changes

- engine/collection/compliance/core.go
This PR helps to answer the question: who created the cluster block that later turns into a collection guarantee.
To answer this, we need a log that ties the cluster block ID and the collection guarantee ID, and this PR adds it.
> [Collection] Log collection proposer

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
The access rest API depends on the onflow/flow package, where protobuf types and generated go files are defined there.
[The PR to add signer indices field has been merged](https://github.com/onflow/flow/pull/932), and now the package has been[ upgraded to v0.3.0](https://github.com/onflow/flow/releases/tag/v0.3.0).
This PR will upgrade the onflow/flow package
> [Signer Indices] upgrade onflow/flow package

- fvm/fvm_test.go
- fvm/handler/accountKey_test.go
- fvm/handler/contract.go
- fvm/handler/contract_test.go
- fvm/mock/state/accounts.go
- fvm/state/accounts.go
We are planning to enable permissionless deployment (disable `restrictedDeploymentEnabled`) after a test period after the Secure Cadence spork.
However, Secure Cadence will also make breaking changes. To allow developers with existing contracts to update their contracts we will allow *updates* to always be permissionless, and have `restrictedDeploymentEnabled` only contract *new* deployments.
> Permissionless contract updates

- cmd/util/ledger/migrations/storage_used_update_migration.go
- consensus/hotstuff/votecollector/combined_vote_processor_v2_test.go
- consensus/hotstuff/votecollector/combined_vote_processor_v3_test.go
- crypto/bls12381_utils.c
- crypto/hash/xor_unaligned.go
- engine/access/rpc/engine.go
- engine/collection/epochmgr/engine.go
- engine/collection/epochmgr/engine_test.go
- engine/common/requester/engine_test.go
- engine/consensus/approvals/assignment_collector_statemachine_test.go
- engine/consensus/approvals/caching_assignment_collector_test.go
- engine/enqueue_test.go
- engine/execution/execution_test.go
- engine/execution/ingestion/engine_test.go
- engine/execution/state/delta/view.go
- engine/unit_test.go
- insecure/wintermute/attackOrchestrator_test.go
- module/jobqueue/consumer_behavior_test.go
- module/jobqueue/consumer_test.go
- module/lifecycle/lifecycle.go
- module/lifecycle/lifecycle_test.go
- module/mempool/herocache/backdata/cache.go
- module/state_synchronization/execution_data_service_test.go
- network/p2p/topic_validator_test.go
- network/test/middleware_test.go
- network/topology/topology_test.go
- storage/badger/batch.go
- utils/unittest/logging.go
While exploring code base I've stumbled upon a couple of race-detector problems. Most of them are harmless issues that only affect test flakiness.  Nevertheless, here is a sample of interesting ones:
* Unprotected `OnSucceed` callback access in badger batches: https://github.com/onflow/flow-go/commit/35babdbc398dbff812d7abf69054e17534623126
* Potential error clobbering in ledger migration's "storage-used" calculation: https://github.com/onflow/flow-go/commit/c42159fc719ed97414922515d362492e1b8b956a
* EpochMgr `epochs` access without lock on `Done`: https://github.com/onflow/flow-go/commit/a0c6cee65888f427a3482e81670cbb88fcce7f9b
* `BLS12_381` verification accesses uninitialized memory: https://github.com/onflow/flow-go/pull/2293#discussion_r850080079
* Unprotected global access in tests …
> Fix race detector issues.

- cmd/bootstrap/run/cluster_qc.go
- cmd/bootstrap/run/qc_test.go
- consensus/hotstuff/committees/static.go
- engine/access/access_test.go
- engine/access/ingestion/engine_test.go
- engine/execution/execution_test.go
- engine/execution/ingestion/engine.go
- engine/execution/ingestion/engine_test.go
- integration/testnet/network.go
- integration/tests/consensus/inclusion_test.go
- model/flow/order/identity.go
- module/signature/checksum.go
- module/signature/checksum_test.go
- module/signature/signer_indices.go
- module/signature/signer_indices_test.go
Close https://github.com/dapperlabs/flow-go/issues/6179
This PR adds checksum to signer indices. 
After using signer indices to replace signer IDs, we lose certain level of debuggability. If we run into invalid QC issue, we can't exclude the case where the Committee.Identities had a bug that not always return the same list for the same block.
The checksum could provide the same debuggability as when signerIDs was used. Since for the above case, it's easy to confirm if the same list of signerIDs were used before matching sig type and verifying the signatures.
Checksum is first computed from the canonical list of identities that are used for generating signer indices.
The computed checksum will be prefixed to the generated signer indices, so that the decoder can use it to compare with it's …
> Add checksum to signer indices

- engine/access/rpc/backend/backend_transactions.go
- engine/execution/computation/computer/computer_test.go
- engine/execution/computation/execution_verification_test.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
The fix is here https://github.com/onflow/cadence/pull/1642.
This patch was backported to Cadence `v0.23.3`, which is currently used in flow-go `v0.25`, as `v0.23.3-patch.1`, i.e. these have the same commits:
- https://github.com/onflow/cadence/pull/1642/commits
- https://github.com/onflow/cadence/compare/v0.23.3...v0.23.3-patch.1
This only imports the new cadence version and adds a test for this scenario.
> Events non-determinism fix

- fvm/fvm.go
- fvm/fvm_test.go
This concerns both Memory and Execution weights.
The default weights dictionary is hardcoded in the FVM in `fvm/meter/weighted/meter.go`.
The state weights dictionary is in the service account's storage: https://github.com/onflow/flow-core-contracts/blob/master/transactions/FlowServiceAccount/set_execution_effort_weights.cdc
Current logic is:
- In each transaction
- Check if the weights dictionary in the state exists
- If it does take the dictionary from state
- If not take the default dictionary
The change in this PR is:
- In each transaction
- Check if the weights dictionary in the state exists
- If it does, take the default weights dictionary and update it with all the entries from the state dictionary (merging them)
- If not take the default dictionary
The reasoning behind this is a …
> [FVM] Merge default execution/memory weights and state weights

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Update Cadence to `v0.23.3-patch.2`, which is `v0.23.3` (currently on TN and MN), with:
- https://github.com/onflow/cadence/pull/1642
(was already included in `v0.23.3-patch.1`), and merged as part of https://github.com/onflow/flow-go/pull/2393
- https://github.com/onflow/cadence/pull/1610
See https://github.com/onflow/cadence/compare/v0.23.3...v0.23.3-patch.2
> Cadence v0.23.3-patch.2

- integration/tests/epochs/epoch_join_and_leave_an_test.go
- integration/tests/epochs/epoch_join_and_leave_vn_test.go
This PR replaces the TEST_RESOURCE_INTENSIVE skip reason with the FLAKY skip reason so that the tests are not skipped entirely and can run in the cron job. Based on the metrics of other epoch join and leave tests for [LN](https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&from=now-30d&to=now&var-package=github.com%2Fonflow%2Fflow-go%2Fintegration%2Ftests%2Fepochs&var-dataset_name=dapperlabs-data.production_src_flow_test_metrics&var-skipped_tests_table=skipped_tests&var-test_results_table=test_results&var-query_limit=100000&var-test=TestEpochJoinAndLeaveLN) and [SN](https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&from=now-30d&to=now&var-package=github.com%2Fonflow%2Fflow-go%2Fintegration%2Ftests%2Fepochs&var-dataset_name=dapperlabs-data.production_ …
> add flaky skip reason so tests can run in cron job

- fvm/blueprints/contracts.go
- fvm/handler/contract.go
- fvm/handler/contract_test.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
Closes https://github.com/dapperlabs/cadence-private-issues/issues/40
Contracts can be deployed, updated, or removed by the service account and accounts it authorizes to do so. That authorization applies to all three operations but we want to permit more fine-grained control: deploy/update and removal should be two separate permissions.
This is somewhat related to https://github.com/onflow/flow-go/pull/2346.
> Separate permission setting of contract deploy/update and removal

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Switch to the internal repos, which contain:
- https://github.com/dapperlabs/cadence-internal/pull/85
- https://github.com/dapperlabs/atree-internal/pull/1
> Secure Cadence internal fixes

- cmd/util/cmd/root.go
- cmd/util/cmd/snapshot/cmd.go
This is useful for recovery in certain cases. We can retrieve a snapshot from a suitable point in time, then start up the node using the snapshot, rather than requiring the node to sync all history.
> Add `util` command to retrieve snapshot at any height

- fvm/fvm_test.go
- fvm/scriptEnv.go
- fvm/state/state_holder.go
- fvm/transactionEnv.go
Closes dapperlabs/cadence-private-issues#50
Just like we already have an exception for the interaction limit for the service account, also add an exception for the memory limit.
> Memory limit exception for service account

- engine/common/synchronization/engine.go
When sync engine delivers a range of blocks to compliance engine, compliance engine will process each of them, once it finishes validating the payload, it will forward to hotstuff for validating the block header. 
However, this creates a race for hotstuff to validate current block's header and compliance engine validate the next block's payload. 
If compliance engine starts to validate the next block before hotstuff finish validating the first block's header, then compliance engine will hit an error saying the next block is unverifiable. 
To resolve, we need to ask compliance engine to wait until hotstuff finishes validating the header, we estimated the avg wait time needed is about `150ms`. it should cover 99.9% cases, and allow nodes to catch up at a max of 6.6 blocks/second.
Note, even …
> avoid race condition in validating blocks

- cmd/Dockerfile
- integration/loader/Dockerfile
- integration/localnet/Makefile
Right now, for some reason `--build` flag for docker-compose is broken so build needs to be ran manually.
```
$ docker image prune -a
$ make stop && make init && make start
...
DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.nodes.yml up --build -d
[+] Running 0/6
⠿ collection_3 Error                                                                                                                           2.5s
⠿ execution_2 Error                                                                                                                            2.5s
⠿ consensus_2 Error                                                                                                                            2.5s
⠿ consensus_3 Error …
```
> chore(docker): fix parallel image builds

- integration/utils/contLoadGenerator.go
Currently, test fails with the following error:
```
5:21PM ERR account creation tx failed error="[Error Code: 1101] cadence runtime error Execution failed:
error: invalid public key: [248, 71, 184, 64, 62, 118, 6, 35, 180, 178, 53, 126, 38, 116, 202, 182, 91, 243, 157, 205, 89, 77, 199, 235, 192, 117, 38, 122, 5, 166, 65, 116, 192, 67, 8, 190, 19, 100, 174, 246, 253, 218, 181, 121, 11, 79, 74, 202, 139, 156, 247, 215, 109, 152, 90, 162, 48, 116, 13, 180, 101, 48, 1, 40, 106, 13, 47, 226, 2, 3, 130, 3, 232]
--> 9d665e105234216749b51b3a301153c069b5c1047a1cf3f55e2ea38a5aa2c033:13:23
|\n13 |       let publicKey2 = PublicKey(\n   |                        ^\n"
```
It looks like it tries to pass the encoded public key (along w/ algo, hash, and weight) to a function that expects a raw public key. …
> chore(tests): fix load test

- engine/execution/ingestion/engine_test.go
- ledger/complete/wal/compactor_test.go
These tests have been consistently passing in quarantine as showcased by the Flaky Test Monitor dashboards for each of them showing consistent passing over the last week and approximately 100 test runs:
`TestUnauthorizedNodeDoesNotBroadcastReceipts` - [Grafana dashboard](https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&var-package=github.com%2Fonflow%2Fflow-go%2Fengine%2Fexecution%2Fingestion&var-dataset_name=dapperlabs-data.production_src_flow_test_metrics&var-skipped_tests_table=skipped_tests&var-test_results_table=test_results&var-query_limit=100000&var-test=TestUnauthorizedNodeDoesNotBroadcastReceipts)
`Test_Compactor` - [Grafana dashboard](https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&var-package=github.com%2Fonflow%2Fflow-go%2Fledger%2Fc …
> unquarantining 2 flaky tests that have been consistently passing in quarantine

- cmd/util/cmd/read-execution-state/list-accounts/cmd.go
- ledger/complete/ledger.go
- ledger/complete/mtrie/forest.go
- ledger/complete/mtrie/forest_test.go
- ledger/complete/wal/checkpointer_test.go
- ledger/complete/wal/compactor_test.go
- ledger/trie.go
Change `Forest.Read()` and `Forest.ReadSingleValue()` to return `[]ledger.Value` without deep copying payload keys.  This avoids 4 heap allocation per key.
This change doesn't affect `Ledger.Get()` (the caller) because it discards the payload keys.
Closes #2475 
Bench comparison of master `Ledger.Get()` vs `Ledger.GetSingleValue()` reading a single value.
```
name          old time/op    new time/op    delta
LedgerGet1-4    6.77µs ± 1%    4.30µs ± 1%  -36.47%  (p=0.000 n=9+9)
name          old alloc/op   new alloc/op   delta
LedgerGet1-4    1.74kB ± 0%    0.69kB ± 0%  -60.55%  (p=0.000 n=10+10)
name          old allocs/op  new allocs/op  delta
LedgerGet1-4      21.0 ± 0%       3.0 ± 0%  -85.71%  (p=0.000 n=10+10)
```
Bench comparison of master `Ledger.Get()` vs new `Ledger.Get()` reading …
> Optimize Ledger.Get() by making Forest.Read() use ~5x fewer allocs/op and run ~20% faster

- integration/utils/contLoadGenerator.go
`txStatsTracker` already dependency injected into the `txTracker` so there is no ned to keep it in an already way too bloated struct.
`supervisorClient` is not used used outside of dep. injection.
> chore(tests): cleanup unused fields from loader

- network/p2p/topic_validator_test.go
- network/validator/pubsub/authorized_sender_validator.go
This PR adds a fix for handling message validation on messages sent on cluster prefixed channels
> [Fix] Adding sync request message as a cluster type message

- consensus/hotstuff/helper/timeout_certificate.go
- model/flow/timeout_certificate.go
This PR replaces signer ids with signer indices as it was done for QC. 
This PR is a few lines since we haven't used TC anywhere yet. 
We need this change as it's blocking https://github.com/dapperlabs/flow-go/issues/6192 since it already uses signer indices for QCs.
> [Consensus] Active Pacemaker signer indices

- fvm/fvm_test.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
A simple bump in cadence version to [secure-cadence-m8](https://github.com/onflow/cadence/releases/tag/secure-cadence-m8)
> Upgrade Cadence to secure-cadence-m8

- integration/localnet/Makefile
Currently, the minimum number of consensus nodes is 2, otherwise the threshold signature construction fails:
```
Bootstrapping a new self-contained, self-connected Flow network...
Flow node counts:
- Collection: 1
- Consensus: 1
- Execution: 1
- Verification: 1
- Access: 1
Network config:
- Clusters: 1
- Epoch Length: 10000
- Staking Phase Length: 2000
- DKG Phase Length: 2000
Number of staked consensus nodes:  1
generating votes from consensus participants:  a3402415f828e985a059bc73761799566fc03beb9a5c46fe6e0756eff89acf4c consensus_1:2137 0xb9747f913c0ddf4519b6c9ab77cb355bc6f663d331f5fb8e38174a1c7b8a2032f63554742712046a0f8373cbe56f9d250cc1a81f108b90a495c7c8a01b4dfc118ee114a033c9741e3a23339671ad9b8c153eb99010ab33853d49a23b3a6b7351
panic: could not CombinedVoteProcessor processor: could …
```
> chore(tests): fix init-light for localnet

- fvm/scriptEnv.go
- fvm/transactionEnv.go
Execution node is producing lots of INFO logs like this, which it's better to use debug level log.
```
{"level":"info","node_role":"execution","node_id":"b5dd412056f6f0f2624550debb71d57e27f93c33d04b977ef024d11976a826bb","error":"[Error Code: 1112] could not get execution parameter from the state (address: f4527793ee68aede path: storage/executionMemoryWeights)","time":"2022-05-26T17:32:33Z","message":"could not set execution memory weights. Using defaults"}
```
If we do want to know whether the default weights was used, better to add it to an existing info log as an extra field.
> upload log level for memory weights

- consensus/hotstuff/signature/packer.go
- consensus/hotstuff/validator/validator.go
- engine/consensus/ingestion/core.go
- engine/consensus/ingestion/core_test.go
- module/signature/errors.go
- module/signature/signer_indices.go
- module/signature/signer_indices_test.go
- state/protocol/badger/mutator.go
- state/protocol/util.go
_Context_
I consider methods like the following as generally unsafe 
https://github.com/onflow/flow-go/blob/632d86098f05e025d52c27692a580d67cf49c9d4/module/signature/errors.go#L112-L117
reasoning:
* In my experience they incentivise engineers to so skip expected byzantine paths in the protocol. For example, the engineer extend method [`DecodeSignerIndicesToIdentifiers`](https://github.com/onflow/flow-go/blob/632d86098f05e025d52c27692a580d67cf49c9d4/module/signature/signer_indices.go#L217) and introduce another sentinel error `X`. For their particular use case, `X` is expected during normal operations, so they add it to `IsDecodeSignerIndicesError`. However, in other segments of the code, this error might not be expected. But by adding `X` to `IsDecodeSignerIndicesError`, the engineer has …
> Suggestion for PR #2462

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Just like for `master` in #2525, update to the latest versions of Cadence, atree, and CBOR in the 0.26 release branch.
In addition, update to the internal version, which point to:
- https://github.com/dapperlabs/cadence-internal/pull/89
- https://github.com/dapperlabs/atree-internal/pull/4
> Update to Cadence 8b113c539a2c, atree 525fbc26f40a, and CBOR ad2eae63303f

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Upgrading flow to[ 0.3.1](https://github.com/onflow/flow/releases/tag/v0.3.1) for adding block height to results
> upgrade flow to v0.3.1

- integration/loader/main.go
Currently, we go through the resolver codepath each time we create a local connection.  This is not too expensive for the benchmark (though it can create unexpected spikes in latencies), but it can be expensive for the docker's resolver.  To avoid DDoS'ing it, let's use `127.0.0.1` for now.  If our nodes switch to IPv6-only we can switch this to `::1`.
> chore(tests): do not go through the resolver for localhost

- engine/channels.go
- network/codec/cbor/msg_channel_mapping.go
- network/p2p/topic_validator_test.go
- network/validator/pubsub/authorized_sender_validator.go
This PR fixes missing message codes sent on cluster prefixed channels  causing false-negative validations in the libP2P authorized sender validator.
> [Fix] add explicit mapping of cluster prefix -> message codes

- integration/utils/worker_stats_tracker.go
- integration/utils/worker_stats_tracker_test.go
Mostly cosmetic changes, except for the cleanup of the stale timestamp buckets that we were previously leaking.
Also while here added a basic test.
> chore(tests): cleanup worker stats tracker and add tests

- module/metrics/execution.go
Port of https://github.com/onflow/flow-go/pull/2549 to v0.26
> Fix underflowing of memory metrics difference values

- integration/go.mod
- integration/utils/worker.go
- integration/utils/worker_test.go
Following changes:
* switch from channel close to a cancelation through context: this would allow context propagation in the future.
* start the first job immediately on Start() instead of waiting for the first Tick.
* add basic test to prevent accidental breakage.
> chore(tests): cleanup worker and add tests

- module/jobqueue/component_consumer_test.go
Quarantine flaky test.
This test is failing about 50% of the time in CI and needs to be quarantine and fixed.
file: `module/jobqueue/component_consumer_test.go`
test: `TestComponentConsumerSuite/TestHappyPath/runs_and_notifies_using_pre-notifier`
[recent CI failed run](https://github.com/onflow/flow-go/runs/6734487844?check_suite_focus=true)
[Grafana dashboard](https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&var-package=github.com%2Fonflow%2Fflow-go%2Fmodule%2Fjobqueue&var-dataset_name=dapperlabs-data.production_src_flow_test_metrics&var-skipped_tests_table=skipped_tests&var-test_results_table=test_results&var-query_limit=100000&var-test=TestComponentConsumerSuite%2FTestHappyPath%2Fruns_and_notifies_using_pre-notifier)
part of issue: …
> quarantine test - TestComponentConsumerSuite-runs_and_notifies_using_pre-notifier

- module/metrics/execution.go
The histogram buckets we previously used for measuring memory estimates had too low of a cap, so this adds more buckets with a higher cap to allow us to see more granulator data.
> Add larger buckets for metrics for memory estimates

- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- cmd/util/ledger/migrations/core_contracts_migration.go
- cmd/util/ledger/migrations/core_contracts_migration_test.go
With the update to Secure Cadence (0.24), which introduces breaking changes, the Core Contracts were updated in:
- https://github.com/onflow/flow-core-contracts/pull/287
- https://github.com/onflow/flow-core-contracts/pull/278
We cannot update these contracts on the current networks as they are incompatible with the currently deployed version of Cadence (deployment will fail with type checks), and we cannot deploy them after the network upgrade, as the core contracts are used during the startup of the Execution Node, before we could send contract update transactions.
Add a state migration which updates the core contracts directly in the execution state.
> Add state migration for Flow Core Contracts

- engine/execution/testutil/fixtures.go
- engine/execution/testutil/fixtures_counter.go
- fvm/context.go
- fvm/fvm_test.go
- fvm/handler/contract.go
- fvm/handler/contract_test.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
This PR separates the context flag for contract removal and contract updates. 
the flag for contract updates is re-writable by the service account state, contract removals are only can be set by flags for now, since there is no plan to disable it anytime soon. 
This should keep removals restricted even when we open up deployments.
> [fvm] separate deployment removal restriction flags

- cmd/access/node_builder/access_node_builder.go
- module/jobqueue/sealed_header_reader.go
- module/jobqueue/sealed_header_reader_test.go
- module/state_synchronization/requester/execution_data_requester.go
- module/state_synchronization/requester/execution_data_requester_test.go
- module/state_synchronization/requester/jobs/execution_data_reader.go
- module/state_synchronization/requester/jobs/execution_data_reader_test.go
- module/state_synchronization/requester/unittest/unittest.go
This pulls https://github.com/onflow/flow-go/pull/2566 into the v0.26 branch
> [State Sync] Lookup ExecutionResult directly instead of using index (v0.26)

- cmd/util/cmd/read-badger/cmd/seals.go
With the new seal index added, when using util cmd to query seals by block ID, it's more useful to query the seal for the given block , instead of the highest in fork seal.
> [util] update cmd to get seal for sealed block

- engine/access/rpc/backend/backend_transactions.go
- engine/access/rpc/engine.go
https://github.com/onflow/flow-go/pull/2412 left the closer logic untouched, preventing the connections cached from being reused. This PR removes the closer logic in place.
> Use Connection Pool Logic

- integration/localnet/Makefile
- integration/localnet/bootstrap.go
- integration/localnet/conf/promtail-config.yaml
- integration/localnet/docker-compose.metrics.yml
This should allow both perf automation and loki to use logs at the same time.
Fixes: #2510
> localnet: switch from docker log driver to promtail

- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- cmd/util/ledger/reporters/account_reporter.go
- cmd/util/ledger/reporters/atree_reporter.go
- cmd/util/ledger/reporters/export_reporter.go
- cmd/util/ledger/reporters/fungible_token_tracker.go
- cmd/util/ledger/reporters/fungible_token_tracker_test.go
- ledger/complete/ledger.go
- ledger/ledger.go
The state extraction util will run the migration and then generate a export-state.json file which includes the statecommitment before and after the migration. 
However, there is a bug that the statecommitment in the exported json file is wrong, it is showing the same statecommitment as the one before the migration. See comment about why it's wrong.
This PR fixes it.
> fix logging current statecommitment in execution state extraction

- engine/execution/computation/manager.go
We were passing these values to these logging functions in the wrong order
> Fix reversed numbers for script metrics

- cmd/util/ledger/migrations/core_contracts_migration.go
Just like we updated the Core Contracts during the Testnet spork, we also need to update them during the Mainnet spork.
I took the addresses from https://docs.onflow.org/core-contracts/. Please verify these are correct.
> Add addresses for Mainnet to Core Contract state migration

- cmd/access/node_builder/access_node_builder.go
- integration/utils/blob_service.go
- module/jobqueue.go
- module/jobqueue/finalized_block_reader.go
- module/jobqueue/sealed_header_reader.go
- module/state_synchronization/requester/execution_data_requester.go
v0.26 Backport #2629: Add exponential backoff for execution data download timeouts
When an ExecutionData request fails, bitswap does not return until the context times out. This means if we naively wait for the full max timeout, there is a large delay whenever there's an issue with a peer or the network. However, we can't just make the timeout short either in case there is a large blob that takes a while to download.
This PR adds an incremental backoff for the timeout, and configuration to control the settings.
> Add exponential backoff for execution data download timeouts - v0.26

- integration/localnet/docker-compose.metrics.yml
Previously, jaeger-all-in-one container was running implicitly under root (its Dockerfile does not have `USER` directive).  Make new stack also run under `root` so there are no permission problems under Linux.
Please note that this should not affect security in any way, since:
* this is the username _inside_ the container.
* these are `localnet`-only containers.
* no changes under macOS or on Linux where docker does not run under root user itself.
> chore(localnet): force uid within the container to be root

- model/flow/sealing_segment.go
- storage/badger/operation/seals.go
follow up to [PR #2551](https://github.com/onflow/flow-go/pull/2551): 
* minor extension of sealing segment's documentation
* fixed some typos
> minor cleanup of sealing segment and fixing typos

- cmd/access/node_builder/access_node_builder.go
- cmd/execution_builder.go
- cmd/util/cmd/execution-data-blobstore/cmd/get.go
- integration/tests/access/execution_state_sync_test.go
- model/encoding/cbor/codec.go
- module/state_synchronization/execution_data_service_test.go
- module/state_synchronization/requester/execution_data_requester_test.go
Execution nodes may produce `ExecutionData` blobs with very large cbor encoded data structures. This PR sets the limits to max for Access Node `ExecutionDataRequest` and adds configuration to the cbor codec to allow providing custom `EncMode`/`DecMode` settings.
> Override cbor DecMode config in execution data requester

- engine/execution/computation/computer/computer.go
- engine/execution/computation/computer/computer_test.go
- fvm/context.go
- fvm/fvm_test.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
Disable reading (mutating) the context from the state for system transaction and explicitly set a very high memory limit.
> [FVM] Don't read context from state on system chunk

- engine/execution/computation/computer/computer.go
The callbacks make the code less readable
> Simplify blockCommitter/eventHasher

- engine/execution/computation/manager_benchmark_test.go
- engine/execution/testutil/fixtures_token.go
This adds a simple Manager benchmark that tries to emulate the end-to-end work performed by the EN.
```
$ go test -tags relic -bench='BenchmarkComputeBlock' -run='^$' ./engine/execution/computation/.
goos: darwin
goarch: arm64
pkg: github.com/onflow/flow-go/engine/execution/computation
BenchmarkComputeBlock/1/cols/16/txes-8               114          10037768 ns/op               627.0 us/tx
BenchmarkComputeBlock/1/cols/32/txes-8                62          18779974 ns/op               586.0 us/tx
BenchmarkComputeBlock/1/cols/64/txes-8                32          36278986 ns/op               566.0 us/tx
BenchmarkComputeBlock/1/cols/128/txes-8               15          71406369 ns/op               557.0 us/tx
BenchmarkComputeBlock/4/cols/16/txes-8                30          35817418 ns/op …
```
> [Exec] Add manager benchmark

- engine/consensus/provider/engine_test.go
`Suite` shouldn't be passed by value because it contains `sync.RWMutex`.
Use `*Suite` instead of `Suite` in `TestOnBlockProposal_RemoteOrigin` to pass `sync.RWMutex` lock by reference.
> Fix copylocks in TestOnBlockProposal_RemoteOrigin

- engine/access/access_test.go
- engine/access/rpc/backend/backend_accounts.go
- engine/access/rpc/backend/backend_events.go
- engine/access/rpc/backend/backend_scripts.go
- engine/access/rpc/backend/backend_test.go
- engine/access/rpc/backend/backend_transactions.go
- engine/access/rpc/backend/connection_factory.go
- engine/access/rpc/backend/connection_factory_test.go
- engine/access/rpc/backend/mock/connection_factory.go
- module/mock/network_metrics.go
- This change removes the use of the grpc closers from AN's connection factory
- This change allows connections to EN to be reused properly without closing the connection at the end of every call
- This change would also fix a race condition from when a request is made, and the deferred closer logic fails to close before another request is then made. For example if `ExecuteScriptAtBlockID` was called an Exec RPC Client would be cached. Before the first `ExecuteScriptAtBlockID` finishes and the deferred closer logic gets to execute, if a second ExecuteScriptAtBlockID was called, the original cached Exec RPC Client would then be reused, and before the second call gets a chance to use the client, the first call could execute the closer logic.
> Invalidate Pooling Logic in AN

- cmd/collection/main.go
- engine/collection/epochmgr/factories/builder.go
- engine/testutil/nodes.go
- module/builder/collection/builder.go
- module/builder/collection/builder_test.go
- module/builder/collection/config.go
https://github.com/onflow/flow-go/pull/2615 targeting `v0.26`
> Implement outcome from [TPM discussion](https://www.notion.so/dapperlabs/Technical-Product-Meeting-with-Dete-054824f0be334392806e1e39641afe48#6147b5a1c83a4842822c9202e8dbf6de). Adds an option to dry-run rate limiting, which will log each time a transaction would have been rate limited (but won't actually rate limit it).
In addition, adjusts default config:
* enables rate limit @ 1tx/collection
* enables dry-run for rate limit
> [`v0.26`] Add dry-run option for collection rate limiting

- module/jobqueue/component_consumer_test.go
Unskipping TestComponentConsumerSuite/TestHappyPath/runs_and_notifies_using_pre-notifier.  Test passes according to new Grafana panel showing skipped tests that are passing 100%.
> Unskipping passing flaky test

- model/flow/header.go
This 1 item caching introduces global lock.  Also code is quite brittle and can cause bugs if `Header` struct changes.
This diff is no-op on Skylake:
```
name                              old us/tx    new us/tx    delta
ComputeBlock/1/cols/16/txes-16     1.44k ± 0%   1.46k ± 3%    ~     (p=0.099 n=9+10)
ComputeBlock/1/cols/32/txes-16     1.37k ± 1%   1.38k ± 1%  +0.60%  (p=0.007 n=9+10)
ComputeBlock/1/cols/64/txes-16     1.36k ± 1%   1.35k ± 0%  -0.51%  (p=0.014 n=10+8)
ComputeBlock/1/cols/128/txes-16    1.34k ± 1%   1.34k ± 0%    ~     (p=0.673 n=10+9)
ComputeBlock/4/cols/16/txes-16     1.36k ± 2%   1.36k ± 1%    ~     (p=0.237 n=10+10)
ComputeBlock/4/cols/32/txes-16     1.34k ± 1%   1.34k ± 1%    ~     (p=0.329 n=10+10)
ComputeBlock/4/cols/64/txes-16     1.35k ± 1%   1.34k ± 2%    ~ …
```
> Remove header caching

- fvm/programs/programs.go
- reduce Get's critical section (don't hold lock when looking up parent's entry)
- guard HasChanges
cc: https://github.com/dapperlabs/flow-internal/issues/1722
> tweak Programs locking + minor refactoring

- cmd/scaffold.go
- follower/consensus_follower.go
The consensus follower has its own `Config` struct which limits the scope of what can be configured by passing in configuration arguments to the constructor. This PR adds compliance config to the Follower's Config, so it is configurable when instantiating a Follower instance. 
Port of https://github.com/onflow/flow-go/pull/2697
> [`v0.26`] Extend consensus follower config to support compliance settings

- integration/go.mod
- integration/utils/contLoadGenerator.go
- integration/utils/tx_result.go
Flow API does not guarantee that `GetTransactionResult` is synchronized with the `GetBlockByHeight` results, hence we can get into a situation where after Follower reports successful execution of the transaction a subsequent `GetTransactionResult` still reports it being only in a `Finalized` state.  Hence, added `GetTransactionResult` that can gently spin on txID waiting for it to get into a terminal state.
> chore(loader): wait for account creation results

- integration/localnet/Makefile
- integration/localnet/README.md
#2759 
According to the change below, multiple execution nodes are required to prevent block seals to be generated in case of execution forks. Thus if there's only one EN node running, no blocks will be sealed. To avoid future confusion in localnet uses, now we put this checking into the Makefile.
https://github.com/onflow/flow-go/pull/632/files#diff-7fd319f5e35ff086e91814317aadbcb86eb3a89b904bf6a3cc38cb7a6ac40bf6R41-R42
Also applying the same check for consensus node.
> [localnet] Adding checking to EXECUTION configuration

- model/flow/sealing_segment.go
- model/flow/sealing_segment_test.go
- state/protocol/badger/snapshot_test.go
This PR adds a test case and extends the implementation of `SealingSegment` to deal with an unhandled edge case:
* sealing segment contains the root block
* sealing segment contains more than one block 
This edge case shows up in integration tests, when we request a root snapshot immediately after the network starts up.
> [Sealing Segment] Handle root sealing segment with multiple blocks

- integration/localnet/bootstrap.go
This is a followup fix that merges #2510 into #2554.
Some cleanup is needed before we can switch from opentracing to opentelemetry.
> chore(localnet): fix observer's trace endpoint

- fvm/env.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
A big chunk of the code in ScriptEnv and TransactionEnv are copy/paste
identical.  It's easy to forget to fix bugs in both place and hard to make
improvements.
Notes:
1. I've decided to merge the shared code piecemeal since it's scary to
merge everything at once.
2. The environment variable e has been renamed to env since it's more
searchable
3. (A real change) I've presized the array allocation in RecordTrace
> dedup code in script/transaction environment (part 1 of many)

- module/trace/trace_test.go
This adds simple benchmarks for root and parent span creation.
This will be useful for estimating testing perf difference between opentracing and opentelemetry.
```
name                              time/op
StartSpanFromParent-8              469ns ± 5%
StartTransactionSpan/cacheHit-8   1.01µs ± 5%
StartTransactionSpan/cacheMiss-8  2.25µs ± 4%
name                              alloc/op
StartSpanFromParent-8               577B ± 0%
StartTransactionSpan/cacheHit-8     775B ± 1%
StartTransactionSpan/cacheMiss-8  2.15kB ± 2%
name                              allocs/op
StartSpanFromParent-8               7.00 ± 0%
StartTransactionSpan/cacheHit-8     10.0 ± 0%
StartTransactionSpan/cacheMiss-8    35.2 ± 3%
```
> chore(tests): add trace benchmark

- Makefile
- cmd/Dockerfile
- crypto/Makefile
- integration/Makefile
- integration/loader/Dockerfile
- utils/binstat/README.md
- utils/binstat/binstat_external_test.go
Since go 1.16 `GO111MODULE=on` is the default. Since 1.17 `go get` for binaries is deprecated. Since 1.18 it is disabled.
Is there any reason to keep it?
> Remove GO111MODULE=on everywhere

- engine/unit.go
Race scenario:
goroutine 1 (calls unit.Launch)
checked the context has not cancelled
context switch
goroutine 2 (calls unit.Done)
cancels the context
finished waiting for the wait group
(unit is "Done" at this point)
context switch
goroutine 1 (remaining half of the original Launch call)
add to wait group
> Fix Unit race condition on stopping.

- consensus/hotstuff/signature/block_signer_decoder.go
- consensus/hotstuff/signature/block_signer_decoder_test.go
* follow up to PR https://github.com/onflow/flow-go/pull/2789
* changes in this PR are identical to fix for `master`: https://github.com/onflow/flow-go/pull/2830
For block `44f..a`, the access API fails to decode the signer indices:
```
could not decode signer indices for block 44ff570d66aeac087da261e7bac13247fa96bbb0792ee65cf8714e3632da034a: signer indices' checkum is invalid: decoder sees a canonical list [...], which has a different checksum eb94d50f than the encoder's checksum ef2c778c: index vector's checksum is invalid
```
I think it the culprit is this line in the code:
https://github.com/onflow/flow-go/blob/01fae8ea3b6658715880aa014866e9b8b61233bb/consensus/hotstuff/signature/block_signer_decoder.go#L38-L39
* because a block includes the signatures for the _parent_
* but we are …
> fixed decoding error for signer indices at epoch switchover

- fvm/env.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
This enables to us to continue with the dedup-ing effort while waiting on #2800.
I've dedup `Hash()` in the same commit as proof of concept.
Per usual, I've renamed the environment variable `e` to `env` to improve searchability.
> Add ComputationMeter interface to facilitate env code dedup-ing

- integration/loader/main.go
- integration/utils/accounts.go
- integration/utils/contLoadGenerator.go
- integration/utils/scripts.go
- integration/utils/scripts/constExecCostTransaction.cdc
#2785 
As part of Dynamic Inclusion Fee feature development (more details can be found at https://www.notion.so/dapperlabs/Variable-Transaction-Fees-Inclusion-Effort-I-20c849105a3945879824e386cc9c3ebf by @janezpodhostnik ), we will need to get proper co-efficient values for the new inclusion fee equation that can fit well with our production transactions with different sizes. Before we do that in production, we will need to be able to create tx with given sizes sent to devnet\testnet to get initial metrics. 
This PR adds a new loader test type that allows us to create and send tx with given size.
> Adding new load test type for constant sized transactions

- cmd/Dockerfile
#2707 
Summary
`make docker-build-execution-debug` now under flow-go master fails with error of `go get` failure of https://github.com/go-delve/delve/cmd/dlv. Error is gone after using `go install` instead of `go get`
Test Plan
[X] run `make docker-build-execution-debug` to see build passing
[X] run built docker image to see it running fine
[X] ssh into the running docker image with `docker exec -it <DOCKER_ID> /bin/bash`
> [Execution] Fixed EN debug docker image build failure

- fvm/env.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
NOTE:
1. There were slight differences between the two GenerateUUID implementation.
ScriptEnv's check for nil first before metering whereas TransactionEnv meter
first before checking for nil.  I've pick the ScriptEnv's implementation as
the common implementation since that seem more correct.
2. The environment variable e has been renamed to env since it's more
searchable.
> dedup code in script/transaction environment (part 2 of many)

- fvm/env.go
- fvm/env_context.go
- fvm/program_logger.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
- fvm/unsafe_random_generator.go
Once env is fully dedup-ed, I plan to split env into coherent units, leaving
env as a facade interface for cadence, with almost no code.
I've split out a few easy pieces in this PR as proof of concept to get some
feedbacks.
> Split env context, unsafe rand gen, and program logger into logical units

- fvm/env.go
- fvm/handler/metrics.go
- fvm/program_logger.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
1. Move program logging related api from commonEnv to ProgramLogger
2. Combine MetricsHandler logic into ProgramLogger
NOTE: I plan to do the same thing with the other handlers, and then move all env
related code into a separate package.
> refactor program logging

- .github/workflows/bench.yml
This is a followup to #2821 that removes the last reference of `GO111MODULE` env var.
> [FVM] cleanup benchstat installation

- cmd/scaffold.go
This diff makes localnet and benchnet perf tests more realistic by supporting fee deduction.  (Fee deduction currently accounts for ~30% of transactions' execution time.)
Issue: https://github.com/dapperlabs/flow-go/issues/6310
> [FVM] Deduct fees on all networks by default

- fvm/accounts_test.go
- network/p2p/dns/resolver.go
Fixing the following linting error
```
network/p2p/dns/resolver.go:37:2: field `processingTXTs` is unused (unused)
processingTXTs map[string]struct{} // ongoing txt lookups through underlying resolver
^
network/p2p/dns/resolver.go:36:2: field `processingIPs` is unused (unused)
processingIPs  map[string]struct{} // ongoing ip lookups through underlying resolver
^
fvm/accounts_test.go:1490:86: SA4009: argument view is overwritten before first use (staticcheck)
run(func(t *testing.T, vm *fvm.VirtualMachine, chain flow.Chain, ctx fvm.Context, view state.View, programs *programs.Programs) {
^
fvm/accounts_test.go:1500:5: SA4009(related information): assignment to view (staticcheck)
view = delta.NewView(func(owner, key string) (flow.RegisterValue, error) {
^
```
> Fix linting

- engine/execution/computation/manager_benchmark_test.go
This diff enables `AccountStorageLimit` and `TransactionFees` for transactions in synthetic tests.  While here it also uses real tracer instead of a `NoopTracer` one to capture its overhead.  This more than doubles execution time and memory usage.
```
$ benchstat old new
name                             old time/op    new time/op    delta
ComputeBlock/1/cols/16/txes-8      10.1ms ± 3%    18.4ms ± 3%   +82.04%  (p=0.000 n=8+10)
ComputeBlock/1/cols/32/txes-8      18.4ms ± 5%    34.5ms ± 1%   +87.19%  (p=0.000 n=9+10)
ComputeBlock/1/cols/64/txes-8      35.2ms ± 7%    67.5ms ± 0%   +91.77%  (p=0.000 n=10+8)
ComputeBlock/1/cols/128/txes-8     67.4ms ± 1%   134.4ms ± 1%   +99.36%  (p=0.000 n=9+10)
ComputeBlock/4/cols/16/txes-8      34.8ms ± 3%    66.8ms ± 1%   +92.20%  (p=0.000 n=10+9) …
```
> [FVM] Deduct fees and limit storage in synthetic benchmarks

- fvm/fvm_bench_test.go
This is more accurate since service account bypasses a lot of checks.
> Run fvm benchmark transactions under a regular account

- admin/commands/common/set_profiler_enabled.go
- cmd/scaffold.go
- module/profiler/profiler.go
- module/profiler/profiler_test.go
While here added a comment.  Noop otherwise.
Issue: https://github.com/dapperlabs/flow-go/issues/6310
> [Profiler] move out of ./utils/debug to ./module/profiler

- module/profiler/profiler.go
[It has been broken since 2013](https://github.com/golang/go/issues/6104). Verified on localnet and removed.
> [Profile] disable threadcreate profiler

- .github/workflows/flaky-test-debug.yml
[Flaky Test Debug Github Actions](https://github.com/onflow/flow-go/actions/workflows/flaky-test-debug.yml) workflow is unnecessarily running every hour and wasting Github runner resources.
It was de-activated manually in Github in the past but has since been reactivated. The schedule is set to run every hour and that needs to be deactivated.
> De-activate schedule on Flaky Test Debug Github workflow

- cmd/node_builder.go
- cmd/scaffold.go
- cmd/scaffold_test.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- module/profiler/profiler.go
- module/profiler/profiler_test.go
- module/profiler/uploader.go
- module/profiler/uploader_test.go
This diffs adds an ability to upload AutoProfiler pprof files to [Cloud Profiler](https://cloud.google.com/profiler/docs/about-profiler).
For this to work VM should be running in GCE, have access to `cloudprofiler.googleapis.com:443`, and have the `https://www.googleapis.com/auth/monitoring.write` scope.  Also, one should check their "Create offline requests per day" quota.
Note that, this functionality is currently hidden behind both `-profiler-enabled` and `-profile-uploader-enabled` feature flags.
While here, also:
* Removed Mutex profiling, since [Block profiling is better](https://github.com/DataDog/go-profiler-notes/blob/main/block.md) for our usecase. 
* Switched from heap to alloc profile.  These only differ in the default sample name but identical otherwise.
Issue: …
> [Profiler] Automatic pprof profile uploads to Google Cloud Profiler.

- engine/collection/compliance/core.go
- engine/consensus/compliance/core.go
This PR removes a O(N^2) loop in processing block proposals. See reasoning in comments.
The loop would cause a unnecessary O(N^2) operation when processing a range of blocks from sync engine and the first block is pending.
> [SyncEngine] not request pending ancestors

- Makefile
- README.md
This also adds support for go1.20+ since `gotip` is already on it:
```
gotip version
go version devel go1.20-f28fa95 Wed Aug 3 12:52:27 2022 darwin/arm64
```
> [Makefile] bump minimum golang version to 1.18

- fvm/env.go
- fvm/env_context.go
- fvm/program_logger.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
- fvm/unsafe_random_generator.go
1. Renamed EnvContext to Tracer
2. Stop passing Context into program logger / tracer / rand gen.  Only pass
in what's necessary.
> Rename EnvContext to Tracer + Reduce dependency on Context

- utils/unittest/logging.go
- utils/unittest/unittest.go
- utils/unittest/unittest_test.go
Currently, we don't have a way of testing for situations that cause fatal log messages because `zerolog` calls `os.Exit(1)` on a call to `Fatal()`. As part of the ingress message implementation for BFT Testing, we have 2 situations that cause a fatal error: 
- when both ingress and egress message are nil
- when both ingress and egress message are not nil
In order to test for these conditions we want to have a mechanism that allows us to test that a fatal error occurred but without exiting the test run while it's running.
This PR was originally part of https://github.com/onflow/flow-go/pull/2811 but got extracted so it's a stand alone PR because it is a generic utility that can be used by other parts of the code to test for crash conditions.
> [BFT Testing] Crash Test utility

- .github/workflows/ci.yml
- bump golangci-lint action from v2 to v3
- bump golangci-lint from 1.45 to 1.46
This fix is based on [changes](https://github.com/onflow/flow-go/pull/2935/files/f4c69ca5f0457012fe2da9ac7106e902c5a892a4..383e69a17f1c918f33276b48ed4cd3e235645071) in a branch by @durkmurder.  Many thanks Yurii!
This unblocks several PRs including PR [2930](https://github.com/onflow/flow-go/pull/2930).
Unfortunately, golangci-lint 1.47 and 1.48 didn't work.  There were lint errors reported on lines untouched for 2 years, etc.
> Bump golangci-lint action from v2 to v3

- fvm/env.go
- fvm/scriptEnv.go
- fvm/state/accounts.go
- fvm/state/address_generator.go
- fvm/state/state_holder.go
- fvm/state/uuids.go
- fvm/transactionEnv.go
- fvm/transactionInvoker.go
- fvm/transaction_test.go
Stop directly accessing State (aka sub-transaction).  In future PRs, I'll
standardize how sub-transactions are created / merge / dropped / etc.
> Expose more StateHolder methods

- engine/access/ingestion/engine.go
Extends https://github.com/onflow/flow-go/pull/2946. This eliminates a case where the `ingestion` engine will request collections below the last full block height.
> [v0.26] Hotfix: Skip requesting collections when below full height

- integration/localnet/Makefile
After we switched from loki to `promtail` in #2609 we added this cleanup.  Now that it's been there for a while, it should be safe to remove it.
> [Localnet] do not uninstall loki plugin on start

- integration/localnet/bootstrap.go
While here:
* added labels to observer logs
* added network, role, and num attributes to the trace emitter to be consistent w/ logs and metrics via `OTEL_RESOURCE_ATTRIBUTES`.
> [Localnet] deduplicate service creation

- cmd/util/cmd/read-execution-state/list-accounts/cmd.go
- cmd/util/ledger/reporters/account_reporter.go
- cmd/util/ledger/reporters/fungible_token_tracker.go
- engine/execution/computation/computer/computer_test.go
- engine/execution/computation/manager_test.go
- fvm/fvm.go
- fvm/handler/contract_test.go
- fvm/handler/programs_test.go
- fvm/meter/weighted_meter.go
- fvm/meter/weighted_meter_test.go
- fvm/programs/programs_test.go
- fvm/state/accounts_test.go
- fvm/state/address_generator_test.go
- fvm/state/state_test.go
- fvm/state/uuids_test.go
- fvm/transactionInvoker_test.go
- fvm/transactionSequenceNum_test.go
- fvm/transactionVerifier_test.go
- fvm/transaction_test.go
Prep work for plumbing fully initialized meter parameters from block computer to
transaction invoker
> Make NewMeter's parameters non-optional

- fvm/env.go
- fvm/executionParameters.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
setExecutionParameter has been converted into a normal function
In the future, we may want to move this into engine, and only fetch the weights / limits once per block
> Dedup setExecutionParameters

- cmd/observer/node_builder/observer_builder.go
Copy the line to parse the `rpc-metrics-enabled` flag from the access node builder to the observer node builder.
> Added rpc metrics flag to Observer Node Builder

- cmd/util/ledger/reporters/account_reporter.go
- engine/execution/computation/manager_test.go
- fvm/account.go
- fvm/executionParameters.go
- fvm/fvm.go
- fvm/meter/meter.go
- fvm/meter/weighted_meter.go
- fvm/meter/weighted_meter_test.go
- fvm/script.go
- fvm/scriptEnv.go
- fvm/state/state.go
- fvm/state/state_holder.go
- fvm/transactionEnv.go
- fvm/transactionInvoker.go
This ensures that all meter parameters are set in one place, which enables us
to safely remove PayerIsServiceAccount special casing (in future PR).
> Fully initialize meter parameters before transaction execution

- fvm/programs/programs.go
There is no need to take and release the lock when modified set is empty.
> [Performance] add fast path to programs cleanup

- integration/localnet/bootstrap.go
- integration/testnet/network.go
- integration/testnet/util.go
This is in preparation for enabling golangci-lint in `./integration/`
> [Testing] Remove legacy ioutil and os.Is* usage

- fvm/env.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
NOTE:
1. I've move meterMemory's logic into MeterMemory.
2. GetStorageCapacity: we're using the script env version, which has additional
comments.
3. GetAccountAvailableBalance: we're using the script env verion, which returns
0 instead of "value" (which is also zero) on error.
4. GetAccountKey: we're using the transaction env version.  accountKeys is
never nil.
> Dedup more environment code

- .github/workflows/bench.yml
This diff:
* Adds `BenchmarkComputeBlock` from `./engine/execution/computation` to the auto-benchstat
* Switches from the `^1.18` (i.e. >= `1.18` < `2.0`) to stricter `1.18`.  This unbreaks benchmark w/ go 1.19 release.
* Adds `.github/workflows/bench.yml` itself to the set of files being tracked.
While here, bump checkout and setup-go versions, and cleanup the comment a bit.
> [Performance] run computation benchmarks on commit

- network/p2p/compressed/compressedStream.go
With new upgrades, closing a stream also closes the writer side. So there is no need to report the writer returned error. Still closing writer on a defer to clean up resources.
> [Networking] Fix gzip stream closer

- fvm/fvm_test.go
- fvm/transactionInvoker.go
1. proc's fields were not correctly populated due to early exiting
2. also fixed meter tests (the tests were testing the wrong things)
(These issue was discovered when I tried to disable limiting while setting
meter weights/limits).
> Fix transaction invoker to not early exit once transaction started

- cmd/scaffold.go
Profiler is using `fnb.RootChainID` which is initialized in `initState`.
This leads to servicename being `unknown-execution` instead of `devnet-execution`.
Fixes: #2903
> [Performance] initialize profiler after the state init

- cmd/scaffold.go
This is a backport of #2985 to the v0.27.
> [Performance] initialize profiler after the state

- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/flaky-test-monitor-integration.yml
- .github/workflows/flaky-test-monitor.yml
- .github/workflows/skipped-test-tracker-integration.yml
- .github/workflows/skipped-test-tracker.yml
https://docs.github.com/en/actions/using-jobs/using-concurrency
Update the actions that are typically run on PRs to cancel themselves if a new commit has been made to that PR
> Cancel previous workflows on the same PR

- cmd/scaffold_test.go
`gcemd.Client` caches some (immutable) results (e.g. ProjectID and InstanceID) in global variables, so it is impossible to run multiple tests against it.
Tested w/:
```
$ go test -race -count 100 -tags relic ./cmd
```
> [Testing] fix TestCreateUploader flakes

- cmd/util/ledger/reporters/export_reporter.go
The export reporter no longer need to query the epoch counter from the execution state, we will query it directly from EN during spork. 
This PR removes that logic and set the epoch counter to 0 for now.
> remove epoch counter and set it to 0

- integration/benchmark/follower.go
- integration/benchmark/follower_test.go
This fixes a bunch of TODOs that were complaining that tests were mostly noops.
While here, also remove the `WithBlockHeight` option: it is unused and testing showed that it was broken.
> [Testing] Add proper mock-based TxFollower tests

- cmd/util/cmd/read-execution-state/list-accounts/cmd.go
- cmd/util/ledger/reporters/account_reporter.go
- cmd/util/ledger/reporters/fungible_token_tracker.go
- engine/execution/computation/computer/computer_test.go
- engine/execution/computation/manager_test.go
- fvm/executionParameters.go
- fvm/fvm.go
- fvm/handler/contract_test.go
- fvm/handler/programs_test.go
- fvm/programs/programs_test.go
- fvm/state/accounts_test.go
- fvm/state/address_generator_test.go
- fvm/state/state.go
- fvm/state/state_holder.go
- fvm/state/state_test.go
- fvm/state/uuids_test.go
- fvm/transactionInvoker_test.go
- fvm/transactionSequenceNum_test.go
- fvm/transactionVerifier_test.go
- fvm/transaction_test.go
Also renamed NewStateHolder to NewStateTransaction in preparation for renaming
the struct.
> Internalize state/meter creation

- admin/commands/execution/checkpoint_trigger.go
- cmd/bootstrap/run/execution_state.go
- cmd/execution_builder.go
- cmd/util/cmd/exec-data-json-export/ledger_exporter.go
- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
- engine/testutil/nodes.go
- ledger/complete/compactor.go
- ledger/complete/compactor_test.go
- ledger/complete/ledger_benchmark_test.go
- ledger/complete/ledger_test.go
- ledger/complete/wal/checkpointer_test.go
- utils/unittest/logging.go
This PR adds an admintool to force checkpoint to be triggered as soon as finish writing the current segment WAL file.
> add admin tool for triggering checkpoint

- Makefile
File path was missed in move update, correcting move from integration/loader to integration/benchmark/cmd/manual
> Repair docker-build-loader Makefile

- engine/execution/testutil/fixtures.go
- fvm/errors/errors.go
- fvm/executionParameters.go
- fvm/executionParameters_test.go
- fvm/fvm_fuzz_test.go
- fvm/fvm_test.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
- fvm/transactionInvoker.go
There was an error occurring on testnet with the new v0.27 ([slack link](https://axiomzen.slack.com/archives/C015G65HR2P/p1660235921269599))
```json
{
"level": "error",
"node_role": "execution",
"node_id": "48601e8a1568f18ca4a574a656710342857f939f598679280a6941cc7b800b6f",
"error": "[Failure Code: 2000] unknown failure: Execution failed:\nerror: fatal error: storage error: get value failed: [Error Code: 1110] computation exceeds limit (10)\n--> \n",
"time": "2022-08-11T14:17:02Z",
"message": "error getting execution memory limit"
}
```
Whats happening here is that the gas limit runs out as the state config (memory weights, execution weights and memory limit) is being loaded, before the transaction really even started execution.
There is a few issues here:
- This error should have not …
> [FVM] Fix transactions with low gas

- engine/access/access_test.go
- engine/access/ingestion/engine.go
- engine/access/ingestion/engine_test.go
- state/protocol/badger/snapshot.go
- storage/badger/blocks.go
- storage/badger/operation/heights.go
- storage/badger/operation/heights_test.go
- storage/blocks.go
- storage/mock/blocks.go
- storage/mocks/storage.go
This pull requests updates the LastFullBlockHeight in the ingestion engine component startup so that we only request missing collections in blocks above that height. In the processFinalizedBlock func we skip requesting collections for blocks under the lastFullBlockHeight.
> Khalil/1761 

- integration/Makefile
Previously it contained TPS test and was explicitly skipped by CI.  Nowadays it contains legitimate unit tests for the end-to-end TPS benchmark.
> [Testing] Enable unit-testing of the benchmark directory

- .github/workflows/ci.yml
- .golangci.yml
- bors.toml
- crypto/ecdsa.go
Main change is enabled linting in sub-packages: `integration` and `crypto`.
While here:
* bumped `actions/setup-go` and `actions/checkout` to v3.
* bumped timeout for golangci to 10m due to recently increased failure rate.
* pin `shellcheck` to `203a3fd018dfe73f8ae7e3aa8da2c149a5f41c33` and move it out of `golangci`.
* moved shellcheck to a separate step.
* run `go generate` before ci lint.
* enable caching for go builds.
* checkout before setup go: caching depends on go.mod being available.
Depends on: #2970 #3007
> [Testing] Enable Lint for ./crypto and ./integration

- Makefile
The Loader files were recently moved and the target location for this makefile target became out of sync. Pointing the target to the new loader location.
These changes were tested with `sudo make docker-build-benchnet CONTAINER_REGISTRY=[gcr.io/flow-benchmark](http://gcr.io/flow-benchmark) IMAGE_TAG=benchnet1` and `sudo make docker-build-loader CONTAINER_REGISTRY=[gcr.io/flow-benchmark](http://gcr.io/flow-benchmark) IMAGE_TAG=benchnet1`. This should cover both the smallest case and the end to end case of usage.
> [Build] Update docker-build-loader target

- Makefile
A followup for #3027 that showed that we do not do mock diffs on the first CI run.
> [Testing] Diff mocks in CI

- insecure/corruptible/network_common_test.go
- utils/unittest/unittest.go
- utils/unittest/unittest_test.go
In this PR:
* Remove the need to pass test name and rely on `t.Name()` instead.
* Add ability to catch error codes > 1. (This may happen in libraries that conform to  BSD's [sysexits.h](https://www.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD+14.0-current&arch=default&format=html) or command-line utils, that frequently use `os.Exit(2)`)
* Add ability to catch explicit set of error codes.
* Switch from text parsing to using `cmd.ProcessState.ExitCode()`.
Ref: #2941
> [Testing] Minor improvements to crash test

- .github/workflows/ci.yml
- Makefile
- crypto/spock.go
- engine/collection/ingest/engine_test.go
- state/protocol/badger/mutator_test.go
Factors out `go vet` changes from #2988 and bumps the CI version.
> [Testing] Bump golangci-lint to v1.47.3

- network/p2p/dht_test.go
- network/p2p/libp2pStream_test.go
- network/p2p/sporking_test.go
- network/p2p/topic_validator_test.go
Factor out test changes from #2988
* fix `TestPubSubWithDHTDiscovery` race.
* remove hardcoded test names from DHTPrefix.
* always wait for nodes to be stopped.
* lower number of streams in test to 50 to be within [libp2p limits](https://github.com/libp2p/go-libp2p/blob/master/limits.go).
@yhassanzadeh13 you may consider returning stopNode closure from `nodeFixture` since stopping is always required.
Ref: #3034
Ref: #2988
> [Networking] Reduce test flakes

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- module/profiler/profiler.go
- module/profiler/profiler_internal_test.go
- module/profiler/profiler_test.go
Switch `ALLOC_HEAP` to upload "allocs" diff within the profiling duration, while `HEAP` only uploads the "inuse" objects.
Aside from being more consistent with both `pprof` http endpoint and `cloudprofiler` reference library, it also workarounds some of GCP API limits since it greatly reduces profile sizes:
```
Failed to create offline profile: rpc error: code = ResourceExhausted desc = Received message larger than max (46449079 vs. 16777216)
```
> [Profiler] Add heap allocation diffs

- storage/badger/operation/common.go
- storage/badger/operation/common_test.go
Adding `upsert` operation to BadgerDB operation list. 
Existing `insert()` errs out when key already exists, `update()` errs out when there's no given key already existed. `upsert` can be useful in certain use cases so that we will not have to `get()->insert()` which is unnecessarily slow.
Ref discussion: https://github.com/onflow/flow-go/pull/2743#discussion_r949695662
**Test**
> Adding Upsert for BadgerDB operations

- fvm/accounts_test.go
- fvm/fvm_blockcontext_test.go
- fvm/fvm_test.go
- fvm/handler/programs_test.go
- fvm/programs/programs.go
- fvm/transaction_test.go
(This is identical to #3084.  I accidently destroy the both local/upstream branch rebasing)
The upcoming changes to program cache will use txIndex as logical time for
optimistic concurrency control.
Fixing the tests up front / in a separate PR since the program cache changes
are massive enough by themselves.
> Fix tests to use correct increasing tx index (attempt #2)

- Makefile
To make sure every call to `make generate-mocks` use the proper version of mock generator, now adding `install-mock-generators` as target dependency of `generate-mocks`.
One-liner change.
> Adding install-mock-generators as dep to generate-mocks in Makefile

- integration/tests/access/access_test.go
- integration/tests/access/consensus_follower_test.go
- integration/tests/access/execution_state_sync_test.go
- integration/tests/bft/passthrough/suite.go
- integration/tests/bft/wintermute/suite.go
- integration/tests/collection/suite.go
- integration/tests/consensus/inclusion_test.go
- integration/tests/consensus/sealing_test.go
- integration/tests/epochs/suite.go
- integration/tests/execution/suite.go
- integration/tests/ghost/ghost_node_example_test.go
- integration/tests/mvp/mvp_test.go
- integration/tests/verification/suite.go
- utils/unittest/logging.go
Noticed during access integration test troubleshooting.  Most of these hardcoded callers are wrong.
> [Testing] Add LoggerForTest to avoid hardcoding Caller

- fvm/env.go
- fvm/handler/programs.go
- fvm/state/state_holder.go
- fvm/state/state_transaction_test.go
- fvm/transactionInvoker.go
- fvm/transactionSequenceNum.go
- fvm/transaction_test.go
1. Refactor program handler's state stack into StateHolder.
2. Switch transaction invoker and seq num verifier to the new api
In a future PR, I'll restrict access to Environment methods (if cadence accesses
anything besides GetCode, we need to know about it, and invalidate the programs
cache accordingly).
> Standardize nested transaction creation/restart/commitment

- module/profiler/profiler.go
- module/profiler/profiler_test.go
Cleanup failed pprof collections.  Also atomically create/write/close/rename files so we won't have half written files there.
Also, while here, add a test that verifies that all pprof file types were created.
Depends on: #3043
> [Profiler] Remove pprof files on failure

- fvm/contractFunctionInvoker.go
- fvm/contractFunctionInvoker_test.go
- fvm/env.go
- fvm/transactionEnv.go
...so we don't forget to call it somewhere, as was the case already (with the storage check).
> [FVM] Move HandleRuntimeError to ContractFunctionInvoker

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- network/p2p/fixture_test.go
- network/p2p/libp2pNodeBuilder.go
- network/p2p/libp2pStream_test.go
- network/p2p/utils_test.go
- network/test/testUtil.go
By default libp2p [autoscales limits based on available system memory](https://github.com/libp2p/go-libp2p/blob/2f0d7502981e8e0806e5a47da493220becc23659/p2p/host/resource-manager/limit_defaults.go#L307-L312).  This is irrelevant in production but in tests flakes rate is inversely proportional to the amount of memory a container has. (This also makes it hard to reproduce the flake locally.)
While here also bump `github.com/libp2p/go-libp2p-resource-manager` to v0.5.3 and reset `streamCount` to 100 in `TestCreateStream.*` tests to verify the fix.
This diff should also fix some of the p2p-related "Unit test" flakes.
> [Networking] Explicitly set resource limits in tests

- engine/execution/computation/manager_benchmark_test.go
Leave only the slowest benchmark since it is the least noisy one.
As a side effect this also speeds up FVM benchmarks by quite a bit and makes output a bit less chaotic.
> [Benchmark] Remove noisy benchmarks

- integration/localnet/Makefile
- integration/localnet/bootstrap.go
This may be useful when we migrate to k8s and there would be no direct access to the pprof files on the filesystem.
> [Testing] Add an ability to enable Localnet pprof uploader

- integration/benchmark/worker_stats_tracker.go
Synchronize stat reads in `Digest()` with a mutex. While here, also group stats into a structure so we don't need to lock/unlock separately for each stat.
> [Benchmark] Remove race in Digest() print

- integration/benchmark/worker.go
- integration/benchmark/worker_test.go
Do not block on channel at the start of the loop.  This removes delay on `Stop()`.  While here, also add a test case that would verify that.
> [Benchmark] Faster stopping of workers

- engine/execution/computation/manager_test.go
1ms is enough to pass the test most of the times but it gets really flaky with race detector on.
Ref: #3034
> [Execution] Fix TestScriptStorageMutationsDiscarded timeout

- integration/benchmark/cmd/ci/main.go
- integration/benchmark/cmd/manual/main.go
- integration/benchmark/prometheus.go
- integration/benchmark/prometheus_test.go
Zero initialized channel is unusable in go, even if the only action taken is close.  Fix this and add a basic test for the `NewStatsPusher` to cover this.
While here, also rename `Close` to `Stop` to be consistent with the rest of benchmark code.
> [Benchmark] Fix crash on stats pusher exit

- integration/benchmark/contLoadGenerator.go
- integration/benchmark/worker_stats_tracker.go
This adds `GetTxExecuted()` API to the loader that @AndrewM-SDET can use in the CI TPS test.  This is a temporary solution until we rework the stats tacker.
> [Benchmark] Expose execution rate from the loader

- network/p2p/dht_test.go
- network/p2p/topic_validator_test.go
Verified with:
```
$ go test github.com/onflow/flow-go/network/p2p/... -failfast -count 50 --tags=relic -v
```
> [Networking] Quarantine flaky tests

- network/stub/buffer.go
- network/stub/hub.go
- network/stub/network.go
This diff fixes concurrency issues in stub networking:
* Protect Hub with it's own lock
* More robust defer unlock pattern in Buffer
* Protects `receiverNetwork` during send instead of sending one.
Ref: #3034
> [Networking] Fix network stub concurrency

- .github/workflows/ci.yml
- .github/workflows/flaky-test-monitor-integration.yml
- .github/workflows/flaky-test-monitor.yml
- Makefile
- crypto/Makefile
- integration/Makefile
Before we proceed with concurrent execution we first need to be sure that we do not have obvious data races in our codebase.
Depends on: #3092
> [Testing] Enable race detector by default

- integration/benchmark/cmd/ci/main.go
- integration/benchmark/cmd/manual/main.go
- integration/benchmark/follower.go
- integration/benchmark/follower_test.go
Following only sealed blocks is beneficial for the load test since it would verify the end-to-end pipeline and could find bottlenecks in verification nodes.
Sealed state is defined as:
> The verification nodes have verified the transaction (the block in which the transaction is) and the seal is included in the latest block
This also matches the flow-cli behavior: https://github.com/onflow/flow-cli/blob/7401e49afd2d7b89e15dc8f42c75fcb279f4e60f/pkg/flowkit/gateway/grpc.go#L148-L151
While here, also bump the account multiplier, since now we have more transactions inflight.
> [Benchmark] Follow sealed blocks

- cmd/execution_builder.go
- cmd/execution_config.go
1. Split ExecutionConfig into its own file
2. Refactored flag setup / validation to be methods of ExecutionConfig instead
of closures within ExecutionNodeBuilder.LoadFlags
3. Renamed `(e *ExecutionNodeBuilder)` to `(builder *ExecutionNodeBuilder)`
4. Created an ExecutionNode struct for the variables in LoadComponentsAndModules
5. As an example, converted the last 3 components' initialization closures into
execution node methods.  If you guys are happy with this, I'll convert the
remaining closures within LoadComponentsAndModules into methods
> Refactor execution node builder (part 1)

- fvm/contractFunctionInvocations.go
- fvm/contractFunctionInvoker.go
- fvm/contractFunctionInvoker_test.go
This enables us to reuse the invoker object for different contracts.
NOTE: I plan to rename ContractFunctionInvoker to SystemContracts,
convert the top level functions in contractFunctionInvocations.go into
SystemContracts' methods, and finally move all of that into the environment
subpackage in future PRs.
> Make ContractFunctionInvoker stateless

- cmd/bootstrap/run/execution_state_test.go
- cmd/bootstrap/transit/cmd/crypto_test.go
- ledger/complete/ledger_benchmark_test.go
- module/executiondatasync/tracker/storage_test.go
A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
> [Testing] Use `T.TempDir` to create temporary test directory

- cmd/execution_builder.go
- cmd/execution_config.go
- engine/execution/computation/computer/computer.go
- engine/execution/computation/manager.go
- engine/execution/computation/manager_benchmark_test.go
- engine/execution/computation/manager_test.go
- engine/testutil/mock/nodes.go
- engine/testutil/nodes.go
Instead of passing the virtual machine (and implicitly the cadence runtime)
into computation.Manager's New function, this creates the virtual machine and
runtime inside the New function itself.
This is prep work for moving the cadence runtime into ReusableCadenceRuntime.
> Create virtual machine / cadence runtime inside computation.Manager

- fvm/meter/meter.go
- fvm/meter/weighted_meter.go
- fvm/meter/weighted_meter_test.go
- fvm/state/state.go
- fvm/state/state_holder.go
- fvm/state/state_test.go
Nested transaction commits no longer fails due to merging meter.
The next metering call (if any) will notice that the limit is reach, so it's
generally safe to not check the limit during merging.
> Merge meter (and interaction) unconditionally

- fvm/environment/event_emitter.go
- fvm/environment/event_emitter_test.go
ref: https://github.com/onflow/flow-go/issues/2813
This is not a breaking change. Scripts can now call emit event, but nothing will happen instead of causing an error. This allows for scripts to call contract functions that would normally emit events.
> [FVM] Events in scripts do nothing instead of causing errors

- engine/access/access_test.go
- integration/tests/access/execution_state_sync_test.go
Backports: https://github.com/onflow/flow-go/pull/3171
The `AccessTest.TestGetSealedTransaction` test was flaky due to an incorrect snapshot state used for an initial lookup in the ingestion engine. Sometimes the snapshot was correct, but usually not. This updates the test to use the correct snapshot.
> [Test] Fix flaky access engine unittest v0.27

- fvm/env.go
- fvm/environment/account_key_reader.go
- fvm/handler/accountKey.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
1. split GetAccountKey out of handler/AccountKeyHandler into
environment/AccountKeyReader
2. combined env's tracer / meter logic into the new reader
3. also dedup commonEnv initialization code (and rm AccountInterface)
> Refactor GetAccountKey into AccountKeyReader

- fvm/env.go
- fvm/handler/contract.go
- fvm/handler/contract_test.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
1. added ContractUpdater interface & NoContractUpdater for script
2. renamed (h *ContractHandler) to (updater *contractUpdater)
3. moved contract update methods from env to updater
4. moved ContractUpdateKeyList and ContractUpdateList into programs/
5. simplified Commit a bit
Note: we can't move the contract updater into environment/ yet since there are still some circular dependencies.
> Refactor contract updater

- cmd/execution_builder.go
- cmd/util/ledger/reporters/account_reporter.go
- cmd/util/ledger/reporters/fungible_token_tracker_test.go
- engine/execution/computation/computer/computer.go
- engine/execution/computation/computer/computer_test.go
- engine/execution/computation/computer/mock/virtual_machine.go
- engine/execution/computation/manager.go
- engine/execution/computation/manager_benchmark_test.go
- engine/execution/computation/manager_test.go
- engine/execution/state/bootstrap/bootstrap.go
- engine/execution/testutil/fixtures.go
- engine/testutil/mock/nodes.go
- fvm/accounts_test.go
- fvm/context.go
- fvm/fvm.go
- fvm/fvm_blockcontext_test.go
- fvm/fvm_fuzz_test.go
- fvm/fvm_signature_test.go
- fvm/fvm_test.go
- fvm/handler/programs_test.go
- fvm/transaction_test.go
- module/chunks/chunkVerifier.go
- module/chunks/chunkVerifier_test.go
- utils/debug/remoteDebugger.go
Prep work for fully integrating programs.BlockPrograms
Note: Because we're in a circular dependency hell (flow-go depends on emulator, which in turn depends on an older version of flow-go), we cannot simply change the Run method's signature.  Instead, we need to create a new RunV2 method to deal with backwards compatibility.  (Full migration to RunV2 / cleanup will requires at least 3 sporks ...)
> Convert programs.Programs into an optional argument for fvm.Run(V2)

- fvm/env.go
- fvm/handler/programs.go
- fvm/programs/programs.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
This enables us to migrate to *programs.TransactionPrograms while the emulator is still stuck with using *programs.Programs.
> Switch ProgramsHandler to use TransactionPrograms interface

- fvm/env.go
- fvm/handler/accountKey.go
- fvm/handler/accountKey_test.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
1. Added AccountKeyUpdater interface, and NoAccountKeyUpdater for script
2. renamed (_ *AccountKeyHandler) to (updater *accountKeyUpdater)
3. convert original AccountKeyHandler methods to private
4. move TransactionEnv's account key methods to accountKeyUpdater
5. also some reformatting
> Refactor AccountKeyUpdater

- fvm/env.go
- fvm/environment/runtime.go
- fvm/environment/system_contracts.go
- fvm/environment/system_contracts_test.go
- fvm/scriptEnv.go
- fvm/transactionEnv.go
Only the runtime needs access to the full environment.  Nothing else in the environment package needs to directly access the full environment.
> Reduce environment circular dependency

- fvm/transactionInvoker.go
port of https://github.com/onflow/flow-go/pull/3228.
Ideally we wouldn't just log it, but this is an improvement.
> [FVM] Log err on TX failure

- fvm/environment/account_creator.go
- fvm/handler/accountKey.go
This is a bit more correct then using Disable/Enable-AllLimitEnforcements since RunWithAllLimitsDisabled resets the enforcement bool back to the original value, instead of forcing it to true.
> Switch adding key and creating account to RunWithAllLimitsDisabled

- engine/execution/testutil/fixtures.go
- fvm/fvm_test.go
- fvm/transaction_test.go
Assign correct/incrementing tx index to each test transaction.
Prep work for migrating to BlockPrograms
> Fix more fvm tests to use incrementing tx index.

- fvm/crypto/crypto_test.go
- fvm/errors/accounts.go
- fvm/errors/base.go
- fvm/errors/codes.go
- fvm/errors/contracts.go
- fvm/errors/errors.go
- fvm/errors/errors_test.go
- fvm/errors/execution.go
- fvm/errors/failures.go
- fvm/errors/txVerifier.go
- fvm/fvm_blockcontext_test.go
- fvm/fvm_test.go
- fvm/handler/accountKey_test.go
- fvm/meter/weighted_meter_test.go
- fvm/transactionVerifier_test.go
- fvm/transaction_test.go
Remove unused errors and introduce an `errorWrapper` that provides an Unwrap function to errors, which we were constantly forgetting.
> [FVM] Error Cleanup

- utils/test_matrix/test_matrix_test.go
Noticed in #3238
@gomisha, this is a good example of a case where CODEOWNERS-based annotation could help: in theory we would want to notify test owners of their flakes.
This is also an example of a test that should be auto-quarantined.
> [Testing] de-flake TestGenerateTestMatrix

- fvm/meter/meter.go
- fvm/meter/weighted_meter.go
- fvm/meter/weighted_meter_test.go
#3103 - we want to move existing storage metering logic in `state.go` into `Meter` interface.
As the first step, now adding storage read\write byte count metering interface to `Meter` interface. Next PR will replace related logic in `state.go` with the new Meter interface.
> [FVM] Adding storage metering to Meter

- fvm/state/state.go
- fvm/state/state_test.go
It replaces existing storage metering functions in state.go with the new interface from #3236
> [FVM] Replacing existing metering in state.go with new interface

- integration/benchmark/cmd/ci/main.go
- integration/benchmark/cmd/manual/main.go
- integration/benchmark/contLoadGenerator.go
- integration/benchmark/worker.go
- integration/benchmark/worker_stats_tracker.go
- integration/benchmark/worker_stats_tracker_test.go
- integration/localnet/Makefile
- module/metrics/loader.go
Added `SetTPS` API that can be used to adjust the load on the fly.  Switched `manual` loader to using this instead of re-creating benchmark client on every run.
[It's better to review this PR w/o whitespace](https://github.com/onflow/flow-go/pull/3246/files?diff=split&w=1).
> [Benchmark] Ability to dynamically adjust TPS

- fvm/context.go
- fvm/env.go
- fvm/environment/contract_updater.go
- fvm/environment/event_emitter.go
- fvm/environment/transaction_info.go
- fvm/transactionEnv.go
I want to move facadeEnvironment into environment/ as well.  To do this, we need to decouple facadeEnvironment from Context.  This is the first step.
Most parameters are logically be assoicated with a module; I've place those parameters next to the module whenever possible.  Some Parameters, such as Chain, are used by multiple modules; I'm keeping these in EnvironmentParams for now.
Note that I'm migrating the parameters a few modules at a time rather than wholesale to make the PRs more reviewable.
> Move Context fields into EnvironmentParams (Part 1)

- fvm/environment/event_emitter.go
- fvm/environment/event_emitter_test.go
- fvm/environment/meter.go
- fvm/environment/mock/environment.go
- fvm/environment/mock/meter.go
- fvm/fvm.go
- fvm/meter/meter.go
- fvm/meter/meter_test.go
- fvm/state/state.go
- fvm/state/state_holder.go
The existing event emit size metering logic in `fvm/environment/event_emitter.go` can also be moved into `Meter` interface.
Changes below are created in individual commits
- Adding new event metering interface in `fvm/meter/meter.go`
- Adding new event metering interface in `State`, `StateTransaction` and `fvm/environment/meter.go` 
we should use environment Meter interface in environment code to avoid potential dep issue with `meter/meter.go`
- Replacing existing event metering logic in event_emitter.go with the new interface
Test
> [FVM] Moving event emit size metering logic to Meter interface

- fvm/errors/accounts.go
- fvm/errors/codes.go
- fvm/errors/errors.go
- fvm/errors/failures.go
We can replace most (if not all) of our error / failure structs with CodedError and CodedFailure.
I've converted one error struct to CodedError, and one failure struct to CodeFailure.  I'll convert the rest if we're happy with this approach.
> Add CodedError / CodedFailure to the errors package

- engine/execution/computation/computer/uploader/retryable_uploader_wrapper.go
`wg.Done()` should be called by a `defer` in a goroutine. Thanks @peterargue for finding out this naive bug I made.
Test
Will port this PR to `v0.27` after merged.
> [Execution] Fixing improper use of WaitGroup in a goroutine for upload retry

- fvm/errors/errors_test.go
- module/chunks/chunkVerifier_test.go
so we can easily swap out implementations later
> fix error initialization in tests

- fvm/errors/base.go
- fvm/errors/codes.go
it's no longer used and is wrong (fvm internal error should be treated as failure)
> Deprecate/delete FVMInternalError

- fvm/environment/accounts.go
- fvm/environment/event_emitter.go
- fvm/errors/accounts.go
- fvm/errors/base.go
- fvm/errors/contracts.go
- fvm/errors/errors.go
- fvm/errors/execution.go
- fvm/errors/failures.go
- fvm/errors/todo_rm_emulator_hack.go
- fvm/errors/txVerifier.go
I'm going to splay the replacement across multiple PRs.  The changes are unreviewable on github if I try to replace them all in one go since that causes too many newline changes for diff-ing.
Note that I've change NewEncodingFailuref a bit.  Previously, the original encoding error was sometimes dropped from the returned error string.
Note: I've added a todo_rm_emulator_hack.go to this diff to deal with emulator circular dependency hell.  Looks like the error type classification in the emulator are incorrect even prior to my changes, so there's no point in trying to keep backwards compatibility.
> Replace error/failure structs with CodedError/CodedFailure (Part 1)

- fvm/environment/account_key_updater_test.go
- fvm/errors/accounts.go
- fvm/errors/base.go
- fvm/errors/execution.go
- fvm/errors/failures.go
- fvm/errors/todo_rm_emulator_hack.go
- fvm/errors/txVerifier.go
Note that I've left CadenceRuntimeError, FrozenAccountError and InvalidProposalSeqNumberError alone since these require special handling. (I'll deal with these in a followup PR)
> Replace error/failure structs with CodedError/CodedFailure (Part 2)

- utils/io/file.go
- utils/io/file_unix.go
- utils/io/file_windows.go
`syscall.Stat_t` is linux-only and would fail on Windows and Plan9.  Separate codepaths into unix/windows.
Verified with:
```
GOOS=windows GOARCH=amd64 go build ./utils/io/...
```
PS. @gomisha given that `flow-cli` [depends on windows builds](https://github.com/onflow/flow-cli/actions/runs/3136555718/jobs/5093616496#step:4:227) maybe we can add a windows build on CI?
> fix Windows build

- cmd/execution_builder.go
`collections` should be init after a valid `transactions` is created.
> [FVM] Properly ordering collection vs transactions order

- engine/access/rest/handler.go
- fvm/errors/accounts.go
- fvm/errors/base.go
- fvm/errors/contracts.go
- fvm/errors/errors.go
- fvm/errors/execution.go
- fvm/errors/failures.go
- fvm/errors/todo_rm_emulator_hack.go
- fvm/errors/txVerifier.go
- fvm/fvm_blockcontext_test.go
Error is renamed to CodedError in order to support anonymous field composition. (`type Error interface` conflicts with `Error() string`)
Also added Find(err, code) and converted remaining errors to CodedError
> Combined Error and CodedError interface.

- fvm/errors/errors.go
- fvm/errors/errors_test.go
- fvm/errors/failures.go
We no longer need the distinction since we can check the code recursively
> Combine Failure into CodedError

- cmd/scaffold.go
Currently, it is very hard to use logs for any performance-sensitive troubleshooting because of low logs' time resolution.  Bump it by 9 orders of magnitude:
```
RFC3339     = "2006-01-02T15:04:05Z07:00"
RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
```
> Increase logger's time resolution from seconds to nanoseconds

- cmd/execution_builder.go
- engine/execution/computation/computer/uploader/retryable_uploader_wrapper.go
- engine/execution/computation/computer/uploader/retryable_uploader_wrapper_test.go
- engine/execution/computation/computer/uploader/uploader.go
Some minor tunings to block upload retry logic:
- adding more logging to upload behavior for easier tracking for DPS debugging purposes
- fixing the improper badger obj init order (thanks @peterargue)
> [Execution] Adding more logging and a fix to block upload retry

- cmd/util/cmd/checkpoint-list-tries/cmd.go
- ledger/complete/wal/checkpointer.go
- ledger/complete/wal/checkpointer_test.go
- ledger/complete/wal/checkpointer_versioning_test.go
- utils/unittest/unittest.go
Reverts onflow/flow-go#3310
Reverting this change, because:
1. We could [split the directory and filename from a file path](https://github.com/onflow/flow-go/pull/3336/files#diff-2ff6507ee260a1e37156b4cae4cc259e7688bbd0007993b20fa193824073105aR31)
2. [DPS depends on a single full path of the checkpoint file](https://github.com/onflow/flow-dps/blob/d119e8c713e9f058dc82d57048a186e7533b529f/service/loader/checkpoint.go#L47), they can keep passing a single path
> [Checpoint V6] Revert "Refactor load checkpoint"

- integration/benchmark/cmd/ci/main.go
- integration/localnet/Makefile
This diff splits CI flags into initial and max TPS to support future TPS auto-tuning.
While here, also move away from text parsing and use the `flag.*` interfaces instead.
> [Benchmark] Split TPS flags into initial and max

- ledger/complete/mtrie/flattener/iterator.go
- ledger/complete/mtrie/flattener/iterator_test.go
- ledger/complete/wal/checkpointer.go
- ledger/complete/wal/checkpointer_serialization_test.go
Backport PR #3050 from master to branch v0.27.
> Backport PR 3050 to v0.27 to reduce memory and speedup checkpoint by splitting trie into subtries

- fvm/errors/errors.go
- fvm/errors/errors_test.go
- fvm/transactionInvoker.go
1. early exit transaction on unrecoverable failure.
2. merge non-failure errors using multierror, rather than dropping one of the error, to expose more information (When combined with #3332, this enables access to the original root cause error code).
3. only flush pending updates when there's no error.
4. on non-error path, only deduct fee when there's no transaction error
> Improve transaction invoker error handling

- fvm/environment/account_creator.go
- fvm/environment/account_freezer.go
- fvm/environment/account_info.go
- fvm/environment/account_key_updater.go
- fvm/environment/contract_updater.go
- fvm/environment/facade_env.go
- fvm/environment/parse_restricted_checker.go
- fvm/environment/transaction_info.go
Added utility generic functions for checking parse restriction.
Sorry for the poor `parseRestrict<x>Arg<y>Ret` naming, but I can't think of anything better.
The generic functions are of the form
`parseRestrict<x>Arg<y>Ret(txnState, opCode, callback, arg1, ..., argX)`
where the callback expects `<x>` number of arguments, and `<y>` number of return values (not counting error). If the callback expects no argument, `<x>Arg` is omitted, and similarly for return value.
> Ensure cadence don't access unexpected operations while parsing (part 2)

- cmd/execution_builder.go
- cmd/util/ledger/reporters/account_reporter.go
- cmd/util/ledger/reporters/fungible_token_tracker_test.go
- engine/execution/computation/computer/computer.go
- engine/execution/computation/computer/computer_test.go
- engine/execution/computation/computer/mock/virtual_machine.go
- engine/execution/computation/manager.go
- engine/execution/computation/manager_benchmark_test.go
- engine/execution/computation/manager_test.go
- engine/execution/state/bootstrap/bootstrap.go
- engine/execution/testutil/fixtures.go
- fvm/accounts_test.go
- fvm/environment/programs_test.go
- fvm/fvm.go
- fvm/fvm_blockcontext_test.go
- fvm/fvm_fuzz_test.go
- fvm/fvm_signature_test.go
- fvm/fvm_test.go
- fvm/scriptEnv.go
- fvm/transaction_test.go
- integration/go.mod
- integration/go.sum
- module/chunks/chunkVerifier.go
- module/chunks/chunkVerifier_test.go
- utils/debug/remoteDebugger.go
Removes the old VM functions that were only kept for emulator compatibility.
relates to https://github.com/onflow/flow-emulator/pull/211
> [FVM] Remove old FVM functions

- integration/benchmark/cmd/ci/main.go
- integration/benchmark/cmd/ci/main_test.go
- integration/benchmark/contLoadGenerator.go
- integration/benchmark/worker_stats_tracker.go
- integration/localnet/Makefile
This PR adds an ability of finding the maximum TPS that the network can handle to the `ci` benchmark
It is currently using a simple AIMD (additive increase/multiplicative decrease) algorithm.
The algorithm starts with `-initial-tps` as a target.  Each time it is able to reach the target TPS, it increases the target by `additiveIncrease`. Each time it fails to reach the target TPS, it decreases the target by `multiplicativeDecrease` factor.  
There are two optimizations on top:
* To avoid oscillation and speedup conversion we skip the adjustment stage if TPS grew compared to the last round.  
* We do not shrink target TPS if it would bring them below the current TPS.
(We disable both optimizations if inflight transactions are above `maxInflight`)
Target TPS is always bounded by …
> [Benchmark] Add ability to auto-detect maximum TPS

- fvm/environment/event_emitter.go
- fvm/environment/meter.go
- fvm/environment/mock/environment.go
- fvm/environment/mock/meter.go
- fvm/fvm_fuzz_test.go
- fvm/fvm_test.go
- fvm/meter/meter.go
- fvm/meter/meter_test.go
- fvm/state/state.go
- fvm/state/transaction_state.go
In PR #3268 the event counter was also moved into meter interface. It caused a problem in event index ([slack thread](https://dapperlabs.slack.com/archives/C01ANSMH5FF/p1665462723443849)) because meter itself has `enforceLimit` condition which event index should not be applied. Event index should increase unconditionally.
Fixed by keeping the event counter inside EventEmitter as usual.
Test
> [FVM] Keeping event counter inside EventEmitter

- ledger/complete/checkpoint_benchmark_test.go
Added:
- `BenchmarkStoreCheckpointV5`
- `BenchmarkStoreCheckpointV6`
- `BenchmarkStoreCheckpointV6Concurrent`
- `BenchmarkLoadCheckpoint`
These benchmarks require `checkpointFile` flag to specify input checkpoint file name (any version).
> Rewrite benchmarks for storing/loading checkpoint

- integration/go.mod
- integration/go.sum
https://github.com/onflow/flow-emulator/releases/tag/v0.38.1
**Test**
> [Integration] Upgrading flow-emulator to v0.38.1

- network/p2p/test/sporking_test.go
This test is passing in Flaky Test Monitor but is consistently failing in CI for many PRs and needs further investigation.
> [Testing] quarantine test - TestCrosstalkPreventionOnNetworkKeyChange in network/p2p/test/sporking_test.go

- fvm/transactionSequenceNum.go
nested transaction commit and restart can no longer fail due to metering (#3144)
> Clean up seq num checker's nested transaction commit/restart

- network/p2p/internal/p2pfixtures/fixtures.go
- network/p2p/p2pbuilder/libp2pNodeBuilder.go
- network/p2p/scoring/app_score_test.go
- network/p2p/scoring/score_option.go
- network/p2p/scoring/subscription_validator.go
- network/p2p/scoring/subscription_validator_test.go
- network/p2p/scoring/utils.go
- network/p2p/scoring/utils_test.go
* refactors go libp2p core dependency
* lint fix
* lint fix
* lint
* re-generates mocks
* implements subscription provider
* exports allowed subscription method
* fix
* implements subscription validator
* renames a file
* refactors packaging
* lint fix
* updates subscription validator
* implements score options
* removes set pubsub sytem
* adds enabling gossipsub peer scoring
* Adds enabling peer scoring for gossipsub to the builder
* wires up identity provider
* adds subscription provider interface
* generates p2p mock
* adds fixtures
* adds topic provider mock
* refactors subscription provider with topic provider
* adds subscription provider
* repackages translator
* refactors translator and connector
* lint fix
* fixes import cycle
* lint fix
* fixes compile errors
* fixes compile …
> [Routing Attacks] Push Access Nodes To Edge (#3379)

- engine/execution/computation/computer/computer_test.go
- engine/execution/testutil/fixtures_event.go
- fvm/fvm_fuzz_test.go
- fvm/fvm_test.go
- utils/unittest/fvm.go
Adding new checking in UT cases to make sure numbers in event index sequence are unique and increasing. As a follow-up to https://github.com/onflow/flow-go/pull/3371#pullrequestreview-1139592903
changes to FVM and execution computer UT are split into separate commits.
> Adding Event Index Sequence checking to UTs

- fvm/transaction.go
- fvm/transactionInvoker.go
- fvm/transactionSequenceNum.go
- fvm/transactionVerifier.go
- Adding `IsSampled()` to TransactionProcedure. Taking the message from [computer.go](https://github.com/onflow/flow-go/blob/master/engine/execution/computation/computer/computer.go#L411-L413) to `TransactionProcedure` to make code slightly easier to read.
- Isolating boilerplace code for creating tracer span for TransactionProcedure into a function.
**Test**
> [FVM] Refactoring TransactionProcedure trace span creation

- module/metrics.go
- module/metrics/execution.go
- module/metrics/labels.go
- module/metrics/noop.go
- module/mock/execution_metrics.go
As the first step for #3312 - now we add metrics interface for the new unweighted computation effort of each block.
> [Metrics] Adding metrics interface for block computation effort vector

- cmd/execution_builder.go
- ledger/complete/wal/checkpoint_v5_test.go
- ledger/complete/wal/checkpoint_v6_reader.go
- ledger/complete/wal/checkpoint_v6_test.go
- ledger/complete/wal/checkpoint_v6_writer.go
- ledger/complete/wal/checkpointer.go
During spork, the EN has to copy the root checkpoint file from bootstrap folder. This PR fixes an issue that instead of copying only one checkpoint file, it also copy other part files to support checkpoint V6
> Fix copy checkpoint on bootstrap

- cmd/access/node_builder/access_node_builder.go
- cmd/execution_builder.go
- cmd/execution_config.go
- integration/localnet/bootstrap.go
- integration/localnet/conf/grafana-exec-sync.json
- integration/localnet/docker-compose.metrics.yml
- network/p2p/blob/blob_service.go
- network/p2p/blob/blob_service_test.go
ENs and ANs use bitswap to share ExecutionData within the staked network. To support permissionless nodes, all messages must be authorized to the specific node/roles that are allowed to participate.
This PR adds an authorization check to all ExecutionData requests over bitswap. It also adds configuration to Execution nodes that allows them to specify an allow list of nodes that can request ExecutionData directly. This enable additional options for handling malicious peers, as well as scaling the execution sync protocol.
> [BFT] Authorize execution data requests over bitswap

- cmd/access/node_builder/access_node_builder.go
- cmd/execution_builder.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- network/p2p/blob/blob_service.go
Temporarily use [`onflow/go-bitswap` fork](https://github.com/onflow/go-bitswap) of `ipfs/go-bitswap` to pull in an unmerged fix.
> Update depenencies to use onflow/go-bitswap fork

- cmd/execution_builder.go
Execution nodes only need a single blob service
> [Execution] remove duplicate blobservice on execution nodes

- fvm/errors/errors_collector.go
- fvm/errors/errors_collector_test.go
- fvm/state/transaction_state.go
- fvm/transactionInvoker.go
1. move errors collection out of the invoker + added test
2. don't commit transaction using defer.  The original defer commit function is also split into validateCommit and commit.  This is prep work for converting the Process() into continuation passing style executor.
3. move error execution path into a method
> Refactor transaction invoker.

- fvm/environment/programs.go
- fvm/state/state.go
- fvm/state/transaction_state.go
- fvm/state/transaction_state_test.go
- fvm/transactionInvoker.go
- fvm/transactionSequenceNum.go
These will be used for implementing continuation passing style executors (The nested transaction will pause after preprocessing, and resume on actual execution).
Also made a bunch of improvements to support caching result (These should be useful for implementing meter weight prefetching):
1. added guard to prevent modification on committed state
2. Commit returns the committed state
3. renamed AttachAndCommitParseRestricted to AttachAndCommit
> Add Pause/Resume functionality to TransactionState

- cmd/execution_builder.go
This is the backport of #3406.
NB! Needed to rewrite it a bit due to changes file layout between v27 and v28
> [Execution] Backport collection retries to v0.27

- network/p2p/test/sporking_test.go
Test no longer failing
Screenshot taken on Oct 24
> Unskip Test TestCrosstalkPreventionOnNetworkKeyChange

- cmd/execution_builder.go
- cmd/execution_config.go
Following diffs are reverted (#3406):
Revert "[Execution] Add comments to the default collection retry parameters"
This reverts commit 1fff25896f9f9221c06d483e66ad672e781c4e86.
Revert "[Execution] Improve variable naming"
This reverts commit eb07fcef5bda45323d19814546209a5623a7410a.
Revert "[Execution] Aggressive collection retries"
This reverts commit 6d9ad5e051bcec65de9e69a829615a8c196368c2.
Ref: https://github.com/onflow/flow-go/issues/3455
> Revert "[Execution] Aggressive collection retries"

- network/p2p/test/sporking_test.go
This test was recently unquarantined but it's now blocking many PRs again. Even though it was passing in quarantine and locally, it still needs further investigation / work to diagnose why it fails in CI.
`network/p2p/test/sporking_test.go`
> [Testing] quarantine flaky test `TestCrosstalkPreventionOnNetworkKeyChange` in `network/p2p/test/sporking_test.go`

- fvm/bootstrap.go
prerequisite for: onflow/flow-go#2767
It doesn't make sense to use the programs cache during bootstrapping.
Avery transaction is a new deploy, and the speed isn't needed.
> [FVM] Use empty programs during bootstrapping

- network/internal/messageutils/utils.go
- network/p2p/network.go
- network/p2p/test/sporking_test.go
- network/p2p/unicast/ratelimit/bandwidth_rate_limiter_test.go
- network/test/middleware_test.go
- network/test/unicast_authorization_test.go
These fields are deprecated, and will be removed in a future PR. For now, don't include them when sending a new message.
> [Network] Stop sending unused message.Message fields

- fvm/transactionInvoker.go
Added an executor object and converted variables that span the entire workflow (preprocessing, actual execution) into fields.  Variables that do not span the entire workflow (e.g., modifiedSets) are left unmodified.
Note that I've also made a few no-op stylistic changes.
> Prep work for converting transaction invoker into continuation passing style executor

- cmd/util/ledger/migrations/storage_used_update_migration.go
- cmd/util/ledger/migrations/storage_used_update_migration_test.go
- engine/execution/computation/computer/computer_test.go
- fvm/accounts_test.go
- fvm/environment/account_creator.go
- fvm/environment/account_creator_test.go
- fvm/environment/accounts.go
- fvm/environment/uuids.go
- fvm/environment/value_store.go
- fvm/errors/codes.go
- fvm/errors/execution.go
- fvm/fvm_test.go
- fvm/state/state.go
- fvm/state/state_test.go
- fvm/state/transaction_state.go
Cadence shouldn't have access to fvm internal state via the value store.  The cadence runtime api as defined today allows arbitrary/unlimited access.
> Prevent cadence from directly accessing fvm internal state

- fvm/programs/block_derived_data.go
- fvm/programs/block_derived_data_invalidator.go
To facilitate parallel\speculative transaction execution, all derived data(programs, meter settings etc.) should be OCC-enabled. This PR separates out the OCC logic in existing BlockPrograms into its own individual generic type, in which:
- `block_derived_data.go`. 
Majority of code\comments are directly taken from block_programs.go, except that `nonAddressSet` is removed from the generic version, which is program specific.
- `block_derived_data_invalidator.go`
Majority of the code\comments are directly from invalidators.go, except some minor renaming, except that ContractUpdate\Key and ModifiedSetsInvalidator are not included. It will be included in new BlockPrograms specific implementations.
NOTE: test will be done in the next PR together with BlockProgram refactoring using this generic …
> [FVM] Adding generic OCC implementation

- fvm/context.go
- fvm/script.go
This also removed the concept of ScriptProcessor since we never override the script execution behavior
> Convert ScriptProcedure.Run into executor object.

- fvm/environment/programs_test.go
- fvm/programs/block_derived_data.go
- fvm/programs/block_derived_data_invalidator.go
- fvm/programs/block_programs.go
- fvm/programs/block_programs_test.go
- fvm/programs/chain_programs_test.go
- fvm/programs/invalidator.go
- fvm/programs/invalidator_test.go
- fvm/transaction_test.go
As the follow-up change to #3484 , now BlockPrograms\TransactionPrograms\Invalidators are all using generic OCC implementation. 
Note that I'm keeping the original interfaces instead of directly exposing `BlockDerivedData` interfaces.
**Test**
> [FVM] Making BlockPrograms internals use generic OCC code

- cmd/execution_builder.go
- engine/execution/computation/manager.go
Currently, the uploader is enabled by default on all nodes, and only skipped because there are no configure uploaders. This causes nodes that don't have uploads enabled to check all blocks in their dbs for blocks to upload
> [Execution] disable block uploads by default

- engine/common/provider/engine.go
- engine/common/requester/engine.go
This PR makes 2 changes:
* In the provider engine, remove the lock protecting `onEntityRequest`. This method doesn't have any shared state and shouldn't need locking
* In the requester engine, unlock before sending a request over unicast to avoid blocking the network layer if there are slow unicast requests.
> [Execution] Improve locking in requester and provider engines

- engine/execution/computation/manager_test.go
this test was broken by https://github.com/onflow/flow-go/pull/3504
> Fix broken uploader unittest

- cmd/execution_builder.go
Reverts onflow/flow-go#3509 which reverted onflow/flow-go#3497. 
The original change:
> Blobservice is required by both the gcp uploader and the provider component
> Break blobservice out to own component in en builder - take 2

- engine/execution/computation/computer/computer_test.go
- fvm/runtime/reusable_cadence_runtime.go
- fvm/transactionInvoker.go
Note: This change uses more memory because the executor now hold on to the cadence runtime used for executing the body until the very end (fees deduction, etc will end up using a second cadence runtime).  This is ok in steady state because the runtimes are still recycled.
> Switch transaction invoker to directly use cadence txn executor

- network/p2p/scoring/score_option.go
Here is an example of spam in the logs:
```
Nov 03 20:51:06 execution-001 docker[44381]: {"level":"debug","node_role":"execution","node_id":"9686399a8a5418a12e762cfaeff2ea348c2137f554560917760e0d47acf2cda4","time":"2022-11-03T20:51:06.192478776Z","message":"rewarding well-behaved non-access node peer with maximum reward value"}
Nov 03 20:51:06 execution-001 docker[44381]: {"level":"debug","node_role":"execution","node_id":"9686399a8a5418a12e762cfaeff2ea348c2137f554560917760e0d47acf2cda4","time":"2022-11-03T20:51:06.192814542Z","message":"rewarding well-behaved non-access node peer with maximum reward value"}
Nov 03 20:51:06 execution-001 docker[44381]: {"level":"debug","node_role":"execution","node_id":"9686399a8a5418a12e762cfaeff2ea348c2137f554560917760e0d47acf2cda4","time":"2022-11-03T20 …
```
> [Networking] Reduce debug-level log spam

- cmd/util/ledger/reporters/fungible_token_tracker_test.go
- engine/execution/computation/computer/computer.go
- engine/execution/computation/computer/computer_test.go
- engine/execution/testutil/fixtures.go
- fvm/accounts_test.go
- fvm/context.go
- fvm/environment/programs_test.go
- fvm/fvm_blockcontext_test.go
- fvm/fvm_test.go
- fvm/transaction.go
- fvm/transactionInvoker.go
- fvm/transaction_test.go
- utils/debug/remoteDebugger.go
I'm going to move all of procedure's Run logic into transaction invoker as follow up.  The TransactionProcessor concept will be replace by a single TransactionExecutor CPS object.  TransactionVerifer and TransactionSeqNumChecker will become like StorageLimitChecker.
> Flatten transaction processor loop.

- engine/common/synchronization/request_heap.go
- engine/common/synchronization/request_heap_test.go
The heap for pending requests has a bug, where the flushes the entire content upon the first ejection. Its my own bug 🤦 . Thanks Peter for noticing.
> fix heap draining bug in synchronization engine

- admin/command_runner.go
- admin/command_runner_test.go
This diff adds selected `/debug/pprof/` profiling endpoints along with `/debug/pprof/trace` to the admin port.
This adds an ability to use standard go tooling for performance troubleshooting e.g.:
```
$ go tool pprof http://localhost:9002/debug/pprof/goroutine
```
Or using standard system tooling, e.g.:
```
$ curl -o trace.out localhost:9002/debug/pprof/trace
```
PS. There is also an ability to manually trigger AutoProfiler: #3520
> [Profiler] Add selected /debug/pprof/ endpoints to admin interface

- admin/README.md
- cmd/scaffold.go
- module/profiler/profiler.go
- module/profiler/profiler_internal_test.go
- module/profiler/profiler_test.go
This PR adds an ability to manually trigger auto-profiler for ad-hoc troubleshooting, e.g.:
```
$ curl localhost:9002/admin/run_command -H 'Content-Type: application/json' \
-d '{"commandName": "set-config", "data": {"profiler-trigger": "1m"}}'
```
> [Profile] Add ability to manually trigger profiler

- admin/README.md
- admin/commands/common/set_golog_level.go
- cmd/scaffold.go
- go.mod
- network/p2p/dht/dht_test.go
It's better to not couple golog and zerolog since they have different log levels and output formats.
> [Networking] Add ability to change libp2p's logging level on the fly

- engine/execution/computation/computer/computer_test.go
- engine/execution/state/delta/delta.go
- engine/execution/state/delta/view.go
- engine/execution/state/delta/view_test.go
- model/flow/ledger.go
- module/chunks/chunkVerifier.go
This PR:
* converts `map[string]flow.RegisterID` to `map[flow.RegisterID]struct{}` to represent sets.
* switches Delta from `map[string]flow.RegisterEntry` to `map[flow.RegisterID]flow.RegisterValue` to save a bit of space.
Currently these are responsible for ~15% of memory allocations:
```
name                             old time/op    new time/op    delta
ComputeBlock/16/cols/128/txes-8     1.83s ± 3%     1.69s ± 2%   -7.59%  (p=0.000 n=10+10)
name                             old alloc/op   new alloc/op   delta
ComputeBlock/16/cols/128/txes-8    1.34GB ± 1%    1.21GB ± 2%   -9.38%  (p=0.000 n=9+10)
name                             old allocs/op  new allocs/op  delta
ComputeBlock/16/cols/128/txes-8     19.8M ± 0%     17.1M ± 0%  -13.48%  (p=0.000 n=8+8)
```
> [Execution] Do not depend on string conversion in register set tracking

- engine/execution/ingestion/engine.go
> [Execution] Minor ingestion logging cleanup

- engine/common/requester/engine.go
- engine/execution/ingestion/engine.go
- storage/badger/commits.go
The `matchOrRequestCollection` hits a lock in requester, which might cause it to hold the lock in requester for too long. This PR moves the side effect (requesting collections) out of the function that holds the lock in order to reduce concurrent tension.
> Refactor fetch collections

- engine/common/requester/engine.go
- engine/common/requester/engine_test.go
Map iteration order is not random, but instead undefined ([as per go spec](https://go.dev/ref/spec#RangeClause)):
> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.
This [does not mean random and especially not uniformly random](https://go.dev/play/p/wfSzSXfVOJa). Therefore pre-randomize the order.
> [Execution] Randomize collection fetch order

- fvm/environment/mock/transaction_programs.go
- fvm/environment/programs.go
- fvm/programs/block_programs.go
- fvm/programs/block_programs_test.go
- fvm/programs/programs.go
Since we're generalizing BlockPrograms into a schema-ed database for storing all sorts of derived data, it no longer make sense to keep track of non address programs inside of the database.
gh: #3102
> Move non address programs tracking to environment.

- engine/execution/state/delta/delta.go
- fvm/state/state.go
- model/flow/identity.go
Generic version is faster than the interface-based one.  While here, also:
* Simplify `RegisterUpdates` -- no need to roundtrip data through `RegisterEntries` just for sorting.
(Followup from #3529)
* Simplify `Union` -- a roundtrip through map is negligible compared to O(n*log(n)) sorting.
* Simplify the rest of `IdentityList` methods to remove the custom binary searches and equality functions.
While here, also mark a race in `DeterministicSample`. 
This also replaces custom implementation of byte comparisons with a standard `Bytes.Compare()` that supports both AVX and [AVX2 on x86_64](https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/internal/bytealg/compare_amd64.s;l=194), hence using `VPCMPEQB` to do 64-byte compares.
Side note about `IdentityList`: looking at the code, it …
> [Execution] Use generic slice algorithms instead of interfaces

- fvm/programs/block_derived_data.go
- fvm/programs/block_derived_data_invalidator.go
- fvm/programs/block_programs.go
- fvm/programs/block_programs_test.go
- fvm/programs/chain_programs_test.go
- fvm/programs/invalidator.go
- fvm/programs/invalidator_test.go
1. Remove ProgramEntry struct.  This was used by the original programs cache implementation and is no longer needed.  The cached Value and State are now directly define in invalidatableEntry.
2. minor changes to the TransactionDerivedData Get api
3. s/item *TransactionDerivedData/txn *TransactionDerivedData/g
gh: #3102
> Refactor generic derived data implementation.

- fvm/bootstrap.go
- fvm/fvm.go
- fvm/script.go
Similar to script procedure, bootstrap procedure only needs to expose the NewExecutor method to conform to the Procedure interface.
gh: #3547
> Convert bootstrap procedure into executor

- fvm/bootstrap.go
- fvm/context.go
- fvm/transaction.go
- fvm/transactionInvoker.go
- fvm/transactionInvoker_test.go
- fvm/transactionSequenceNum.go
- fvm/transactionSequenceNum_test.go
- fvm/transactionStorageLimiter.go
- fvm/transactionStorageLimiter_test.go
- fvm/transactionVerifier.go
- fvm/transactionVerifier_test.go
- fvm/transaction_test.go
1. moved TransactionProcedure.Run into transaction executor
2. made txn verifier stateless to improve composability.
3. replace verifier and seq num checker's Process methods with more descriptive name since they no longer need to implement the Process interface.
4. renamed CheckLimits to CheckStorageLimits
5. renamed invocationExecutor to transactionExecutor
gh: #3547
> Move transaction procedure Run logic into transaction executor.

- integration/benchmark/contLoadGenerator.go
- integration/benchmark/tx_result.go
No need to wait for account creation transactions being sealed.
> [Benchmark] Faster account creation

- integration/benchmark/contLoadGenerator.go
This is to accidentally not run out of tokens during tests even at high TPS.
> [Benchmark] Use smaller transfer size for benchmark transactions

- integration/benchmark/contLoadGenerator.go
- module/metrics/loader.go
Sometimes at high TPS we never receive a notification from a transaction being executed/sealed.  This leads to feedback loop stalling since it waits for ongoing transactions to finish.
While we are figuring out where and why this happens let's unblock the benchmarking by proceeding and logging such events.  Later we can cross-correlate logs for these transaction IDs.
> [Benchmark] Notify on slow transactions

- integration/benchmark/contLoadGenerator.go
This removes `availableAccountsLo` that is currently unused.
> [Benchmark] Remove unused code

- cmd/node_builder.go
- cmd/scaffold.go
- integration/benchmark/cmd/ci/main.go
- integration/benchmark/cmd/manual/main.go
- module/metrics/example/setup.go
- module/metrics/server.go
- module/profiler/profiler.go
- module/profiler/profiler_internal_test.go
- module/profiler/profiler_test.go
This PR adds following admin commands:
* profiler-set-mem-profile-rate
* profiler-set-block-profile-rate
* profiler-set-mutex-profile-fraction (really want to rename that to "rate", but kept for consistency w/ golang naming)
While here, also remove the `-profiler-mem-profile-rate` command line argument and `/debug/pprof` interface from the metrics port.
Ref: https://github.com/onflow/flow-go/issues/3455
> [Profiler] Add admin commands to control profiling rates

- fvm/meter/meter.go
- fvm/meter/meter_test.go
- fvm/state/state.go
- fvm/state/transaction_state.go
- fvm/state/transaction_state_test.go
This allows nested transaction to use a different set of meter parameters that are not inherited from the parent transaction, and allows us to meter different parts of the transaction using different parameters. (See discussion in #2922 for additional context)
gh: #3102
> Enable nested transaction to use a different set of meter parameters

- integration/benchmark/cmd/ci/main.go
- integration/benchmark/follower.go
This speeds up the convergence to maximum sustainable TPS (`additiveIncrease` increase) and reduces variance of the results (`multiplicativeDecrease` increase.)
Also reduce timeout on `pollCollections` to 1s: a value that is closer to our block generation time.
> [Benchmark] Speedup benchmark convergence

- engine/collection/compliance/core.go
- state/cluster/badger/mutator.go
- state/cluster/badger/mutator_test.go
- state/errors.go
- state/protocol/badger/mutator.go
- state/protocol/errors.go
* Adds `UnverifiableExtensionError` to differentiate extensions which aren't certainly invalid, and cannot be processed (for cluster consensus `ReferenceBlockID`
* Updates some error message and documentation wording
> Small improvements to error types and messages in block extension logic

- integration/benchmark/cmd/ci/main.go
- integration/benchmark/contLoadGenerator.go
- integration/benchmark/worker_stats_tracker.go
- integration/benchmark/worker_stats_tracker_test.go
This diff mostly cleans up codebase by removing the useless facades from load generator and stats tracker.  As a side effect makes stat fetches atomic.
> [Benchmark] Remove facades from the benchmark library

- cmd/util/ledger/reporters/account_reporter.go
- fvm/context.go
- fvm/executionParameters.go
- fvm/fvm.go
- fvm/fvm_test.go
- fvm/state/state.go
- fvm/state/state_test.go
- fvm/transactionInvoker_test.go
Storage interaction limit is part of meter parameters and should be set along the other meter parameters.
gh: #3102
> Fix storage interaction limit setup

- engine/collection/compliance/core.go
Add missing handling for error type added in https://github.com/onflow/flow-go/pull/3577
> Handle unverifiable input error in cluster compliance core

- fvm/executionParameters.go
- fvm/programs/block_derived_data.go
- fvm/programs/block_derived_data_test.go
- fvm/programs/block_programs.go
- fvm/programs/invalidator.go
This adds a second (meter param overrides) table to the derived block data database.  The database is committed via Validate/Commit 2PC (For now, Validate is not called during actual execution since there are no conflicts in sequential execution)
Note that this PR triggers meter params invalidation when contracts are updated. This is incorrect, but it's no worst than before since updating meter params would also break programs invalidation.  I'll add correct meter param invalidation in a followup PR.
gh: #3102
> Meter param overrides cache skeleton.

- engine/collection/compliance/core.go
- engine/common/follower/engine.go
- engine/common/provider/engine.go
- engine/consensus/compliance/core.go
- network/p2p/network.go
- network/validator/pubsub/topic_validator.go
Adjust a few log events and settings based on results from canary testing BFT baseline protections
> [BFT] Tune logging and settings based on canary testing

- fvm/executionParameters.go
- fvm/fvm.go
- fvm/script.go
- fvm/transactionInvoker.go
The transaction (/script) procedure originally uses two separate transaction state to process a single request.  This merges the two transaction states into one, and only override the meter params for body execution.  The rest of the transaction (i.e., auth check, seq num check, meter override parsing) uses basic/non-overridden meter setting.
gh: #3547 #3102
> Only override meter parameters for transaction/script body execution

- integration/tests/epochs/epoch_join_and_leave_ln_test.go
- integration/tests/epochs/epoch_static_transition_test.go
- module/epochs.go
- module/epochs/qc_voter.go
- module/epochs/qc_voter_test.go
This PR updates and re-enables the `TestEpochStaticTransition` and `TestEpochJoinAndLeaveLN` integration tests.
* The static test was already passing and required no changes
* The LN test was failing due to an unhandled error when a node submits a vote in the epoch before it leaves the network
* This is fixed by returning the appropriate error type in this case
* Also updates the relevant unit tests to check for the error type
* Created an issue for another scenario which arises in this test case, but doesn't impact the test result https://github.com/dapperlabs/flow-go/issues/6435
> Update Epoch Collection Node Join/Leave Integration Test

- cmd/access/main.go
- cmd/access/node_builder/access_node_builder.go
The access node builder options were leftover from when the consensus follower library instantiated an AN. That has since been refactored, so this can now be simplified. Adjust the setup to align with the execution and verification nodes.
> [Access] Remove unused builder options

- cmd/node_builder.go
- cmd/scaffold.go
- module/util/util.go
This is a revision of https://github.com/onflow/flow-go/pull/3503 which updated `scaffold.go` to start the profiler as one of the first components. Due to changes needed for the admin command, this PR changes the implementation to use `DependableComponent` so the profiler will start asynchronously.
Before this PR, the profiler was started as a `Component` that was added after all other node specific components. This meant that the profiler would delay startup until after all other components were loaded. On nodes that perform a lot of startup logic like execution nodes, the profiler would not be able to capture any of that data.
> [Profiler] Start profiler asynchronously

- engine/execution/computation/computer/computer.go
- engine/execution/computation/computer/result_collector.go
Refactor all execution result collection logic into ResultCollector.  In particular, BlockCommitter and EventHasher are foled into the collector.
Note that BlockCommiter's Commit and EventHasher's Hash are now part of CommitCollection and called inside executeCollection instead of executeBlock. The order of operation got reordered a bit to improve pipeline efficiency.
Also note that the system chunk error logging got moved into executeTransaction as is logged on a per transaction level.  This is a no-op in reality since the system chunk only has a singlge transaction.
gh: #3547
> Refactor computer result collection

- consensus/hotstuff/voteaggregator/vote_aggregator.go
- engine/access/ingestion/engine.go
- engine/collection/compliance/engine.go
- engine/collection/ingest/engine.go
- engine/collection/synchronization/engine.go
- engine/common/fifoqueue/fifoqueue.go
- engine/common/fifoqueue/fifoqueue_test.go
- engine/common/synchronization/engine.go
- engine/consensus/compliance/engine.go
- engine/consensus/ingestion/engine.go
- engine/consensus/matching/engine.go
- engine/consensus/sealing/engine.go
- engine/enqueue_test.go
Previously, the `FifoQueue`'s constructor took an optional argument that specified the queue's capacity, and defaulted to `maxint`. While all instantiations did specify a capacity, this pattern makes it easy to unintentionally omit the capacity override and configure an unlimited queue.
Update the `NewFifoQueue` constructor to take a required `maxCapacity` argument.
> [Engine] Require explicit capacity for Fifo queue

- admin/README.md
- admin/command_runner.go
- admin/command_runner_test.go
- cmd/access/node_builder/access_node_builder.go
- cmd/node_builder.go
- cmd/scaffold.go
- integration/localnet/bootstrap.go
This PR makes the max response size for the Admin server configurable, and adds the `read-execution-data` command to ANs running execution sync
> [Access] Add admin command to get execution data

- cmd/execution_builder.go
- engine/execution/state/state.go
- state/protocol/badger/state.go
- state/protocol/badger/state_test.go
- storage/badger/procedure/executed.go
- storage/badger/procedure/executed_test.go
This PR fixes an issue that the finalized height and executed height metrics is not reported on startup until there is block being finalized and executed.
For EN which takes a while to load the execution state, the finalized height and executed height is not shown on metrics.
This PR fixes it by reporting finalized height and executed height on startup.
> [Metrics] Report finalized height and executed height on startup

- cmd/execution_builder.go
This check is always true on the `else if` branch
> [Execution] Remove useless condition from builder

- cmd/util/cmd/execution-state-extract/cmd.go
- ledger/complete/wal/checkpointer.go
The `ReadLastTrieRootHashFromCheckpoint` is incorrect for checkpoint V6. 
Since state extraction will always specify block hash, we could simply remove this function.
> Remove read last trie

- ledger/complete/wal/checkpointer.go
- ledger/complete/wal/checkpointer_test.go
This codepath is not used anymore and checkpointer releases the memory immediately once the file is processed.
> [Execution] Kill pagecache mass eviction code

- cmd/node_builder.go
- cmd/scaffold.go
This PR reduces the number of calls to `Fatal()` during node bootstrapping by returning errors to the caller so they can be handled appropriately. All of the errors returned are ultimately returned from the node builder's `Build()` method and result in a final call to `Fatal()` in the node's main method. The only exception is the case of the consensus follower library, which allows the implementor to handle the error directly.
> [Bootstrap] Improve error handling in node scaffold

- engine/execution/computation/computer/computer.go
- engine/execution/computation/computer/computer_test.go
- engine/execution/computation/computer/result_collector.go
- engine/execution/computation/manager_test.go
- engine/execution/ingestion/engine.go
- engine/execution/messages.go
- engine/execution/state/unittest/fixtures.go
- module/metrics.go
- module/metrics/example/execution/main.go
- module/metrics/execution.go
- module/metrics/noop.go
- module/mock/execution_metrics.go
1. consistently use collection for naming, instead of using collection/chunk interchangeably
2. simplify adding collection to the result
3. return all collection/block stats as a struct using a single api call
4. clean up collection/block stats metric logging
gh: #3547
> Cleanup ComputationResult

- network/internal/testutils/testUtil.go
This is what `libp2p` does in their own tests, e.g.: https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/circuitv2/client/reservation_test.go#L85
> [Networking] Do not use resource limits in tests

- module/metrics/labels.go
- module/metrics/network.go
Adds missing label _LabelViolationReason_ to OnUnauthorizedMessage metric.
> Add missing metric label. 

- cmd/node_builder.go
- cmd/scaffold.go
- network/p2p/scoring/score_option.go
- utils/logging/samplers.go
This PR uses `zerolog.BurstSampler`s to rate limit `Debug` and `Trace` level events. Any events that exceed the limit will be dropped. This helps protect nodes from significant performance issues when debug logging is enabled.
Note: This is being added to avoid liveness issues when a large volume of logs are generated. It may result in lost log events which would require further changes to logging to prevent.
This PR also sets the min log level to `Trace` which allows enabling trace events via the `--loglevel` flag or admin command.
> [Logging] Add log throttle for debug/trace level events

- cmd/execution_builder.go
Backports https://github.com/onflow/flow-go/pull/3497 from v0.28 to master
This fixes the initialization order of the blobservice and uploaders in the execution node builder. Blobservice is needed by both the provider engine and GCP uploader, and the uploaders are also needed by the provider
> [Execution] Break blobservice out to own component in en builder

- admin/command_runner_test.go
- engine/access/access_test.go
- engine/access/apiproxy/access_api_proxy_test.go
- engine/access/rest_api_test.go
- engine/access/rpc/backend/connection_factory_test.go
- engine/access/rpc/rate_limit_test.go
- engine/access/secure_grpcr_test.go
- integration/testnet/network.go
- integration/tests/access/access_test.go
- integration/tests/access/observer_test.go
- network/internal/p2pfixtures/fixtures.go
- network/internal/testutils/testUtil.go
- network/p2p/p2pnode/protocolPeerCache_test.go
- network/p2p/test/fixtures.go
- utils/unittest/fixtures.go
When running unit tests on a mac, there are many alert popups asking for permission to allow incoming connections. This is caused by using `0.0.0.0` as the listen address in the test setup. Update unit tests to instead use localhost.
> [Testing] Use localhost in unit tests to reduce firewall alerts

- fvm/errors/codes.go
- fvm/errors/execution.go
- fvm/transactionPayerBalanceChecker.go
- fvm/transactionPayerBalanceChecker_test.go
This should be a failure because it can only happen if the communication between the core contract and FVM is faulty, which means something isn't set up correctly.
> [FVM] Change payer balance check error to a failure

- cmd/execution_builder.go
- cmd/execution_config.go
- cmd/util/cmd/execution-state-extract/cmd.go
- cmd/util/cmd/execution-state-extract/execution_state_extract.go
- cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
- ledger/complete/compactor.go
- ledger/complete/ledger.go
- ledger/complete/ledger_test.go
- ledger/complete/wal/checkpointer.go
- ledger/complete/wal/wal.go
From the next spork, the checkpoint V5 will be deprecated, and we will only support reading and generating checkpoint V6
> Only read and write checkpoint in v6

- engine/common/provider/engine.go
- engine/common/requester/engine.go
Changing the provider engine's log level into INFO for making debugging execution halt issue easier
> Change info level log for provider engine

- cmd/consensus/notifier.go
- consensus/hotstuff/integration/instance_test.go
- consensus/hotstuff/mocks/timeout_signature_aggregator.go
- consensus/hotstuff/notifications/log_consumer.go
- consensus/hotstuff/signature.go
- consensus/hotstuff/timeoutcollector/aggregation.go
- consensus/hotstuff/timeoutcollector/aggregation_test.go
- consensus/hotstuff/timeoutcollector/timeout_processor.go
- consensus/hotstuff/timeoutcollector/timeout_processor_test.go
- module/signature/signer_indices.go
This PR fixes a bug which can occur under specific conditions and results in consensus halt effectively undermining liveness. 
Replicas perform a multi-message BLS aggregation to build a TC. To verify such signature we need to provide list of signers and messages used to construct the signature. We provide this data as part of `flow.TimeoutCertificate` structure as two separate lists `SignerIndices` and `NewestQCViews`. Strictly speaking TC verification depends on correct relation between signers and messages, should the order of signers or messages be altered and we cannot verify the signature anymore. 
And that's exactly what has happened when replicas contributed with different messages, signers got sorted in canonical order because of signer indices implementation but messages weren't …
> [Consensus] TC aggregation multi-message verification fix

- network/internal/testutils/testUtil.go
- network/p2p/connection/connection_gater_test.go
- network/p2p/connection/peerManager.go
- network/p2p/p2pnode/libp2pNode_test.go
- network/test/echoengine_test.go
- network/test/epochtransition_test.go
- network/test/meshengine_test.go
- network/test/middleware_test.go
- utils/unittest/protected_map.go
Fixes unittests under `network` flagged by the race detector. Mostly races within the tests themselves, but there was also a race in the peer manager.
> [Testing] Fix races in network unittests

- cmd/access/node_builder/access_node_builder.go
- cmd/collection/main.go
- cmd/consensus/main.go
- cmd/execution_builder.go
- cmd/observer/node_builder/observer_builder.go
- cmd/verification_builder.go
- consensus/integration/nodes_test.go
- engine/collection/epochmgr/factories/epoch.go
- engine/collection/epochmgr/factories/sync_core.go
- engine/collection/synchronization/engine.go
- engine/collection/synchronization/engine_test.go
- engine/common/synchronization/engine.go
- engine/common/synchronization/engine_test.go
- engine/testutil/nodes.go
- follower/follower_builder.go
- model/chainsync/status.go
- module/chainsync/core.go
- module/chainsync/core_rapid_test.go
- module/chainsync/core_test.go
- module/metrics/chainsync.go
* Fixes a bug in the sync engine, where many sync `Status` objects would share a reference to the same `Header` due to a re-used loop variable (see https://github.com/onflow/flow-go/commit/a874156937a518704c14edbb8a0a4a4832dee3b1)
* Adds the chain ID to the sync core, making it possibly to easily differentiate between follower and cluster sync core logs, on collection nodes
* Adds the chain ID to the chainsync metrics, for the same reason
> Fix sync engine bug, improve observability

- cmd/access/node_builder/access_node_builder.go
Currently, the public network's metrics collector is initialized when setting up the network objects. However, starting in `v0.28`, the public network's libp2p node is created before the network objects, so it is initialized with a noop metrics collector, resulting in all public network metrics being dropped.
This PR moves the metrics initialization to before all components are started.
> [Access] Fix public network metrics

- cmd/access/node_builder/access_node_builder.go
Backports: https://github.com/onflow/flow-go/pull/3716
Currently, the public network's metrics collector is initialized when setting up the network objects. However, starting in `v0.28`, the public network's libp2p node is created before the network objects, so it is initialized with a noop metrics collector, resulting in all public network metrics being dropped.
This PR moves the metrics initialization to before all components are started.
> [Access] Fix public network metrics v0.28 backport

- integration/benchmark/contLoadGenerator.go
Currently, `SetTPS` is a blocking call.  Since it only blocks in cases where we decrease TPS (waiting for current transaction to finish) -- it causes tests to be biassed towards lower numbers.
> [Benchmark] Non-blocking SetTPS

- go.mod
- go.sum
- insecure/go.mod
- insecure/go.sum
- integration/benchmark/follower.go
- integration/benchmark/follower_test.go
- integration/benchmark/mock/client.go
- integration/go.mod
- integration/go.sum
This switches the follower from using `GetBlockByHeight` and `GetCollection` to a single `GetTransactionResultsByBlockID`.
Initial improvement suggestion: @peterargue 
Depends on: https://github.com/onflow/flow-go-sdk/pull/332
> [Benchmark] Simplify transaction follower

- fvm/transactionInvoker.go
ref: https://github.com/onflow/flow-go/issues/2767
I realised that checking the payers account balance should not be metered because of 2 reasons:
1. It should be part of inclusion fees, not execution fees. All transactions need to have this check, and the check is of a constant complexity.
2. Adding additional computation cost to transactions will potentially break any daps that have fine tuned their transaction gas limits. Which we will eventually have to do, but that needs a longer communication change, and we can batch more changes like that together.
> Don't meter the payer balance check

- fvm/transactionInvoker.go
Meter param overrides and programs parsing are now part of PreprocessTransactionBody
gh: #3547
> Split ExecuteTransactionBody into two

- cmd/Dockerfile
Cleanup the dockerfile
* Remove unused `production-transit-nocgo` target. The build stage was removed in https://github.com/onflow/flow-go/pull/1378
* Add some more comments and breakup the file for readability
> [Docker] Remove unused build target and cleanup comments

- network/p2p/cache/node_blocklist_wrapper.go
- network/p2p/cache/node_blocklist_wrapper_test.go
- network/p2p/middleware/middleware.go
This PR fixes a bug in the node block list wrapper where ejected identities are returned from the Identities func when provided with the not ejected identity filter. It filters block listed nodes again after modifying the ejected field and adds a unit test for this edgecase.
> Filter ejected peers in the middleware topologypeers provider

- fvm/transactionInvoker.go
- fvm/transactionVerifier.go
1. moved all inexpensive check ahead of crypto library calls
2. parallelize crypto library call
Note: there's no observed difference in speed in benchmarks since the benchmark transactions all involve a very small number of signatures (there's basically no parallelism to be had).  We can expect minor speed up for transactions with large number of signatures
> parallelize signature verification

- integration/localnet/bootstrap.go
In a large benchmark environments it does not make sense to give every binary all `NumCPU` threads.  Otherwise we are looking at the order of thousands of GC threads threshing caches across the cores.
Also while here, remove `BINSTAT` since we do not use it.
> [Benchmark] Limit GOMAXPROCS on localnet

- .github/workflows/ci.yml
- .github/workflows/flaky-test-debug.yml
- Makefile
- tools/test_monitor/run-tests.sh
`docker-build-flow` is the primary make target for building flow-go docker images. The corrupted images are only needed when running the BFT tests, so remove the `docker-build-flow-corrupt` from the main target and only added it when needed
> [BFT Testing] Only build corrupted images when required

- .github/workflows/cd.yml
- Makefile
- cmd/Dockerfile
Currently, the docker images without `netgo` require an extra manual step to build. Add them into CD so they're built for every version
> [CD] Automate without-netgo image building

- integration/benchmark/cmd/ci/adjuster.go
- integration/benchmark/cmd/ci/main.go
Transactions in-progress are very inertial.  To prevent the initial windup let's delay TPS adjustment by a couple of minutes.
> [Benchmark] Prevent PID windup at start

- engine/execution/messages.go
- fvm/transactionInvoker.go
Just set the result values unconditionally.
Also remove IsSampled check around ComputationIntensities.  The intensities are used for metric logging rather than tracing and hence should not be sampled.
> Simplify setting transaction procedure result values

- engine/verification/utils/unittest/helper.go
When chunk verifier returns error, a placeholder signature is generated for that chunk.
> Improve verification test's error message

- engine/execution/computation/execution_verification_test.go
- engine/verification/verifier/engine.go
- engine/verification/verifier/engine_test.go
- module/chunks.go
- module/chunks/chunkVerifier.go
- module/chunks/chunkVerifier_test.go
- module/mock/chunk_verifier.go
From the caller's perspective, there's not need to treat non-system vs system chunk differently.
> Simplify chunk verifier api

- module/metrics.go
- module/metrics/example/collection/main.go
- module/metrics/example/consensus/main.go
- module/metrics/labels.go
- module/metrics/network.go
- module/metrics/noop.go
- module/mock/network_core_metrics.go
- module/mock/network_metrics.go
- network/p2p/network.go
A previous change (https://github.com/onflow/flow-go/pull/3757) updated the network message metrics. This PR fixes a modified label and adds a label for protocol (`pubsub` vs `unicast`)
> [Network] Add protocol metrics label

- engine/execution/computation/computer/computer_test.go
- fvm/environment/system_contracts_test.go
- fvm/executionParameters_test.go
- fvm/runtime/reusable_cadence_runtime.go
Various places create Cadence `runtime.Config`s, e.g. `NewReusableCadenceRuntime` creates an empty one, even when the runtime was potentially created using a different one (e.g. by `ReusableCadenceRuntimePool.newCustomRuntime`).
Propagate the runtime configuration, so it is consistently the same everywhere in `ReusableCadenceRuntimePool` and `ReusableCadenceRuntime`.
> Ensure the same runtime config is used

- fvm/transactionVerifier.go
As per Leo's suggestions.
Co-authored-by: Leo Zhang (zhangchiqing) <zhangchiqing@gmail.com>
> Improve transaction verifier clarity

- cmd/util/ledger/reporters/account_reporter.go
- engine/execution/computation/computer/computer.go
- engine/execution/computation/manager_test.go
- fvm/context.go
- fvm/environment/facade_env.go
- fvm/environment/value_store.go
- fvm/executionParameters.go
- fvm/fvm.go
- fvm/script.go
- fvm/transaction.go
- fvm/transactionInvoker.go
- fvm/transactionSequenceNum.go
- fvm/transactionSequenceNum_test.go
- fvm/transactionVerifier.go
Transaction procedure's span was set using a snowflake api.  This change makes span setup consistent with the rest.
This also plumb trace span correctly through script environment.
> Set transaction procedure's trace span via context

- fvm/errors/base.go
- fvm/errors/errors.go
- fvm/errors/errors_collector_test.go
- fvm/errors/failures.go
- fvm/fvm.go
- fvm/script.go
Don't rely on As() to unwrap errors when searching for a non-fatal error code since multierror.Error's As() will only inspects the first error in the list (other error codes in the errors list are ignored).
> Improve error code search.

- integration/localnet/Makefile
- integration/localnet/bootstrap.go
Right now we are logging too much data from ~30 daemons on the same box most of which debug data.  Since production runs with an info level by default, let's switch to it in benchmarks too.
PS. Keep default at DEBUG to preserve backwards compatibility with previous localnet setups (it is quite useful for local troubleshooting.)
> [Benchmark] Match log-level w/ production

- fvm/derived/derived_block_data.go
- fvm/derived/derived_chain_data_test.go
- fvm/derived/invalidator.go
- fvm/environment/contract_updater.go
- fvm/environment/contract_updater_test.go
- fvm/environment/derived_data_invalidator.go
- fvm/environment/derived_data_invalidator_test.go
- fvm/environment/mock/derived_transaction_data.go
- fvm/environment/programs.go
- fvm/environment/programs_test.go
- fvm/programs/programs.go
ref:  [Improve FVM Program Cache Invalidation](https://github.com/onflow/flow-go/issues/3015)
Smart contract invalidation.
This relies on Cadence properly calling Get/Set program (which should already be the case, because other parts of the code also depend on this). The proper use of Get/Set will be guaranteed once we replace Get/Set with a single `GetOrCreate(location, create_function)` function. This will be a future PR.
The principle is that we store program dependencies together with the program in the cache. These dependencies are filled when cadence calls Get/Set program.
**Example**
```mermaid
graph TD
C-->D
C-->B
B-->A
```
With this dependency graph, if B is already in cache and we are loading C:
- Get C:
- Get B. We have B with dependency A, so A is added to C as a dependency
- …
> [FVM] Smart/partial programs cache invalidation

- engine/common/follower/engine.go
- engine/consensus/compliance/core.go
- engine/consensus/ingestion/core.go
- engine/consensus/matching/core.go
- engine/consensus/sealing/core.go
- engine/execution/computation/computer/computer.go
- engine/execution/ingestion/engine.go
- engine/verification/assigner/engine.go
- engine/verification/fetcher/engine.go
- engine/verification/requester/requester.go
- engine/verification/verifier/engine.go
- module/builder/collection/builder.go
- module/builder/consensus/builder.go
- module/finalizer/consensus/finalizer.go
- module/mock/tracer.go
- module/trace/log_tracer.go
- module/trace/noop.go
- module/trace/trace.go
- module/trace/trace_test.go
- module/tracer.go
- state/cluster/badger/mutator.go
Remove isSample from Start`<Block|Collection|Transaction>`Span's return value. The span attribute value overhead is minimal.
Note that we usually set the same attribute values into the logger at the same time.  If the attribute value formatting is expensive, we can just precompute the formatted value and reuse it for both the span and the logger.
> Simplify Start Entity Span.

- engine/access/access_test.go
- engine/access/rpc/backend/backend_accounts.go
- engine/access/rpc/backend/backend_events.go
- engine/access/rpc/backend/backend_scripts.go
- engine/access/rpc/backend/backend_test.go
- engine/access/rpc/backend/backend_transactions.go
- engine/execution/rpc/engine_test.go
This is a cleanup for the switch to Protobuf v2 API.
* It is now forbidden to copy ptotobuf messages by value since they have [DoNotCopy](https://godoc.org/google.golang.org/protobuf/internal/pragma#DoNotCopy) embedded in them.  So switch to passing pointers.
* It is incorrect to compare protobuf messages by value w/ [DeepEqual](https://developers.google.com/protocol-buffers/docs/reference/go/faq#deepequal), so switched tests to use `go-cmp` and [protocmp.Transform()](https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp#Transform)
ref: https://github.com/onflow/flow/pull/1215
> [Access] Do not copy protobuf messages
