onflow/flow-go

network/message_scope.go

`PayloadType()` is used when generating incoming metrics labels. `m.msg.Payload` is always a byte slice, whereas `m.decodedPayload` is the actual message struct

[Network] Fix inbound message metrics label

---

.github/workflows/tools.yml

The PR adds a github action workflow that can be run on demand to build the `bootstrap`, `transit` and `util` tools, then upload them to GCS

[CI] Add github action to build boot-tools on demand

---

integration/dkg/dkg_client_wrapper.go

The DKG Client wrapper used in the dkg emulator test made use of an `enabled` flag which could be concurrently written by the test thread and read by the DKG controller thread, causing a data race.

Fix data race in DKG integration test

---

cmd/execution_builder.go
cmd/util/ledger/reporters/account_reporter.go
engine/execution/computation/computer/computer.go
engine/execution/computation/manager.go
engine/execution/computation/manager_benchmark_test.go
engine/execution/computation/manager_test.go
engine/execution/testutil/fixtures.go
engine/testutil/mock/nodes.go
fvm/README.md
fvm/accounts_test.go
fvm/fvm.go
fvm/fvm_blockcontext_test.go
fvm/fvm_fuzz_test.go
fvm/fvm_signature_test.go
fvm/fvm_test.go
module/chunks/chunkVerifier.go
utils/debug/remoteDebugger.go

Note that we can't simply redefine fvm.VirtualMachine from a struct into an interface since that breaks the emulator.

Define vm interface in fvm instead of computer

---

Makefile

The `--ssh default` flag is only needed for building when the repo contains a dependency within a private repo. This is generally not needed so removing.
Running with this flag causes CI builds to fail: https://github.com/onflow/flow-go/actions/runs/3896458835/jobs/6653020995

[CI] Remove --ssh flag from docker build for util

---

cmd/scaffold.go
module/metrics/node_info.go
module/metrics/node_info_test.go

https://github.com/onflow/flow-go/issues/3597
This PR implements reporting of static metrics that are common for each node type. 
Currently we report _sporkID_, _version_ and _commit_. 
Prometheus doesn't support reporting static metrics, the recommended way is to use `GaugeVec` with dummy data, the metrics itself are reported as gauge labels. 
Metrics are reported as part of startup process in scaffold code, this allows to utilize same logic for all nodes.

[General] Reporting node info metrics

---

engine/execution/computation/computer/computer.go

This is both prep work for flattening transaction execution loops and prep work for pre-computing / caching txnId for tracing (see #3793)

Pre-populate []transactions into collectionItem

---

fvm/environment/programs.go
fvm/fvm_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

relates to: https://github.com/onflow/flow-go/issues/3802
uses cadence from: https://github.com/onflow/cadence/pull/2241
If `GetProgram` is called and returns nil `SetProgram` must be called. Cadence recently changed that some parsing errors that occur during program loading are not critical (and cadence execution continues). In this case `SetProgram` mist be called with a `nil` to signal that program loading is done, but no program was loaded. 
Should not be merged to master. Master should get the proper fix of changing `get` and `set` into a `getOrSet(loadProgramClosure)`

[FVM]SetProgram can be called with nil

---

engine/execution/state/delta/delta.go
engine/execution/state/delta/delta_test.go
engine/execution/state/delta/view.go
engine/execution/state/mock/register_updates_holder.go
engine/execution/state/state.go
fvm/environment/derived_data_invalidator.go
fvm/environment/programs_test.go
fvm/state/state.go
fvm/state/transaction_state.go
fvm/state/view.go
fvm/utils/view.go
ledger/partial/ledger_test.go
module/chunks/chunkVerifier.go
utils/debug/remoteView.go

return RegisterEntries instead of ([]RegisterID, []RegisterValue)
it's safer, and we can potentially skip sorting in the future.  It probably does less work as well.

Change RegisterUpdates's return type

---

.github/workflows/tools.yml
Makefile

backports: https://github.com/onflow/flow-go/pull/3787 and https://github.com/onflow/flow-go/pull/3798

[CI] Add github action to build boot-tools on demand - v0.29 backport

---

engine/execution/state/state.go
ledger/partial/ledger_test.go
module/chunks/chunkVerifier_test.go

they've been replaced by RegisterEntriesToKeysValues

remove RegisterIDToKey & RegisterValuesToValues from execution state

---

engine/execution/computation/computer/computer_test.go
engine/execution/convert.go
engine/execution/messages.go
fvm/environment/env.go
fvm/environment/event_emitter.go
fvm/environment/mock/environment.go
fvm/environment/mock/event_emitter.go
fvm/transaction.go
fvm/transactionInvoker.go
model/convert/fixtures/fixture.go
model/flow/execution_result.go
module/chunks/chunkVerifier.go
module/chunks/chunkVerifier_test.go

This reduce the number of places that needs to convert service events, and can be parallelized in the future as part of fvm execution.

Convert service event as part of fvm execution

---

.github/workflows/bench.yml

Newest version changed CLI flags quite severely and removed html output.  Let's wait until development there settles.

[Github] Pin benchstat version

---

integration/testnet/network.go

This PR changes integration test utilities to use a consistent method and root location when creating temporary directories for use in tests. 
This is to mitigate an issue where integration tests would fail on macOS, due to a permissions issue when initializing bootstrap and data directories for Docker containers.
```
lchown /var/folders/bm/wbf3kfs91911lr5w6qyw126c0000gn/T/TestEpochJoinAndLeaveANTestEpochJoinAndLeaveAN4216456854/001/bootstrap/execution-state/00000000: operation not permitted
```
As far as I can tell, `t.TempDir()` created directories which caused `operation not permitted` errors, whereas `os.MkdirTemp("/tmp", ...)` did not. We aren't sure what causes the two methods to behave differently at this point, but using "the good one" consistently works to fix the test failure.

Use consistent method for creating temp dirs

---

engine/execution/state/delta/view.go
engine/execution/state/delta/view_test.go
engine/execution/state/state_test.go
fvm/environment/accounts_test.go
fvm/state/view.go
fvm/utils/view.go
utils/debug/remoteView.go

This simplifies changing view implementations.  We can add them back in the future if the support is needed.

Remove Touch/Delete from view interface.

---

fvm/derived/table_test.go
fvm/environment/account_creator.go
fvm/environment/accounts.go
fvm/environment/derived_data_invalidator_test.go
fvm/environment/meter.go
fvm/environment/uuids.go
fvm/state/state.go
fvm/state/state_test.go
fvm/state/transaction_state.go
fvm/state/transaction_state_test.go
fvm/transactionInvoker.go

1. Replace EnableAllLimitEnforcements/DisableAllLimitEnforcements with RunWithAllLimitsDisabled
2. Remove enforceLimit parameter from Get/Set calls.
3. Internalize meter enforceLimits check into State.
This enables us to compose view implementations (meter/interaction limits view, spock view, delta, etc) in the future.

Refactor meter/interaction limits control

---

cmd/access/node_builder/access_node_builder.go
cmd/consensus/main.go
engine/access/ingestion/engine.go
integration/Makefile
integration/go.mod
integration/go.sum
integration/templates/create-and-setup-node.cdc
integration/testnet/client.go
integration/tests/epochs/epoch_join_and_leave_sn_test.go
integration/tests/epochs/epoch_join_and_leave_vn_test.go
integration/tests/epochs/suite.go
integration/tests/lib/util.go
integration/utils/templates/create-and-setup-node.cdc
integration/utils/transactions.go
state/protocol/badger/validity.go
state/protocol/badger/validity_test.go

This PR re-enables all epoch integration tests, reduces time taken by epoch integration tests by about 30%, and fixes a bug in the snapshot validator function.
- Fix off-by-one error in snapshot validator function
- Update documentation of validator, and require in Access Node as well
- Remove expiry-escape mitigation in AN ingestion, which is now covered by the snapshot validator
- Replace separate staking step transactions (create account, fund, set up staking collection, register node) with one custom transaction
- This enables reducing the epoch length by 50%, speeding up the test significantly
Before improvements, was 650-720s.
After improvements, is 400-430s
Before improvements, was 30-40m
After improvements, is ~23m

Re-enable Epoch Integration Tests

---

consensus/hotstuff/eventhandler/event_handler.go

We process pending blocks in the EventHandler prior to starting the main event loop. This allows us to validate the pending blocks and process their QC/TCs prior to accepting any new blocks. Part of this may involve changing views, which will cause us to initiate a new timeout in the TimeoutController.
The TimeoutController uses a context to gracefully shut down its ticker goroutine, which is derived from the EventHandler's lifecycle context and is set during the Start function. Currently, we process pending blocks prior to starting the Pacemaker. So the Pacemaker context will be nil at this point. If we process a pending block which causes us to change views, then we will attempt to derive a child of a nil context, which causes a panic!
Since we persist the new view before hitting the …

Start pacemaker before processing pending blocks

---

fvm/state/state.go
fvm/state/transaction_state.go
fvm/transactionInvoker.go
fvm/transactionStorageLimiter.go
fvm/transactionStorageLimiter_test.go

The implementation is buggy; it doesn't handle DropDelta correctly. Luckily, we only use it for storage check and the bug is never triggered.

Remove UpdatedAddresses from fvm State

---

fvm/environment/accounts.go

Have a single point/function where the storage used is set.
preparation for: https://github.com/onflow/flow-go/issues/3826

[FVM] Refactor accounts set storage used

---

fvm/environment/programs.go
fvm/state/state.go

Just to be more safe, before setting the program in the cache, check the no writes have been performed during program loading.

[FVM] Add restriction that program loading cannot write to registers

---

fvm/derived/table_test.go
fvm/environment/account_creator.go
fvm/environment/accounts.go
fvm/environment/derived_data_invalidator_test.go
fvm/environment/uuids.go
fvm/errors/execution.go
fvm/state/state.go
fvm/state/state_test.go
fvm/state/transaction_state.go
fvm/state/transaction_state_test.go
fvm/state/view.go
fvm/transactionStorageLimiter_test.go

The (owner, key) tuple are RegisterID's implementation detail.  The view interface should not be expose to these details.
I'll update the lower level apis in future PRs.

Use RegisterId instead of (owner, key)-tuple as key for accessing register values

---

cmd/util/cmd/checkpoint-collect-stats/cmd.go
cmd/util/ledger/migrations/account_migration.go
cmd/util/ledger/migrations/storage_fees_migration.go
cmd/util/ledger/migrations/utils.go
cmd/util/ledger/reporters/atree_reporter.go
engine/execution/computation/computer/computer_test.go
fvm/accounts_test.go
fvm/environment/account_creator.go
fvm/environment/account_creator_test.go
fvm/environment/account_key_updater_test.go
fvm/environment/accounts.go
fvm/environment/accounts_test.go
fvm/environment/derived_data_invalidator.go
fvm/environment/derived_data_invalidator_test.go
fvm/environment/mock/accounts.go
fvm/environment/programs_test.go
fvm/environment/uuids.go
fvm/environment/value_store.go
fvm/errors/codes.go
fvm/errors/execution.go
fvm/fvm_test.go
fvm/state/state.go
fvm/state/state_test.go
model/flow/ledger.go
model/flow/ledger_test.go

1. Refactored flow internal state register id creation from fvm/state to model/flow
2. Convert IsStabIndex, IsInternalState (aka IsFVMStateKey) into register id methods
3. Format RegisterID's key using PrintableKey's logic.
4. Replace accounts (owner, key)-tuple inputs with register id
5. Cleaned up some errors.

Use RegisterID instead of (owner, key)-tuple for accessing accounts

---

network/p2p/connection/connection_gater_test.go

Fixing: `TestConnectionGating/inbound_connection_from_an_allowed_node_is_rejected`
It was failing with the following error:
```
--- FAIL: TestConnectionGating/inbound_connection_from_an_allowed_node_is_rejected (0.02s)
fixtures.go:354: 
Error Trace:    /Users/yahya/go/src/github/onflow/flow-go/network/p2p/connection/fixtures.go:354
/Users/yahya/go/src/github/onflow/flow-go/network/p2p/connection/connection_gater_test.go:89
Error:          Should be empty, but was [<swarm.Conn[*tcp.TcpTransport] /ip4/127.0.0.1/tcp/63352 (16Uiu2HAm25DESm7brWshLYESjNKrye1b2gps6NQpJRmWj7Xjy34Q) <-> /ip4/127.0.0.1/tcp/63343 (16Uiu2HAmG8RAYybc2tR1evq23rn1UAMeNfsPSxZGHxsNFaK81md7)>]
Test:           TestConnectionGating/inbound_connection_from_an_allowed_node_is_rejected
```
The reason for the failure is:
1. …

Fixes Connection Gater Test

---

engine/common/rpc/convert/convert.go
engine/common/rpc/convert/convert_test.go
module/blobs/blob_store.go
module/executiondatasync/execution_data/util.go
storage/badger/seals.go

This PR fixes a panic in the state stream API when handling an execution data for a block with an empty service chunk. It also relaxes validation of transactions from execution data to handle service transactions.
Finally, it introduces a new method `execution_data.CalculateID()` which allows you to calculate the execution data id from a `BlockExecutionData`. This enables consumers of the state stream API to verify the data they receives matches the data included in the sealed `ExecutionResult`

[Access] Fix panic converting execution data to protobuf messages

---

fvm/derived/table_test.go
fvm/environment/accounts.go
fvm/meter/meter_test.go
fvm/state/state_test.go
fvm/state/transaction_state_test.go
fvm/transactionStorageLimiter_test.go
fvm/utils/view.go

Prep work for sanitizing the owner (ensure owners are 8 bytes string) / replacing owner type from string to Address.

Initialize register ids with flow.NewRegsiterId instead of flow.RegisterID{...}

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
fvm/derived/derived_block_data.go
fvm/environment/programs_test.go
module/metrics.go
module/metrics/execution.go
module/metrics/noop.go
module/mock/execution_metrics.go

references: https://github.com/onflow/flow-go/issues/2862
Add metrics for how many programs are cached at the end of a block.

Add cached programs metrics

---

network/internal/testutils/testUtil.go
network/p2p/connection/connection_gater.go
network/p2p/connection/connection_gater_test.go
network/p2p/p2pbuilder/libp2pNodeBuilder.go
network/p2p/p2pnode/libp2pNode_test.go
network/test/middleware_test.go

This PR wires in an identity provider to the connection gater to ensure that an `info` level log is always printed displaying the remote `peer_id` together with its `flow.Identifier` upon dialing or rejecting a connection.

[Networking] Enables logging of peer ids together with node id upon connection establishment

---

engine/access/rpc/backend/backend_accounts.go
engine/access/rpc/backend/backend_events.go
engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/backend_transactions.go
engine/common/rpc/errors.go
engine/common/rpc/errors_test.go
engine/execution/rpc/engine.go

This PR improves the error reporting for requests that are proxied to Execution nodes. This is accomplished using a new method `rpc.ConvertMultiError` which accepts a `multierror` and returns a `grpc.Status` wrapped error. This uses the following logic:
* If all errors have the same status code, use it
* If there are 2 different codes, and one is either `Unavailable` or `DeadlineExceeded`, use the other code
* In all other cases, return the default code
It also makes a few general improvements:
* Replaces several generic errors with `codes.Internal` (instead of the default `codes.Unknown`)
* Adds specific codes in several places where none were added before (`codes.InvalidArgument` or `codes.NotFound`)

[Access] Improve Access API error reporting for results from ENs

---

engine/execution/ingestion/engine.go
engine/execution/ingestion/uploader/manager.go

Uploading computation result to clouds should not block saving computation result to disk / bcasting the result to the flow network.
Also fixed a benign data race while I'm at it (Upload and RetryUploads should not check for Enabled using a separate critical section)

Parallelize saving and uploading computation result.

---

engine/execution/computation/computer/computer_test.go
engine/execution/computation/manager.go
engine/execution/computation/manager_benchmark_test.go
fvm/environment/env.go
fvm/environment/runtime.go
fvm/environment/system_contracts_test.go
fvm/executionParameters_test.go
fvm/fvm_bench_test.go
fvm/fvm_test.go
fvm/runtime/reusable_cadence_runtime.go
fvm/runtime/reusable_cadence_runtime_test.go

Based on @SupunS's PR https://github.com/onflow/flow-go/pull/3918
Only the manager, which sets up the VM Context (and thus the cadence runtime Config)  for scripts and transactions, needs to have the account linking check enabled:
```go
// see: engine/execution/computation/manager.go
// AccountLinking is enabled everywhere except on mainnet
AccountLinkingEnabled: chainID != flow.Mainnet,
```

Enable Account Linking - Fix

---

.github/workflows/ci.yml

changed retry reference in CI workflow from `nick-invision` ==> `nick-fields`
According to https://github.com/nick-fields/retry:
```
Ownership of this project was transferred to my personal account nick-fields from my work account nick-invision
```
Note: having the old references is causing CI errors on downstream mirrored `flow-go` repos when running CI workflows.

[CI] Update `ci.yml` retry reference `nick-invision` => `nick-fields`

---

engine/common/rpc/convert/convert.go

export `convert.MessageToTrieUpdate` so that it can be used by clients without needing to convert the entire `ChunkExecutionData`

[Access] Export MessageToTrieUpdate converter method

---

ledger/complete/mtrie/trie/trie.go

The input variable `parentNode` in the trie `update` function is causing some confusion. This PR renames `parentNode` into `currentNode` and added some comments.
No logic change.

Rename variables and update comments for trie update function

---

cmd/util/cmd/read-execution-state/list-accounts/cmd.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/execution_verification_test.go
engine/execution/computation/manager_benchmark_test.go
engine/execution/computation/manager_test.go
engine/execution/computation/programs_test.go
engine/execution/state/bootstrap/bootstrap.go
engine/execution/state/delta/storage_snapshot.go
engine/execution/state/delta/view.go
engine/execution/state/delta/view_test.go
engine/execution/state/state.go
engine/verification/utils/unittest/fixture.go
fvm/accounts_test.go
fvm/environment/programs_test.go
fvm/fvm_bench_test.go
ledger/partial/ledger_test.go
module/chunks/chunkVerifier.go

This enables us to compose storage snapshot implementations (e.g., chunk verifer's partial ledger) and allow us to add batch read support in the future.

Change delta view to read from StorageSnapshot interface instead of readFunc

---

state/protocol/badger/validity.go

This PR removes the requirement that included nodes have non-zero weight, from `EpochSetup` service event validation. 
This requirement, in combination with a Staking contract bug, caused EECC to be triggered on Mainnet Feb 15.
Service event validation is intended to ensure that service events contain valid data. Although it was largely working as designed in this case (a service event which had unexpected data due to a bug in the smart contract was rejected), since the protocol state does correctly handle nodes with zero weight already, removing this requirement will safely prevent any similar smart contract problem from triggering EECC in the future.

Remove requirement that `weight > 0` in `EpochSetup` validation

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

https://github.com/dapperlabs/cadence-internal/compare/v0.31.3..v0.31.5

Update to Cadence v0.31.5 (internal)

---

fvm/derived/table.go
fvm/derived/table_invalidator.go
fvm/derived/table_invalidator_test.go
fvm/derived/table_test.go

Skip rechecking previously validated entries.

Amortize derived data validation cost

---

fvm/fvm_blockcontext_test.go
fvm/meter/interaction_meter.go
fvm/meter/interaction_meter_test.go
fvm/meter/meter_test.go

closes: https://github.com/onflow/flow-go/issues/3782
Interaction metering was very aggressive.
When merging sub-meters (as from the importing cadence contracts) the storage reads were simply added together. Which meant that if the parent meter already counted a read for a register that the child meter also counted, the same register will be counted as read twice.
In reality interaction metering is supposed to only meter first read from a register, and last write to a register.

[FVM] Change interaction metering

---

engine/access/rest/router.go

The rest metrics handler causes high memory on ANs. Disable it on mainnet until it's fixed.
heap profile:

[Access] Disable rest metrics v0.29

---

engine/execution/computation/manager.go
fvm/fvm_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Cadence v0.31.5-account-link-pragma is v0.31.5 + account linking pragma (https://github.com/onflow/cadence/pull/2359 / onflow/cadence#2355)

Update to Cadence v0.31.5-account-link-pragma

---

access/handler.go
consensus/hotstuff/committee.go
consensus/hotstuff/signature/block_signer_decoder.go
consensus/hotstuff/signature/block_signer_decoder_test.go
engine/execution/rpc/engine.go
engine/protocol/handler.go

Backport https://github.com/onflow/flow-go/pull/3906

[v0.29] Backport: `Fix OBO and inconsistency in signer indices decoding used in Access API #3906`

---

engine/execution/state/mock/execution_state.go
engine/execution/state/mock/read_only_execution_state.go
engine/execution/state/state.go

This PR removes two methods (`RetrieveStateDelta`, and `GetCollection`) from the ReadOnlyState given its legacy code and not used by any components. GetCollection is not used given we construct an `executableBlock` object and pass it to the block computer.

[Execution] clean up - remove unused code

---

fvm/environment/accounts_status.go
fvm/environment/accounts_status_test.go
fvm/transactionVerifier_test.go
fvm/transaction_test.go

ref: https://github.com/onflow/flow-go/issues/3983
This just disables account freezing. The (un)freezing functions still exist and still sets the frozen byte, but the byte is never read and accounts are always treated as not frozen.
I will make a different PR(s) to cleanup the code. I left the tests in for now, as its easier to chase down all the places where cleanup is needed.

Disable account freezing

---

engine/execution/computation/computer/computer.go
engine/execution/state/delta/view.go
engine/execution/state/delta/view_test.go
fvm/environment/programs_test.go
fvm/state/state.go
fvm/state/state_test.go
fvm/state/transaction_state.go
fvm/state/transaction_state_test.go
fvm/state/view.go
fvm/utils/view.go
module/chunks/chunkVerifier.go
utils/debug/remoteView.go

Note that this change is slightly less efficient than the original implementation since UpdatedRegisters does extra/unnecessary sorting. The sorting is only needed for ledger updates, we should move aways from sorting the updates in general.

Change View merging to operate on execution snapshot

---

fvm/fvm_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Diff: https://github.com/onflow/cadence/compare/v0.31.5-account-link-pragma...v0.31.5-account-link-improvements
- Emit an event when an account is linked 
- onflow/cadence#2370
- onflow/cadence#2368
- Enforce account links to be private
- onflow/cadence#2369
- onflow/cadence#2366

Update Cadence to v0.31.5-account-link-improvements

---

fvm/environment/meter.go
fvm/environment/programs.go
module/trace/constants.go

Refactor GetAndSet (a.k.a. [GetOrLoad](https://github.com/onflow/cadence/pull/2362)) to make it easier to understand what is going on.
The next step is to remove the individual get and set methods, as they shouldn't be used anymore.
Work towards: https://github.com/onflow/cadence/issues/1684

Refactor get or load program

---

fvm/derived/table.go
fvm/derived/table_test.go

Computing (a.k.a.: loading) a derived value ( programs for the programs cache, metering settings for the metering settings cache)  is done in a state transaction (to record state interaction, and metered quantities). 
If computing errors the state transaction is left in a state where you could not just handle the error and continue.
By committing the current nested state transaction in case of a error during the compute function the caller can choose to handle the error and continue execution.
This will allow for further simplification of GetOrLoadProgram. Ref: https://github.com/onflow/flow-go/pull/3976
Work towards: https://github.com/onflow/cadence/issues/1684

Commit nested transaction on derived value compute error

---

consensus/hotstuff/committees/consensus_committee_test.go

I'm unable to reproduce test failures for this test locally as configured: https://github.com/dapperlabs/flow-go/issues/6564. By lowering the timeout when waiting for an async event to 1s, I can reproduce the failure locally. 
Increasing the timeout from 5s to 30s in this PR to see if it helps.

Increase timeout for committee test

---

engine/access/rpc/backend/backend.go
engine/access/rpc/backend/backend_accounts.go
engine/access/rpc/backend/backend_block_details.go
engine/access/rpc/backend/backend_block_headers.go
engine/access/rpc/backend/backend_events.go
engine/access/rpc/backend/backend_execution_results.go
engine/access/rpc/backend/backend_network.go
engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions.go
engine/access/rpc/backend/errors.go
engine/collection/rpc/engine.go
engine/common/rpc/errors.go
engine/common/rpc/errors_test.go
engine/execution/rpc/engine.go

Closes: https://github.com/onflow/flow-go/issues/3987

[Access] Improve api error handling

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/result_collector.go
engine/execution/computation/manager_benchmark_test.go

1. flatten execution loop to operation directly on transactions, bypassing collections
2. change result collector to only operate on transaction result (and generate collection views internally)
3. change result collector to pipleine transaction processing
Note that I've purposely left result collector in a messy state to minimize the number of changes (most of the changes in result collector are just indent changes).  I'll go back to clean it up in a follow up PR.

Decouple transaction execution from result collection

---

fvm/environment/account_key_reader.go
fvm/environment/mock/account_key_reader.go
fvm/environment/transaction_info.go

Consistently use "runtime" prefix for common.Address variable

Rename some address variables

---

cmd/collection/main.go
cmd/execution_builder.go
engine/common/provider/engine.go

See @jordanschalm's comment here for context: https://github.com/onflow/flow-go/pull/3880#discussion_r1090883044
Move the `HasWeight` identity check out of the common provider engine, and explicitly pass it in when instantiating. The `provider` is a generic engine and some usecases may need to support nodes from past/future epochs.

[Engine] Move weight check out of common provider engine

---

engine/common/follower/cache/cache.go
engine/common/follower/cache/cache_test.go

• extending secondary index to store _all_ blocks by their respective view
• adding pruning logic
* When we eject a block, we just delete the corresponding element in the `byView` map https://github.com/onflow/flow-go/blob/ec683db33b286b5620d7248499944143291e6a94/engine/common/follower/cache/cache.go#L91
Imagine that we have two blocks for the same view in the cache and one is ejected. Then, we wouldn’t be detecting equations anymore for this block.
I am not sure that this is a problem. I don’t think so. But it makes it very hard to precisely quantify the guarantees the cache makes. Its more a conceptual concern. I have grown very weary of code that has subtle behaviours that are hard to reason about.
* Similarly with the pruning:
We just let the cache run full and then rely on random …

Suggestions for PR 3965 (part 2)

---

engine/execution/state/state.go

Note that this also changes the cache to store nil values (ledger tree traversal is expensive regardless of its value)

make LedgerStorageSnapshot's readCache thread safe

---

consensus/hotstuff/committee.go
consensus/hotstuff/signature/block_signer_decoder.go
consensus/hotstuff/signature/block_signer_decoder_test.go

This PR attempts to fix error which happens on mainnet: 
```
$ flow blocks get 47169688 -n mainnet 
:x: Command Error: error fetching block: client: rpc error: code = Unknown desc = could not retrieve identities for block 424d4016debbab47e5feeeda3f63957d8f559d413dae28510cb7950a1ea53b46 with QC view 0: by-view query for unknown epoch
```
When requesting blocks from old epoch(not previous or current) we end up calling `IdentitiesByEpoch` which relies on local cache, and this cache doesn't have that epoch. This is the reason why getting an old block fails. 
Proposed hot-fix is to use `IdentitiesByBlock` as fallback if the primary path has failed.

[Committee] Fallback mechanism for `DecodeSignerIDs`

---

.github/workflows/builds.yml
.github/workflows/tools.yml

the `cd.yaml` workflow will build and push docker images for certain tags pushed to the repo. This is great for official releases where images are needed for all roles. It's overkill for hotfix images where only a single node role is needed.
This PR adds a new manually triggered workflow that allows building/pushing images for a specific set of node roles.

[CI] Add workflow to build individual docker images

---

.github/workflows/builds.yml

The original version would spawn jobs and do all of the pre-build steps for all roles, wasting runner resources. This change:
* Only creates jobs for roles that were selected
* Skips building relic on the node runner since it is already run during the docker builds

[CI] Only run jobs for selected roles

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/computer/result_collector.go
fvm/storage/snapshot_tree.go
fvm/storage/snapshot_tree_test.go
module/chunks/chunkVerifier.go

This simplify parallel execution (the tree is immutable and the list of write sets can be used for OCC validation), but at the expense of less efficient value lookups (the cost is amortized by compaction).

Replace View with SnapshotTree as storage representation

---

fvm/environment/facade_env.go
fvm/environment/programs.go

ref: https://github.com/onflow/cadence/issues/1684
Change the dependency stack for transaction/script programs to always have root dependencies. The root dependencies in this case are dependencies of the script/transaction procedure itself. 
The reason we want this is to have a map of "seen" imports, so we know when we need to reapply metering and when not... which is the next/last step in this PR chain.
I added a reset (which is called when switching from the transactions happy path/normal execution to the transaction failure path/fee deduction) that clears all non address programs and dependencies tracked, to avoid any potential cache poisoning.

Track script/transaction procedure program depedencies

---

cmd/util/ledger/reporters/fungible_token_tracker_test.go
engine/execution/computation/manager_benchmark_test.go
engine/execution/computation/manager_test.go
engine/execution/computation/programs_test.go
engine/execution/testutil/fixtures.go
fvm/accounts_test.go
fvm/fvm_blockcontext_test.go
fvm/fvm_fuzz_test.go
fvm/fvm_signature_test.go
fvm/fvm_test.go

Derived txn data is now an optional parameter.  The explicit setup is no longer needed (except for programs test and benchmark)

Remove derived block/txn data from (most) tests

---

fvm/derived/derived_block_data.go
fvm/environment/programs.go
fvm/environment/programs_test.go
fvm/errors/codes.go
fvm/errors/execution.go
fvm/fvm_test.go

closes: https://github.com/onflow/cadence/issues/1684
This removes metering imports multiple times within the same "scope".
with this scenario:
```
A
B imports A
C imports A,B
D imports C,A, B  <- order is important
```
this is the loading process:
- scope D: count importing D
- scope C: count importing C
- count importing A
- scope B: 
- count importing  A (even though it has been seen in scope C it has not been seen in scope B so we need to count it)
- don't count importing A it has already been seen in scope D
- don't count importing B (and dependencies) it has already been seen in scope D
The reason for this is that any of those individual "scopes"/contracts/programs need to be loaded independently because they are cached independently.

Remove double counting of imports

---

consensus/hotstuff/committee.go
consensus/hotstuff/committees/consensus_committee.go
consensus/hotstuff/signature/block_signer_decoder.go
consensus/hotstuff/signature/block_signer_decoder_test.go
module/epochs.go
module/epochs/epoch_lookup.go

- Ports https://github.com/onflow/flow-go/pull/4063 to `master`
- Adds additional documentation of the issue, and a link to an issue https://github.com/onflow/flow-go/commit/7364a433caa73648f8409f5da6fa7963666a0b2f

Port #4063 to master

---

.github/workflows/test-monitor-flaky.yml
.github/workflows/test-monitor-regular-skipped.yml

The Flaky test monitor processes results and makes them available on a test-by-test basis in Bigquery, however there is not a way to see the full test output.
Here's an example of where this can be useful: https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&var-package=github.com%2Fonflow%2Fflow-go%2Fintegration%2Fdkg&var-dataset_name=dapperlabs-data.production_src_flow_test_metrics&var-skipped_tests_table=skipped_tests&var-test_results_table=test_results&var-query_limit=100000&var-test=TestWithEmulator%2FTestNodesDown&from=1679042550234&to=1679065565932
The test failed, but the output shows an immediate timeout. Did the test itself time out without printing any logs? Did a previous test time out? It's difficult to tell without more context.

Add step to print results of test monitor

---

fvm/state/execution_state.go
fvm/state/execution_state_test.go
fvm/state/transaction_state.go
fvm/state/transaction_state_test.go
fvm/transactionInvoker.go

I'm going to refactor delta view into SpockState and StorageState.  Renaming State to ExecutionState to distinguish the different states.

Rename State to ExecutionState

---

ledger/complete/wal/checkpoint_v6_leaf_reader.go
ledger/complete/wal/checkpoint_v6_test.go

This PR fixes the `OpenAndReadLeafNodesFromCheckpointV6` by letting it take the leaf nodes channel.
This also allow the caller to specify the buffer of the channel

Fix read leaf nodes

---

fvm/fvm.go
fvm/script.go
fvm/state/transaction_state.go
fvm/state/transaction_state_test.go

This also include fixes to script execution (to ensure the returned execution snapshot reflects all changes) and a bunch of renaming within TransactionState

Add FinalizeMainTransaction method to TransactionState

---

cmd/bootstrap/run/execution_state.go

Originally a piece from https://github.com/onflow/flow-go/pull/3736.
GenerateExecutionState is now used in the code. It used to not be for a while.

Remove obsolete comment

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to cadence version [v0.31.5-account-linking-improved-pragma-patch.1](https://github.com/onflow/cadence/releases/tag/v0.31.5-account-linking-improved-pragma-patch.1)

Update cadence version

---

integration/tests/epochs/epoch_join_and_leave_sn_test.go
integration/tests/epochs/suite.go
state/protocol/badger/state.go
state/protocol/badger/state_test.go

Re-enable SN epoch integration test

---

cmd/access/node_builder/access_node_builder.go
cmd/collection/main.go
cmd/consensus/main.go
cmd/execution_builder.go
cmd/observer/node_builder/observer_builder.go
cmd/verification_builder.go
consensus/integration/nodes_test.go
engine/common/follower/integration_test.go
engine/testutil/nodes.go
engine/verification/assigner/blockconsumer/consumer_test.go
engine/verification/utils/unittest/helper.go
follower/follower_builder.go
insecure/wintermute/helpers.go
module/builder/collection/builder_test.go
module/jobqueue/finalized_block_reader_test.go
state/cluster/badger/mutator_test.go
state/protocol/badger/mutator.go
state/protocol/badger/mutator_test.go
state/protocol/util/testing.go

Extracting pieces from https://github.com/onflow/flow-go/pull/3736 so its easier to digest and merge.
This one adds a currently unused log to follower state, to be used in the next PR.

Add logger to FollowerState

---

.github/workflows/bench.yml

I will open an issue to fix this properly. This is just to unblock https://github.com/onflow/flow-go/pull/4126
Issue to fix this properly: https://github.com/onflow/flow-go/issues/4147

Ignore benchstat on forks

---

engine/execution/computation/computer/computer_test.go

This test does not actually test the computer.  The account status was populate into the view during account creation, before the block is executed.

Remove bad test

---

cmd/access/node_builder/access_node_builder.go
integration/testnet/network.go

This modifies the default config for Access nodes to enable execution sync by default.
Operators are advised to add a flag to specify the directory where the data should be stored. e.g.
```
--execution-data-dir=/data/execution_data
```

[Access] Enable execution sync by default

---

cmd/observer/node_builder/observer_builder.go

https://github.com/onflow/flow-go/issues/3040
Previously observer logs and metrics were marked as "access". Changed them to display correctly as "observer".

[Observer] Fixed issue with incorrect observer logs

---

consensus/hotstuff/forks/blockQC.go
consensus/hotstuff/forks/block_builder_test.go
consensus/hotstuff/forks/forks.go
consensus/hotstuff/integration/instance_test.go
consensus/hotstuff/model/block.go
consensus/hotstuff/pacemaker/pacemaker.go
consensus/hotstuff/pacemaker/pacemaker_test.go
consensus/hotstuff/pacemaker/view_tracker.go
consensus/hotstuff/pacemaker/view_tracker_test.go
consensus/participant.go
engine/common/follower/compliance_core.go
engine/common/follower/pending_tree/pending_tree.go
engine/common/follower/pending_tree/pending_tree_test.go
model/flow/block.go

Goal: consensus follower detects finalization one view earlier
* see issue https://github.com/onflow/flow-go/issues/4154 for further context
* this is Part 1, which prepares the PaceMaker (no logical changes, only code cleanups and extensions)
**This PR is a backport (squashed) of PR https://github.com/onflow/flow-go/pull/4155**

[Backport] Step 1 of Follower optimization

---

cmd/bootstrap/cmd/finalize.go
integration/benchnet2/Makefile

This PR tweaks and finalizes the changes to BN2 CI workflows for creating and deleting Benchnet 2 networks.
This PR is made in conjunction with https://github.com/dapperlabs/flow-go/pull/6632
- removed old way of testing new network is accessible 
- removed `make k8s-expose-locally`
- removed `make k8s-test-network-accessibility`
- using new way now (`flow blocks get latest --host access1-<network_id>.benchnet.onflow.org:80`)
ref: https://github.com/dapperlabs/flow-go/pull/6632

[BN2] Update BN2 creation, deletion CI workflows

---

engine/execution/ingestion/stop_control.go

I was trying to extract this change 
https://github.com/onflow/flow-go/pull/3736/files#diff-c495742b9ab8ee8b5b050d102767ba106b2fda1cbf4f1c0a49acee333a118c0fR107 out of this PR https://github.com/onflow/flow-go/pull/3736, but I wasn't quite sure what was going on, so I did some cleaning as well.
- changed some naming
- changed formatting
- added todos to look into in the future
I think they might be related to these tests being disabled:
```
func Test_OnlyHeadOfTheQueueIsExecuted(t *testing.T) {
unittest.SkipUnless(t, unittest.TEST_FLAKY, "To be fixed later")
```
```
func TestBlocksArentExecutedMultipleTimes_multipleBlockEnqueue(t *testing.T) {
unittest.SkipUnless(t, unittest.TEST_TODO, "broken test")
```
I'll take a look at that next.

Cleanup stop control component

---

fvm/state/transaction_state.go
fvm/state/transaction_state_test.go
fvm/transactionInvoker.go

Pause/Resume nested txn was a premature optimization.  Removing pause/resume, and reordering execution back to normal ordering simplify interim read set computation, and removes unnecessary assumptions.

Simplify transaction preprocessing

---

engine/access/access_test.go
engine/common/rpc/convert/convert.go
go.mod
model/flow/service_event.go
model/flow/service_event_test.go
model/flow/version_beacon.go
model/flow/version_beacon_test.go
utils/unittest/fixtures.go

Continuing to dissect this PR https://github.com/onflow/flow-go/pull/3736 into smaller chunks.
This just adds the service event model and tests. 
I changed the equal to tests and some naming and comments from the original in the #3736 PR.

Add version beacon service event model

---

.github/workflows/ci.yml
integration/Makefile
integration/tests/upgrades/stop_at_height_test.go
integration/tests/upgrades/suite.go

Continuing to dissect this PR https://github.com/onflow/flow-go/pull/3736 into smaller chunks.
This one separates out the integration tests for version upgrades.
The version beacon integration tests will be added to this test suite.

Separate integration test for version upgrades

---

README.md
engine/access/state_stream/backend.go
engine/access/state_stream/backend_executiondata_test.go
engine/access/state_stream/engine.go
integration/benchmark/cmd/ci/main.go
integration/benchmark/cmd/manual/main.go
integration/localnet/README.md
module/executiondatasync/execution_data/entity.go
module/mempool/herocache/execution_data.go
module/mempool/herocache/execution_data_test.go
module/mempool/herocache/internal/wrapped_entity.go
module/state_synchronization/requester/execution_data_requester_test.go
module/state_synchronization/requester/jobs/execution_data_reader_test.go
module/state_synchronization/requester/unittest/unittest.go
utils/unittest/fixtures.go

Backports: https://github.com/onflow/flow-go/pull/4197
Also backports https://github.com/onflow/flow-go/pull/4224 since they were merged in the same commit

[Access] Fix execution data cache in state stream - v0.30 backport

---

fvm/state/execution_state.go
fvm/state/spock_state.go
fvm/state/storage_state.go
fvm/state/transaction_state.go
fvm/state/transaction_state_test.go

The interim read set will be used for verification while the transaction is still mid-execution (The finalized execution snapshot's read set will be used for verification prior to commit)

Add InterimReadSet method to transaction state.

---

storage/badger/cleaner.go

Jitter computation casted using wrong units, resulting in running database GC more frequently than desired.

[v0.30] Fix cleaner interval units bug

---

storage/badger/cleaner.go

Jitter computation casted using wrong units, resulting in running database GC more frequently than desired.
(Port of https://github.com/onflow/flow-go/pull/4231 to `master`)

[master] Fix Cleaner Units Bug

---

engine/execution/computation/computer/computer_test.go
fvm/fvm.go
fvm/storage/derived/table.go

Don't commit derived snapshot read transaction's data back to the block.  This is safe since all values are derived from the primary source.
This simplify 2PC between the primary index and the derived indices.
This also fixes a bad test setup which prevented us from committing bootstrap programs previously.

Change derived snapshot read transaction commit behavior

---

consensus/hotstuff/forks/blockQC.go
consensus/hotstuff/forks/block_builder_test.go
consensus/hotstuff/forks/blockcontainer.go
consensus/hotstuff/forks/forks.go
consensus/hotstuff/forks/forks2.go
consensus/hotstuff/forks/forks2_test.go
consensus/hotstuff/forks/forks_test.go
consensus/hotstuff/model/block.go
consensus/hotstuff/model/errors.go
engine/common/follower/compliance_core.go
engine/common/follower/compliance_engine.go
engine/common/follower/pending_tree/pending_tree.go
engine/common/follower/pending_tree/pending_tree_test.go
model/flow/block.go

backport of https://github.com/onflow/flow-go/pull/4190 to v0.30
**changes are identical to https://github.com/onflow/flow-go/pull/4190**

backport of Forks2 to v0.30

---

fvm/environment/facade_env.go
fvm/fvm.go
fvm/storage/derived/derived_block_data.go
fvm/storage/derived/table.go
fvm/storage/derived/table_test.go
fvm/storage/logical/time.go

script are always executed at the end of block

Simplify snapshot read transactions

---

.github/workflows/builds.yml
Makefile
cmd/Dockerfile

This PR adds support for building containers that references private repos using CI. This is most commonly used for security patches, but could also work for forks.

[CI] Enable builds using private repos

---

cmd/bootstrap/cmd/clusters.go
cmd/bootstrap/cmd/constants.go
cmd/bootstrap/cmd/constraints.go

- log a more useful error message if `n_clusters > n_collectors`
- remove unnecessary constraint that clusters must have at least 3 members

Update cluster config constraints

---

integration/go.mod
integration/tests/upgrades/suite.go
integration/tests/upgrades/version_beacon_service_event_test.go

Extracted from https://github.com/onflow/flow-go/pull/3736, and added more cases.
Add integration test to confirm version beacon events are emitted when adding a version boundary.

Add Version Beacon integration test

---

fvm/storage/primary/snapshot_tree.go
fvm/storage/primary/snapshot_tree_test.go
fvm/storage/snapshot_tree.go
fvm/storage/snapshot_tree_test.go

The block database will hold the latest version of the timestamped snapshot tree.  The transactions will hold a rebaseable snapshot tree (and rebase to latest snapshot whenever transaction validate succeed).

Add support data structures for in memory block database.

---

access/handler.go

The emulator does not have a real finalized header cache.  We need to provide a stub implementation instead.

Update access handler to use finalized header cache interface object

---

cmd/util/cmd/epochs/cmd/flags.go
cmd/util/cmd/epochs/cmd/reset.go
cmd/util/cmd/epochs/cmd/reset_test.go

In https://github.com/onflow/flow-core-contracts/pull/365, we removed the payout argument from the resetEpoch transaction and function. Here, we update the CLI tool which generates arguments for this transaction accordingly.

Remove payout flag, arg from resetEpoch cmd

---

engine/collection/compliance/core.go
engine/collection/compliance/core_test.go
engine/consensus/compliance/core.go
engine/consensus/compliance/core_test.go

- Removes unecessary `parent` argument
- Uses `Exists` method rather than retrieving the whole parent header

Compliance Core - clean up extra arg

---

go.mod
model/flow/version_beacon.go
model/flow/version_beacon_test.go

Add version beacon verify function
this was originally added in https://github.com/onflow/flow-go/pull/3736 state/protocol/badger/validity.go but it doesn't really belong there IMO.
I didn't want to use two different libraries for semver so I changed EqualTo to github.com/coreos/go-semver/semver as well

Add version beacon verify function

---

fvm/storage/primary/block_data.go
fvm/storage/primary/block_data_test.go
fvm/storage/snapshot/storage_snapshot.go

BlockData will serve as the block's primary index.  BlockData together with DerivedBlockData (i.e., secondary indices) will form the "complete" block database.
Unlike derived block data, this is a fairly textbook MVCC implementation (the only noteable departure is we don't need to physically copy the read set's values into the scratch space / execution state since the snapshots are immutable LSM trees).

In-memory MVCC block database.

---

engine/collection/compliance/engine_test.go
engine/consensus/compliance/engine_test.go

This PR fixes two flaky unit tests for consensus and cluster consensus compliance engines. This behavior was caused by concurrent writes to unprotected map. I have removed that logic since it isn't needed anymore.

[Tests] Flaky tests for compliance engine

---

fvm/environment/facade_env.go
fvm/environment/unsafe_random_generator.go
fvm/environment/unsafe_random_generator_test.go

Note: since txn index is undefined for scripts, it'll just use 0 as salt by default.
This also fixes the generator to not silently ignore rand gen initialization error.

Add txn index as salt to the random generator seed.

---

CODEOWNERS

In practice, people only update the trace constants.

rm module/trace owner

---

insecure/rpc_inspector/validation_inspector_test.go

This PR fixing flaky `TestGossipSubSpamMitigationIntegration` test. That was failing with the following error: 
```
=== CONT  TestGossipSubSpamMitigationIntegration
unittest.go:223: 
Error Trace:	/home/runner/work/flow-go/flow-go/utils/unittest/unittest.go:223
/home/runner/work/flow-go/flow-go/network/internal/p2pfixtures/fixtures.go:180
/home/runner/work/flow-go/flow-go/network/internal/p2pfixtures/fixtures.go:210
/home/runner/work/flow-go/flow-go/network/p2p/test/fixtures.go:509
/home/runner/work/flow-go/flow-go/network/p2p/test/fixtures.go:517
/home/runner/work/flow-go/flow-go/insecure/rpc_inspector/validation_inspector_test.go:425
Error:      	could not close done channel on time: timeout did not happen on receiving expected pubsub message
Test: …
```

[Fix] Fixes flaky `TestGossipSubSpamMitigationIntegration`

---

fvm/blueprints/scripts/systemChunkTransactionTemplateDualAuthorizer.cdc
fvm/blueprints/system.go

See https://github.com/onflow/flow-go/issues/4291 for details.
I tested that the system transaction work on testnet/mainnet by running the following script:
```cadence
import FlowEpoch from 0x9eca2b38b18b5dfe
import NodeVersionBeacon from 0x8c5303eaa26202d6
pub fun main(): UInt64 {
let serviceAccount = getAuthAccount(0x8c5303eaa26202d6)
let epochAccount = getAuthAccount(0x9eca2b38b18b5dfe)
let epochHeartbeat =
serviceAccount.borrow<&FlowEpoch.Heartbeat>(from: FlowEpoch.heartbeatStoragePath) ??
epochAccount.borrow<&FlowEpoch.Heartbeat>(from: FlowEpoch.heartbeatStoragePath) ??
panic("Could not borrow heartbeat from storage path")
epochHeartbeat.advanceBlock()
let versionBeaconHeartbeat =
serviceAccount.borrow<&NodeVersionBeacon.Heartbeat>(from: NodeVersionBeacon.HeartbeatStoragePath) ?? …
```

Change system transaction to have dual authorizers

---

module/mempool/herocache/backdata/cache.go
network/p2p/p2pbuilder/inspector/rpc_inspector_builder.go

This PR addresses the `panic: runtime error: integer divide by zero` issue encountered in the `TestValidationInspector_ActiveClusterIdsNotSet_Graft_Detection`. The root cause of the problem was an uninitialized value for the `ClusterPrefixedTopicsReceivedCacheSize` attribute in the `validation.ControlMsgValidationInspectorConfig`. As a result, both the `sizeLimit` and the `bucketNum` of the created `HeroCache` would be set to zero. When a new element was added to the cache, a division by `bucketNum` (to identify the corresponding bucket) would occur, causing the test to panic. 
To proactively address this issue, this PR introduces a check for the `bucketNum` of the `HeroCache` during initialization and causes a panic if the `bucketNum` is set to zero. This approach helps identify missing …

Fixes panic on dividing by zero for `TestValidationInspector_ActiveClusterIdsNotSet_Graft_Detection`

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/result_collector.go

Prep work for parallel workers pulling requests off the queue.
This also rename transaction to transactionRequest since the term is overloaded.

Queue transaction requests instead of returning a slice of transaction requests

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
module/metrics.go
module/metrics/execution.go
module/metrics/noop.go
module/mock/execution_metrics.go
module/trace/constants.go

The memory stats is meaningless.  There are too many background goroutines interfering, especially when we execute transactions in parallel.

Remove inaccurate transaction memory usage metric

---

fvm/fvm_bench_test.go

There are a bunch of version beacon failures after the plumbing fixes.  janez will look into those.
```
--- FAIL: BenchmarkRuntimeNFTBatchTransfer
fvm_bench_test.go:695:
Error Trace:	/Users/patricklee/workspace/github.com/onflow/flow-go/fvm/fvm_bench_test.go:695
/Users/patricklee/workspace/github.com/onflow/flow-go/fvm/fvm_bench_test.go:623
Error:      	Should be empty, but was [Error Code: 1101] error caused by: 1 error occurred:
* transaction preprocess failed: [Error Code: 1101] cadence runtime error: Execution failed:
error: cannot find declaration `FlowEpoch` in `9eca2b38b18b5dfe.FlowEpoch`
--> 17bdab0c7ac0959d1a455941c153da68507cd1fd4fce03161eb27c220088adf8:1:7
|
1 | import FlowEpoch from 0x9eca2b38b18b5dfe
|        ^^^^^^^^^ available exported declarations are:
error: cannot find …
```

Fix fvm bench test setup.

---

engine/execution/state/unittest/fixtures.go
model/flow/version_beacon.go
module/state_synchronization/requester/execution_data_requester_test.go
state/errors.go
state/protocol/badger/mutator.go
state/protocol/badger/mutator_test.go
state/protocol/badger/snapshot.go
state/protocol/badger/state.go
state/protocol/badger/state_test.go
state/protocol/badger/validity.go
state/protocol/badger/validity_test.go
state/protocol/inmem/convert.go
state/protocol/inmem/convert_test.go
state/protocol/inmem/encodable.go
state/protocol/inmem/snapshot.go
state/protocol/invalid/snapshot.go
state/protocol/mock/snapshot.go
state/protocol/snapshot.go
storage/badger/operation/version_beacon.go
storage/badger/operation/version_beacon_test.go
storage/badger/version_beacon.go
storage/version_beacon.go
utils/unittest/version_beacon.go

The last part of https://github.com/onflow/flow-go/pull/3736.
This one is a bit bigger as it is harder to split.
Some things that still need addressing (in future PRs):
- we have a few switch cases between service events where the default branch errors and thus a branch is needed for all service events event if it is empty. This is not a good pattern. there should be a single place for validating if the service event is of valid type, so we don't have to put empty cases everywhere else.
- the validation that the version beacon service event is sequential is still missing.

Add version beacon to snapshot

---

engine/execution/computation/manager_benchmark_test.go

We need to check for error before using res

Fix benchmark error check

---

admin/README.md

Command no longer exists - replaced by `set-config`

Remove outdated command from readme

---

cmd/access/node_builder/access_node_builder.go
engine/access/state_stream/backend.go
engine/access/state_stream/backend_events_test.go
engine/access/state_stream/backend_executiondata_test.go
engine/access/state_stream/engine.go
storage/badger/headers.go
storage/headers.go

Closes: https://github.com/onflow/flow-go/issues/4233
When setting up a new stream and the client requested to start from the root block, skip ahead 1 block. This addresses a corner case caused by the fact that the root block has no execution state changes, and thus has no execution data blob.
For the purposes of the streaming API, the root block is one block before whichever block the node operator chose as the execution sync [start height](https://github.com/onflow/flow-go/blob/6aee5ddaabc5ee6bb7edab5e9c0987b270a0bea8/cmd/access/node_builder/access_node_builder.go#L654). By default, this is the `RootBlock`, which is either the `SporkRootBlock` or the `RootBlock` used when starting the node mid-spork.

[Access] Skip root block when streaming from execution data

---

fvm/fvm_bench_test.go

We are not interested in the outcome of the system transaction in these tests.
The system transaction does to the total time, but it should be a really small portion compared to the other transactions in the block.
The last time the Bench tests were working the system transaction was also not included. It was recently added in this [PR](https://github.com/onflow/flow-go/pull/4078)

FVM bench test fix

---

cmd/observer/node_builder/observer_builder.go

Execution sync is currently not support on observers. Remove it for now to avoid churn when making changes to the module. It will be readded in a future PR when support is enabled.

[Observer] Remove unsupported execution sync from observer bootstrap

---

engine/access/rest/events.go
engine/access/rest/events_test.go
engine/access/rest/models/event.go

Closes: https://github.com/onflow/flow-go/issues/4216
When querying for events by block range, if the end height is higher than the latest sealed height on the node, it is reset to the sealed height. This is OK for the grpc endpoints because they return empty `BlockEvents` entries for each block searched, so clients can see which was the last block. The REST API currently returns no results for blocks with no events, so clients have no way to tell what the actual searched range was.
This PR updates the REST api to always return a `BlockEvents` result for blocks searched, even if it has no events. This is makes the behavior consistent with the gRPC version of the API.

[Access] Update REST get events to return empty BlockEvents for blocks with no events

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
ledger/complete/ledger.go
ledger/complete/ledger_test.go

This PR removes the reporting feature for the state extraction util, why?
because:
- The report takes a really long time, and causing it’s hard to tell if the state extraction is completed
- The [post reporting](https://github.com/onflow/flow-go/blob/master/cmd/util/cmd/execution-state-extract/execution_state_extract.go#L109) can be done with a different command line, it just needs to read the checkpoint file again into memory, which is now quite fast.
- The [pre reporting](https://github.com/onflow/flow-go/blob/master/cmd/util/cmd/execution-state-extract/execution_state_extract.go#L101) is currently used printing epoch counter, which we are no longer using during spork, instead we are sending a script querying on an EN to find the latest epoch counter, and using the epoch end view to …

Remove reporting feature from state extraction

---

Makefile

While modifying automation for BN2, the Makefile was unnecessarily updated to pin a docker tag that is being added to our images at build time. This tag is unnecessary and is unneeded. Furthermore, it is causing confusion when executing builds.

Remove pinned docker tag from being created during builds

---

engine/access/rpc/backend/backend_transactions.go

A [change](https://github.com/onflow/flow-go/pull/4263) was added recently to support searching for tx results by block and collection. This had a bug where if transaction was included in a block, but the block had not yet been fully indexed, `GetTransactionResult` would return a `NotFound` error with the message `not found: could not retrieve collection: key not found`. Normally, the api would return a result, but the status would be pending.
This PR update the endpoint to only return `NotFound` in this situation if the request include the blockID or collectionID as search criteria.

[Access] Do not return not found for tx result when collection not indexed

---

Makefile
cmd/Dockerfile
crypto/Makefile
crypto/bls12381_utils.go
insecure/Makefile
integration/Makefile
integration/benchmark/cmd/manual/Dockerfile

BLST library uses ADX instructions to speed up computations. It implements software versions with and without ADX instructions. It uses the ADX version by default, but provides a CGO flag to use the non-ADX version when compiled by Go.
Using the flag is necessary for machines without ADX support. 
So far the crypto lib was using the CGO flag by default to disable ADX. This PR switches the default to use ADX to benefit from the performance speed up. In order for tests and builds to work with older machines (without ADX), all makefiles have been updated to detect ADX support and add the CGO flag accordingly.
- all Makefile detect ADX support and assign a new CGO flag to empty or no-ADX flag. 
- The new CGO flag is used by all Go commands, passed as argument to all Dockerfiles.

[Crypto] enable ADX support by default

---

integration/tests/collection/proposal_test.go

`TestMultiCluster` test has been passing about 95% of the time in the [Flaky Test Monitor](https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&var-package=github.com%2Fonflow%2Fflow-go%2Fintegration%2Ftests%2Fcollection&var-dataset_name=dapperlabs-data.production_src_flow_test_metrics&var-skipped_tests_table=skipped_tests&var-test_results_table=test_results&var-query_limit=100000&var-test=TestMultiCluster&from=now-30d&to=now) and can be unquarantined.

[Testing][CI] Unquarantine TestMultiCluster (integration/tests/collection/proposal_test.go)

---

integration/tests/access/execution_state_sync_test.go

`TestExecutionStateSync has been passing about 98% of the time in the [Flaky Test Monitor](https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&var-package=github.com%2Fonflow%2Fflow-go%2Fintegration%2Ftests%2Faccess&var-dataset_name=dapperlabs-data.production_src_flow_test_metrics&var-skipped_tests_table=skipped_tests&var-test_results_table=test_results&var-query_limit=100000&var-test=TestExecutionStateSync&from=now-30d&to=now) and can be unquarantined.

[Testing][CI] Unquarantine TestExecutionStateSync (integration/tests/access/execution_state_sync_test.go)

---

engine/access/rpc/backend/backend_transactions.go
engine/execution/rpc/engine.go

`GetTransactionResultsByBlockID` was updated to support decoding CCF encoded events from the EN. The encoding version was pulled from the wrong data structure resulting in it being interpreted as cdc-json.

[Access] Fix AN event decoding in GetTransactionResultsByBlockID

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

https://github.com/dapperlabs/cadence-internal/compare/v0.31.6-patch.1...v0.31.6-patch.2

[v0.29] Update to Cadence v0.31.6-patch.2

---

engine/execution/ingestion/engine.go
module/mempool/queue/queue.go
module/mempool/queue/queue_test.go

This PR handles an unexpected case where the internal state can not find the executed block. In this case, we will crash the EN and log the entire internal state for debugging purpose.

[Execution] panic when on executed block error

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

https://github.com/onflow/cadence/pull/2568

Update to Cadence v0.39.9

---

fvm/environment/programs.go
fvm/environment/programs_test.go
fvm/fvm_test.go

When loading a program and the loading fails. We need to pop the dependency stack, but not include the offending program as a dependency further up the stack. This is to avoid having dependencies in the stack that were never loaded into the derived cache.
Usually encountering an error when loading a program would terminate the whole tx/script, but storage iteration is an exception to that. If a program is needed to parse a value from storage during storage iteration, and that program is broken, the iteration will move to the next value in storage instead of terminating.

Dependency tracking on load error

---

cmd/scaffold.go
state/protocol/badger/state.go

There is a bug in the state bootstrapping from an existing protocol db where the latest finalized header is mistakenly cached as the latest sealed header. This broke execution state sync since this header is used to determine the next block to processes on startup.

Fix sealed header cache in state bootstrap

---

cmd/scaffold.go
state/protocol/badger/state.go

There is a bug in the state bootstrapping from an existing protocol db where the latest finalized header is mistakenly cached as the latest sealed header. This broke execution state sync since this header is used to determine the next block to processes on startup.

Fix sealed header cache in state bootstrap - backport

---

integration/localnet/builder/bootstrap.go

This flag was removed from collection node CLI flag list, so remove it from the list of flags added by the localnet bootstrap

[Localnet] Remove unused hotstuff-proposal-time flag from bootstrap

---

Makefile

This PR fixes a CI issue where there were intermittent failures of `verify-mocks` Makefile target in CI that weren't reproducible locally.
The fix is to add `go mod tidy` to put `go.mod`, `go.sum` into a good state before verifying mocks. Otherwise, `verify-mocks` would often show `git diff` differences in `go.sum`.

[CI] fix verify-mocks intermittent CI failure

---

cmd/execution_config.go
engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/execution_verification_test.go
engine/execution/computation/manager.go
engine/execution/computation/manager_benchmark_test.go
engine/execution/computation/manager_test.go
engine/execution/computation/programs_test.go
engine/execution/state/state.go
engine/testutil/nodes.go
engine/verification/utils/unittest/fixture.go
fvm/fvm_bench_test.go
fvm/storage/transaction.go

WARNING: it is currently unsafe to enable concurrent execution because it exposes a cadence type equivalence check issue, which in turn causes non-deterministic execution.
Unsurprisingly, enabling concurrent execution today will slightly slow down block execution since transaction conflict rate is currently 100%.  Transactions access pattern will need to be restructure in order to take advantage of concurrent execution, but it is reassuring from a correctness standpoint to see that conflicting transactions are correctly detected / retried.  (For performance expectations, see "Concurrency Control Performance Modeling: Alternatives and Implications", 1987).
Issue: #3547

Expose computer max concurrency parameter.

---

engine/verification/verifier/engine.go

This PR improves the logging details for chunk faults in `verifier` engine by (1) logging a generic message when such faults are happening and the chunk is not verified (2) adding the chunk fault type. This streamlines the process of spotting the verification failure and sealing halts in tests and production.

[Verification] Improves logging details for chunk faults

---

network/p2p/test/sporking_test.go

This test has been consistently passing in [quarantine](https://dapperlabs.grafana.net/d/toErpbynz/single-test-metrics?orgId=1&var-package=github.com%2Fonflow%2Fflow-go%2Fnetwork%2Fp2p%2Ftest&var-dataset_name=dapperlabs-data.production_src_flow_test_metrics&var-skipped_tests_table=skipped_tests&var-test_results_table=test_results&var-query_limit=100000&var-test=TestCrosstalkPreventionOnNetworkKeyChange&from=now-6M&to=now) for the past 6 months and can be unquarantined.

[Testing][CI] Unquarantine test - TestCrosstalkPreventionOnNetworkKeyChange

---

cmd/execution_builder.go
cmd/execution_config.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/testutil/nodes.go

Add a cli flag to enable a temporary workaround for a networking issue between a small number of ENs and LNs. When enabled, the EN will only request collections from nodes with a `*.onflow.org` hostname.

[Execution] Temporary workaround for LN networking issue

---

network/p2p/middleware/middleware.go
network/p2p/middleware/middleware_test.go

This PR fixes the bug with the chunk data pack max message size when processing a received message from an EN. It also adds a supporting test for it.

[Networking] Fixes the bug with chunk data pack max message size.

---

network/p2p/middleware/middleware.go
network/p2p/middleware/middleware_test.go

https://github.com/onflow/flow-go/pull/4530

Back-porting PR4530:  Fixes the bug with chunk data pack max message size

---

engine/access/rpc/backend/backend_transactions.go

These were fixed in v0.31 here:
https://github.com/onflow/flow-go/pull/4462
https://github.com/onflow/flow-go/pull/4465
Execution nodes now use CCF encoding for events returned from their grpc API. They include a new version parameter to specify which encoding was used for the returned events. For `GetTransactionResultsByBlockID`, the encoding is returned in the top level `GetTransactionResultsResponse` message, not in each of the included `GetTransactionResultResponse` messages.
There was a bug on the Access node where it attempted to get the encoding from each `GetTransactionResultResponse`. When not specified, the default value is json-cdc, so the payload was not converted.
Note: not including the change to write the encoding version for every results on the EN side. That's unnecessary

[Access] Fix CCF decoding in GetTransactionResultsByBlockID

---

engine/access/state_stream/handler.go
engine/access/state_stream/handler_test.go
engine/common/rpc/convert/convert.go
engine/common/rpc/convert/convert_test.go
utils/unittest/generator/events.go

Fix the State Stream API to return JSON-CDC encoded events like the rest of the AccessAPI.
A more robust change will be included on master that includes options to override the version for an individual AN

[Access] Update state stream API to return json-cdc encoded events

---

model/convert/service_event.go
utils/unittest/service_events_fixtures.go

"%d.%d.%d%s" should have been "%d.%d.%d-%s". but to make it cleaner I used the semver.VersionObject

Fix Version Beacon event conversion

---

engine/access/state_stream/engine.go

Backports: https://github.com/onflow/flow-go/pull/4540
Currently, the state streaming API only records unary grpc metrics. This PR adds support for collecting streaming grpc metrics as well.

[Access] Add grpc streaming metrics - v0.31 backport

---

engine/access/state_stream/engine.go

Currently, the state streaming API only records unary grpc metrics. This PR adds support for collecting streaming grpc metrics as well.

[Access] Add grpc streaming metrics

---

engine/execution/ingestion/uploader/model.go
engine/execution/ingestion/uploader/model_test.go

Closes https://github.com/onflow/flow-go/issues/4558
Previously, only last event is included in uploaded block data (repeated n times).
This PR fixes the bug and includes all events.

Fix missing events in block data uploaded to GCP

---

cmd/access/node_builder/access_node_builder.go
engine/access/rest/middleware/metrics.go
engine/access/rest/router.go
engine/access/rest/router_test.go
module/metrics.go
module/metrics/access.go
module/metrics/labels.go
module/metrics/namespaces.go
module/metrics/rest_api.go
module/mock/access_metrics.go
module/mock/rest_metrics.go

Backports: 
* https://github.com/onflow/flow-go/pull/4452
* https://github.com/onflow/flow-go/pull/4571
This PR backports 2 fixes for issues with REST metrics that resulted in performance issues on the prometheus node. It normalizes the request URL to route names instead of full URLs which contained request specific information (like blockIDs)

[Access] Fix issues with REST Metrics - v0.31 backport

---

.gitignore
engine/execution/computation/computer/computer_test.go

The problem is that EpochCommit event is of nondeterministic byte size. This is because of the changes to the random.

Make tests less flaky

---

.github/workflows/ci.yml
.github/workflows/semver-tags.yaml
cmd/bootstrap/transit/cmd/utils.go
cmd/build/version.go
cmd/build/version_test.go
cmd/execution_builder.go
cmd/scaffold.go
cmd/util/cmd/execution-state-extract/export_report.json
engine/access/access_test.go
engine/access/rest/routes/node_version_info_test.go
engine/access/rpc/backend/backend.go
engine/access/rpc/backend/backend_network.go
engine/testutil/nodes.go
integration/localnet/builder/bootstrap.go

closes: https://github.com/onflow/flow-go/issues/4414 
This PR makes it mandatory that the git tags pushed to this repository are in semver format, with an optinal "(.+\/)*v" prefix. meaning that these are all valid: crypto/v0.24.5-fvm, tools/flaky_test_monitor/v0.23.5, v0.23.5, 0.23.5-fvm
Changes:
- CI that checks the tag on git push. This doesn't prevent pushing or using incorrect tags, but it does notify the user (through a failed github action) that something isn't ok
- Nodes will fail to startup if they have a version that cannot be parsed (is a semver with an optional "v" prefix)
- integration tests CI have git clone with `fetch-depth: 0` this is so that all tags are fetched, so that the version is detected correctly.
- some renaming to make the code clearer.

Git tag validation

---

engine/common/rpc/convert/execution_data.go
engine/common/rpc/convert/execution_data_test.go
utils/unittest/fixtures.go

There was a bug in the logic that converts `ledger.TrieUpdate` objects to their protobuf form. The iteration did not properly handle memory reuse by the for loop, resulting the the output containing copies of the last element only.
This PR updates this logic to use the correct element, and improves tests to cover this case.
The previous tests only use a single path in the `TrieUpdate`, so this case was never exercised.

[Access] Fix slice iteration bug in TrieUpdate protobuf conversion

---

fvm/environment/random_generator.go

This PR enables cadence's `unsafeRandom` for script execution instead of erroring. This allows scripts not to panic although the returned random value is not equal to the value returned when run as a transaction.
This behaviour is clarified in https://github.com/onflow/flips/pull/120 (https://github.com/onflow/flips/pull/120/commits/051c82b8c3fbf959908ee401eaff00e2d8b7418f)

[FVM] enable unsafe Random for script execution

---

utils/grpcutils/grpc.go

Closes: #4596
The amount of data returned from some Access API requests has increased over time, resulting in response size errors on Access and Execution nodes. While the max message size is configurable via CLI flags, this PR updates the default to be well above the current largest messages.

[Access] Update default grpc max message size to 1GiB

---

utils/grpcutils/grpc.go

Backports: https://github.com/onflow/flow-go/pull/4609

[Access] Update default max message size to 1GiB - v0.31 backport

---

.github/workflows/builds.yml
.github/workflows/tools.yml

This makes it easier to see what the original input settings were if you need to rerun the job

[CI] Print builds and tools job inputs

---

network/p2p/middleware/middleware.go

I ran into an issue on benchnet where chunk data packs exceeded 10MB, resulting in ENs failing to send responses.
There was a previous change that fixed this issue on the receiving side: https://github.com/onflow/flow-go/pull/4530. This uses a different [code path](https://github.com/onflow/flow-go/blob/master/network/p2p/middleware/middleware.go#L647-L647), and the `messageType` field includes a `*`.
On the sending side, the [code path](https://github.com/onflow/flow-go/blob/master/network/p2p/middleware/middleware.go#L369-L369) explicitly removes the `*`:
https://github.com/onflow/flow-go/blob/cc67154583f10942b7990bd91d5516069fec4517/network/message_scope.go#L199-L201
This PR adds a tactical fix to accept either format, but we should also revisit this logic to make it more consistent.

[Network] Fix chunk datapack size and timeout limits

---

.github/workflows/tools.yml

Add a summary to the the tools build workflow so that the user explicitly knows where the objects were uploaded.
Please reference the following workflow execution as an example of how the summary is generated at the end. https://github.com/onflow/flow-go/actions/runs/4622665760

Update workflow to add summary for GCS location for tools

---

network/alsp/manager/manager_test.go
network/internal/testutils/testUtil.go
network/test/blob_service_test.go
network/test/echoengine_test.go
network/test/epochtransition_test.go
network/test/meshengine_test.go
network/test/middleware_test.go
network/test/unicast_authorization_test.go

This pull request represents an improvement in handling spork ID creation within individual tests, moving away from a shared package-level variable. The change addresses several issues that were identified in our previous approach.
1. **Encapsulation**: By relocating the spork ID creation logic to individual tests, we achieve better encapsulation. Previously, the caller was unaware that a spork ID was being created internally, which could lead to confusion and errors if a new spork ID was mistakenly created elsewhere.
2. **Modifiability**: Since the spork ID was a package-level variable, it was susceptible to unnoticed changes, leading to debugging challenges. By managing spork IDs at the test level, we reduce the potential for unexpected modifications.
3. **Flexibility**: The previous …

[Networking] Relocate the logic for creating the spork ID within the test code

---

cmd/execution_builder.go
engine/execution/state/state.go
storage/badger/chunkDataPacks.go
storage/badger/chunk_data_pack_test.go
storage/chunkDataPacks.go
storage/mock/chunk_data_packs.go

Backport [the fix](https://github.com/onflow/flow-go/pull/4618/files) to v0.31
- Close the chunk data pack database during shutdown 
- Rollback stored chunk data packs when fail to store execution result

v0.31 handle chunk data pack database close

---

cmd/execution_builder.go
cmd/execution_config.go
cmd/util/cmd/truncate-database/cmd.go
engine/execution/state/state.go
integration/localnet/builder/bootstrap.go
integration/testnet/network.go
module/mempool/queue/queue_test.go
storage/badger/chunkDataPacks.go
storage/badger/chunk_data_pack_test.go
storage/chunkDataPacks.go
storage/mock/chunk_data_packs.go

- Change chunk data pack to be stored in a separate badger database, so that it can be pruned to reduce disk space usage.
Tested works on canary.

store chunk data pack in a separate database

---

module/mempool/queue/queue.go
module/mempool/queue/queue_test.go

A slight change to the string function to remove the previously seen flakey behaviour, + add levels to the children printed

Change queue.String() to iterate through children

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to
- cadence [v0.41.0-stable-cadence.1](https://github.com/onflow/cadence/releases/tag/v0.41.0-stable-cadence.1)
- flow-go-sdk [v0.44.0-stable-cadence.1](https://github.com/onflow/flow-go-sdk/releases/tag/v0.44.0-stable-cadence.1)

Update cadence version to v0.41.0-stable-cadence.1

---

.github/workflows/ci.yml
crypto/Makefile
crypto/bls12381_utils.c
crypto/bls12381_utils.go
crypto/bls12381_utils.h
crypto/blst_src/README.md
crypto/blst_src/blst_src.c

- add C code sanitizers Makefile targets:
- memory sanitizer `msan` (only works on Linux and with clang)
- address sanitizer `asan` (only works on Linux)
- other sanitizers (only work on Linux)
- add sanitizers (but `msan`) to a CI job and they are required to pass for new PRs
- `msan` has many false positive errors from `use-of-unitialized-value`. These errors have been debugged one by one to make sure no uninitialized memory has been read. 
- `NO_MSAN` macro has been added during debugging to disable `msan` in functions. The macro was left in the code for future debugging. It is only defined when compiling with defined `MSAN` (look at the `c-msan` target in Makefile).
Side changes:
- Update `./bls_src/README` with instructions of updating BLST version.
- clean up non used Fermat modular …

[Crypto] C code sanitization

---

fvm/environment/facade_env.go

This is mainly to unblock certain downstream dependencies, until the concrete implementation.
The relevant build errors are the following:
```bash
../../flow-go/fvm/environment/facade_env.go:15:21: cannot use &facadeEnvironment{} (value of type *facadeEnvironment) as Environment value in variable declaration: *facadeEnvironment does not implement Environment (missing method ReadRandom)
../../flow-go/fvm/environment/facade_env.go:142:29: cannot use env (variable of type *facadeEnvironment) as Environment value in argument to env.Runtime.SetEnvironment: *facadeEnvironment does not implement Environment (missing method ReadRandom)
../../flow-go/fvm/environment/facade_env.go:227:3: cannot use env (variable of type *facadeEnvironment) as Environment value in argument to NewAccountKeyUpdater: …
```

Add a NO-OP implementation of `ReadRandom` on `facadeEnvironment`

---

engine/common/rpc/convert/execution_data.go
engine/common/rpc/convert/execution_data_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
utils/unittest/fixtures.go

Closes: https://github.com/onflow/flow-go/issues/4707
Uses protobuf changes from https://github.com/onflow/flow/pull/1382
Updates rpc message converters to handle `ChunkExecutionData` with `TransactionResults`

[State Sync] Update ExecutionData rpc converters with tx results

---

.github/workflows/builds.yml
.github/workflows/cd.yml
.github/workflows/tools.yml

This PR updates the docker login approach to better support the new credential format. It switches from the docker-login gha helper to authenticate with gcloud. The docker helper doesn't seem to correctly support the new format.
Test runs
* Builder: https://github.com/onflow/flow-go/actions/runs/6227541426/job/16902395485
* Tools: https://github.com/onflow/flow-go/actions/runs/6253436703
* CD: https://github.com/onflow/flow-go/actions/runs/6253423667/job/16978801212

[CI] Update the workflows to use new auth

---

module/executiondatasync/execution_data/internal/execution_data_versions.go
module/executiondatasync/execution_data/serializer.go
module/executiondatasync/execution_data/serializer_test.go
module/executiondatasync/provider/provider_test.go

Closes: https://github.com/onflow/flow-go/issues/4708
Serialized execution data blobs include a header byte that's used by the serializer to determine how to deserialize its contents. Each unique format should have a different version to simplify version management by consumers.
`ChunkExecutionData` was recently updated (https://github.com/onflow/flow-go/pull/4699) to include transaction results. This changed the format, so we need to also update the header byte.
This PR also adds unittests to the serializer to confirm the previous version can be deserialized into the new format. It is not required that the flow-go codebase maintains backwards compatibility, but it's helpful to understand how it will impact clients.

[State Sync] Update chunk execution data serializer header version

---

fvm/flex/flex_test.go
fvm/flex/handler_test.go
fvm/flex/stdlib/emulator/flex.gen.go
fvm/flex/stdlib/emulator/flex.go
fvm/flex/stdlib/flex.cdc
fvm/flex/stdlib/flex.go
fvm/flex/stdlib/flex_test.go
fvm/transactionInvoker.go

Extend the type definition with e.g. `FlowOwnedAccount`.
The type definition relies on `FlowToken.Vault`. As the type definition depends on environment, generate the type definitions into an environment-specific package. Start with the emulator environment.

Flex: Refactor and extend generated type definition

---

module/state_synchronization/indexer/indexer_core.go
module/state_synchronization/indexer/indexer_core_test.go
module/state_synchronization/indexer/indexer_test.go
storage/badger/batch.go
utils/unittest/fixtures.go

Closes: https://github.com/onflow/flow-go/issues/4739, https://github.com/onflow/flow-go/issues/4674
This PR adds support for indexing `flow.LightTransactionResults` and `flow.Events` from ExecutionData as part of the data indexing.

[Access] Index tx results and events

---

storage/pebble/bootstrap.go

The `indexing batch of leaf nodes` message is very noisy and generally not needed.

[Access] Adjust logging in checkpoint loading

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to [Cadence v0.39.16](https://github.com/onflow/cadence/releases/tag/v0.39.16)

Update to Cadence v0.39.16

---

module/metrics/collection.go
module/metrics/compliance.go

The proposer label makes the metric very high-cardinality, meaning it consumes a lot of Grafana resources to deal with (~2-3% of total series on Grafana). We do not use this label any more, and having it makes for more complex queries over this metric than necessary. For example, we should be able to replace
```
avg by (role) (sum by (num) (rate(consensus_compliance_finalized_blocks_total{role="consensus",network="$network"}[2m])))
```
with 
```
avg(rate(consensus_compliance_finalized_blocks_total{role="consensus",network="$network"}[2m]))
```
We make the same change to the corresponding collection node metric.

Remove proposer label from `block_height` metrics

---

engine/access/state_stream/handler.go
engine/access/state_stream/handler_test.go
engine/common/rpc/convert/events.go
engine/common/rpc/convert/execution_data.go
engine/common/rpc/convert/execution_data_test.go
utils/unittest/generator/events.go

Closes: https://github.com/onflow/flow-go/issues/4504
Backports https://github.com/onflow/flow-go/pull/4533
Updates `ExecutionDataAPI` to use json-cdc event encoding.

[Access] Update state stream API to return json-cdc encoded events - backport master

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v0.41.10](https://github.com/onflow/flow-go-sdk/releases/tag/v0.41.10)
- [onflow/cadence v0.42.0](https://github.com/onflow/cadence/releases/tag/v0.42.0)

Auto update to onflow/cadence v0.42.0

---

Makefile
scripts/update-cadence.sh
scripts/update-core-contracts.sh

Wanted to add/change some makefile commands to make it more convenient to upgrade dependencies.
1. Added `make tidy` to update-core-contracts, since that is the required next step anyway
2. Added another script to update cadence version in all `flow-go` `go.mod` files

Tiny QoL makefile update for updating dependencies

---

ledger/complete/mtrie/flattener/encoding.go
ledger/complete/wal/checkpoint_v6_reader.go
ledger/complete/wal/checkpoint_v6_test.go

This PR adds a `ReadTriesRootHash` function under `github.com/onflow/flow-go/ledger/complete/wal/` to read root hash of the tries from a V6 checkpoint file

read trie root hash from checkpoint

---

ledger/complete/wal/checkpoint_v6_reader.go
ledger/complete/wal/checkpoint_v6_writer.go

This PR extracts a withFile function to be used for handling file opening and closing when reading checkpoint files.

Refactor checkpoint reader with WithFile

---

engine/access/state_stream/engine.go
engine/access/state_stream/handler.go
engine/access/state_stream/handler_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Here are the related protobuf changes: https://github.com/onflow/flow/pull/1353
Update the `ExecutionDataAPI` to use its own namespace

[Access] update execution data protobuf to new namespace

---

module/jobqueue/component_consumer.go
module/jobqueue/component_consumer_test.go
module/jobqueue/consumer.go
module/jobqueue/consumer_test.go

Closes: https://github.com/onflow/flow-go/issues/4839
Fixes a race condition that can occur while starting up a jobqueue consumer with the following changes:
* Ignore calls to `JobConsumer.Check()` before `Start` is called. This prevents the dangerous situation that can cause the `processedIndex` value to be reset.
* Refactor `ComponentConsumer`'s startup to ensure that the processing loop is run after the component starts up.
* Add tests covering the race condition for both cases.

[Access] Fix race condition in jobqueue

---

model/flow/mapfunc/identity.go
model/flow/protocol_state.go
model/flow/protocol_state_test.go
state/protocol/inmem/convert.go
state/protocol/protocol_state/updater.go
state/protocol/protocol_state/updater_test.go
storage/badger/protocol_state.go
storage/badger/protocol_state_test.go
utils/unittest/fixtures.go

Summary of central changes:
* `model/flow/protocol_state.go`:
- revised goDoc of protocol state implementation
- changed `ProtocolStateEntry.PreviousEpoch` to pointer (consistent with `ProtocolStateEntry.NextEpoch`)
- There should be no significant algorithmic changes. Though, I have switched the order of the if and else branches when processing an Epoch Setup event. For me, this is much more in line with the intuitive order of documentation.
* `state/protocol/protocol_state/updater.go`:
- notable updates and revisions of goDoc
- tried to address concerns around inconsistent handling of invariances
- updated code to work with `ProtocolStateEntry.PreviousEpoch` being potentially a nil pointer
* `storage/badger/protocol_state_test.go`:
- detailed goDoc revisions for test …

suggestions for PR #4834

---

cmd/access/node_builder/access_node_builder.go
cmd/verification_builder.go
engine/testutil/nodes.go
engine/verification/assigner/blockconsumer/consumer.go
engine/verification/fetcher/chunkconsumer/consumer.go
engine/verification/fetcher/chunkconsumer/consumer_test.go
module/jobqueue.go
module/jobqueue/component_consumer.go
module/jobqueue/component_consumer_test.go
module/jobqueue/consumer.go
module/jobqueue/consumer_behavior_test.go
module/jobqueue/consumer_test.go
module/mock/job_consumer.go
module/state_synchronization/indexer/indexer.go
module/state_synchronization/indexer/indexer_test.go
module/state_synchronization/requester/execution_data_requester.go
module/state_synchronization/requester/execution_data_requester_test.go

This PR moves the default index from Start method to constructor in order to prevent from a wrong default index being used before the Start method is called.

[JobQueue] Move the DefaultIndex from Start method to constructor

---

fvm/runtime/reusable_cadence_runtime.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v0.41.12](https://github.com/onflow/flow-go-sdk/releases/tag/v0.41.12)
- [onflow/cadence v0.42.1](https://github.com/onflow/cadence/releases/tag/v0.42.1)

Auto update to onflow/cadence v0.42.1

---

cmd/scaffold.go
cmd/scaffold_test.go
engine/common/rpc/errors.go
insecure/corruptlibp2p/libp2p_node_factory.go
module/metrics/libp2p_resource_manager.go
network/p2p/dht/dht_test.go
network/p2p/p2pbuilder/gossipsub/gossipSubBuilder.go
network/p2p/p2pbuilder/libp2pNodeBuilder.go
network/p2p/p2pnode/libp2pNode.go
network/p2p/test/fixtures.go

Adaptively builds the logic of isolating DHT capability within ANs and ENs for `mainnet23` (v0.31).
The reference PR is https://github.com/onflow/flow-go/pull/4800 but note that the changes have been adapted to v0.31 and not backported fully.

[Networking] Isolates DHT capability within ANs and ENs

---

network/p2p/pubsub.go

Partial backport of https://github.com/onflow/flow-go/pull/4790 (easing peer scoring warning-state log conditions).

[Networking] Partial backport of 4790 (easing peer scoring warning-state log conditions)

---

cmd/access/node_builder/access_node_builder.go
engine/access/access_test.go
engine/access/ingestion/engine.go
engine/access/ingestion/engine_test.go
engine/common/rpc/errors.go

This PR adds support for indexing collections from local execution data when a node falls behind on indexing.
It's enabled with the following flag `--execution-data-collection-catchup-enabled=true`
It requires that execution data sync is enabled (on by default)

[Access] Index collections from execution data when behind

---

engine/execution/state/bootstrap/bootstrap_test.go
fvm/environment/uuids.go
fvm/environment/uuids_test.go
utils/unittest/execution_state.go

This is so that the uuid fits into a smaller type. 
This is a temporary fix intended to give the community more time to migrate.
more discussion here: https://discord.com/channels/613813861610684416/1162086721471647874/1166809690936709181
**do not merge to master** this is only a v0.32 change

Switch to always using the 0th partition for UUID generation

---

cmd/util/cmd/truncate-database/cmd.go

The chunk data pack was split into a separate badger DB, it's only needed for execution node, however, when the node operator for non-execution node was using the truncate-database cmd for truncating the protocol badger DB, it was asked for specifying the chunk-data-pack-dir. 
This PR changes so that the chunk data pack dir is optional, and it only truncates the chunk data pack directory if the flag is specified.

[Util] make chunk-data-pack-dir optional for non-execution node

---

cmd/execution_config.go
cmd/node_builder.go

As we are introducing new configs (such as chunk-data-pack-dir), these configs become required. This introduces extra works for node operations who now have to add the extra flag. However, we do have a default value for the new configs, but the default value is designed for local laptop. 
So this PR changes the default config values for docker containers, as the node operators are mostly running the software as containers. SO that node operators do not have to explicitly add flags for them.

[Node operation improvement] Make path configs to be usable by container by default

---

integration/tests/access/access_api_test.go

Add wait wrappers for integration tests so the index gets synced, this is because the index will fall behind a bit compared to latest sealed height found in protocol state storage.

[Access] Add wait in integration tests for index to be synced

---

engine/execution/computation/query/executor.go
engine/execution/rpc/engine.go
module/execution/scripts.go
module/execution/scripts_test.go

Closes: https://github.com/onflow/flow-go/issues/4881
Changing how errors are being handled to preserve the code that is needed.

[Access] Script execution coded errors

---

module/execution/scripts.go
module/execution/scripts_test.go
module/state_synchronization/indexer/indexer.go

Closes: https://github.com/onflow/flow-go/issues/4880
Support calls for get blocks as part of the script execution.

[Access] Allow get blocks script calls 

---

insecure/integration/functional/test/gossipsub/scoring/ihave_spam_test.go

This PR removes t.Parallel from the following tests TestGossipSubIHaveBrokenPromises_Above_Threshold
and TestGossipSubIHaveBrokenPromises_Below_Threshold .

Remove t.Parallel from GossipsubScoring tests

---

cmd/access/node_builder/access_node_builder.go
storage/pebble/bootstrap.go
storage/pebble/bootstrap_test.go
storage/pebble/constants.go

EN and AN have different machine resource, EN could use higher worker counter than AN, so I'm making it configurable. 
It allows us to benchmark the checkpoint importing speed with different worker count.

[Storehouse Bootstrap] make worker count as option for indexing checkpoint

---

config/default-config.yml
network/p2p/p2pbuilder/libp2pscaler_test.go
network/p2p/p2pbuilder/utils.go

This PR slightly refactors applying the limit on inbound connections. With changes in this PR, the limit is only applied when the corresponding flag is set. Otherwise, the libp2p default limit is applied.

[Networking, 0.32] Refactors inbound connection limit application

---

access/handler.go
engine/access/rpc/backend/backend_scripts.go

Closes: https://github.com/onflow/flow-go/issues/4919
Closes: https://github.com/onflow/flow-go/issues/4918
This PR includes 3 fixes:
1. Add validation for address to `GetAccount`. This was missing from this endpoint, but existed for other `GetAccount*` endpoints.
2. Improve error comparison for semantically identical script execution errors
3. Return `InvalidArgument` errors from AccessAPI handler when request contained invalid `flow.Identifier`

[Access] Improve logging and validation in local script exec

---

engine/execution/rpc/engine.go
engine/execution/rpc/engine_test.go
engine/execution/scripts/engine.go

Closes: https://github.com/onflow/flow-go/issues/4916
Currently, when an Access node calls `GetAccount*` with a block that is no longer in the EN's trie, it returns `codes.Internal`. This PR adds a sentinel and updates the handler to instead return `codes.OutOfRange`.
This will ensure that the new grpc circuit breaker available on ANs does not incorrectly classify these responses.

[Execution] Return OutOfRange instead of Internal when account block is not cached

---

engine/access/rest/request/address.go
engine/access/rest/request/address_test.go
engine/access/rest/request/get_account.go
engine/access/rest/request/get_account_key.go
engine/access/rest/request/get_account_key_test.go
engine/access/rest/request/get_account_test.go
engine/access/rest/request/proposal_key.go
engine/access/rest/request/signature_test.go
engine/access/rest/request/signatures.go
engine/access/rest/request/transaction.go
engine/common/rpc/convert/validate.go

Closes: https://github.com/onflow/flow-go/issues/4928
Add check in REST API when parsing addresses that the address is both well formed hex and valid for the network the node is running on.

[Access] Validate addresses match network in rest api

---

engine/access/rpc/backend/backend_scripts.go

This PR improves the log messages emitted when comparing script exec between ANs and ENs.
* Add duration
* Add script args
* Improve error message comparisons to handle different levels of message truncation

[Access] Improve script exec compare logging

---

module/metrics/unicast_manager.go

This PR fixes two metrics that lack an initialization on the unicast manager.

[Networking] Fixing nil dereferencing due to missing metrics initialization

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update cadence to [v0.42.4](https://github.com/onflow/cadence/releases/tag/v0.42.4)

[v0.32] Update cadence to v0.42.4

---

engine/access/rest/routes/subscribe_events_test.go
engine/access/rest/routes/websocket_handler.go

Closes: https://github.com/onflow/flow-go/issues/4952
This PR updates the websockets `Origin` header handling to allow any origin. The default behavior requires that either the `Origin` header is not set, or that it matches the host's hostname. This is inconsistent with the REST API, and breaks websockets for browser based clients unless the AN's hostname matches the URL.

[Access] Allow all origins by default on websockets connections

---

ledger/common/convert/convert_test.go
model/flow/ledger.go
model/flow/ledger_test.go
storage/pebble/registers_test.go

Closes: https://github.com/onflow/flow-go/issues/4938
This PR adds special handling for global register keys, which have empty owner strings. Previously, the empty string was converted to an address, resulting in `NewRegisterID` converting it to `0000000000000000`. With this change, these global registerIDs remain an empty string.
This caused problems on Access nodes when indexing `TrieUpdates` data from checkpoints or execution data. Instead of preserving the empty string, registers were written to the db using an empty address. This caused `uuid` lookups to fail.

[Ledger] Add special handling for global register keys

---

ledger/common/convert/convert.go
ledger/common/convert/convert_test.go

Add a PayloadToRegister convert function for storehouse.
Working towards https://github.com/onflow/flow-go/issues/4682
Depend on https://github.com/onflow/flow-go/pull/4942

[Storehouse] add PayloadToRegister

---

engine/access/rpc/backend/backend.go
integration/tests/epochs/cohort2/epoch_join_and_leave_vn_test.go
integration/tests/epochs/suite.go
integration/tests/lib/util.go

This PR modifies the block rate in the Verification Node test to address sealing lagging finalization. In the VN epoch integration test only, we enable `require-seals-for-approvals`, which requires VN participation in sealing. In practice, this results in sealing lagging finalization (see [here](https://www.notion.so/dapperlabs/VN-Epoch-Test-Flakey-Nov-8-2023-175c8ed3d2dd421b9d03ef49c8be9902?pvs=4) for some tests) by up to 100 blocks.
- This over-ran the default snapshot history limit, preventing the test from validating state
- This also causes epoch transition failures, because DKG requires somewhat up-to-date sealing w.r.t. the DKG phase length, which is small in these tests.
To fix the problem, I increased the block rate delay for consensus nodes, from 100ms to 250 ms. This PR also …

[Flaky Test] Modifies block rate in VN test to address sealing lagging finalization

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to Cadence [v0.42.5](https://github.com/onflow/cadence/releases/tag/v0.42.5)

Update cadence to v0.42.5

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to Cadence [v0.42.5](https://github.com/onflow/cadence/releases/tag/v0.42.5)

[v0.32] Update cadence to v0.42.5

---

network/p2p/inspector/validation/control_message_validation_inspector.go

Fixes inspector logs for async errors.

[Networking] Update RPC inspector error log

---

engine/execution/storehouse.go
module/finalizedreader/finalizedreader.go
module/finalizedreader/finalizedreader_test.go

Working towards https://github.com/onflow/flow-go/issues/4682
Finalized Reader is needed by storehouse to check whether an executed block is finalized in which case it will index the register updates in storehouse.

[Storehouse] Add Finalized Reader

---

cmd/consensus/main.go
consensus/hotstuff/notifications/telemetry.go

Metrika [messaged us via slack](https://dapperlabs.slack.com/archives/C01FNL8769W/p1700002569454369?thread_ts=1699972061.491989&cid=C01FNL8769W
) saying that there is some lack of data in Mainnet 24: 
> none of the consensus nodes have the “proposer” label anymore?
Digging into the current telemetry events, I found that starting in Mainnet 24, the [`TelemetryConsumer`](https://github.com/onflow/flow-go/blob/master/consensus/hotstuff/notifications/telemetry.go) captures
* none of the events emitted via the [`FinalizationConsumer`](https://github.com/onflow/flow-go/blob/ccb723f7cbb3658f0b705cacddfeae28bfb1f9e2/consensus/hotstuff/consumer.go#L99-L113)
* none of the events emitted via the  [`CommunicatorConsumer`](https://github.com/onflow/flow-go/blob/ccb723f7cbb3658f0b705cacddfeae28bfb1f9e2/ …

Missing consensus telemetry events from `FinalizationConsumer` and `CommunicatorConsumer`

---

engine/execution/storehouse.go
engine/execution/storehouse/register_engine.go
engine/execution/storehouse/register_store.go
engine/execution/storehouse/register_store_test.go
engine/execution/storehouse/storehouse_test.go

This PR implements the RegisterStore. 
https://github.com/onflow/flow-go/issues/4659

[Storehouse] Implement Register store

---

engine/execution/storehouse.go
engine/execution/storehouse/executing_block_snapshot.go
engine/execution/storehouse/executing_block_snapshot_test.go
utils/unittest/fixtures.go

Working towards https://github.com/onflow/flow-go/issues/4682
Close https://github.com/onflow/flow-go/issues/4996

[Storehouse] Add Extending block snapshot

---

model/flow/constants.go
module/metrics/execution.go

Port of https://github.com/onflow/flow-go/pull/4615
This just adds additional metrics. It is ok to deploy wit a rolling deploy.

Add transaction ms per computation metrics - port

---

engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/backend_scripts_test.go
fvm/errors/codes.go

Closes: https://github.com/onflow/flow-go/issues/5030
Explicitly handle FVM errors for context cancelation and timeouts, and return the appropriate errors to the client.

[Access] Handle script canceled and timeout errors

---

cmd/access/node_builder/access_node_builder.go
cmd/execution_config.go
engine/execution/computation/query/executor.go
module/execution/scripts.go
module/execution/scripts_test.go

Closes: https://github.com/onflow/flow-go/issues/4776
This PR makes script execution options configurable by a node operator, including:
* Execution timeout
* Computation limit
* Error message size limit
* Log time threshold

[Access] Make script exec configurable

---

access/handler.go
engine/access/apiproxy/access_api_proxy.go
engine/access/mock/access_api_client.go
engine/access/mock/access_api_server.go
engine/access/mock/execution_api_client.go
engine/access/mock/execution_api_server.go
engine/execution/rpc/engine.go
engine/execution/rpc/engine_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

https://github.com/onflow/flow-go/issues/4754
In this pull request are Introduced new endpoints on the Execution node grpc API, that return transaction result error messages.
Related PR:
https://github.com/onflow/flow/pull/1398

[Access] Add endpoints to Execution nodes to support getting Transaction Result error messages

---

engine/execution/checker/engine.go
engine/execution/execution_test.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/execution/ingestion/loader/unexecuted_loader.go
engine/execution/ingestion/loader/unexecuted_loader_test.go
engine/execution/ingestion/stop/stop_control.go
engine/execution/ingestion/stop/stop_control_test.go
engine/execution/state/mock/execution_state.go
engine/execution/state/mock/read_only_execution_state.go
engine/execution/state/mock/script_execution_state.go
engine/execution/state/state.go

Working towards #4998 
This PR moves the IsBlockExecuted to execution state struct, so that we can provide different implementation for ledger-based storage or storehouse-based storage.

[Storehouse] Execution State - Update IsBlockExecuted

---

engine/access/rpc/connection/cache.go

Access nodes crashed with the following stack trace after the HCU on devnet:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d8aec6]
goroutine 16851798 [running]:
go.uber.org/atomic.(*Bool).CompareAndSwap(...)
/go/pkg/mod/go.uber.org/atomic@v1.11.0/bool.go:66
github.com/onflow/flow-go/engine/access/rpc/connection.(*CachedClient).Close(0xc09bfd5080?)
/app/engine/access/rpc/connection/cache.go:26 +0x26
created by github.com/onflow/flow-go/engine/access/rpc/backend.NewCache.func1
/app/engine/access/rpc/backend/backend.go:229 +0x76
```
This is caused by 2 race conditions in the connection cache.
1. When a connection fails because the backend is unavailable, it is removed from the cache, and the …

[Access] Fix race condition in connection cache

---

fvm/fvm_test.go
fvm/transactionInvoker.go

Closes: #5068 
This PR fixes an issue with EVM setup. It moves the setup in the preprocess of the transaction invoker, since the Cadence env needs to have `EVMInternal` values set during the preprocess as it loads the transaction program and the checker fails otherwise.

[EVM] Fix the setup process

---

integration/go.mod
integration/go.sum

Switch to PR version of `onflow/flow-emulator` to incorporates all of the recent updates to the Access API

[Testing] Fix emulator version

---

.github/workflows/ci.yml
.github/workflows/flaky-test-monitor.yml
engine/access/rpc/backend/backend.go
integration/Makefile
integration/tests/access/cohort1/access_api_test.go
integration/tests/access/cohort2/observer_test.go
integration/tests/access/cohort3/access_circuit_breaker_test.go
integration/tests/access/cohort3/access_test.go
integration/tests/access/cohort3/consensus_follower_test.go
integration/tests/access/cohort3/execution_state_sync_test.go
integration/tests/access/cohort3/grpc_compression_test.go
integration/tests/access/cohort3/rest_state_stream_test.go
integration/tests/bft/framework/passthrough_test.go
integration/tests/epochs/cohort2/epoch_join_and_leave_vn_test.go
integration/tests/epochs/suite.go
integration/tests/lib/util.go
network/p2p/p2pnode/resourceManager_test.go
network/test/cohort1/meshengine_test.go
network/test/cohort1/network_test.go
network/test/cohort2/blob_service_test.go
network/test/cohort2/echoengine.go
network/test/cohort2/echoengine_test.go
network/test/cohort2/epochtransition_test.go
network/test/cohort2/unicast_authorization_test.go
utils/test_matrix/test_matrix.go
utils/test_matrix/test_matrix_test.go

Backports: https://github.com/onflow/flow-go/pull/4906

[CI][Testing] Add BuildJet CI runners for unit tests, integration tests; cache Docker images - backport

---

insecure/integration/functional/test/gossipsub/rpc_inspector/validation_inspector_test.go
network/p2p/distributor/gossipsub_inspector.go
network/p2p/inspector/validation/control_message_validation_inspector.go
network/p2p/scoring/registry.go
network/p2p/test/fixtures.go

This PR fixes the flakey behavior with `TestGossipSubSpamMitigationIntegration`. 
**Test scenario**:
The test assesses the comprehensive effectiveness of our GossipSub control message spam mitigation system. It initiates with a spammer, representing an attacker, bombarding a victim node through various control message spam attacks. The expectation is for the victim's RPC inspector module to detect these attacks and report them to the GossipSub score registry. The registry, in turn, penalizes the spammer based on the GossipSub's application-specific score. The severity of the attack is calibrated to be high, ensuring that the spammer's penalty eventually crosses the graylisting threshold. This results in the suppression of all GossipSub RPC exchanges between the spammer and the victim. …

[Networking] Fixing flakey TestGossipSubSpamMitigationIntegration

---

cmd/execution_builder.go
insecure/integration/functional/test/gossipsub/rpc_inspector/validation_inspector_test.go
insecure/integration/functional/test/gossipsub/scoring/ihave_spam_test.go
module/finalizedreader/finalizedreader.go
module/finalizedreader/finalizedreader_test.go

This PR caches the last finalized height in finalized reader, so that it reduce one DB call when register store checks the latest finalized block

[Storehouse] Optimize finalized reader to cache last finalized height

---

cmd/execution_config.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/testutil/nodes.go
integration/testnet/client.go
integration/testnet/network.go
integration/tests/lib/testnet_state_tracker.go
module/finalizedreader/finalizedreader.go
module/finalizedreader/finalizedreader_test.go

This PR fixes an issue in creating the storage snapshot for ingestion engine

[Storehouse] Fix storage snapshot

---

cmd/execution_builder.go
engine/execution/execution_test.go
engine/execution/state/state.go
engine/testutil/mock/nodes.go
engine/testutil/nodes.go

This PR fixed getting highest executed block ID when storehouse is enabled. 
The highest executed block ID is updated when executing blocks, however, when EN is restarted, it re-execute all blocks since last finalized and executed blocks, therefore, the highest executed block ID after restart becomes the highest finalized and executed block.

[Storehouse] Fix getting highest executed block ID when storehouse is enabled

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Updating to Cadence [v0.42.6](https://github.com/onflow/cadence/releases/tag/v0.42.6)

[v0.32] Update cadence to v0.42.6

---

cmd/collection/main.go
cmd/execution_builder.go
cmd/execution_config.go
engine/execution/state/state.go
engine/execution/storehouse.go
engine/execution/storehouse/in_memory_register_store.go
engine/execution/storehouse/register_store.go
integration/benchnet2/automate/templates/helm-values-all-nodes.yml
ledger/complete/wal/wal.go

This PR Improves logging for storehouse, and also change the default trie folder path

[Storehouse] Improving logging

---

ledger/common/pathfinder/pathfinder.go
ledger/complete/ledger.go
ledger/complete/mtrie/node/node.go
ledger/complete/mtrie/trie/trie.go
ledger/complete/wal/checkpoint_v6_test.go
ledger/ledger.go
ledger/mock/migration.go

Switch migrations to migrate payloads by reference, to reduce memory usage.

Migrate payloads by reference

---

Makefile
integration/Makefile

Makes the following changes to integration test make targets:
* Fixes `access-test` target to include new cohorts
* Removes `ci-integration-tests` from integration makefile since it was identical to `integration-tests`
* Updates `ci-integration` in main makefile to use `integration-tests` target

[CI] Cleanup integration make targets

---

cmd/util/ledger/migrations/storage_fees_migration.go
cmd/util/ledger/migrations/utils.go
cmd/util/ledger/reporters/atree_reporter.go
cmd/util/ledger/reporters/storage_snapshot.go
engine/access/state_stream/backend/backend_executiondata_test.go
engine/execution/scripts/engine.go
fvm/environment/accounts.go
fvm/environment/accounts_test.go
fvm/environment/derived_data_invalidator_test.go
fvm/meter/meter_test.go
fvm/storage/derived/table_test.go
fvm/storage/snapshot/snapshot_tree_test.go
fvm/storage/state/execution_state_test.go
fvm/storage/state/spock_state_test.go
fvm/storage/state/storage_state_test.go
fvm/storage/state/transaction_state_test.go
fvm/transactionStorageLimiter_test.go
ledger/common/convert/convert.go
ledger/common/convert/convert_test.go
ledger/partial/ledger_test.go
model/flow/ledger.go
model/flow/ledger_test.go
module/chunks/chunkVerifier_test.go
module/state_synchronization/indexer/indexer_core_test.go
storage/badger/operation/interactions_test.go
storage/pebble/registers_test.go
utils/debug/registerCache.go
utils/unittest/fixtures.go

Currently, `NewRegisterID` accepts a string for the owner field, which needs to be either a valid flow address or an empty string. This creates issues when developers make incorrect assumptions about the inputs, and allows for unrealistic test scenarios that miss important corner cases.
Refactor `NewRegisterID` to accept a `flow.Address` and adjust callers/tests.

[Ledger] Refactor NewRegisterID to accept address

---

engine/access/state_stream/backend/backend.go
engine/access/state_stream/backend/backend_executiondata_test.go
engine/access/state_stream/backend/handler.go
engine/access/state_stream/backend/handler_test.go
engine/common/rpc/convert/execution_data.go
engine/common/rpc/convert/execution_data_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Closes: https://github.com/onflow/flow-go/issues/5137
Depends on: https://github.com/onflow/flow/pull/1417
RegisterIDs contain a binary representation of the owner's address formatted as a string. The original implementation used a string to pass the field. This broken clients since protobuf requires string fields to be valid UTF-8.

[Access] Fix GetRegisterValues input types

---

network/p2p/tracer/gossipSubMeshTracer.go

This is a minor expansion on top of https://github.com/onflow/flow-go/pull/5083, which surrounds all trace level logs in GossipSub tracer with level check.

[Networking] Surrounding Trace Level Logs With Level Check in Gossipsub Tracer

---

cmd/execution_builder.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/loader/unfinalized_loader.go
engine/execution/state/mock/execution_state.go
engine/execution/state/state.go

This PR let Execution Node load unfinalized blocks when storehouse is enabled.

[Storehouse] Use unfinalized loader when storehouse is enabled

---

fvm/environment/meter.go
fvm/evm/stdlib/contract.go
fvm/evm/stdlib/contract_test.go

Follow-up for: https://github.com/onflow/flow-go/issues/4937
- The computation metering for `EVM.encodeABI` proactively calculates the length of the `[UInt8]` resulting array, based on the `[AnyStruct]` array of Cadence values. Dynamic & static variables are accounted for separately.
- The computation metering for `EVM.decodeABI` is the length of the `[UInt8]` array that is passed in.
Decoding a `[UInt8]` array that was previously encoded with `EVM.encodeABI`, takes up the exact same computation as the encoding.

Report proper computation for `EVM.encodeABI` & `EVM.decodeABI` methods

---

insecure/integration/functional/test/gossipsub/scoring/scoring_test.go
network/p2p/scoring/score_option.go

This PR disables invalid message delivery penalty on v0.32 till we can configure scoring parameters externally. This is to mitigate an edge case in GossipSub.

[Networking] Disables invalid message delivery penalty on v0.32

---

engine/access/rpc/backend/backend_accounts.go
engine/access/rpc/backend/backend_accounts_test.go
engine/consensus/approvals/assignment_collector_tree.go
engine/consensus/approvals/testutil.go
engine/consensus/sealing/core.go
engine/execution/ingestion/loader/unexecuted_loader.go
engine/execution/ingestion/loader/unexecuted_loader_test.go
engine/execution/ingestion/loader/unfinalized_loader.go
engine/execution/ingestion/loader/unfinalized_loader_test.go
engine/execution/ingestion/stop/stop_control.go
engine/execution/ingestion/stop/stop_control_test.go
engine/execution/state/state.go
module/finalizedreader/finalizedreader.go
module/finalizer/consensus/finalizer.go

This PR optimizes the FinalizedBlockIDAtHeight method of the FinalizedReader used by Storehouse

[Storehouse] Optimize finalized reader to use block id index

---

cmd/access/node_builder/access_node_builder.go
cmd/execution_builder.go
engine/execution/ingestion/loader/unfinalized_loader.go
engine/execution/state/bootstrap/bootstrap.go
engine/testutil/nodes.go
storage/pebble/bootstrap.go
storage/pebble/bootstrap_test.go

Close https://github.com/onflow/flow-go/issues/5183
This PR fixes loading blocks on startup for storehouse when the node is dynamic bootstrapped

[Storehouse] Fix dynamic bootstrapping for storehouse

---

engine/access/rpc/backend/script_comparer.go

Update the Access node's script execution comparer to log result and error mismatches using `error` level. This makes debugging issues easier on production nodes with a lot of traffic.
mismatches are very rare, so this should only generate a handful of new logs per hour.

[Access] Log script exec mismatches as error

---

cmd/execution_builder.go
cmd/execution_config.go
engine/execution/checker/core.go
engine/execution/checker/core_test.go
engine/execution/checker/engine.go

Close https://github.com/onflow/flow-go/issues/5173
This PR refactors the checker engine to close https://github.com/onflow/flow-go/issues/5173

[Execution] Refactor Checker Engine

---

fvm/evm/stdlib/contract.cdc
fvm/evm/stdlib/contract_test.go

These functions can be used to `ABI` encode/decode function calls, along with their arguments.
Example usage:
```cadence
// bytes for address 0x7A58c0Be72BE218B41C608b7Fe7C5bB630736C71
let address = EVM.EVMAddress(
bytes: [
122, 88, 192, 190, 114, 190, 33, 139, 65, 198,
8, 183, 254, 124, 91, 182, 48, 115, 108, 113
]
)
// ABI encode a function call with its arguments
let data = EVM.encodeABIWithSignature(
"withdraw(address,uint256)",
[address, UInt256(250)]
)
// ABI decode a function call with its arguments
// Note: We can probably infer the types with some string manipulation on the given signature
let values = EVM.decodeABIWithSignature(
"withdraw(address,uint256)",
types: [Type<EVM.EVMAddress>(), Type<UInt256>()],
data: data
)
```

Add the `EVM.encodeABIWithSignature` and `EVM.decodeABIWithSignature` functions

---

engine/access/rpc/backend/backend_events.go
engine/access/rpc/backend/backend_events_test.go
engine/access/rpc/backend/backend_transactions.go

Closes: https://github.com/onflow/flow-go/issues/5200
`Header.ID` calculations were using up a sizeable amount of resources in the get events handler. This PR updates the endpoint to cache the calculations for the duration of the request.

[Access] Optimize header ID calculation in get events

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/migrations/atree_register_migration.go
cmd/util/ledger/migrations/atree_register_migration_test.go
cmd/util/ledger/migrations/cadence_value_validation.go
cmd/util/ledger/migrations/cadence_value_validation_test.go

Updates PR #4633 
Updates #4576
Updates https://github.com/onflow/cadence/issues/2983
This change replaces hash-based validation of Cadence values in PR #4633 in order to prepare for atree inlining to be incorporated into the migration program.
Also added `--validate` flag to enable validation during migration since enabling validation can increase duration of migration.
Enabling validation will use `cadence.Equal()` to compare every Cadence value before/after migration.

Replace hash-based validation of migrated Cadence values to use `Equal()`

---

crypto/hash/empty.go
crypto/random/empty.go

Updating dependencies in other repos is failing because the packages `onflow/flow-go/crypto/hash` and `onflow/flow-go/crypto/random` do not exist anymore. 
This PR reverts the packages as empty (similar to `onflow/flow-go/crypto`)  to unblock the other repos updates.

Revert deleted `crypto/hash` and `crypto/random` packages

---

fvm/fvm_test.go

The EVM test had some workarounds that are no longer needed since https://github.com/onflow/flow-go/pull/5106.

Update EVM test

---

cmd/util/ledger/migrations/change_contract_code_migration.go
engine/execution/computation/manager.go
fvm/bootstrap.go
fvm/evm/stdlib/abiOnlyContract.cdc
fvm/evm/stdlib/contract.go
fvm/evm/stdlib/contract_test.go
fvm/fvm_test.go

Adds the relevant config options and contract code, for deploying the `EVM` contract with only the necessary functionality for `ABI` encoding/decoding:
- `EVM.encodeABI`
- `EVM.decodeABI`
- `EVM.encodeABIWithSignature`
- `EVM.decodeABIWithSignature`
The `EVM.EVMAddress` type is also included in the minified `EVM` contract, as it is required for encoding/decoding to the Solidity `address` type.

[EVM] Add feature flag for deploying `EVM` contract only with ABI functionality

---

engine/access/rpc/backend/backend_events.go
engine/access/rpc/backend/backend_events_test.go
engine/access/rpc/backend/backend_transactions.go

Backports: https://github.com/onflow/flow-go/pull/5214
`Header.ID` calculations were using up a sizeable amount of resources in the get events handler. This PR updates the endpoint to cache the calculations for the duration of the request.

[Access] Optimize header ID calculation in get events - v0.32

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
cmd/scaffold.go
config/config_test.go
config/default-config.yml
follower/follower_builder.go
insecure/corruptlibp2p/libp2p_node_factory.go
insecure/integration/functional/test/gossipsub/rpc_inspector/validation_inspector_test.go
insecure/integration/functional/test/gossipsub/scoring/ihave_spam_test.go
module/metrics.go
module/metrics/gossipsub_rpc_validation_inspector.go
module/metrics/labels.go
module/metrics/noop.go
module/mock/gossip_sub_metrics.go
module/mock/gossip_sub_rpc_validation_inspector_metrics.go
module/mock/lib_p2_p_metrics.go
module/mock/network_metrics.go
network/internal/p2pfixtures/fixtures.go
network/netconf/flags.go
network/p2p/builder/libp2pNodeBuilder.go
network/p2p/config/peer_scoring.go
network/p2p/consumers.go
network/p2p/distributor/gossipsub_inspector_test.go
network/p2p/inspector/validation/control_message_validation_inspector.go
network/p2p/inspector/validation/control_message_validation_inspector_test.go
network/p2p/scoring/registry.go
network/p2p/scoring/registry_test.go
network/p2p/scoring/scoring_test.go
network/p2p/test/fixtures.go
utils/unittest/unittest.go

This PR temporarily reverts [PR #4978](https://github.com/onflow/flow-go/pull/4978) due to an architectural conflict with [PR #5234](https://github.com/onflow/flow-go/pull/5234).
While developing [PR #4978](https://github.com/onflow/flow-go/pull/4978), our goal was to refine peer scoring by individually counting errors. However, recent challenges in GossipSub revealed the need for an aggregated approach to manage inspection errors, setting thresholds as outlined in [PR #5234](https://github.com/onflow/flow-go/pull/5234). In consultation with @kc1116, we decided to revert [PR #4978](https://github.com/onflow/flow-go/pull/4978) and rework its architecture to align with the strategies introduced in [PR #5234](https://github.com/onflow/flow-go/pull/5234). Given the extensive nature of this …

[Networking] Reverting 4978

---

cmd/util/cmd/read-badger/cmd/commits.go
cmd/util/cmd/read-badger/cmd/find-block-by-commit/main.go
cmd/util/cmd/read-badger/cmd/find-block-by-commits/main.go
cmd/util/cmd/root.go

This PR adds a command to util to find block ID by state commitment within a height range.
This is useful to know which block is the checkpoint for. 
When recovering an execution node to an old state, we need to know which block is the checkpoint file for. The checkpoint file contains tries with state commitments as trie root hashes. However, the checkpoint file doesn't contain block information, it's difficult to know which blocks are the state commitments for. With this util command, we can specify a height range, and look up the block ID for a list of state commitments we read from the checkpoint file

[Util] Find block ID by state commitment

---

fvm/evm/types/events.go

Currently, the event payload does not include this field:
```shell
- height (UInt64): 1
- totalSupply (UInt64): 5000000000000000000
- parentHash (String): "0x0000000000000000000000000000000000000000000000000000000000000000"
- stateRoot (String): "0xe81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421c0"
- receiptRoot (String): "0x48015828c844bff65608bad9fbd1967ea69a2132aaa3223a0d169b4d11cf743e"
- transactionHashes (?): ["0x7b72b5729cafbd2472a7c5b28e2cb9bf6b4de80cc15dae786a0b13aebc54e97e"]
hex: 5b22307837623732623537323963616662643234373261376335623238653263623962663662346465383063633135646165373836613062313361656263353465393765225d
```

[Flow EVM] Include the block hash in `evm.BlockExecuted` event payload

---

cmd/util/ledger/migrations/change_contract_code_migration.go
fvm/bootstrap.go
fvm/evm/evm.go
fvm/evm/evm_test.go
fvm/fvm_bench_test.go
fvm/fvm_test.go
fvm/systemcontracts/system_contracts.go
fvm/transactionStorageLimiter.go
fvm/transactionStorageLimiter_test.go

What was done in this PR
- A new system account (not a contract in this case) was introduced for EVM state storage. 
- The tests that use the EVM contract use the EVM account address from systemcontracts
- only skip the storage check on the EVM storage account if EVM is actually enabled. 
The EVM contract account will be the service account on all networks.
The EVM state storage account will be the fifth account on all transient networks. On non-transient networks an Account still has to be picked to serve that purpose.

Use correct EVM address in tests and transient networks

---

Makefile

Revert https://github.com/onflow/flow-go/pull/5157. The change to `without-netgo` image tags is not compliant with the docker tag format

[CI] Revert change to use semver build for without-netgo images - v0.33

---

Makefile

Revert https://github.com/onflow/flow-go/pull/5157. The change to `without-netgo` image tags is not compliant with the docker tag format

[CI] Revert change to use semver build for without-netgo images

---

engine/execution/ingestion/engine.go
module/metrics/execution.go

Simplify ingestion engine by moving a metrics-related state var to metrics module.

[Execution] Move maxCollectionHeight to metrics

---

fvm/evm/evm_test.go
fvm/evm/stdlib/contract.cdc
fvm/evm/stdlib/contract_test.go

[Flow EVM] reducing the scope of deposit to COAs only

---

engine/execution/state/bootstrap/bootstrap_test.go
fvm/environment/uuids.go
fvm/environment/uuids_test.go
utils/unittest/execution_state.go

port of https://github.com/onflow/flow-go/pull/4914

UUID partition change - port

---

fvm/evm/types/events.go
model/events/parse.go
model/events/parse_test.go
model/flow/event.go

It turns out that `flow` service/protocol events, are allowed to have only 2 parts, e.g. `flow.AccountCreated`.
The two newly-introduced EVM related events:
- `flow.evm.BlockExecuted`
- `flow.evm.TransactionExecuted`
do not comply with this format, hence, they are considered as invalid event types:
```shell
rpc error: code = InvalidArgument desc = invalid event filter: invalid event type flow.evm.BlockExecuted: invalid event type: flow.evm.BlockExecuted
```

Update event validation logic to account for the `evm.*` events

---

cmd/access/node_builder/access_node_builder.go
engine/access/rpc/backend/script_executor.go

Backports: https://github.com/onflow/flow-go/pull/5075
Limit the block range an AN will use for executing scripts and getting accounts when configured to use local data.
This is a stop-gap solution for node upgrades before https://github.com/onflow/flow-go/issues/5040 is completed.
Usage:
When a cadence/fvm upgrade is planned: after the stop height is known and before it is reached, add the `--script-execution-min-height` flag passing the stop height and update the AN to the new version. This will cause the AN to stop locally executing scripts for any height below the stop height.
When running a "historic" node, set
* `--script-execution-min-height` to the first block supported by the current version
* `--script-execution-max-height` to the last block supported by the current version
The …

[Access] add config to limit script execution range - master

---

cmd/access/node_builder/access_node_builder.go
engine/access/rpc/backend/script_executor.go

Backports: https://github.com/onflow/flow-go/pull/5075
Limit the block range an AN will use for executing scripts and getting accounts when configured to use local data.
This is a stop-gap solution for node upgrades before https://github.com/onflow/flow-go/issues/5040 is completed.
Usage:
When a cadence/fvm upgrade is planned: after the stop height is known and before it is reached, add the `--script-execution-min-height` flag passing the stop height and update the AN to the new version. This will cause the AN to stop locally executing scripts for any height below the stop height.
When running a "historic" node, set
* `--script-execution-min-height` to the first block supported by the current version
* `--script-execution-max-height` to the last block supported by the current version
The …

[Access] add config to limit script execution range - v0.33

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/static_type_migration.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Work towards onflow/cadence#3007
Add a utility code to easily define static type migration rules through a CSV file with Cadence syntax

Cadence 1.0 state migrations: Update to new static types migration

---

fvm/fvm_test.go
fvm/systemcontracts/system_contracts.go

A short doc about the accounts here:
https://www.notion.so/dapperlabs/EVM-Contract-and-storage-address-c45c953569854b1db4b0feec8258783d

Set the correct testnet/mainnet evm state storage account

---

fvm/systemcontracts/system_contracts.go

Set the correct testnet/mainnet evm state storage account - port

---

fvm/evm/handler/addressAllocator.go
fvm/evm/types/address.go

- add comments to clarify:
- security reasoning behind choosing an address prefix of 12 bytes
- reasoning behind the index to postfix mapping 
- rename some function and constants to match the underlying logic
- minor code simplification

suggestions for COA address 

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-M2](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M2)
- [onflow/cadence v1.0.0-M5](https://github.com/onflow/cadence/releases/tag/v1.0.0-M5)

Update to Cadence v1.0.0-M5

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-M3](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M3)
- [onflow/cadence v1.0.0-M6](https://github.com/onflow/cadence/releases/tag/v1.0.0-M6)

Update to Cadence v1.0.0-M6

---

cmd/scaffold.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
ledger/complete/compactor_test.go
ledger/complete/wal/wal.go
module/executiondatasync/tracker/storage.go

Log the progress of loading wal segment files and initialization during startup

Log progress of loading wal segment file

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-M4](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M4)
- [onflow/cadence v1.0.0-M7](https://github.com/onflow/cadence/releases/tag/v1.0.0-M7)

Update to Cadence v1.0.0-M7

---

cmd/util/cmd/extract-payloads-by-address/cmd.go
cmd/util/cmd/extract-payloads-by-address/extract_payloads_test.go

Requires #5386 
This PR adds `extract-payload-by-address` utility program for creating a subset of execution state which can save time during development, testing, and support/troubleshooting.
Given the intended use case, this utility uses stream reading and writing to reduce memory requirements and can be used on laptops, etc.
It requires these flags: 
- `--input-filename`
- `--output-filename`
- `--addresses` filters payloads to export for specified addresses (accounts)

Add utility to extract payloads by addresses

---

fvm/evm/types/events_test.go

This will help to avoid errors when changing the type of the event fields.

[Flow EVM] Add tests to assert that Flow EVM events can be properly CCF encoded/decoded

---

engine/access/rpc/backend/backend_events_test.go
engine/access/rpc/backend/event_index_test.go
engine/access/rpc/backend/events_index.go
engine/access/state_stream/backend/backend_events_test.go
engine/access/state_stream/backend/backend_executiondata_test.go

Events returned by `ByBlockID` called on the badger storage object are returned in the same order stored. Events are keyed on [ blockID, txID, txIndex, eventIndex ]. This makes querying easier, but results in a list of events that is not in the same order that the tx appeared in the block.
The usually isn't a problem when querying with the polling endpoints, but when streaming it's possible to subscribe to all events. In this case, it's unintuitive for the returned list to not be in tx order.
This PR sorts events returned to the API by txIndex to ensure the returned order is correct.

[Access] Sort events returned from index in tx index order

---

admin/README.md
cmd/bootstrap/run/execution_state.go
cmd/execution_builder.go
cmd/util/cmd/checkpoint-collect-stats/cmd.go
cmd/util/cmd/exec-data-json-export/ledger_exporter.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
engine/execution/ingestion/engine.go
engine/testutil/nodes.go
go.mod
ledger/complete/compactor.go
ledger/complete/compactor_test.go
ledger/complete/ledger_benchmark_test.go
ledger/complete/ledger_test.go
ledger/complete/mtrie/trie/trie.go
ledger/complete/wal/checkpoint_v6_reader.go
ledger/complete/wal/checkpoint_v6_writer.go
ledger/complete/wal/checkpointer.go
ledger/complete/wal/checkpointer_test.go
module/metrics.go
module/metrics/execution.go
module/metrics/noop.go
module/mock/execution_metrics.go
module/mock/wal_metrics.go

Close https://github.com/onflow/flow-go/issues/5392

Add checkpoint size metrics

---

fvm/evm/emulator/emulator.go
fvm/evm/emulator/state/stateDB.go
fvm/evm/emulator/state/stateDB_test.go
fvm/evm/handler/blockstore.go
fvm/evm/handler/handler.go
fvm/evm/handler/handler_test.go
fvm/evm/types/block.go
fvm/evm/types/events.go
fvm/evm/types/events_test.go
fvm/evm/types/result.go
fvm/evm/types/state.go

<details>
<summary>Conflict resolution</summary>
```diff
commit 6944e9d91cacce71aa450e3d9bf65fe821d03c08
Merge: 6b0ce48e3d 8b2113a309
Author: Bastian Müller <bastian@turbolent.com>
Date:   Tue Feb 20 12:46:04 2024 -0800
Merge branch 'master' into bastian/update-stable-cadence-11
diff --git a/fvm/evm/types/events.go b/fvm/evm/types/events.go
remerge CONFLICT (content): Merge conflict in fvm/evm/types/events.go
index adf763feb9..140467ad7e 100644
--- a/fvm/evm/types/events.go
+++ b/fvm/evm/types/events.go
@@ -120,8 +120,8 @@ func (p *TransactionExecutedPayload) CadenceEvent() (cadence.Event, error) {
EVMLocation{},
string(EventTypeTransactionExecuted),
[]cadence.Field{
-<<<<<<< 6b0ce48e3d (Merge pull request #5396 from onflow/kan/preview-net-chain-id)
cadence.NewField("blockHeight", …
```

Update Stable Cadence feature branch

---

utils/binstat/binstat.go

Adds Windows support to binstat.go `gettid` utility

Add Windows support when compiling with CGO_ENABLED

---

engine/access/rpc/backend/backend_events_test.go
engine/access/rpc/backend/event_index_test.go
engine/access/rpc/backend/events_index.go
engine/access/state_stream/backend/backend_events_test.go
engine/access/state_stream/backend/backend_executiondata_test.go

Backport: https://github.com/onflow/flow-go/pull/5404

[Access] Sort events returned from index in tx index order - backport

---

fvm/evm/emulator/emulator.go
fvm/evm/emulator/emulator_test.go
fvm/evm/types/call.go

This PR fixes the tx hash missing for some of the direct calls.

[Flow EVM] fix tx hash bug for direct calls (deposit, withdraw)

---

fvm/evm/handler/handler.go

The `evm.BlockExecuted.hash` & `evm.TransactionExecuted.blockHash` fields did not match up, e.g.
```shell
Index    5
Type    evm.TransactionExecuted
Tx ID    67244b4d6f7e8ed4a5687099386e66424ec8d6adfa1abf739b9b227beb544b24
Values
- blockHeight (UInt64): 2 
- blockHash (String): "0x5d85046405a803acf1920cfafb7508f1817f7c905a616e012ea0420704f68c09" 
- transactionHash (String): "0x95f00658e23f24928fe5a1c4af91df8fdd7b4cf02ea63cc86911d197dfa7912e" 
- transaction (String): "fff83c81ff0194000000000000000000000000000000000000000094000000000000000000000002fcb52dccbbaa997780891b1ae4d6e2ef50000082520880" 
- failed (Bool): false 
- vmError (String): "" 
- transactionType (UInt8): 255 
- gasConsumed (UInt64): 21000 
- deployedContractAddress (String): "0000000000000000000000000000000000000000" 
- …
```

Move `blockHash` calculation after deduction of supply diff

---

fvm/evm/handler/handler.go

Port of https://github.com/onflow/flow-go/pull/5462 from `feature/stable-cadence` to `master` branch.

Move `blockHash` calculation after deduction supply diff

---

integration/tests/access/cohort3/execution_state_sync_test.go

The DB is closed and deleted by `Cleanup` [method](https://github.com/onflow/flow-go/blob/leo/fix-execution-state-sync-tests/integration/testnet/network.go#L291) during `TearDownTest` call. 
Calling DB.Close again would try to remove the lock or db folder which has already removed. This sometimes [causing an endless loop](https://github.com/dgraph-io/badger/issues/664) because when badger can't find the files to delete, it will run a loop to try deleting them, and end up causing the tests to run longer and hit timeout eventually.

Remove db close in execution state sync tests

---

cmd/util/cmd/addresses/cmd.go
cmd/util/cmd/root.go

This is useful when using `util` with `execution-state-extract` with `--extract-payloads-by-address`

Add sub-command to generate addresses for a chain

---

integration/Makefile

The integration tests might have multiple tests in it, if one fails, it continue to run other tests, and this not only makes the integration tests to run for much longer, but also make it hard to find the original error message. 
This PR adds the flag to fail the integration tests on the first failure, so that error message can be found at the end of the CI log.

Add failfast to integration tests

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-M7](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M7)

[Cadence 1.0] Update to SDK v1.0.0-M7

---

cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/deploy_migration.go
cmd/util/ledger/migrations/merge.go

Add extra logs to the merge function.
When doing account based migration only that one account should have changes.

Add logs to merge

---

cmd/util/ledger/util/payload_grouping.go
cmd/util/ledger/util/payload_grouping_test.go

Closes #5485
Updates https://github.com/onflow/cadence/issues/3096
This fixes data race in account grouping.
While at it, also added test to reproduce the data race.

Fix data race in account grouping for account based migration

---

cmd/util/cmd/bootstrap-execution-state-payloads/cmd.go
cmd/util/cmd/root.go

Work towards onflow/cadence#3096

Add util command to generate payloads for bootsrapped execution state

---

engine/execution/state/bootstrap/bootstrap_test.go
fvm/accounts_test.go
fvm/evm/stdlib/contract.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
utils/unittest/execution_state.go

- [onflow/flow-go-sdk v1.0.0-M8](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M8)
- [onflow/cadence v1.0.0-M9](https://github.com/onflow/cadence/releases/tag/v1.0.0-M9)
Note: Hide whitespace changes to see actual API adjustments

Update to Cadence v1.0.0-M9

---

cmd/access/node_builder/access_node_builder.go
storage/pebble/cache.go
storage/pebble/lookup.go
storage/pebble/registers.go
storage/pebble/registers_cache.go

Closes: #5277
This PR adds a simple cache for register lookups on Access nodes. This improves the performance of scripts that lookup frequently queried registers, like common contract code.

[Access] Add initial register cache implementation

---

cmd/execution_builder.go

[Execution] Remove duplicated observer collection indexer

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.10](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.10)
- [onflow/cadence v1.0.0-preview.12](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.12)

Update to Cadence v1.0.0-preview.12

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
cmd/util/ledger/migrations/account_based_migration.go
cmd/util/ledger/migrations/account_size_filter_migration.go
cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/contracts.go
cmd/util/ledger/migrations/staged_contracts_migration.go
ledger/complete/ledger.go

Depends on #5539  
Work towards #3162
- Remove "known problematic accounts"
- Improve logging
- Test that migrated values may refer to types of core contracts
- Optimize contract lookup: Instead of gathering all contracts when migrating each account, gather all contracts once, after updating/deploying contracts and before running the value migrations
- Add migration to filter accounts by max size

[Cadence 1.0] Improve migrations

---

engine/access/rpc/backend/backend.go
engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions.go
engine/access/rpc/backend/backend_transactions_test.go
engine/access/rpc/backend/transactions_local_data_provider.go
integration/localnet/builder/bootstrap.go

Closes: #5531 
Access nodes support returning tx results from local data. This was not working as expected for the `GetTransactionResultsByBlockID`. The request would fail to lookup the collection for the system tx and return a `NotFound` error.
This PR adds handling for the system tx, and also caches the txID to collectionID lookups since there are typically more than 1 tx per collection.

[Access] Handle system transaction in local result mode

---

cmd/Dockerfile
insecure/Makefile
integration/Makefile
integration/benchmark/cmd/manual/Dockerfile

Fix typo for a CGO flag when building for non-adx CPUs. 
Side change:
Update `Makefile` in test modules to match the main repo Makefile. This has no functional impact but keeps the code base consistent

Fix build typo

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration_test.go

`NonFungibleToken.Collection` changed from a nested type requirement to an interface

[Cadence 1.0] Add missing rule for NonFungibleToken.Collection type

---

cmd/util/ledger/migrations/cadence_values_migration.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.11](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.11)
- [onflow/cadence v1.0.0-preview.13](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.13)

Update to Cadence v1.0.0-preview.13

---

fvm/fvm_test.go
fvm/transactionInvoker.go

closes: https://github.com/onflow/flow-go/issues/3834

Meter computation in the account storage check

---

cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.12](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.12)
- [onflow/cadence v1.0.0-preview.14](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.14)

Update to Cadence v1.0.0-preview.14

---

admin/command_runner.go

Add CPU profile support to the admin server. This can be used generate on-demand profiles.

[Admin] Add support for CPU profiles via admin server

---

admin/command_runner.go

Add CPU profile support to the admin server. This can be used to generate on-demand profiles.

[Admin] Add support for CPU profiles via admin server - master backport

---

cmd/util/ledger/migrations/staged_contracts_migration.go
cmd/util/ledger/migrations/staged_contracts_migration_test.go
cmd/util/ledger/migrations/test-data/cadence_values_migration/test_contract_upgraded.cdc

Fixes part of https://github.com/onflow/cadence/issues/3098#issuecomment-1998065770
The `elaborations` and the  `ContractAdditionHandler` used for the contract update validator needs to be initialized using **all payloads**, not just with the payloads of the migrating account.

Fix import resolving during staged contract updates

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.13](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.13)
- [onflow/cadence v1.0.0-preview.15](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.15)

Update to Cadence v1.0.0-preview.15

---

cmd/access/node_builder/access_node_builder.go
engine/access/access_test.go
engine/access/rpc/backend/backend.go
engine/access/rpc/backend/backend_accounts.go
engine/access/rpc/backend/backend_events.go
engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions.go
engine/access/rpc/backend/backend_transactions_test.go
engine/access/rpc/backend/config.go
engine/access/rpc/backend/event_index_test.go
engine/access/rpc/backend/retry.go
engine/access/rpc/backend/transaction_results_indexer.go
engine/access/rpc/backend/transactions_local_data_provider.go
engine/access/state_stream/backend/backend_events.go
engine/common/rpc/convert/events.go
engine/common/rpc/errors.go
integration/localnet/builder/bootstrap.go
integration/tests/access/cohort1/access_api_test.go

Backports: https://github.com/onflow/flow-go/pull/5306, https://github.com/onflow/flow-go/pull/5532
This PR backports 2 PRs that implemented local data support in the transaction results API endpoints. The new functionality is gated by a new CLI flag `--tx-result-query-mode` which defaults to the existing behavior.

[Access] Use local transaction result data in Access API - v0.33

---

engine/access/rpc/backend/transactions_local_data_provider.go
engine/common/rpc/convert/events.go

When running an AN configured to use local events for tx results, the event conversion was thrown away. This was caused by updating a local variable reference within a loop instead of the original data.

[Access] Fix event conversion in local TxResults endpoint

---

utils/binstat/binstat.go

closes #5584 
Relaxes the requirement for elapsed time because some systems do not have time resolution precise enough in comparison to the execution time.

Relax requirement for elapsed time during binstat init

---

fvm/evm/stdlib/contract.cdc
fvm/evm/stdlib/contract.go
fvm/evm/stdlib/contract_test.go

Sample usage:
```cadence
import EVM from 0x1
access(all)
fun main(): EVM.EVMBlock {
return EVM.getLatestBlock()
}
```
The current fields of the `EVMBlock` struct are:
```cadence
access(all)
struct EVMBlock {
access(all)
let height: UInt64
access(all)
let hash: String
access(all)
let totalSupply: Int
init(height: UInt64, hash: String, totalSupply: Int) {
self.height = height
self.hash = hash
self.totalSupply = totalSupply
}
}
```

Implement `EVM.getLatestBlock()` function to expose info about the latest block

---

module/mempool/stdmap/backend_test.go

This was causing the assertions to check before the test logic completed
previously fixed on master: https://github.com/onflow/flow-go/pull/5275

[CI] Fix synchronization in some mempool unittests

---

cmd/util/ledger/migrations/cadence_values_migration.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.16](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.16)
- [onflow/cadence v1.0.0-preview.18](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.18)

Update to Cadence v1.0.0-preview.18

---

fvm/evm/emulator/emulator.go
fvm/evm/emulator/emulator_test.go
fvm/evm/emulator/state/stateDB.go
fvm/evm/emulator/state/stateDB_test.go
fvm/evm/emulator/state/state_growth_test.go
fvm/evm/handler/handler.go
fvm/evm/handler/handler_test.go
fvm/evm/types/codeFinder.go
fvm/evm/types/emulator.go
fvm/evm/types/errors.go
fvm/evm/types/proof_test.go
fvm/evm/types/result.go
fvm/evm/types/state.go

This PR 
- is part 1 of the changes needed for #5501 
- changes the stateDB 
- adds the `Reset` method to clean up the transient part of the storage (logs, transient slots, ... ), this method can be used between transactions. 
- separate `Finalize` part of the `Commit` method and add it as a separate method. Finalize, commit the changes from the Atree cache into the final ledger state. This has been added so when executing multiple transactions, we can save time on the serialization time of Atree. 
- updates the way we return errors from the emulator and handle them on the handler
- validation errors are also now part of the result and won't be returned by methods like `RunTransaction`. 
- now any returned error from the emulator requires reverting the flow transaction (is a non-fatal but …

[Flow EVM] prepare the StateDB and the Emulator to support batch run operations

---

cmd/util/cmd/root.go

This PR adds `extract-payload-by-address` command to `util` program.

Add util command to extract payload by address

---

README.md
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- upgrade `onflow/crypto`
- clarify build constraints related to https://github.com/onflow/crypto when importing the flow-go module. This also addresses https://github.com/onflow/crypto/issues/7.

Upgrade `onflow/crypto` and clarify build details

---

cmd/util/ledger/migrations/cadence_values_migration.go

Currently, storage health check always fails with "slabs not referenced from account storage" in pre-migration because storage maps are not loaded in Cadence runtime storage even though payloads are loaded.
This PR fixes this problem by loading storage map explicitly after loading payloads in storage.
Updates https://github.com/onflow/cadence/issues/3192
cc: @turbolent

Fix storage health check in Cadence 1.0 migration

---

fvm/environment/block_info.go
fvm/errors/codes.go
fvm/errors/execution.go
model/flow/sealing_segment.go
model/flow/sealing_segment.md
state/protocol/badger/snapshot.go
state/protocol/badger/snapshot_test.go

Close https://github.com/dapperlabs/flow-go/issues/6939

limit the height range when querying getBlock in FVM

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

In this pull request:
- removed `replace` for `protobuf` and updated to last version
- removed `replace` for `flow-emulator` and updated to last version

Updates protobuf and flow-emulator versions

---

cmd/util/ledger/migrations/staged_contracts_migration.go

This needs to be used in the Flow CLI for preliminary staging validation, would be useful to have this exported if there are any changes in the future/elimates code duplication.
re. https://github.com/onflow/flow-cli/pull/1495

Export user defined type change checker

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/migrations/atree_register_migration.go
cmd/util/ledger/migrations/atree_register_migration_test.go
cmd/util/ledger/migrations/utils.go

This PR adds debug flags to check storage health before and after atree migration.
- `check-storage-health-before`
- `check-storage-health-after`

Add storage health check flags for atree migration

---

network/p2p/tracer/internal/cache.go

Backports: https://github.com/onflow/flow-go/pull/5641
Switch to using string concatenation instead of `fmt.Sprintf` when generating rpc tracer IDs. the latter is 9x slower, so this will make a noticeable difference for this high volume action.

[Network] Use string concatenation in rpc tracer ID

---

utils/binstat/binstat.go

Relax requirement for elapsed time during binstat init
I am unsure what the status is on https://github.com/onflow/flow-go/pull/5575, so I just made this PR to cherry-pick the fix from `master` to `feature/stable-cadence`, since this causes issues for Windows users trying to use the Flow CLI & the `flow-c1` CLI does not have this fix yet.

Port binstat fix to `feature/stable-cadence`

---

cmd/util/ledger/migrations/atree_register_migration.go
cmd/util/ledger/migrations/atree_register_migrator_runtime.go
cmd/util/ledger/migrations/cadence_value_validation_test.go

Rename the migrator runtime used in the atree register inlining migration, and make it clear that it is only supposed to be used for the atree register inlining migration. It only allows storage operations, but does not support e.g. parsing and type checking of contracts.
This is prep work to allow master to be merged more easily into the Cadence 1.0 feature branch and https://github.com/onflow/cadence/issues/3233. The Cadence 1.0 migrations also use this runtime at the moment, but need support for parsing and checking of contract. We plan to move from a per-account runtime/storage, to a whole state one, so we can parse and check all contracts once in a separate migration (https://github.com/onflow/cadence/issues/3233).

Improve naming for migrator runtime

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/change_contract_code_migration.go
cmd/util/ledger/migrations/change_contract_code_migration_test.go
cmd/util/ledger/migrations/staged_contracts_migration.go
cmd/util/ledger/migrations/staged_contracts_migration_test.go

Work for https://github.com/onflow/cadence/issues/3050
Assuming the state/storage that is currently being migrated also contains the staged contracts captured by the [MigrationContractStaging](https://contractbrowser.com/A.2ceae959ed1a7e7a.MigrationContractStaging), this change will read and collect those staged contracts from the storage itself, so they don't needs to be provided externally as a CSV file, etc.
The old way of providing the staged contracts externally/as an argument (as a CSV file) is still supported. The new approach comes into effect only if they are not externally provided.

Collect staged contracts from the storage itself

---

cmd/util/ledger/migrations/cadence_values_migration.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.19](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.19)
- [onflow/cadence v1.0.0-preview.20](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.20)

Update to Cadence v1.0.0-preview.20

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/change_contract_code_migration.go
cmd/util/ledger/migrations/change_contract_code_migration_test.go
cmd/util/ledger/migrations/staged_contracts_migration.go
cmd/util/ledger/migrations/staged_contracts_migration_test.go

Failures are already and always reported.
Also, clean up and remove the unnecessary `ChangeContractCodeMigration` wrapper around `StagedContractsMigration`

Only log failed staged updates if verbose logging is enabled

---

fvm/environment/block_info.go
model/flow/constants.go
model/flow/sealing_segment.go
model/flow/sealing_segment.md
state/protocol/badger/snapshot.go
state/protocol/badger/snapshot_test.go

This PR is to adjust the number of extra blocks included in the sealing segment, so that it's backward compatible with the old root snapshot generated before which doesn't have `DefaultTransactionExpiry` (600) number of extra blocks.

v0.33 adjust extra blocks in sealing segment

---

cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/staged_contracts_migration.go
cmd/util/ledger/migrations/staged_contracts_migration_test.go

Currently, the reporter entries lack detail and they are at times ambiguous.
Implement `json.Marshaler` and consistently format details and add a "kind" property to indicate the kind of reporting entry.

Improve JSON encoding of reporter entries

---

cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/migrations/atree_register_migration.go
cmd/util/ledger/migrations/cadence_value_validation.go
cmd/util/ledger/migrations/utils.go

- Remove unused `AccountsAtreeLedger`. It's from '21 and not used either by atree register inlining nor Cadence 1.0 migration
- Improve comment
- Generate set of all storage map domains from slice (ensure they are in sync)
@fxamacker @janezpodhostnik seeing `AccountUsageMigrator` made me wonder: I guess we also want to run this after the Cadence 1.0 migration, because it also changes account storage usage (even if just slightly)?

Improve migrations

---

engine/execution/ingestion/throttle.go
engine/execution/ingestion/throttle_test.go

Working towards https://github.com/onflow/flow-go/issues/5298
This PR adds a throttle module that allows execution ingestion engine to load up to the first 500 blocks and start fetching data and executing them even if it's falling far behind.

[Execution] Add ingestion throttle

---

admin/commands/storage/read_protocol_snapshot.go
cmd/util/cmd/read-protocol-state/cmd/snapshot.go
cmd/util/common/checkpoint.go

This PR adds logs/return the checkpoint file to the admin tool when generating protocol snapshot from latest checkpoint. This allows us to know which checkpoint file is for the generated protocol snapshot file

Log the checkpoint file when generating protocol snapshot

---

engine/execution/ingestion/core.go
model/flow/entity.go
model/flow/entity_test.go

Working towards https://github.com/onflow/flow-go/issues/5297
The ingestion core implements the main business logic of execution node continuously executing blocks. 
- It forwards block and collection data from other components to the block queue module where the state of whether a block becomes executable is managed
- It listens to the tasks from block queue and execute on them using the external dependencies, such as block executor and collection fetcher.

[Execution] Ingestion - add ingestion core

---

integration/benchmark/load/load_type_test.go

This PR syncs feature branch feature/atree-inlining-cadence-v0.42 to latest master branch.

Sync feature/atree-inlining-cadence-v0.42 with latest master

---

cmd/Dockerfile

port of https://github.com/onflow/flow-go/pull/5750 to master

fix util docker build - port to master

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
cmd/util/ledger/migrations/staged_contracts_migration_test.go
cmd/util/ledger/util/util.go
model/flow/ledger.go

Add a migration which detects and filters out unreferenced slabs

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
cmd/util/ledger/migrations/account_based_migration.go
cmd/util/ledger/migrations/fix_broken_data_migration.go
cmd/util/ledger/migrations/fix_broken_data_migration_test.go
cmd/util/ledger/migrations/utils.go
cmd/util/ledger/util/util.go

Work towards https://github.com/onflow/cadence/issues/3220
Port #5755 to https://github.com/onflow/flow-go/tree/feature/atree-inlining-cadence-v0.42
Work done by @fxamacker
This PR adds `--fix-testnet-slabs-with-broken-references` flag to the migration program.
It uses a feature from onflow/atree#388 to fix 10 testnet registers affecting 9 testnet accounts.
The 9 testnet accounts are hardcoded in this commit to prevent accidentally applying this fix to any other accounts.
In testnet, broken references seem to have resulted from a bug that was fixed 2 years ago by onflow/cadence#1565.
A broken reference is a `StorageID` referencing a non-existent register.  So far, only 10 registers in testnet (none on mainnet) were found to contain broken references.

Port #5755 to feature/atree-inlining-cadence-v0.42

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/ledger/migrations/account_based_migration.go
cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/fix_broken_data_migration.go
cmd/util/ledger/migrations/fix_broken_data_migration_test.go
cmd/util/ledger/migrations/utils.go

Work towards https://github.com/onflow/cadence/issues/3220
This PR adds `--fix-testnet-slabs-with-broken-references` flag to the migration program.
It uses a feature from onflow/atree#388 to fix 10 testnet registers affecting 9 testnet accounts.
The 9 testnet accounts are hardcoded in this commit to prevent accidentally applying this fix to any other accounts.
In testnet, broken references seem to have resulted from a bug that was fixed 2 years ago by onflow/cadence#1565.
A broken reference is a `StorageID` referencing a non-existent register.  So far, only 10 registers in testnet (none on mainnet) were found to contain broken references.

Add migration to fix refs to non-existent registers

---

engine/execution/ingestion/block_queue/queue.go
engine/execution/ingestion/block_queue/queue_test.go
engine/execution/ingestion/core.go

Fixed an edge case in block queue caused by a race condition.

Fix block queue edge case

---

.github/workflows/ci.yml

Recently, we've noticed some codecov jobs taking hours to complete. This PR upgrades the action to the latest version and adds a timeout. If the step fails due to a timeout, the job will continue without error

[CI] Add timeout to codecov

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
cmd/util/ledger/migrations/fix_broken_data_migration.go
cmd/util/ledger/migrations/fix_broken_data_migration_test.go

This PR reduces logging, improves reports, and creates a payload file containing all slabs with broken references (currently only 10 testnet slabs and none on mainnet).
Changes include:
- Log filtered slab count instead of slab IDs to reduce overly verbose logging
- Write hex encoded account (instead of raw bytes) in reports
- Write all slabs with broken references to a payload file
- currently 10 testnet slabs which affects 9 testnet accounts (none on mainnet)
- more info about this at #5755
- Refactor code

Improve migration logging, reports, and new file for very old problematic slabs

---

fvm/evm/evm_test.go
fvm/evm/handler/handler.go
fvm/evm/handler/handler_test.go
fvm/evm/stdlib/contract.cdc
fvm/evm/types/events.go
fvm/evm/types/events_test.go
fvm/fvm_test.go
model/events/parse.go
model/events/parse_test.go
model/flow/event.go

Closes: #5414 
**💔 API Breaking Change**
Remove the special event type for evm: `evm.BlockExecuted` and `evm.TransactionExecuted` and make them be generic Flow event types: `A.{evm contract address}.EVM.TransactionExecuted` and `A.{evm contract address}.EVM.BlockExecuted`.

[EVM] Remove special EVM type

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
engine/execution/computation/computer/computer.go
fvm/context.go
fvm/fvm.go
fvm/storage/block_database.go
fvm/storage/derived/derived_block_data.go
fvm/storage/derived/table.go
fvm/storage/primary/block_data.go
integration/testnet/client.go
integration/tests/access/cohort1/access_api_test.go
module/execution/scripts.go
module/execution/scripts_test.go
module/state_synchronization/indexer/indexer_core.go
module/state_synchronization/indexer/indexer_core_test.go
module/state_synchronization/indexer/indexer_test.go
module/state_synchronization/indexer/util.go
module/state_synchronization/indexer/util_test.go
utils/dsl/dsl.go

Closes: https://github.com/onflow/flow-go/issues/5278
Add support for running the programs cache on Access nodes with script execution enabled. This improves overall script execution performance since the most common cadence contracts will be cached.

[Access] Add support for programs cache on access nodes - v0.33

---

cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
cmd/util/ledger/migrations/fix_broken_data_migration.go
cmd/util/ledger/migrations/fix_broken_data_migration_test.go

This PR reduces logging, improves reports, and creates a payload file containing all slabs with broken references (currently only 10 testnet slabs and none on mainnet).
Changes include:
- Log filtered slab count instead of slab IDs to reduce overly verbose logging
- Write hex encoded account (instead of raw bytes) in reports
- Write all slabs with broken references to a payload file
- currently 10 testnet slabs which affects 9 testnet accounts (none on mainnet)
- more info about this at #5755
- Refactor code

Port PR #5803 to Improve migration logging, reports, and output file

---

cmd/scaffold.go

Backports: https://github.com/onflow/flow-go/pull/5785
Log the "configuration loaded" message that includes the node's running config at `error` level. This ensures it's included in the logs for nodes running with "error" level.

[Logging] Log configuration loaded message at error level - v0.33

---

cmd/scaffold.go

Closes: https://github.com/onflow/flow-go/issues/5784
Log the "configuration loaded" message that includes the node's running config at `error` level. This ensures it's included in the logs for nodes running with "error" level.

[Logging] Log configuration loaded message at error level

---

fvm/evm/emulator/emulator.go

We should skip account checks (nonce checks) on Dry Runs as they are used for gas estimation and it's not expected to provide valid nonce when doing gas estimation on EVM.

[EVM] Skip nonce check on dry runs

---

engine/execution/rpc/engine.go
engine/execution/rpc/engine_test.go
model/flow/chunk.go
model/flow/event_test.go

Close https://github.com/dapperlabs/flow-go/issues/6959#issuecomment-2071211198
This PR adds the check that when there is no event for a block check if it's consistent with the event hash in the execution result, which should be the default hash for an empty event collection.

adding checks when a block has no events

---

go.mod
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

We're using a forked version anyway, so this doesn't change the actually run version.

[Access] rollback boxo to 0.17

---

integration/tests/access/cohort3/grpc_state_stream_test.go
network/p2p/inspector/validation/control_message_validation_inspector_test.go
network/p2p/scoring/registry_test.go
network/p2p/tracer/gossipSubMeshTracer_test.go
network/p2p/tracer/gossipSubScoreTracer_test.go

This PR updates the hooked loggers used in the network/p2p tests. Currently these hooks are writing all logs to std.Out causing long test runs, and making it causing github actions raw log downloads and inspection to fail.

Fix flakey network/p2p tests

---

integration/tests/access/cohort1/access_api_test.go
integration/tests/access/cohort3/collection_indexing_test.go
integration/tests/access/cohort3/execution_state_sync_test.go
integration/tests/access/cohort3/grpc_state_stream_test.go
integration/tests/access/cohort3/grpc_streaming_blocks_test.go
integration/tests/epochs/base_suite.go
integration/tests/ghost/ghost_node_example_test.go

Experimenting to see if this helps speed up the tests. at the very least it will make it so we can download the Access Cohort 3 test logs

[CI] Reduce log level in integration tests

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.25](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.25)
- [onflow/cadence v1.0.0-preview.25](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.25)

Update to Cadence v1.0.0-preview.25

---

cmd/util/ledger/migrations/cadence_values_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Same as #5834 for the atree inlining feature branch
Merge `feature/stable-cadence` into `feature/atree-inlining-cadence-v1.0`, and update to Cadence v1.0.0-preview-atree-register-inlining.25

Sync atree inlining branch Cadence 1.0 and update to Cadence v1.0.0-preview-atree-register-inlining.25

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
engine/execution/computation/computer/computer.go
fvm/context.go
fvm/fvm.go
fvm/storage/block_database.go
fvm/storage/derived/derived_block_data.go
fvm/storage/derived/table.go
fvm/storage/primary/block_data.go
integration/testnet/client.go
integration/tests/access/cohort1/access_api_test.go
module/execution/scripts.go
module/execution/scripts_test.go
module/state_synchronization/indexer/indexer_core.go
module/state_synchronization/indexer/indexer_core_test.go
module/state_synchronization/indexer/indexer_test.go
module/state_synchronization/indexer/util.go
module/state_synchronization/indexer/util_test.go
storage/pebble/cache.go
storage/pebble/lookup.go
storage/pebble/registers.go
storage/pebble/registers_cache.go
utils/dsl/dsl.go

Backports the following changes from v0.33:
* https://github.com/onflow/flow-go/pull/5347
* https://github.com/onflow/flow-go/pull/5585
Add a simple cache for register lookups on Access nodes. This improves the performance of scripts that lookup frequently queried registers, like common contract code.
Add support for running the programs cache on Access nodes with script execution enabled. This improves overall script execution performance since the most common cadence contracts will be cached.

[Access] Backport register and program cache to master

---

cmd/collection/main.go
cmd/consensus/main.go
engine/unit.go
module/epochs/machine_account.go
module/epochs/machine_account_test.go
module/metrics.go
module/metrics/labels.go
module/metrics/machine_account.go
module/metrics/namespaces.go
module/metrics/noop.go

This PR updates machine account status reporting, in preparation for [FLIP 74](https://github.com/onflow/flips/blob/main/governance/20230323-transaction-fee.md) which we anticipate being applied around the Crescendo spork. 
- Adds metrics for machine account misconfiguration and account balance notification (previously only logged)
- Adds metric for recommended minimum, so operators can uniformly alert on `balance - min < 0`
- Adds the machine account address in the metric's constant labels
- Runs reporter routine persistently in the background, with a longer polling period
- Replaces `engine.Unit` with `ComponentManager`
Node reporting a misconfiguration:
Node reporting balance changes:
Suggested query for balance alerts:

[Mainnet25] Update Machine Account Status Reporting for FLIP 74

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration.go

Reuse the cache added in https://github.com/onflow/cadence/pull/3232 across different accounts in the entitlements migration

Reuse static type cache across migrations in different accounts

---

fvm/evm/handler/blockstore_test.go
fvm/evm/types/block.go

Closes: #5846 
Add RLP decoding of blocks before the breaking change of introducing new `timestamp` field. This was introduced in the PR: https://github.com/onflow/flow-go/pull/5660 and it created an issue for the blockstore to decode blocks that are lacking the timestamp field.

[EVM] Add decoder for blocks without timestamp

---

network/p2p/connection/connection_gater_test.go
network/p2p/scoring/registry_test.go
network/p2p/scoring/subscription_validator_test.go

This PR quarantines flakey tests. 
- TestConnectionGating_ResourceAllocation_AllowListing
- TestSubscriptionValidator_Integration
- TestScoringRegistrySilencePeriod

Quarantine flakey network tests

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update `feature/atree-inlining-cadence-v0.42` to [v0.42.11-atree-register-inlining.2](https://github.com/onflow/cadence/releases/tag/v0.42.11-atree-register-inlining.2)
See https://dapperlabs.slack.com/archives/CG0B7CJAJ/p1715099929473579

Update to Cadence v0.42.11-atree-register-inlining.2

---

fvm/environment/block_info.go
fvm/environment/block_info_test.go
utils/unittest/fixtures.go

Closes #5852
#5607 broke the `getBlock` function in Cadence.
When a block is not available, indicate it via the `exists` return value, but do not return an error.
`blockInfo` had no tests, which is why #5607 silently broke the `getBlock` function.
This PR fixes the bug and adds a test for `blockInfo`.

Do not return an error when block is unavailable due to expiry

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.26](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.26)
- [onflow/cadence v1.0.0-preview.26](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.26)

Update to Cadence v1.0.0-preview.26

---

engine/execution/computation/manager.go
fvm/fvm_test.go

These are unblocked by Cadence 1.0, and can be enabled with its release

Enable attachments on mainnet

---

model/flow/protocol_state.go
state/protocol/badger/mutator_test.go
state/protocol/protocol_state/epochs/factory.go
state/protocol/protocol_state/epochs/fallback_statemachine.go
state/protocol/protocol_state/epochs/fallback_statemachine_test.go
state/protocol/protocol_state/epochs/happy_path_statemachine_test.go

https://github.com/onflow/flow-go/issues/5717
https://github.com/onflow/flow-go/issues/5724
https://github.com/onflow/flow-go/issues/5726
This PR adds data types and logic for extending current epoch using approach based around `EpochExtension`s. 
It is implemented by extending `EpochStateContainer` in Dynamic Protocol State to support an extra field `EpochExtensions`. 
The `epochs.FallbackStateMachine` implements logic to add epoch extensions when needed. 
There are several rules when and how epoch is extended:
1. If we are entering EFM we are checking if the next epoch has been committed, if not then we drop whatever intermediate state that was previously setup for the next epoch.
2. If next epoch has been committed then no epoch extensions are added to the current epoch since we want …

[EFM Recovery] Dynamic Protocol State injects `EpochExtension`s

---

integration/benchmark/account/account_provider.go
integration/benchmark/load/load_type.go
integration/benchmark/load/load_type_test.go
integration/benchmark/load/token_transfer_multiple_load.go
integration/benchmark/scripts/scripts.go
integration/benchmark/scripts/tokenTransferMultiTransaction.cdc
integration/benchmark/server/load-config.yml

closes: https://github.com/onflow/flow-go/issues/5329 
Adding a new load type to the TPS automation:
- **token-transfer-multi**: Multiple flow token transfers in one transaction. By default 100, but can be settable in the future.

Add new TPS loader load type

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go

Closes: #5423 
Execution data is synced when a block is sealed. So when you dynamically bootstrap a node, it will start syncing from the sealed height forward. At the beginning of a spork, the root finalized and sealed blocks are the same. When starting from a snapshot, but not from the beginning of a spork they are typically about 6 blocks apart.

Fixed initial block height value for execution data requester

---

fvm/evm/handler/blockstore_test.go
fvm/evm/types/block.go
fvm/evm/types/block_test.go

Support decoding of all previous block types. Block types were changing during development and since it was deployed on previewnet we must make sure we can decode those previously stored blocks.

[EVM] Support decoding of all previous block types

---

fvm/evm/handler/blockstore_test.go
fvm/evm/types/block.go

This PR fixes decoding of blocks that do have timestamp field but not yet have total gas used field. 
There was a period when these blocks were stored on previewnet and we need to handle decoding of such types.

[EVM] Fix decoding blocks with no total gas used

---

fvm/environment/block_info.go
fvm/environment/block_info_test.go

This PR is to [revert the change from this PR](https://github.com/onflow/flow-go/pull/5895). We should not merge this PR unless it is to be deployed with an HCU. 
Update: HCU is scheduled for May 15, merging it now.

v0.33 enable get block fix

---

engine/execution/state/state.go

Backport: https://github.com/onflow/flow-go/pull/5903

Backport: Fix get highest executed and finalized height

---

engine/execution/state/state.go

This PR fixes an issue in GetHighestFinalizedAndExecution function.

Fix get highest executed and finalized height

---

module/signature/type_encoder.go

fixes https://github.com/onflow/flow-go/issues/5899
`module/signature` is imported by the flow-emulator and is causing a build error when built without cgo (in the wasm build). This PR makes a minor change with no functional change, to avoid the build error.

Fix wasm build in `module/signature`

---

cmd/util/ledger/migrations/atree_register_migration.go
cmd/util/ledger/migrations/cadence_value_validation.go
cmd/util/ledger/migrations/cadence_value_validation_test.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
cmd/util/ledger/migrations/fix_broken_data_migration.go
cmd/util/ledger/migrations/utils.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

This PR optimizes atree migration by using new atree functions:
- `NondeterministicFastCommit()` for nondeterministic commit to atree storage
- `BatchPreload()` to preload atree slabs in parallel
Informal test showed ~15% speedup (about 1 hour 20 minutes faster) on m1 vm using `nworkers=40` with all storage checks and validations enabled.  Using more cpu cores or different input data (testnet vs mainnet data) may show different speedups.
Changes to migration program in flow-go is not extensive because most of the changes are in onflow/atree repo.  More info at: http://github.com/onflow/atree/releases

Optimize Cadence v0.42 + atree inlining migration

---

cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/migrations/deploy_migration_test.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
cmd/util/ledger/migrations/fix_broken_data_migration_test.go
cmd/util/ledger/util/registers/registers.go

At the end of the migration, registers are converted back to payloads.
This effectively doubles the memory usage, as the key-value pairs are stored both in the registers and in the newly created payloads.
Reduce peak memory usage, by allowing the garbage collection of account registers that have already gotten converted to payloads.
This change brings peak memory usage back to similar, and at times even lower, levels before #5897.
Also optimize speed by creating payloads in parallel.

Optimize creation of new payloads

---

cmd/util/ledger/migrations/account_storage_migration.go
cmd/util/ledger/migrations/cadence_value_diff.go
cmd/util/ledger/migrations/cadence_value_diff_test.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
cmd/util/ledger/migrations/fix_broken_data_migration.go
cmd/util/ledger/migrations/staged_contracts_migration_test.go
cmd/util/ledger/migrations/utils.go
cmd/util/ledger/util/registers/registers.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

This PR updates Cadence 1.0 migration to use newer and faster functions provided by atree:
- `NondeterministicFastCommit()` as faster alterative to `FastCommit()`
- `BatchPreload()` to decode slabs in parallel
More details at https://github.com/onflow/atree/releases
Equivalent change for atree migration (not Cadence 1.0 migration) was 1h20m faster on m1 with nworkers=40 and all storage checks & validation enabled.  However, speedup can vary depending on number of cpus, input data (mainnet vs testnet), etc.
`NondeterministicFastCommit` placed all instances of storage `Commit()` in Cadence migrations.
`BatchPreload()` is only used where all slabs are expected to be loaded:
- storage health check
- Cadence value diff reporter 
- fix broken references migration
- filter unreferenced slab …

Use faster atree funcs to speedup Cadence 1.0 migration

---

cmd/util/ledger/migrations/migrator_runtime.go
fvm/storage/state/execution_state.go
fvm/storage/state/spock_state.go
fvm/storage/state/spock_state_test.go
fvm/storage/state/transaction_state.go

closes: https://github.com/onflow/flow-go/issues/5919

Disable spock proof generation for migrations

---

state/protocol/protocol_state/epochs/base_statemachine.go
state/protocol/protocol_state/epochs/fallback_statemachine.go
state/protocol/protocol_state/epochs/fallback_statemachine_test.go
state/protocol/protocol_state/epochs/happy_path_statemachine.go
state/protocol/protocol_state/epochs/statemachine.go

https://github.com/onflow/flow-go/issues/5726
Previously we could maintain EFM only if we have entered it in staking or setup phases, if we have entered EFM when next epoch has been already committed then we wouldn't perform epoch transition because `FallbackStateMachine` ignored request for transition to the next epoch. 
This PR updates `FallbackStateMachine` to use the same logic for epoch transitions as the happy path. Additionally activated previously disabled tests and restructured logic.

[EFM] Transition to committed epoch in EFM

---

cmd/util/ledger/migrations/account_based_migration.go
cmd/util/ledger/migrations/account_size_filter_migration.go
cmd/util/ledger/util/registers/registers.go
cmd/util/ledger/util/topn.go
cmd/util/ledger/util/topn_test.go

Depends on #5897
Currently, the migrations of accounts are scheduled in address order. If there are large accounts at high addresses, the migration might end up waiting for a these accounts, with most available workers idling.
Schedule the migration of large accounts first to increase utilization of available workers.

Improve scheduling in account-based migration

---

engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/backend_scripts_test.go

Closes: #5876
Backports: https://github.com/onflow/flow-go/pull/5877

[Access] Failover when script exceeds computation or memory limit - backport

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.29](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.29)
- [onflow/cadence v1.0.0-preview.28](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.28)

Update to Cadence v1.0.0-preview.28

---

fvm/evm/evm_test.go
fvm/evm/handler/handler.go

Closes: #5902 
Don't return an error if validation issue is encountered, instead return a result.

[EVM] Return result on validation error

---

engine/execution/state/bootstrap/bootstrap_test.go
fvm/evm/stdlib/contract.cdc
fvm/evm/stdlib/contract_test.go
utils/unittest/execution_state.go

Related: #5422 
Follow up on #5892
Including suggestions from @turbolent in the original PR

[EVM] EVMAddress de/serialization follow up

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/change_contract_code_migration.go
cmd/util/ledger/migrations/deploy_migration.go

See https://discord.com/channels/613813861610684416/1167476806333513800/1239682951923368016
The reduced version of the EVM contract is now deployed to TN and MN. These contracts need to be updated to the full EVM contract in the migration.
In the old Emulator state, the EVM contract does not exist at all, so the full EVM contracts needs to get deployed.

Update or deploy EVM contract, depending on chain

---

state/protocol/badger/mutator.go
state/protocol/badger/state.go

- Replace direct inspection of service events at the `FollowerState` level with use of the Dynamic Protocol State API. 
- Simplifies `isFirstBlock` function
This addresses the following item from https://github.com/onflow/flow-go/issues/5666: 
> We still directly operate on service events to emit epoch-related metrics events in the FollowerState ([code](https://github.com/onflow/flow-go/pull/5477/files#diff-c79d3fc5d32f153917b7cd923ab4ba64ef22f12268ddd13f353a06391f68a96dR880)). We should instead emit metrics events using the Protocol State field, and only manipulate service events with the StateMutator and protocol state machines (lower level logic).

Use Dynamic Protocol State API to compute events / metrics

---

fvm/environment/block_info.go
fvm/environment/block_info_test.go

Reverts onflow/flow-go#5896, because there is no HCU mainnet to deploy this, however, it's been deployed to devnet.

Revert "v0.33 enable get block fix"

---

engine/execution/ingestion/core.go
engine/execution/ingestion/core_test.go
engine/execution/ingestion/machine.go

This PR adds test cases for ingestion core engine and metrics.

[Execution] Add ingestion core tests

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.30](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.30)
- [onflow/cadence v1.0.0-preview.29](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.29)

Update to Cadence v1.0.0-preview.29

---

cmd/util/ledger/util/payload_grouping.go
ledger/common/convert/convert.go
ledger/common/convert/convert_test.go
ledger/trie.go
ledger/trie_encoder.go
ledger/trie_test.go
module/state_synchronization/indexer/indexer_core_test.go
storage/pebble/bootstrap_test.go

This PR adds `Payload.Address()` to extract and return payload address.  This can be used (e.g. by migrations) to reduce overhead of extracting address from payload key.
Discussion :thread: https://github.com/onflow/flow-go/pull/5942#issuecomment-2117936857

Add Payload.Address() to allow migrations, etc. to reduce overhead

---

engine/execution/computation/computer/computer.go
fvm/environment/system_contracts.go
fvm/fvm_test.go
fvm/transactionInvoker.go

This fixes 2 issues that were found on the dependency check mechanism:
- indeterministically ordered inputs into the cadence function caused the emitted events to be indeterministic causing a execution result fork (the state was still deterministic).
- the check dependencies function was called in the system transaction. It should not be. (this is a really minor thing, and only helps with a little bit of performance improvement)
The FVM tests originally missed the indeterminism, because it was doing an `require.ElementsMatch` instead of `require.Equal`. It is not enough that the elements match they must also always be in the same order. I also added a test that the authorisers are deterministically ordered and re-ran the same test 100 times (`-test.count 100`).

Fix FVM call to checkDependencies

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

This PR updates flow-go feature branch to use latest commit in Cadence feature branch:
- flow-go feature branch:  [feature/atree-inlining-cadence-v0.42](https://github.com/onflow/flow-go/tree/feature/atree-inlining-cadence-v0.42)
- cadence feature branch: [feature/atree-register-inlining-v0.42](https://github.com/onflow/cadence/tree/feature/atree-register-inlining-v0.42)

Update feature branch feature/atree-inlining-cadence-v0.42

---

cmd/bootstrap/cmd/partner_infos.go
cmd/collection/main.go
cmd/consensus/main.go
cmd/dynamic_startup.go
cmd/util/cmd/common/validation.go
cmd/util/cmd/epochs/cmd/recover.go
module/grpcclient/flow_client.go

Move FlowClient to other package, so that engines can reuse it as well without depending on the top `cmd` package namespace.

move FlowClient to grpcclient package

---

cmd/util/ledger/migrations/cadence_values_migration_test.go

Work towards onflow/cadence#3366
Ensure that the migration is deterministic by asserting in what order the value migration function is called.
Ran this with `go test -count 100 -v -race -run=TestCadenceValuesMigration` locally and it passed.

Assert migration order

---

cmd/util/ledger/migrations/account_based_migration.go
cmd/util/ledger/migrations/contract_checking_migration.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
cmd/util/ledger/migrations/fix_broken_data_migration.go
cmd/util/ledger/migrations/staged_contracts_migration.go
cmd/util/ledger/util/registers/registers.go

Work towards onflow/cadence#3366

Make more parts of the migration deterministic

---

engine/execution/ingestion/fetcher/access_fetcher.go

This PR resolves an issue that when the execution node is running in observer mode and is falling far behind, it's execution might halt on startup due to the guarantee buffer is too small to hold all the collections from loading unexecuted blocks.

[Execution] Increase guarantee buffer

---

fvm/evm/evm_test.go
fvm/evm/handler/handler.go
fvm/evm/types/block.go

Closes https://github.com/onflow/flow-go/issues/5951
For EVM blocks that were produced from `EVM.batchRun`, or COA interactions, the `TotalGasUsed` field was not being calculated.

[EVM] Calculate `EVM.BlockExecuted.TotalGasUsed` for Tx batch runs and COA calls

---

engine/execution/block_result.go

ref: https://github.com/onflow/flow-go/issues/5956
I added more information in the case when `ChunkAt` is about to panic.
Should be ported to master

Add more information to panic

---

cmd/util/ledger/migrations/fix_broken_data_migration.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Currently, all broken testnet data is fixed during atree migration because the default predicate function is passed from flow-go to atree.
Although we want to fix all broken testnet data, we also want to avoid accidentally fixing and not finding out about new broken testnet data.
This PR passes a function provided by Cadence so atree can call it to determine if specific broken data should be fixed during migration.  This allows us to avoid accidentally fixing broken data that we did not know about.

Use Cadence func to decide which testnet data to fix during atree migration

---

cmd/scaffold.go

It was previously only enabled for testnet.

Enable dependency check for all networks

---

fvm/evm/types/codeFinder.go

This method performs the inverse mapping of `ExecutionErrorCode` and `ValidationErrorCode`.
It returns the corresponding error object, given an `ErrorCode` value.

[EVM] Add the `GetErrorForCode` helper method

---

cmd/util/cmd/find-inconsistent-result/cmd.go
cmd/util/cmd/root.go
cmd/util/cmd/update-commitment/cmd.go

Adding a util command to update commitment by block ID.
This is useful for running tests involve state migration. After the state migration, the statecommitment is changed. Using the update commitment tool allows us to continue re-executing transactions.
For instance, testing atree-inlining by rolling back executed height, migrate the state with atree-inlining feature and update commitment to continue re-executing the blocks.

v0.33 add util update commit

---

integration/testnet/network.go

Also remove unneeded hotstuff startup time flag

Disable cruisectl by default in integration tests

---

cmd/scaffold.go

Currently, we validate the root snapshot every time we startup, meaning that for all startups after the first, we are validating the same thing that we wrote to disk.
This causes a problem on v0.33, because some parts of the software expect a sealing segment of length 590+, and others expect a sealing segment of length 600+. In particular, this can cause a node to accept a root snapshot file when bootstrapping, then reject the root snapshot DB-backed object on subsequent startups, because the DB-backed snapshot is returning an invalid sealing segment.

Only validate root snapshot when loading file

---

cmd/util/ledger/migrations/utils.go

Closes #6072 
Currently, migrations don't include AccountCapabilityStorageDomain during traversal and storage health check.  This causes payloads in the domain to not be migrated.
This affects atree migration and maybe also Cadence 1.0 migration.
This commit adds AccountCapabilityStorageDomain to migrations.

Fix migrations missing AccountCapabilityStorageDomain

---

cmd/util/ledger/migrations/utils.go

Closes #6072 
Currently, migrations are not migrating payloads in account capability domain.
This affects atree migration and maybe also Cadence 1.0 migration. Equivalent  PR for Cadence 1.0 is:
- #6074
This PR adds `AccountCapabilityStorageDomain` to migrations so their payloads can get migrated.

Fix atree migration not migrating payloads from AccountCapabilityStorageDomain (feature/atree-inlining-cadence-v0.42)

---

cmd/util/ledger/migrations/utils.go

Closes https://github.com/onflow/flow-go/issues/6069
Currently, migrations don't include PathCapabilityStorageDomain during traversal and storage health check. This causes payloads in the domain to not be migrated.
This affects atree migration and maybe also Cadence 1.0 migration.  Equivalent fix in master branch is:
- #6070 
This PR adds PathCapabilityStorageDomain to migrations.

Fix migrations missing PathCapabilityStorageDomain in feature/atree-inlining-cadence-v0.42

---

cmd/util/cmd/atree_inlined_status/atree_inlined_status_test.go
cmd/util/cmd/atree_inlined_status/cmd.go
cmd/util/cmd/diff-states/cmd.go
cmd/util/cmd/root.go
cmd/util/ledger/util/atree_util.go
cmd/util/ledger/util/state.go

atree-inlined-status command examines atree payloads and outputs JSON showing number of payloads migrated (v1), not migrated (v0), etc.
Among some other flags, user can specify
- n-workers (default=8)
- n-payloads (default=all, number of payloads to sample)
- state
- state-commitment
This program can be used for testing and debugging migration results.  For example, it can be used to confirm the fix in:
- https://github.com/onflow/flow-go/pull/6064
Discord 🧵 https://discord.com/channels/613813861610684416/1248713111943254228/1249711182193885184

Add atree-inlined-status command to util program to check migration results

---

cmd/util/ledger/migrations/utils.go

Closes #6069
Currently, migrations don't include PathCapabilityStorageDomain during traversal and storage health check.  This causes payloads in the domain to not be migrated.
This affects atree migration and maybe also Cadence 1.0 migration.
This PR adds PathCapabilityStorageDomain to migrations.

Fix Cadence 1.0 migration missing PathCapabilityStorageDomain

---

cmd/util/ledger/migrations/atree_register_migration.go
cmd/util/ledger/migrations/utils.go
cmd/util/ledger/migrations/utils_test.go

Closes #6076 
Currently, migrations are silently mishandling payloads from unrecognized domains.
This PR updates atree migration to detect and log unrecognized domains.
For context, some unrecognized domains were found today while manually examining binary payloads data:
- https://github.com/onflow/flow-go/issues/6069
- https://github.com/onflow/flow-go/issues/6072

Detect and log unrecognized domains during migration

---

engine/execution/computation/computer/computer_test.go
engine/execution/computation/computer/result_collector.go
module/metrics.go
module/metrics/example/execution/main.go
module/metrics/execution.go
module/metrics/noop.go
module/mock/execution_metrics.go

ref: [#5598](https://github.com/onflow/flow-go/issues/5598)
We need the execution node to expose the computation intensities metric. In order to do that I refactored the metrics interface and cleaned up metrics collection done by the computer.

Change metrics collection in computer

---

cmd/util/cmd/atree_inlined_status/atree_inlined_status_test.go
cmd/util/cmd/atree_inlined_status/cmd.go
cmd/util/cmd/root.go
cmd/util/ledger/util/atree_util.go
cmd/util/ledger/util/state.go
ledger/complete/ledger.go
model/flow/ledger.go

`atree-inlined-status` command examines atree payloads and outputs JSON showing number of payloads migrated (v1), not migrated (v0), etc.
Among some other flags, user can specify
- n-workers (default=8)
- n-payloads (default=all, number of payloads to sample)
- state
- state-commitment
This program can be used for testing and debugging migration results.  For example, it can be used to confirm the fix in:
- https://github.com/onflow/flow-go/pull/6064
Discord 🧵 https://discord.com/channels/613813861610684416/1248713111943254228/1249711182193885184

Port atree-inlined-status cmd (PR 6063) to feature/atree-inlining-cadence-v0.42

---

fvm/evm/emulator/emulator.go
fvm/evm/evm_test.go
fvm/evm/types/result.go

To correctly compute the gas estimation with `EVM.dryRun`, we need to add any gas refunds to the used gas.
Any potential gas refunds are required during transaction execution, and only after they are refunded to the transaction author.

[EVM] Take into account gas refunds in `EVM.dryRun`

---

model/flow/sealing_segment.go
model/flow/sealing_segment.md
state/protocol/badger/snapshot.go
state/protocol/badger/snapshot_test.go

https://github.com/onflow/flow-go/pull/5673 modified the sealing segment length to always use 590 extra blocks, which can produce invalid snapshots in some circumstances. This PR reverts the portion of that PR which modifies SealingSegment length, so that sealing segments always contain at least 600 blocks in total (required in bootstrapping validation). See https://dapperlabs.slack.com/archives/CUU2KQL4A/p1717002753935329 for additional context.

[v0.33] Revert sealing segment length changes from #5673

---

integration/tests/access/cohort3/grpc_state_stream_test.go
integration/tests/access/cohort3/grpc_streaming_blocks_test.go

Remove custom cruise control overrides in Access integration tests. These were copied from old tests that now have different values for this setting. Using default to see if that helps with flakiness, or at least don't add more.

[CI] Remove cruise control overrides in Access integration tests

---

integration/tests/epochs/base_suite.go
integration/tests/epochs/cohort2/epoch_join_and_leave_sn_test.go
integration/tests/epochs/cohort2/epoch_join_and_leave_vn_test.go

Use a uniform 250ms block time target for other epoch tests. 
Ran 10 CI runs against https://github.com/onflow/flow-go/pull/6061/commits/058e3c4e76f292c060957b7a6111fa2a25f3dc57 with 0 epoch test failures.

[Flaky Tests] Testing adjusting safety threshold and block time variables

---

cmd/util/ledger/migrations/cadence_value_diff.go

Currently, dict key comparison uses nil `*interpreter.Interpreter`. This causes a panic if dict key is enum type and interpreter is needed to retrieve type info for comparison.
This PR prevents the panic by passing non-nil `Interpreter` for dict key comparisons.
This was discovered while running diff-states on testnet states.

Fix panic in `diff-states` command when comparing enum dict key

---

cmd/util/cmd/diff-states/cmd.go
cmd/util/cmd/diff-states/diff_states_test.go
cmd/util/ledger/migrations/cadence_value_diff.go

Closes #6091
Currently, it takes days to run `diff-states` on mainnet state because comparisons are not done in parallel.
This PR optimizes diff-states cmd by adding concurrency to:
- diff accounts in parallel
- diff domains in parallel
Discussion: https://discord.com/login?redirect_to=%2Fchannels%2F613813861610684416%2F1250927028702806136%2F1250965995636527154
cc: @turbolent

Optimize diff-states cmd by comparing data in parallel

---

cmd/util/ledger/migrations/cadence_value_diff.go

Currently, `diffCadenceValues()` is used in `diffCadenceDictionaryValue()` to compare dict keys in old and new dict values.  The complexity is O(n^2) where n is number of keys.
This commit removes explicit key comparisons in `diffCadenceDictionaryValue()` and detects not-found keys when retrieving elements for comparisons. The complexity is O(n) where n is number of keys.
Speedup for 1 account using 10 goroutines (from diff-states logs on gcp):
- before: 1 hour 9 minutes
- after:  1 minute 18 seconds
For best results, this PR should be used with:
- https://github.com/onflow/flow-go/pull/6097
- https://github.com/onflow/flow-go/pull/6105
When combined with PRs 6097 and 6105, this improvement allows diff-states to compare mainnet state:
- before: manually stopped after 6+ days
- after: …

Speedup diff-states by over 50x (6+ days -> under 3 hours) by removing old bottleneck

---

cmd/util/cmd/find-trie-root/cmd.go
cmd/util/cmd/root.go
ledger/complete/wal/encoding.go
ledger/complete/wal/encoding_test.go

This PR adds a util command to find trie root hash in the wal file. It allows us to roll back executed height to any height.
Context: the current util allows us to roll back executed height to any height, which remove the execution results in the database. However, the EN is not able to start up, because the checkpoint and wal file has not been rollback to the corresponding height. 
Rolling back the checkpoint and wal has been quite difficult, we've made tool to find the block for the block, however, it only allow us to roll back executed height to the block of the checkpoint. In order to be able to roll back to any height, we need to find the trie root hash in the wal files, and this is what this find trie root hash util is made for.

Add util for finding trie root hash

---

cmd/scaffold.go
network/p2p/cache/protocol_state_provider.go
state/protocol/events/logger.go

This PR adds some height and view to the logs when epoch events happen.

Log epoch height view

---

cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/contract_checking_migration.go
fvm/environment/accounts.go

Avoid iterating over all registers just to find the contract code registers, by getting all contract names from the contract names register, and directly looking up contract code registers.
This required exposing the contract names register encoding and decoding.

Optimize contracts checking migration

---

cmd/util/cmd/diff-states/cmd.go

Though it may seem non-sensical to compare on the value level if there are no differences on a raw level, as mentioned in the usage of the flag, this is mostly useful when comparing a state with itself, e.g. when trying to test that a state can be iterated over on a value level

Improve diff tool: Add a flag which forces value comparison

---

cmd/util/ledger/migrations/account_based_migration.go
cmd/util/ledger/util/registers/registers.go
cmd/util/ledger/util/topn.go
cmd/util/ledger/util/topn_test.go

Closes #6130
This ports @turbolent's optimization to process largest accounts first since they take longer.

Port PR 5901 from Cadence 1.0 migration to atree migration

---

engine/execution/state/bootstrap/bootstrap_test.go
fvm/evm/stdlib/contract.cdc
fvm/evm/stdlib/contract_test.go
utils/unittest/execution_state.go

[Flow EVM] add uuids to the deposit and withdraw events

---

fvm/evm/emulator/emulator.go
fvm/evm/evm_test.go

Closes: https://github.com/onflow/flow-go/issues/6135
Addresses the case from [EIP-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md#specification)
> - Define "all but one 64th" of N as N - floor(N / 64).
> - If a call asks for more gas than the maximum allowed amount (i.e. the total amount of gas remaining in the parent after subtracting the gas cost of the call and memory expansion), do not return an OOG error; instead, if a call asks for more gas than all but one 64th of the maximum allowed amount, call with all but one 64th of the maximum allowed amount of gas (this is equivalent to a version of EIP-90https://github.com/ethereum/EIPs/issues/90 plus EIP-114https://github.com/ethereum/EIPs/issues/114). CREATE only provides all but one 64th of the parent gas to the child …

Add a buffer gas of "all but one 64th" for gas used on `EVM.dryRun`

---

fvm/evm/emulator/emulator.go
fvm/evm/emulator/emulator_test.go
fvm/evm/types/call.go
fvm/evm/types/call_test.go

Closes: #6115 
To support the 3rd party tools that are not Flow aware, we compute the hash for the direct calls using Legacy Tx format. Yet we don't have signatures, and the uniqueness of hash values is dependent on the source (From field) and nonce. In this PR we define a canonical format for the legacy tx where we include the source information as part of the signatures (V) and we also define what should be set for R, and S.

[Flow EVM] fix the issue with the hash calculation of the direct calls

---

tools/move-checkpoint.sh

This PR adds a tool to move checkpoint files. It does both moving and renaming.
See the following example:
```
root@mainnettest-24-execution:/var/flow# bash move-checkpoint.sh test/checkpoint.001 test/root.checkpoint
Moved: /var/flow/test/checkpoint.001 -> /var/flow/test/root.checkpoint
Moved: /var/flow/test/checkpoint.001.000 -> /var/flow/test/root.checkpoint.000
Moved: /var/flow/test/checkpoint.001.001 -> /var/flow/test/root.checkpoint.001
Moved: /var/flow/test/checkpoint.001.002 -> /var/flow/test/root.checkpoint.002
Moved: /var/flow/test/checkpoint.001.003 -> /var/flow/test/root.checkpoint.003
Moved: /var/flow/test/checkpoint.001.004 -> /var/flow/test/root.checkpoint.004
Moved: /var/flow/test/checkpoint.001.005 -> /var/flow/test/root.checkpoint.005
Moved: …
```

[Tools] Add a script to move checkpoint files

---

cmd/util/ledger/migrations/cadence_test.go
cmd/util/ledger/migrations/contract_checking_migration.go
cmd/util/ledger/migrations/migration_metrics_collector.go

Fix  Cadence 1.0 migration: Ignore empty contracts when checking all contracts

---

integration/benchmark/cmd/ci/main.go

We are moving our BigQuery tables to a new project, and this change will ensure the new project is used. A new table has been created, and the existing service account has been granted write access to the table.

Update TPS monitor automation to write to new BigQuery table

---

model/convert/service_event.go

Fixes: https://discord.com/channels/613813861610684416/1108479699732152503/1254802566139740293
`invalidCadenceTypeError` can cause NPEs when generating the error message, since `expectedType` passed into the method is always the zero-value of the corresponding Go-type. Then the `expectedType.Type()` can be `nil`, and hence `expectedType.Type().ID()` would cause a NPE.
Instead, print the Go-type. This makes even more sense, since this error is thrown only if the Go-types are mismatching.

Fix `invalidCadenceTypeError` creation

---

.github/workflows/actions/test-monitor-process-results/action.yml
.github/workflows/flaky-test-monitor.yml

This PR updates the Flaky Test Monitor workflow to leverage a new BQ table in a separate project. As part of this change, we are using Workload Identity rather than Service Account keys to ensure that we do not rely on persistent secrets. The changes have been made to the repo to make the appropriate secrets/envs available to the workflow.
For an example run of this, please reference the following [workflow run](https://github.com./onflow/flow-go/actions/runs/9652826902).

Update Flaky test monitor to use new table

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/contract_cleanup_migration.go
cmd/util/ledger/migrations/contract_cleanup_migration_test.go

Follow-up to onflow/cadence#3436
Inspired by the old contract deduplication migration, https://github.com/onflow/flow-go/blob/feature/atree-inlining-cadence-v0.42/cmd/util/ledger/migrations/deduplicate_contract_names_migration.go

Improve Cadence 1.0 migration: Clean up contract names and code

---

engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/script_comparer.go
engine/access/rpc/backend/script_comparer_test.go

This PR reduces logging related to script execution on Access nodes by making the following changes:
* Log script results comparison differences at `Debug` level
* Use the logging frequency gate for all log messages that contain the script. When the script has been logged recently, just log the hash
* Log script results in base64 instead of hex.

[Access] Reduce logging for script executions

---

cmd/util/cmd/diff-states/cmd.go
cmd/util/cmd/diff-states/diff_states_test.go
cmd/util/ledger/reporters/reporter_output.go
cmd/util/ledger/reporters/reporter_output_test.go

Closes #6175 
Currently, `reports.ReportWriter` outputs all JSON objects to the same JSON array, which can cause JSON parsers like jq to crash on very large reports.
This PR adds support for JSONL format, so each JSON object is output to a separate line in the output file.  This allows each object to be parsed independently (rather than requiring every object in the array to be parsed).
While at it, modify the `diff-states` command to use JSONL format because it can generate 20GB reports.

Add support for JSONL report format as alternative to JSON array report

---

cmd/execution_builder.go
integration/go.mod
integration/go.sum
integration/localnet/builder/bootstrap.go
ledger/complete/wal/checkpointer.go

Close https://github.com/onflow/flow-go/issues/6167. 
This PR reduce bootstrapping time by creating soft links of checkpoint files instead of copying them. Could save ~10 mins for bootstrapping.
Tested on mainnet test EN, and worked.

Link checkpoint on bootstrapping

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.38](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.38)
- [onflow/cadence v1.0.0-preview.36](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.36)

Update to Cadence v1.0.0-preview.36

---

tools/move-checkpoint.sh

This PR fixes an issue in the move-checkpoint.sh tool that a subfile didn't get moved.

[Tool] Add the missing checkpoint subfile to be moved

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
cmd/util/ledger/util/payload_file.go

Currently, when migrations specify a payloads file as output (instead of checkpoint), the new trie is created with migrated payloads first and then migrated payloads are written to payload file.
This PR optimizes migrations that generate payloads file as output by creating new trie with migrated payloads in parallel.
While at it, also refactored code related to:
- extracting payloads from different input (payload file and checkpoint file)
- exporting payloads to different output (payload file and checkpoint file)
This optimization reduces atree migration duration by about 21 minutes on a test vm (m1-ultramem-160 using nworkers=150 to migrate old testnet state).

Optimize migrations by creating output payloads file in parallel to new trie creation

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/execution-state-extract/execution_state_extract_test.go

This port to master is for completeness only because atree migration in a feature branch is used for creating the atree inlined payloads file for other migrations to use (e.g. Cadence 1.0 migration).
- From PR: https://github.com/onflow/flow-go/pull/6193
- From Branch: https://github.com/onflow/flow-go/tree/feature/atree-inlining-cadence-v0.42
Currently, when migrations specify a payloads file as output (instead of checkpoint), the new trie is created with migrated payloads first and then migrated payloads are written to payload file.
This PR optimizes migrations that generate payloads file as output by creating new trie with migrated payloads in parallel.
While at it, also refactored code related to:
- extracting payloads from different input (payload file and checkpoint file)
- …

Port PR 6193 to master (speedup migration by ~21 minutes on m1-ultramem-160)

---

ledger/complete/wal/checkpoint_v6_test.go

Fix https://github.com/onflow/flow-go/issues/6166
This PR fixes an issue that the `OpenAndReadLeafNodesFromCheckpointV6` function assumes all the leaf nodes are stored in subtrie files and read from them. However, when the trie only has very few nodes, it's possible some subtrie branch isn't deep enough, the subtrie is empty, and some payload has to be stored in the top trie leaf nodes. This would cause an issue that those payload stored in top trie will not be read. That's why it caused the `TestWriteAndReadCheckpointV6LeafMultipleTriesOK` test case to be flakey, since it create a trie with 40 payloads, if running many times, it will hit the case where a payload gets stored to a toptrie, and fail the test case.
It's not an issue for Testnet or Mainnet, where they have way more payloads …

When reading leaf nodes from a checkpoint, also read from the top trie

---

cmd/util/ledger/migrations/cadence_values_migration.go
engine/execution/computation/execution_verification_test.go
fvm/fvm_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.39](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.39)
- [onflow/cadence v1.0.0-preview.37](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.37)

Update to Cadence v1.0.0-preview.37

---

fvm/systemcontracts/system_contracts.go

Closes https://github.com/onflow/flow-go/issues/6210
Closes https://github.com/onflow/flow-go/issues/6142

Add missing System Contracts

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.40](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.40)
- [onflow/cadence v1.0.0-preview.38](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.38)

Update to Cadence v1.0.0-preview.38

---

cmd/util/cmd/root.go
cmd/util/cmd/run-script/cmd.go

Add a new util command `run-script`, which can read in a state from a payloads file, or alternatively from a trie and a state commitment, runs a script, and prints the JSON-encoded result of the script.
This is useful for debugging purposes.

[Util] Add command to run a script

---

cmd/util/cmd/execution-state-extract/cmd.go

Fix assignment of migrated payloads, remove accidental variable shadowing
It would be great to have (a) test(s) for the migration path of the execution state extraction command.
@fxamacker already checked the pre-1.0 branch, and the bug does not exist there:
https://github.com/onflow/flow-go/blob/feature/atree-inlining-cadence-v0.42/cmd/util/cmd/execution-state-extract/cmd.go#L339

[Util] Fix execution state extraction

---

cmd/util/cmd/run-script/cmd.go

- Improve logging
- Read script before lengthy state loading

[Util] Improve run script command

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/change_contract_code_migration.go
cmd/util/ledger/migrations/deploy_migration.go
fvm/evm/stdlib/contract.go
fvm/evm/stdlib/contract_minimal.cdc

Add a new EVM contract change mode that deploys the minimal EVM contract (ABI-only) and updates it to the full contract.
This is the same strategy we currently use for TN and MN: We already manually deployed a minimal, pre-1.0 Cadence contract to those chains, and during the migration, we will update it to the full contract.
However, for the Emulator we want to do this automatically for users.
See https://discord.com/channels/613813861610684416/1263903370574430239 for more information.

[Cadence 1.0 migration] Improve EVM contract migration

---

cmd/util/ledger/migrations/burner.go
cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/deploy_migration.go
cmd/util/ledger/migrations/evm.go
cmd/util/ledger/util/programs.go
cmd/util/ledger/util/registers/registers.go
engine/execution/state/bootstrap/bootstrap_test.go
fvm/evm/stdlib/contract.cdc
utils/unittest/execution_state.go

Depends on #6249 
When the EVM contract is updated from minimal to full contract, the `EVM.Heartbeat` resource must be set up.

[Cadence 1.0 migration] Add migration to setup EVM heartbeat resource

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.43](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.43)
- [onflow/cadence v1.0.0-preview.40](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.40)

Update to Cadence v1.0.0-preview.40

---

fvm/evm/emulator/emulator.go
fvm/evm/emulator/emulator_test.go

This PR makes sure the tracer gets a possible invalid error passed in, instead of currently getting passed in `err` which anyway is nil, and that is causing a panic in the tracer implementation, because if the error is nil it assumes there are calls made which isn't the case for invalid tx.

[EVM] Trace supplied with invalid error

---

cmd/util/ledger/migrations/contract_cleanup_migration.go
cmd/util/ledger/migrations/contract_cleanup_migration_test.go

Sort the list of contract names before iterating over it. Go `map`s do not have a deterministic iteration order

[Cadence 1.0 migration] Fix non-determinism in contract code and contract names cleanup migration

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_test.go
cmd/util/ledger/migrations/change_contract_code_migration.go
cmd/util/ledger/migrations/change_contract_code_migration_test.go
cmd/util/ledger/migrations/contract_checking_migration.go
cmd/util/ledger/migrations/staged_contracts_migration.go

System contracts should always check. Report errors, even when verbose error reporting is turned off

[Cadence 1.0 migration] Always report checking errors for system contracts

---

fvm/evm/emulator/state/base.go
fvm/evm/emulator/state/delta.go
fvm/evm/emulator/state/stateDB.go
fvm/evm/emulator/state/stateDB_test.go

[Flow EVM] Backport of #6289

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/util/registers/registers.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Depends on https://github.com/onflow/cadence/pull/3511

 Fix migration of storage path capabilities

---

state/protocol/protocol_state/epochs/fallback_statemachine.go
state/protocol/protocol_state/epochs/fallback_statemachine_test.go

This PR updates how `FallbackStateMachine` processes epoch recover event so the state isn't modified if an invalid event has been supplied. 
Added extended test case to ensure correct behavior.

[EFM] Fix `EpochRecover` processing in EFM

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration_test.go

Fix `IssueStorageCapConMigration`: After issuing the capability controllers, commit the changes to storage, and merge the write set into the migrated registers.
Also, add tests to verify the migrated state. Currently the assertions only assert reports.

[Cadence 1.0 Migration] Merge and commit changes after issuing cap cons

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.47](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.47)
- [onflow/cadence v1.0.0-preview.44](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.44)

Update to Cadence v1.0.0-preview.44

---

fvm/evm/debug/tracer.go
fvm/evm/debug/tracer_test.go
fvm/evm/emulator/emulator.go
fvm/evm/emulator/emulator_test.go
fvm/evm/handler/handler_test.go
fvm/evm/types/result.go

The tracer can be used for multiple transactions and later collect results being called. We need to support storing interim results until the collection time. 
Unfortunately, the call tracer is stateful and if not cleaned up could result in bugs. for example, a failed transaction might change the internal state of the call tracer and the next transaction would start from an invalid state. This usually result in an "incorrect number of top-level calls" error. 
This PR updates the tracer to collect and hold on to the tracing results after each transaction execution (onTxEnd) and reset the internal state of the tracer before each transaction execution (onTxStart).
It also makes the trace collection during batchRun function more clear.

[Flow EVM] patch evm debug tracer to collect results and reset internal state after each tx execution

---

cmd/util/cmd/root.go
cmd/util/cmd/system-addresses/cmd.go

Add a command similar to `addresses`, which prints the addresses of all system accounts, based on the information in the system contracts struct

[Util] Add a command to print all system addresses

---

engine/common/version/version_control.go

Devnet51's root protocol state snapshot does not include information about past version beacon events like it's supposed to, so none of the ANs/ENs have events in their DBs. This was causing ANs to log messages at info level for each height. 
The version control also only updated the processed height counter when an event was found causing cascasing log events. This reduces the log level and fixes the counter update

[Access] Reduce logging from version control

---

engine/access/rest/middleware/logging.go
engine/access/rpc/backend/backend_scripts.go

Reduce logs emitted form Access APIs:
* Log local script execution failures at debug level. These are largely errors about unindexed blocks.
* Log REST api errors at info level instead of error

[Access] Reduce logging on some access endpoints

---

module/epochs.go
module/epochs/epoch_lookup.go
module/epochs/epoch_lookup_test.go
state/protocol/protocol_state/epochs/identity_ejector.go

for our `EpochLookup` we have introduced the auxiliary component `epochRangeCache`. While the implementation is highly optimized (using an array of value types as opposed to pointers for improved data locality), it leaked implementation details (specifically the concept of zero values representing the "undefined" value). The documentation was hardly clarifying this special meaning of the zero value, and in [some areas was still (incorrectly) talking about nil values](https://github.com/onflow/flow-go/blob/2aeebea1359c9089633de5608fad1405c1adb1c3/module/epochs/epoch_lookup.go#L37-L38). 
This PR:
* cleans up the documentation
* increases encapsulation so that the `EpochLookup` does not need to concern itself with the implementation detail how  `epochRangeCache` represents the undefined …

[EFM] minor polishing

---

fvm/environment/meter.go
model/flow/constants.go

closes: https://github.com/onflow/flow-go/issues/6346
I also fixed the `MainnetExecutionEffortWeights`. They are used for some tests.
This does not require an HCU

[FVM] Update fee related constants

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.51](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.51)

Update to Go SDK v1.0.0-preview.51

---

state/protocol/kvstore.go
state/protocol/protocol_state/epochs/statemachine.go

This is an amendment to Yurii's PR https://github.com/onflow/flow-go/pull/6318. In his PR, [Yurii requested](https://github.com/onflow/flow-go/pull/6318#discussion_r1713465471)
> @AlexHentschel can I ask you update following comment which explains what is a finalization safety threshold as protocol parameter which is used in several places and not only epoch commitment?
This PR provides the **requested documentation update** (no logic changes). It targets Yurii's branch `yurii/6020-rename-finalization-threshold`.

Updated documentation of `FinalizationSafetyThreshold`

---

cmd/util/ledger/util/migration_runtime_interface.go
fvm/environment/facade_env.go
fvm/environment/mock/environment.go
fvm/environment/program_recovery.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.53](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.53)
- [onflow/cadence v1.0.0-preview.50](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.50)

Update to Cadence v1.0.0-preview.50

---

fvm/evm/stdlib/contract_test.go

Make the tests more readable and maintainable by using the hex address directly

[EVM] Improve EVM addresses in tests

---

cmd/util/cmd/check-storage/cmd.go
cmd/util/ledger/util/util.go

Closes #6405
Currently, the util program's check-storage command doesn't support the `cap_tag` domain.
`cap_tag` domain was created on testnet and needs to be included in storage health check to avoid false alarms about unreferenced slabs.
This PR adds support for the cap_tag domain to `util` program's `check-storage` command.

Add support for `cap_tag` domain in `check-storage` command of `util` program

---

consensus/hotstuff/eventhandler/event_handler.go
consensus/hotstuff/eventhandler/event_handler_test.go
consensus/hotstuff/model/proposal.go
consensus/hotstuff/safety_rules.go
consensus/hotstuff/safetyrules/safety_rules.go

this PR contains a temporary solution for the implementation bias observed for Cruise Control on Testnet. 
* The issue was first reported here: https://flow-foundation.slack.com/archives/C071612SJJE/p1723722918506329
This code targets the crescendo deployment branch `v0.37`. This affects only testnet (and not in a critical manner). Fix if fully downwards compatible. Hence, this can be rolled out as part of any future release to testnet and mainnet. 
- The call to [`forks.AddValidatedBlock` emits the `OnBlockIncorporated` notification](https://github.com/onflow/flow-go/blob/d9f7522d6c502d7e148dab69c926279202677cf8/consensus/hotstuff/forks/forks.go#L261) for `block` with view $v$, which the `BlockTimeController` uses as [its starting point for the …

cruisectl delay implementation bias (fix for deployment branch `v0.37`)

---

.github/workflows/tools.yml

This PR adds the sha256 checksum of the boot tools and util to its tar files.
See result https://github.com/onflow/flow-go/actions/runs/10569117930/job/29281315382

[CI] print and include the sha256 checksum of the boot tools and util

---

cmd/util/cmd/diff-states/cmd.go

Currently, the `util` program's `diff-states` command doesn't support the `cap_tag` domain.
`cap_tag` domain was created on testnet and needs to be supported by `diff-states` to compare Cadence values.
This PR adds support for the `cap_tag` domain to util program's `diff-states` command.

Add support for `cap_tag` domain in `diff-states`

---

cmd/util/cmd/diff-states/cmd.go

This PR skips EVM storage account during Cadence values comparison in `util` program's `diff-states` command.

Port PR #6401 (Skip EVM storage account for value comparison in diff-states cmd) to v0.37 branch

---

cmd/util/cmd/check-storage/cmd.go
cmd/util/ledger/util/util.go

Currently, the util program's check-storage command doesn't support the `cap_tag` domain.
`cap_tag` domain was created on testnet and needs to be included in storage health check to avoid false alarms about unreferenced slabs.
This PR adds support for the cap_tag domain to `util` program's `check-storage` command.

Port PR #6406 (Add support for `cap_tag` domain in check-storage cmd) to v0.37 branch

---

cmd/util/cmd/diff-states/cmd.go

Currently, the `util` program's `diff-states` command doesn't support the `cap_tag` domain.
`cap_tag` domain was created on testnet and needs to be supported by `diff-states` to compare Cadence values.
This PR adds support for the `cap_tag` domain to util program's `diff-states` command.

Port PR #6407 (Add support for `cap_tag` domain in `diff-states` cmd) to v0.37 branch

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

This PR updates the `go-ds-pebble` dependency to the latest version following the merge of [ipfs/go-ds-pebble#36](https://github.com/ipfs/go-ds-pebble/pull/36). The replace directive has been removed, and the dependency now points to the official `github.com/ipfs/go-ds-pebble` repository.

[Access] Updated go-ds-pebble version

---

fvm/evm/events/events.go

Decode legacy block event that doesn't contain `prevrandao` field. These events were emitted on testnet so we must make sure we can decode them using the events package.

[EVM] Decode legacy block event

---

cmd/util/ledger/migrations/account.go
cmd/util/ledger/migrations/cadence.go

Reported in https://discord.com/channels/613813861610684416/1278736553795129374
After migrating an Emulator state snapshot to Cadence 1.0, sending any transaction against the migrated state fails:
```
Transaction ID: 7c2bf8e9f491fa0b033b984a677304897c7eaecab85586adff163a874bd9345a
❌ Command Error: failed to submit transaction: client: rpc error: code = Internal desc = [Error Code: 1201] error caused by: 1 error occurred:
* transaction execute failed: [Error Code: 1101] cadence runtime error: Execution failed:
--> 4b77dc12dc452df7174ff3f73b70dfe4d1e5434d8b40e78deefe3b7b6ae7105d:14:8
|
14 |         evmHeartbeat.heartbeat()
|         ^^^^^^^^^^^^^^^^^^^^^^^^
error: unexpected error: backend error: set value failed: failed to update storage for …
```

[Cadence 1.0 migration] Add EVM storage account creation migration

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.54](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.54)
- [onflow/cadence v1.0.0-preview.51](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.51)

Update to Cadence v1.0.0-preview.51

---

cmd/bootstrap/run/qc.go
cmd/bootstrap/run/qc_test.go
consensus/hotstuff/verification/combined_signer_v2_test.go
consensus/hotstuff/verification/combined_signer_v3_test.go
consensus/integration/epoch_test.go
consensus/integration/nodes_test.go
model/flow/dkg.go

This contains suggested amendments for PR https://github.com/onflow/flow-go/pull/6338. It mostly proposes changes related to two of my PR review comments 
* confusing, possibly incorrect/inconsistent usage of [ParticipantData](https://github.com/onflow/flow-go/blob/4292b2b951106b519220e6c6a76c4b380744cdd7/cmd/bootstrap/run/qc.go#L27) (see [my PR comment](https://github.com/onflow/flow-go/pull/6338#discussion_r1735395983)): 
*  I am not entirely sure, what the meaning of `ParticipantData.Participants` is, due to missing documentation. In [my PR comment](https://github.com/onflow/flow-go/pull/6338#discussion_r1735395983) comment, I am describing how I think it is inconsistently used. 
* However, before fixing the usage problem, we need to agree on the meaning of the …

suggested documentation extension for PR #6338

---

engine/verification/verifier/engine.go

This PR adds block id and height to the log of verified approval.

[Verification] Adding block id and height in verified approvals

---

engine/common/follower/compliance_core.go

backport of https://github.com/onflow/flow-go/pull/6419
--- 
The following error message was logged by a freshly-bootstrapped AN:
```
{"level":"error","node_role":"access","node_id":"63ee3a914c0274caf8837260a26d06989e744ed242078b2b274d547d362d94a2","engine":"follower_core","origin_id":"faa62915ccfd5f85ac37de31827828b9222bbcfbb6892c3dd61f927b5437c612","chain_id":"flow-testnet","first_block_height":213442756,"first_block_view":2266431,"last_block_height":213442756,"last_block_view":2266431,"last_block_id":"dfa94213567f985fde228f3f5551bfd81741c291496a123812dae857dae7288a","range_length":1,"error":"error verifying leader signature for block dfa94213567f985fde228f3f5551bfd81741c291496a123812dae857dae7288a: error retrieving voter Identity at view 2266431: by-view query for unknown …
```

[backport] minor revision of log, to clarify the root causes of likely benign error log

---

cmd/util/cmd/common/clusters.go

During refactoring in 2024-04, this check was modified to incorrectly use the wrong variable (operating on all nodes, not only Collection Nodes). This commit uses the correct variable, and renames the filtered lists.

[v0.37] Fix cluster assignment >2/3 internal check

---

network/p2p/inspector/validation/control_message_validation_inspector.go

Currently nodes emit thousands of warning logs when sample size is calculated based on the last highest ihave count received and this sample size exceeds our configured message id threshold count. This log does not necessarily always indicate a suspicious activity as we have seen larger amounts of iWant messages being received compared to the initial default value in the network config. This PR changes the log level from warn to debug, so that these logs can be used as an extra step of debugging when looking into an issue.

Verbose sample size logs

---

access/validator.go
engine/collection/ingest/engine_test.go

Backport https://github.com/onflow/flow-go/pull/6435
> In some cases, the Cadence parser can panic rather than return an error. This PR changes the TransactionValidator -- which attempts to parse scripts as part of transaction validation -- to recover from such panics and return the recovered error.
> 
> See: https://github.com/dapperlabs/flow-go/issues/6964 and https://github.com/onflow/cadence/issues/3428

[v0.37] Transaction Validator recovers from script parse panic

---

cmd/execution_builder.go

Backport https://github.com/onflow/flow-go/pull/6444
> We have observed execution nodes (in particular Mainnet EN1) occasionally fail to retrieve collections using this engine, which can cause temporary execution halts. Setting a retry maximum of 10s empirically results in a much faster recovery from these faults (default is 2m).

[v0.37] Lower retry interval in EN requester engine

---

access/validator.go
engine/collection/ingest/engine_test.go

In some cases, the Cadence parser can panic rather than return an error. This PR changes the `TransactionValidator` -- which attempts to parse scripts as part of transaction validation -- to recover from such panics and return the recovered error.
See: https://github.com/dapperlabs/flow-go/issues/6964 and https://github.com/onflow/cadence/issues/3428

Transaction Validator recovers from script parse panic

---

cmd/execution_builder.go

We have observed execution nodes (in particular Mainnet EN1) occasionally fail to retrieve collections using this engine, which can cause temporary execution halts. Setting a retry maximum of 10s empirically results in a much faster recovery from these faults (default is 2m).

Lower retry interval in EN requester engine

---

cmd/util/cmd/check-storage/cmd.go
cmd/util/cmd/check-storage/evm_account_storage_health.go
cmd/util/cmd/check-storage/evm_account_storage_health_test.go

Closes #6393
Currently, the new storage health check command added to `util` program does not support decoding and checking EVM registers.
- https://github.com/onflow/flow-go/pull/6364
This PR updates `check-storage` command to decode and check EVM registers.
A draft version of this program didn't find any problems with EVM registers before September 4 spork.  Same with this version after spork.

Add support for checking EVM registers in `check-storage` command

---

cmd/bootstrap/run/qc.go
model/flow/epoch.go

This PR contains some suggested amendments for PR https://github.com/onflow/flow-go/pull/6338:
* Extended documentation where generalized protocol logic meets bootstrapping implementation, the latter still being limited to handling DKG data from a trusted dealer only. This is an important part in the code, that might need to be generalized in the future. 
* [flow.DKGIndexMap](https://github.com/onflow/flow-go/blob/0e6cd5d392a381fdb6db2adb018c619c5dacbbc6/model/flow/dkg.go#L34-L85) has the important documentation attached. I think we should use it in all places, instead of the ambiguous field definition `map[Identifier]int`.

[EFM] Extended documentation where generalized protocol logic meets bootstrapping implementation

---

cmd/util/cmd/check-storage/cmd.go
cmd/util/cmd/check-storage/evm_account_storage_health.go
cmd/util/cmd/check-storage/evm_account_storage_health_test.go

Currently in v0.37, the new storage health check command added to `util` program does not support decoding and checking EVM registers.
- https://github.com/onflow/flow-go/pull/6364
This PR updates `check-storage` command to decode and check EVM registers by porting PR 6430 to v0.37 branch:
- https://github.com/onflow/flow-go/pull/6430
A draft version of this program didn't find any problems with EVM registers before September 4 spork.  Same with PR 6430 version after spork.

Port PR 6430 (Support EVM registers in check-storage) to v0.37

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/ledger/util/state.go

When running state extraction with a wrong `--execution-state-dir` flag, the error message is misleading. 
This PR adds check to ensure checkpoint file can be found in the specified `--execution-state-dir` and improved error message when a wrong or empty folder is used.

[Util] Check checkpoint file exists when running state extraction

---

engine/common/follower/compliance_core.go

The following error message was logged by a freshly-bootstrapped AN:
```
{"level":"error","node_role":"access","node_id":"63ee3a914c0274caf8837260a26d06989e744ed242078b2b274d547d362d94a2","engine":"follower_core","origin_id":"faa62915ccfd5f85ac37de31827828b9222bbcfbb6892c3dd61f927b5437c612","chain_id":"flow-testnet","first_block_height":213442756,"first_block_view":2266431,"last_block_height":213442756,"last_block_view":2266431,"last_block_id":"dfa94213567f985fde228f3f5551bfd81741c291496a123812dae857dae7288a","range_length":1,"error":"error verifying leader signature for block dfa94213567f985fde228f3f5551bfd81741c291496a123812dae857dae7288a: error retrieving voter Identity at view 2266431: by-view query for unknown epoch","time":"2024-08-27T23:46:56.492526784Z","message":"unable to …
```

minor revision of log, to clarify the root causes of likely benign error log

---

storage/pebble/approvals.go
storage/pebble/approvals_test.go

Addressing [review comments](https://github.com/onflow/flow-go/pull/6197#discussion_r1717466594)
Running concurrency test 100 times and passed:
```
go test --failfast --tags=relic  -run=TestApprovalStoreTwoDifferentApprovalsConcurrently -count=100
PASS
ok      github.com/onflow/flow-go/storage/pebble        7.535s
```

[Pebble Refactor] Making indexing approval concurrent-safe

---

module/finalizer/collection/finalizer_pebble.go
module/finalizer/collection/finalizer_pebble_test.go
module/finalizer/consensus/finalizer_pebble.go
module/finalizer/consensus/finalizer_pebble_test.go

[Working towards this](https://github.com/onflow/flow-go/issues/6337)
This PR makes both collection and consensus finalization concurrent safe by using locks.
Test cases passed:
```
go test --failfast --tags=relic -run=TestFinalizerPebble/concurrency_safety -count=100
PASS
ok      github.com/onflow/flow-go/module/finalizer/collection   119.160s
go test --failfast --tags=relic -run=TestMakeFinalConcurrencySafe -count=100
PASS
ok      github.com/onflow/flow-go/module/finalizer/consensus    28.351s
```

[Pebble Refactor] Making finalization concurrent safe

---

storage/pebble/my_receipts.go
storage/pebble/my_receipts_test.go

Addressing [review comments](https://github.com/onflow/flow-go/pull/6197#discussion_r1712428303)
Running the concurrency test for 100 times passed:
```
go test --failfast --tags=relic   -run=TestMyExecutionReceiptsStorage/store_different_receipt_concurrent_for_same_block_should_fail -count=100
PASS
ok      github.com/onflow/flow-go/storage/pebble        6.191s
```

[Pebble Storage] Make indexing own receipts concurrent safe 

---

fvm/evm/debug/tracer.go
fvm/evm/emulator/emulator_test.go

This PR moves the result map updates outside of the concurrent path (uploaded). This prevents concurrent writes to the map in case of uploader failures to upload the results.

[EVM] patch evm debug tracer

---

cmd/bootstrap/cmd/rootblock.go
cmd/bootstrap/cmd/rootblock_test.go
cmd/bootstrap/run/qc.go
cmd/util/cmd/common/node_info.go

Backport https://github.com/onflow/flow-go/pull/6472
This PR removes the internal partners from the partners in order to resolve the "not enough internal nodes" error we encountered during mainnet25 spork.

[Backport] Remove internal partners from root block creation

---

integration/benchnet2/flow/templates/access.yml
integration/benchnet2/flow/templates/collection.yml
integration/benchnet2/flow/templates/consensus.yml
integration/benchnet2/flow/templates/execution.yml
integration/benchnet2/flow/templates/verification.yml

Use `network` and `role` for default labels

[Benchnet] Align default label names

---

config/default-config.yml
insecure/integration/functional/test/gossipsub/rpc_inspector/validation_inspector_test.go
insecure/integration/functional/test/gossipsub/scoring/scoring_test.go
integration/tests/bft/base_suite.go
network/p2p/scoring/scoring_test.go

For the upcoming mainnet upgrade, peer-scoring should be turned off by default.

switching off peer-scoring by default

---

cmd/bootstrap/transit/cmd/pull.go

After the Crescendo network upgrade, the execution state file (`root.checkpoint*`) could not be downloaded via the transit script. The transit script kept reporting `skipping existing file from transit servers` even though the file didn't exist locally.
e.g. Execution node operator reported this:
The root cause of this issue is that the md5 for a remote object is often reported as an empty []byte array by GCS library. The `if` condition [here](https://github.com/onflow/flow-go/blob/5916debb73cc13717f1c090179e32ba038e65166/cmd/bootstrap/transit/cmd/pull.go#L100) succeeds due to this and skips the file without downloading it.

update to transit script pull command to download file if md5 of remote file is not known

---

cmd/bootstrap/cmd/rootblock.go
cmd/bootstrap/cmd/rootblock_test.go
cmd/bootstrap/run/qc.go
cmd/util/cmd/common/node_info.go

This PR removes the internal partners from the partners in order to resolve the "not enough internal nodes" error we encountered during mainnet25 spork.

Remove internal partners from root block creation

---

fvm/evm/impl/abi.go
fvm/evm/stdlib/contract_test.go

Although these are arbitrary precision numbers, in solidity `uint` / `int` are basically aliases for `uint256` & `int256` respectively (https://docs.soliditylang.org/en/latest/types.html#integers).
So we can encode/decode `UInt` & `Int` in the same way we do for `UInt256` & `Int256` respectively.

Handle `UInt`,`Int` Cadence types for EVM ABI encoding/decoding

---

fvm/evm/emulator/emulator_test.go
fvm/evm/emulator/tracker.go
fvm/evm/emulator/tracker_test.go
fvm/evm/handler/handler_test.go
fvm/evm/precompiles/replayer.go
fvm/evm/precompiles/replayer_test.go
fvm/evm/testutils/misc.go
fvm/evm/types/precompiled.go
fvm/evm/types/precompiled_test.go

Since we have state change checksum going forward, there is no need to check the input of the captured precompiled calls. Currently emitting inputs as part of captured precompiled calls is costly and removing this unnecessary data part can reduce an EVM transaction cost (especially for COA proofs).

[Flow EVM] adding a new encoding type for captured precompiled calls

---

cmd/util/cmd/checkpoint-collect-stats/cmd.go
ledger/complete/ledger_stats.go

Updates #6361
Changes to `checkpoint-collect-stats` command include:
- Add optional `state-commitment` flag.  When this new flag is provided, program only collects stats of one trie with specified state commitment, instead of all tries in checkpoint file (currently 500 tries).
This flag reduces noise when tracking growth of single trie over time.
- Add support for input data from payloads file.  Payloads file is an alternative input and output for migration.
- Prevent overwriting existing file by using `ReportFileWriterFactory` to write stats output.

Update `checkpoint-collect-stats` command to support payloads file and state commitment

---

cmd/bootstrap/cmd/final_list.go
cmd/bootstrap/cmd/finalize.go
cmd/bootstrap/cmd/finalize_test.go
cmd/bootstrap/cmd/rootblock.go

Backport https://github.com/onflow/flow-go/pull/6484

Backport v0.37 [Bootstrap] Fix duplication detection in root block finalization

---

fvm/environment/program_recovery.go

Closes https://github.com/onflow/flow-go/issues/6450
Adds an implementation of `NonFungibleToken.Collection.getIDs()` to the recovered program for unmigrated NFT contracts.
This will allow projects that didn't migrate to be able to query broken collections and recreate ownership with a newly deployed contract.

Adds `getIDs()` to NFT program recovery

---

fvm/evm/emulator/emulator.go
fvm/evm/emulator/state/stateDB.go
fvm/evm/emulator/state/stateDB_test.go
fvm/evm/emulator/state/state_growth_test.go
fvm/evm/emulator/state/updateCommitter.go
fvm/evm/emulator/state/updateCommitter_test.go
fvm/evm/types/result.go
fvm/evm/types/state.go

[EVM] port of #6451 - Adding commitment over state update

---

engine/common/version/version_control.go
engine/common/version/version_control_test.go

Backports: https://github.com/onflow/flow-go/pull/6535

[Access] Add support for ignoring version beacon events for compatible versions

---

.github/workflows/builds.yml
.github/workflows/cd.yml

This change will allow better control of the build process for containers.
Environments allow control over
a) Additional approval for usage of the environment/secrets, and
b) Allows admins to limit which branches can access the secrets
As of writing, the `Production Docker Registry` environment requires @Kay-Zee or @sjonpaulbrown approval to push to the docker registry, but this will be expanded once testing is complete.
Also, branches are limited to `master` and `v0.37`, which means we will have to update `v0.37` to the new "active" branch whenever that happens. This should be exceedingly rare with our current release schedule.

Use Production Docker Registry environment for pushing to docker

---

model/convert/service_event.go
utils/unittest/service_events_fixtures.go

https://github.com/onflow/flow-go/issues/6320
Several changes have been made to the `EpochCommit` service event:
- It now has 5 fields instead of 3.
- Previously, the group key and participant keys were represented as a single array. Now, the group key has been moved to a separate field.
- The `dkgIdMapping` field has been introduced.
The latest state of the `EpochCommit` event can be viewed [here](https://github.com/onflow/flow-core-contracts/blob/jord/6213-dkg-mapping/contracts/epochs/FlowEpoch.cdc#L133).
This PR updates how the `EpochCommit` event is converted from Cadence to Go. Additionally, the fixtures have been updated to match the new changes so they can be verified using tests.
:exclamation: This PR does **not** change the Go structure of `EpochRecover`. Structurally, …

[EFM] Updated type conversion of `EpochCommit`

---

model/convert/service_event.go
model/flow/epoch.go
model/flow/service_event_test.go
utils/unittest/service_events_fixtures.go

https://github.com/onflow/flow-go/pull/6495
This PR is based on https://github.com/onflow/flow-go/pull/6494 and introduces similar changes that were made to the `EpochCommit` but for the `EpochRecover` service event.

[EFM] Updated type conversion of `EpochRecover`

---

cmd/util/cmd/read-badger/cmd/find-block-by-commits/main.go

The intention here should be to initialize a slice with a capacity of  len(commitSlice)  rather than initializing the length of this slice.
The online demo: https://go.dev/play/p/q1BcVCmvidW

fix: fix slice init length

---

engine/common/version/version_control.go

Original PR that added this feature: https://github.com/onflow/flow-go/pull/6536

Marking v0.37.18 as backward compatible in terms of script execution

---

cmd/access/node_builder/access_node_builder.go
cmd/bootstrap/utils/md5.go
cmd/observer/node_builder/observer_builder.go
engine/access/access_test.go
engine/access/ingestion/engine_test.go
model/flow/transaction_timing.go
module/metrics.go
module/metrics/noop.go
module/metrics/transaction.go
module/mock/access_metrics.go
module/mock/transaction_metrics.go
module/state_synchronization/indexer/collection_executed_metric.go
module/state_synchronization/indexer/indexer_core_test.go

Backports: https://github.com/onflow/flow-go/pull/6512

Add a Time To Seal metric to access node to track time it takes to seal a transaction

---

cmd/observer/node_builder/observer_builder.go
cmd/utils.go
follower/follower_builder.go

Changed log level not to spam messages

---

engine/execution/checker/core.go

This PR added logs to print the block height when checking the executed block matches the sealed result.

Print log when checks the executed block matches the sealed result

---

module/metrics/transaction.go

The new time_to_seal metric was reporting NaN for values. Fixed this issue.

Fixed issues where time-to-seal was NaN

---

cmd/bootstrap/cmd/block.go
cmd/bootstrap/cmd/dkg.go
cmd/bootstrap/cmd/rootblock.go
cmd/util/cmd/epochs/cmd/recover.go

- Previously the DKG index mapping was omitted from the bootstrapping command. This uses a similar approach to that used in integration tests. 
- Removes a duplicate flag (epoch counter was specified twice)

EFM Recovery: Fixes from Benchnet Testing

---

fvm/evm/debug/tracer.go

Currently, the `gas` field was always set to `0x0`, due to the tracing reset being done on `OnTxStart`:
```json
{
"txHash": "0xf730eacee38a28f93fcf1a9a1f9c360542fe20e3200510126976bb9ee7fd3fca",
"result": {
"from": "0x0000000000000000000000030000000000000000",
"gas": "0x0",
"gasUsed": "0x5208",
"to": "0x2c91520ee9e2c55593dc425e1c2b82026391dea7",
"input": "0x",
"value": "0x18321634f200",
"type": "CALL"
}
}
```

[Flow EVM] Move tracing reset to `OnTxEnd` hook

---

.github/workflows/ci.yml
Makefile
actions/private-setup/action.yml

This PR introduces changes to support building private dependencies in the CI pipeline, specifically for private Cadence repositories.
---
1. **Update CI steps to load Cadence Deploy Key in CI:**
- Adds CI step to load the `CADENCE_DEPLOY_KEY` into the SSH agent for accessing private repositories.
- Configures Git to use SSH for dependencies.
- Dynamically sets `SSH_AUTH_SOCK` in the environment.
- Warns if `CADENCE_DEPLOY_KEY` is not set, allowing the workflow to continue.
2. **Update `GOPRIVATE` Configuration:**
- Updates `GOPRIVATE` to `github.com/onflow/*` in both the GitHub Actions workflow and the `Makefile` to bypass the Go module proxy for private repositories.
---
These changes enable seamless fetching and building of private Cadence dependencies during CI, improving the …

Add support for building private dependencies in CI

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to https://github.com/onflow/cadence/releases/tag/v1.0.3

Update to Cadence v1.0.3

---

fvm/evm/handler/handler.go

We are printing two height fields in this comment.
```
{"level":"info","node_role":"execution","node_id":"9686399a8a5418a12e762cfaeff2ea348c2137f554560917760e0d47acf2cda4","module":"FVM","block_id":"5746e32bc6cd4fcad57821ba55311afcb627c10e452c688609150e0b704c592e","height":94184081,"system_chunk":true,"system_transaction":true,"num_collections":3,"num_txs":5,"tx_id":"0e56f890392ad3f2a0dcc7a0e859b6d41f3c17556aa85a0f8831ae25a6537e39","tx_index":4,"height":8179395,"tx_count":0,"total_gas_used":0,"total_supply":13728292374567592960,"time":"2024-11-20T00:45:01.257491335Z","message":"EVM Block Committed"}
```

update height in comment

---

fvm/evm/offchain/blocks/block_context.go

Extracted from https://github.com/onflow/flow-go/pull/6755.
This was needed to fix the re-execution on testsnet

Fix testnet EVM replay

---

fvm/evm/offchain/utils/collection_test.go
fvm/evm/testutils/backend.go

Working towards https://github.com/onflow/flow-go/issues/6552
This PR added test cases to verify that the offchain package is able to sync blocks from EVM genesis block to the latest blocks, and derive consistent state.

Add testcase for offchain evm backward compatibilities

---

cmd/util/cmd/epochs/cmd/recover.go
consensus/hotstuff/signature/randombeacon_signer_store.go
consensus/hotstuff/verification/combined_verifier_v3.go
consensus/hotstuff/votecollector/combined_vote_processor_v2_test.go
consensus/hotstuff/votecollector/combined_vote_processor_v3_test.go
consensus/integration/epoch_test.go
consensus/integration/nodes_test.go
integration/testnet/network.go
model/convert/service_event.go
state/protocol/badger/mutator_test.go
state/protocol/validity.go

Minor follow up to Tarak's great [PR #6590](https://github.com/onflow/flow-go/pull/6590) on the `Random Beacon documentation`  
The goDoc still talks in some locations about the "DKG key". This is outdated terminology and we are trying to use "Random Beacon key" instead (reasoning: DKG is only _one_ of the means to produce the threshold key shares. Much more descriptive is the usage for the keys - the random beacon - and not the source of the keys).

updating the term `DKG key` as it is outdated

---

cmd/scaffold.go
cmd/util/cmd/root.go
cmd/util/cmd/verify_execution_result/cmd.go
engine/execution/computation/execution_verification_test.go
engine/verification/fetcher/engine.go
engine/verification/fetcher/engine_test.go
engine/verification/verifier/verifiers.go
fvm/initialize/options.go
model/verification/convert/convert.go

Working towards https://github.com/onflow/flow-go/issues/6557
This PR implemented option 4 in the above issue. 
It adds a util command `verify-execution-result` that takes execution node's data and verifies every single chunks for a range blocks. 
Since we would like to make sure future cadence versions are backward compatible. This util allows us to capture any backward compatibilities issue from either FVM or cadence related changes. 
For instance, if cadence introduces a breaking change, then it will be caught by running this `verify-execution-result` with a latest snapshot of EN. The util can verify the last 1M blocks, and 1 of the chunk might fail caused by the breaking change.
I have verified with the latest testnet snapshot, and it worked. It verified 200K blocks after 3 hours, …

[Util] Add verify execution result cmd

---

cmd/util/cmd/root.go
cmd/util/cmd/verify-evm-offchain-replay/main.go
cmd/util/cmd/verify-evm-offchain-replay/verify.go
fvm/evm/handler/blockHashList.go
fvm/evm/offchain/blocks/block_proposal.go
fvm/evm/offchain/blocks/provider.go
fvm/evm/offchain/sync/replay.go
fvm/evm/offchain/sync/replayer.go
fvm/evm/offchain/sync/replayer_test.go
fvm/evm/offchain/utils/collection_test.go
fvm/evm/offchain/utils/replay.go
fvm/evm/offchain/utils/verify.go
fvm/evm/testutils/gob.go

This PR adds a util cmd for verifying the evm offchain replay. 
No API change for gateway.

Add verification tool for evm offchain replay

---

Makefile

The following PR injects secrets to enable private cadence builds. This pattern is already used for our binary builds, but in this case, we need to support the util builds.

Update Makefile to support private util builds

---

cmd/util/cmd/verify_execution_result/cmd.go
engine/verification/verifier/verifiers.go
storage/pebble/open.go
storage/pebble/open_test.go

This PR:
- Skip unexecuted sealed block when verifying execution result with the util commands. This is to solve the problem that when automation is trying to verify the last X sealed blocks, it fails because the last sealed block is not executed. 
- Raise error if the chunk data pack db is not initialized, useful when specifying with a wrong chunk data pack dir
- Log the specified chunk data pack dir

Fix verify execution result

---

engine/verification/assigner/engine.go
engine/verification/fetcher/engine.go

Part of https://github.com/onflow/flow-go/issues/6807 for [VN Assigner](https://github.com/onflow/flow-go/blob/c1cd71ba972464312a87e7717846d8b60381bd6c/engine/verification/assigner/engine.go#L27) engine and [VN Fetcher](https://github.com/onflow/flow-go/blob/a9d7587f9442d34e5deebd61d4b11def9e43deb4/engine/verification/fetcher/engine.go#L37) engine.
In both cases, the engine.Unit was only used for its context. In similar situations, other code uses a context.Background() instead.
Not completely replacing ReadyDoneAware interface with Component yet, due to them still wrapping more complex engines that still use engine.Unit and ReadyDoneAware.

Remove engine.Unit from Assigner engine and Fetcher engine

---

engine/access/rpc/connection/connection_test.go

Tests were failing due to an unexported value being different in the protobuf message. Fixed by using type check
```
=== RUN   TestProxyAccessAPI
panic: 
mock: Unexpected Method Call
-----------------------------
Ping(*context.valueCtx,*access.PingRequest)
0: &context.valueCtx{Context:(*context.valueCtx)(0xc00f91db60), key:grpc.streamKey{}, val:(*transport.Stream)(0xc0000d4c60)}
1: &access.PingRequest{XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
The closest call I have is: 
Ping(string,*access.PingRequest)
0: "mock.Anything"
1: &access.PingRequest{XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:1}
Diff: 0: PASS:  (*context.valueCtx=context.Background.WithValue(type transport.connectionKey, val <not …
```

[Access] Fix mocking in connection unittests

---

ledger/complete/wal/checkpoint_v6_writer.go
storage/operation/prefix.go
storage/operation/reads.go
storage/operation/writes.go
storage/operation/writes_functors.go
utils/merr/closer.go
utils/merr/closer_test.go

This PR:
1. Extract uncurried functions from storage writes operations. Useful for refactoring with the uncurried functions
2. Handle the error closing the iterator
3. Add the prefix and related functions

Extract uncurried functions from storage writes

---

module/builder/collection/builder.go

This field reads the first height of an epoch, which may be unavailable if the node is using Dynamic Bootstrap.

[v0.37] Removes unused first height field from LN builder

---

cmd/util/cmd/verify_execution_result/cmd.go
engine/verification/verifier/verifiers.go
engine/verification/verifier/verifiers_test.go

Backport https://github.com/onflow/flow-go/pull/6830

Backport v0.37 add nWorker to verify execution result

---

cmd/util/cmd/verify_execution_result/cmd.go
engine/verification/verifier/verifiers.go
engine/verification/verifier/verifiers_test.go

Speed up the verify execution result command by adding a `nWorker` parameter which allows the verification to run concurrently. 
a n2-highcpu-32 used to run at 1.5 block / second, but with this change a n2-highcpu-48 instance running with `nWorker=30` can complete 10K blocks verification in 3 mins, which is 55 blocks / second.

[Util] add nWorker to verify execution result

---

engine/execution/ingestion/uploader/retryable_uploader_wrapper.go
engine/execution/ingestion/uploader/retryable_uploader_wrapper_test.go
engine/execution/ingestion/uploader/uploader.go
engine/execution/ingestion/uploader/uploader_test.go
module/component/component.go

AsyncUploader now uses the Component interface, and a channel is used to buffer upload tasks until a worker goroutine is available to begin the upload.
- An [arbitrary value of 3](https://github.com/onflow/flow-go/pull/6809/files#diff-2ba04bc060b7bbc8d31bb4a84c91a0bbfc31e2c781ff0f5ef15c0153427d2ddbR39-R41) was chosen as the worker count; need feedback on an appropriate number for this (and the [channel buffer size](https://github.com/onflow/flow-go/pull/6809/files#diff-2ba04bc060b7bbc8d31bb4a84c91a0bbfc31e2c781ff0f5ef15c0153427d2ddbR36) as well). This could also potentially be configurable.
- Also affects the [BadgerRetryableUploadWrapper](https://github.com/onflow/flow-go/commit/9c57c77c1772cb258e0be1dda91cb133e2b5e473) which wraps an AsyncUploader.
In addition, updated documentation …

Refactor AsyncUploader to replace Engine.Unit with ComponentManager

---

integration/localnet/builder/bootstrap.go
module/dkg/client.go
module/dkg/dkg_check_v2.cdc
module/dkg/dkg_submit_result_v1.cdc

This PR implements backward-compatibility for DKG result submission. 
The implementation here uses differences in the smart contract to decide which transaction to use for result submission. Compared to the protocol-version-based approach described in the issue, this has the benefit that the smart contract upgrade does not need to be coordinated with the Protocol HCU.

DKG Result Submission Backward Compatibility

---

integration/benchnet2/Makefile

This PR extracts epoch configs as env variables in BN2, allowing them to be overridden (see https://github.com/onflow/flow-go-internal/pull/7028).

Add epoch configs as env variables to Benchnet2 Makefile

---

fvm/evm/events/events.go
fvm/evm/evm_test.go
fvm/evm/types/result.go

Closes https://github.com/onflow/flow-go/issues/6770

Include human-friendly error messages on EVM transaction events

---

cmd/util/cmd/verify_execution_result/cmd.go
engine/verification/verifier/verifiers.go

Log the progress of backward compatibility tests.

[Util] Log verification progress

---

cmd/util/cmd/read-protocol-state/cmd/blocks.go

This PR adds a sub command to the read-protocol-state util to query last executed and sealed block for execution node in order to prevent failure when extracting checkpoint from latest sealed block which might not be executed.

[Util] Add query last executed sealed block

---

engine/consensus/approvals/approval_collector.go
engine/consensus/approvals/approval_collector_test.go
engine/consensus/approvals/chunk_collector_test.go
engine/consensus/approvals/testutil.go
engine/consensus/approvals/verifying_assignment_collector_test.go
engine/consensus/sealing/core_test.go
engine/verification/assigner/engine_test.go
engine/verification/utils/mocked.go
engine/verification/utils/unittest/helper.go
model/chunks/chunkassignment.go
module/chunks/chunk_assigner.go
module/chunks/chunk_assigner_test.go
module/validation/seal_validator.go
module/validation/seal_validator_test.go
utils/unittest/chain_suite.go

The assignment of verifiers to chunks of an execution receipt should be immutable after it is created. Currently it is mutable, with the `Assignment.Add()` method being used to add chunks (and the verifiers for them) one-by-one during creation. This PR adds a new `AssignmentBuilder` type and moves the `Add()` method to it.
`Assignment` now has no methods that mutate it. However, the initial implementation doesn't do a deep copy of the data, so any changes to the Builder will continue to be reflected in already-built `Assignment`s. No existing code does this or should do this (reuse the Builder after building the assignment) so I believe this isn't a problem.
In addition, the PR converts the type of the mapping from chunks to verifiers from a `map[chunk.Index]` to a slice, still indexed by …

Make chunk assignment immutable

---

.github/workflows/ci.yml
cmd/util/cmd/common/node_info.go
engine/access/rpc/backend/backend_transactions.go
engine/collection/compliance/core_test.go
engine/common/grpc/forwarder/forwarder.go
engine/consensus/compliance/core_test.go
engine/consensus/matching/core_test.go
engine/errors.go
integration/tests/access/cohort4/execution_data_pruning_test.go
module/mempool/errors.go
module/validation/seal_validator.go
state/errors.go
state/protocol/badger/mutator.go
state/protocol/badger/mutator_test.go
utils/grpcutils/grpc.go
utils/unittest/logging.go

This PR upgrades the golangci-lint action to use version 1.63 (from 1.54), in order to add support for Go versions 1.22+. It addresses a few lint issues added since 1.54 (mainly a new govet rule about format strings). 
The linter [supports Go versions up to the version used to build the binary](https://golangci-lint.run/welcome/faq/#which-go-versions-are-supported). Older linter releases are not re-built when a new Go release comes out.
Context: https://github.com/onflow/flow-go/pull/6871#discussion_r1915706202

Upgrade golangci linter to 1.63

---

cmd/util/cmd/verify_execution_result/cmd.go
engine/verification/verifier/verifiers.go

Backport https://github.com/onflow/flow-go/pull/6834 to master

Backport log verify execution result master

---

cmd/execution_builder.go
cmd/util/cmd/find-inconsistent-result/cmd.go
engine/execution/checker/core.go
engine/execution/checker/core_test.go
engine/execution/ingestion/loader/unexecuted_loader.go
engine/execution/ingestion/loader/unexecuted_loader_test.go
engine/execution/state/mock/execution_state.go
engine/execution/state/mock/read_only_execution_state.go
engine/execution/state/state.go
engine/testutil/mock/nodes.go
storage/badger/procedure/executed.go
storage/badger/procedure/executed_test.go

Close https://github.com/onflow/flow-go/issues/6908
This PR replace the `HighestExecutedBlock` with `LastExecutedBlock` to be stored in database. This refactor will simplify the refactor from badger transaction to badger batch updates for execution data.

[Execution Data] Replace HighestExecutedBlock with LastExecutedBlock

---

engine/access/rpc/connection/connection_test.go
engine/access/rpc/connection/grpc_compression_benchmark_test.go
engine/access/rpc/connection/node_mock.go

Fixes failures from https://github.com/onflow/flow-go/actions/runs/12402358137/job/34623739390?pr=6779
Needed to merge https://github.com/onflow/flow-go/pull/6779 which upgrades the testify library

[Access] Fix access connection tests for latest version of testing library

---

state/protocol/badger/mutator.go
state/protocol/badger/state.go

Since finalized block and sealed block are updated together, the cache could be update together as well. Combining them could eliminate any edge case when accessing the cache.

[Protocol State] Combine the caches for last finalized and last sealed block

---

fvm/environment/derived_data_invalidator_test.go
fvm/executionParameters.go
fvm/fvm_test.go
fvm/systemcontracts/system_contracts.go

more description here: https://github.com/onflow/flow-go/pull/6891

Move execution parameter to separate account

---

cmd/util/cmd/debug-tx/cmd.go
cmd/util/cmd/root.go

[v0.37] Backport: Add util command to debug transaction

---

engine/consensus/matching/engine.go
engine/consensus/matching/engine_test.go

Refactor the Consensus Matching Engine to move away from deprecated interfaces, as well as improve error handling and documentation. The changes are relatively straightforward drop-in replacements, due to the engine already being structured as an initial set of workers launched when the engine is started.
- Replace deprecated `engine.Unit` with `ComponentManager`
- Replace deprecated `network.Engine` with `network.MessageProcessor`
- Use concrete types where appropriate
- Use `ctx.Throw` to propagate irrecoverable errors instead of `Log.Fatal`, which also allows for tests to verify behaviour by using mock contexts
Closes https://github.com/onflow/flow-go/issues/6854

Refactor Consensus Matching Engine: `engine.Unit` -> `ComponentManager`

---

Makefile

This PR updates the `make` targets to handle the injection of the cadence deploy key that enables cloning repos. Currently, this is blocking builds as the key is needed, but it is not currently being injected.

Update Makefile to handle key injection

---

engine/execution/state/bootstrap/bootstrap_test.go
fvm/bootstrap.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
utils/unittest/execution_state.go

Closes https://github.com/onflow/flow-emulator/issues/535
Adds the `NFTStorefrontV2` and `USDCFlow` smart contracts to the flow-go bootstrapping so they are automatically deployed to the emulator. Will make it easier for developers to test with these contracts without having to deploy them themselves.

Adds `NFTStorefrontV2` and `USDCFlow` to bootstrapping

---

cmd/util/cmd/debug-script/cmd.go
cmd/util/cmd/debug-tx/cmd.go
fvm/environment/block_info.go
utils/debug/README.md
utils/debug/api.go
utils/debug/registerCache.go
utils/debug/remoteDebugger.go
utils/debug/remoteView.go

- Refactor and improve the code of the remote debugger
- Add a new storage snapshot backed by the execution data / state streaming API implemented by access nodes
- Enable EVM
- Add support for `getCurrentBlock()` calls
- Add a flag that dumps all read and written registers
- Add support for running "mid-block" transaction: Also run all transactions preceding the TX in question

Refactor the remote debugger and add support for using the execution data API

---

engine/common/version/version_control.go

Backports the version control overrides from v0.37 to master, which is needed before rolling out master as an HCU.

[Access] Backport version control overrides from v0.37

---

fvm/evm/offchain/sync/replay.go

Closes: https://github.com/onflow/flow-go/issues/6951
Follow up on: https://github.com/onflow/flow-go/issues/6770
The `errorMessage` field of `EVM.TransactionExecuted` event, now has a more human-friendly representation.
So we need to use the `ErrorMessageWithRevertReason` when validating the execution replay of an EVM tx.

Use `ErrorMessageWithRevertReason` when validating replay of EVM tx

---

fvm/evm/emulator/emulator.go
fvm/evm/evm_test.go

Closes: https://github.com/onflow/flow-go/issues/6843
Relevant issue: https://github.com/onflow/flow-go/issues/6301
The buffer gas added in `EVM.dryRun`, was a best-effort solution, to find the minimum required gas, that would make a transaction succeed. The calculation was based on top of the actual gas used for a given transaction. However, this did have some issues, and it would fail for certain cases.
With the implementation of the local state index on EVM Gateway, we have completely [reworked](https://github.com/onflow/flow-evm-gateway/pull/671) the `eth_estimateGas` endpoint, and it uses the same logic as `Geth`, to calculate the minimum required gas needed for a transaction to succeed.
With that change deployed, we no longer need to add any buffer gas to the result of `EVM.dryRun`. …

Remove buffer gas added in the gas used from `EVM.dryRun`

---

cmd/util/cmd/verify_execution_result/cmd.go
engine/verification/verifier/verifiers.go
engine/verification/verifier/verifiers_test.go

The current backward compatibilities testing tool (verify execution result) will stop as soon as it found a mismatch. This PR adds a flag to control that and by default it will not stop but continue verifying.

[Util] Add flag to backward compatibilities testing tool to continue verify when mismatching is found

---

cmd/execution_builder.go

We run a script to get the epoch counter from the state during node startup. 
This script is not run by the block execution manager or the query engine, so it has its own FVM context. This FVM context was not taking the default settings used in Transaction execution and in the query engine.

Add default fvm context to the epoch counter script

---

fvm/evm/emulator/emulator.go

Closes: https://github.com/onflow/flow-go/issues/6842
This will remove the need for having to trigger this tracer hook on EVM Gateway:
- https://github.com/onflow/flow-evm-gateway/blob/main/services/evm/executor.go#L109-L113
- https://github.com/onflow/flow-evm-gateway/blob/main/api/debug.go#L244-L248
And we will have all the necessary hooks in a single place, instead of being in separate repositories.

[Flow EVM] Trigger `OnLog` tracer hooks upon successful call & tx results

---

cmd/util/cmd/execution-state-extract/cmd.go

#6572 left some code related to the Cadence 1.0 and authorization fixes migrations in the code base, e.g. the flags.
Remove them

Remove last remnants of Cadence 1.0 and authorization fixes migrations

---

access/handler.go
engine/access/rest/websockets/models/block_digest.go
engine/access/rpc/backend/backend_stream_block_digests_test.go
model/flow/block.go
network/channels/channel.go

Closes:  #6665, #6667
This pull request addresses two issues related to the misuse and redundancy of the `ID()` method in `BlockDigest` and `ChannelList`.
- `BlockDigest`: the id field has been renamed to `BlockID`, and the `ID()` method has been removed. All affected unit tests and usages have been updated to reflect this change.
- `ChannelList`: the `ID()` method has been removed, and all relevant tests have been verified to ensure correctness.

[Malleability] Refactor BlockDigest and ChannelList types

---

engine/execution/ingestion/block_queue/queue.go
utils/unittest/chain_suite.go

Closes: #6679 
This PR fixes the implementation of the `ID()` method for the `MissingCollection` type to cover all fields. In addition, the unused method `EntityWithID` was removed.
Changes have no impact on tests.
https://github.com/onflow/flow-go/blob/914f3531b2b79a695ce8a11a8bc713adf86bd120/engine/execution/ingestion/core.go#L312

[Malleability] MissingCollection type ID method malleable.

---

cmd/util/cmd/check-storage/cmd.go
cmd/util/cmd/check-storage/evm_account_storage_health.go
cmd/util/cmd/checkpoint-collect-stats/account_stats.go
cmd/util/cmd/diff-states/cmd.go
cmd/util/ledger/migrations/cadence_value_diff.go

Currently, `util` program's `check-storage` command (to check storage health) only supports account storage format v1.  However, we need to also support the recently added v2.
This commit adds two flags to check storage health of account format (v1 or v2).
- `account-format-v1` flag should be on if state contains any accounts in v1 format
- `account-format-v2` flag should be on if state contains any accounts in v2 format
**IMPORTANT**: Both flags should be specified if both v1 and v2 are present in the state.

Add  support for account format v2 in util `check-storage`

---

cmd/util/cmd/diff-states/cmd.go
cmd/util/ledger/migrations/cadence_value_diff.go
cmd/util/ledger/migrations/cadence_value_diff_test.go

Closes #6989 
This PR adds `--exclude-randombeaconhistory` flag to util's `diff-states` command.
This flag can be used to reduce noise when comparing states.
Without this flag, the diff-states report (JSONL) can sometimes contain lines that are 30+ GB each, depending on the states being compared (e.g. before/after test of partial zero-downtime migration).
While at it, also removed some obsolete concurrency code.

Add `--exclude-randombeaconhistory` to `diff-states` cmd in `util` program

---

engine/access/state_stream/backend/backend_executiondata.go
integration/localnet/builder/bootstrap.go
integration/localnet/builder/ports.go
integration/testnet/network.go
integration/tests/access/cohort3/execution_state_sync_test.go
integration/tests/access/cohort4/execution_data_pruning_test.go
integration/tests/access/cohort4/grpc_state_stream_test.go
integration/tests/epochs/base_suite.go

I rewrote part of the `ExecutionStateSyncSuite` integration tests which were flaky. 
In the original code, we stopped the network and inspected the DBs for the access and observer nodes to make sure they each had all of the expected execution data. This ran into issue because the observer was often much slower than the access node, so some of the data was missing.
I fixed it by switching to use the state stream APIs to fetch data from each node as it becomes available. I also tweaked the shutdown logic for the epoch tests since I noticed they were logging errors connecting to nodes after stopping the network.

[Access] Fix flakiness in ExecutionStateSync integration test

---

cmd/access/node_builder/access_node_builder.go

Closes: https://github.com/onflow/flow-go/issues/7015
Disable the registers db pruner by default

[Access] Disable registers db pruning by default

---

cmd/node_builder.go
cmd/scaffold.go
cmd/scaffold/pebble_db.go
cmd/scaffold/pebble_db_test.go
follower/consensus_follower.go
follower/database/init.go
integration/testnet/network.go
storage/pebble/open.go

This PR adds a flag `pebble-dir` with default value `/data/pebble-dir` for storing pebble database data. It will be used for the transition from badger to pebbleDB.

[Storage Refactor] Init pebble DB in scaffold.

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
cmd/util/cmd/run-script/cmd.go
engine/access/rest/server.go
engine/access/rest/websockets/controller.go
engine/access/rpc/engine.go

Closes #7012 
Add feature flag for access and observer nodes to enable new WebSockets Stream API

Add feature flag for new websockets stream API

---

engine/access/rest/websockets/controller.go
engine/access/rest/websockets/data_providers/account_statuses_provider.go
engine/access/rest/websockets/data_providers/account_statuses_provider_test.go
engine/access/rest/websockets/data_providers/events_provider.go
engine/access/rest/websockets/data_providers/events_provider_test.go

Data providers now check if state stream api is not nil. Improved error messages for clients as well.
Closes #7005 #7008

Return error if --state-stream-addr no configured.

---

fvm/evm/offchain/query/viewProvider.go

Closes: https://github.com/onflow/flow-go/issues/6962

Update EVM `ViewProvider` to return block `View` at its end state

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.3.3](https://github.com/onflow/flow-go-sdk/releases/tag/v1.3.3)
- [onflow/cadence v1.3.3](https://github.com/onflow/cadence/releases/tag/v1.3.3)

Update to Cadence v1.3.3

---

consensus/hotstuff/cruisectl/block_time_controller_test.go
state/protocol/badger/snapshot.go
state/protocol/convert_test.go
state/protocol/inmem/epoch.go

Update the code to be in line with the formal protocol:
Epoch extensions are only added to the current epoch when we fail to transition to the next epoch in the happy path; epochs can only have extensions after they have been entered. The chronological ordering of events is: Epoch Setup, Epoch Commit, (optional) Epoch Extension. Therefore it makes more sense to include extensions with the epochCommit type rather than the epochSetup type, since a non-committed epoch cannot have extensions.
Also updates `inmem/epoch.go` `epochSetup` struct to only implement the required methods for `TentativeEpoch`, while the methods for `CommittedEpoch` are moved to the `epochCommit` struct.
Initially from code review comments: https://github.com/onflow/flow-go/pull/6974#discussion_r1950147238

Epoch Interface Refactor: update epoch extensions

---

cmd/collection/main.go
engine/collection/epochmgr/factories/compliance.go
engine/collection/pusher/engine.go
engine/collection/pusher/engine_test.go
engine/testutil/nodes.go

Some collection node modules (pusher) depend on some unused database storage modules. This PR removes them.

Collection node: remove unused db dependencies

---

integration/benchnet2/automate/templates/helm-values-all-nodes.yml
integration/localnet/Makefile
integration/localnet/builder/bootstrap.go
integration/testnet/network.go

The default block rate for transient networks is 1bps, but Cruise Control defaults to a maximum view duration of 910ms (desired default for Mainnet). This causes Cruise Control to prevent the network from operating within the target timing and accumulate error between actual wall-clock time and target timing. 
This PR adjusts the config for Localnet and Benchnet so that Cruise Control can operate within the 1bps timing.

Adjust upper bound of Cruise Control for test networks

---

engine/execution/pruner/core.go
module/block_iterator/state.go
module/block_iterator/state_test.go

This PR fixes two issues:
1. When I increase the threshold to retain more chunk data packs, it run into a fatal error, saying the latest is less than next block. 
```
{"level":"fatal",..."error":"failed to create block iterator: failed to create range for block iteration: latest block is less than next block: 242742568 < 245752965","time":"2025-03-03T20:40:39.583143782Z","message":"unhandled irrecoverable error"}
```
This is resolved by allowing the latest to go backward and even blow the next block to iterate.
2. Report the pruning related metrics on startup, so that the metrics won't report as 0, which causes the dashboard showing some confusing spikes.

[Executino] Chunk data pack pruning config fix

---

cmd/node_builder.go
cmd/scaffold.go
cmd/scaffold/pebble_db.go
cmd/verification_builder.go
storage/dbops/dbops.go

Depend on:
- https://github.com/onflow/flow-go/pull/6868
- https://github.com/onflow/flow-go/pull/6947
- https://github.com/onflow/flow-go/pull/6872
Working towards: https://github.com/onflow/flow-go/issues/6515
This PR adds flags to all node type for switching database operations, as well as switching from badger to pebble for verification node storing all verification specific data, such as approvals and chunk locators.

[Storage Refactor] Using flags to roll out database operation changes for Verification nodes.

---

module/mempool/common.go
module/mempool/stdmap/backDataHeapBenchmark_test.go
module/mempool/stdmap/backend.go
module/mempool/stdmap/backend_test.go
module/mempool/stdmap/eject.go
module/mempool/stdmap/eject_test.go
module/mempool/stdmap/options.go

This PR reverts the accidental merge introduced in [PR #7110](https://github.com/onflow/flow-go/pull/7110). The changes from the branch `andron/updte-backend-to-work-with-generics-backdata` were unintentionally merged into [UlianaAndrukhiv/7073-mapBackData-generic-refactoring](https://github.com/onflow/flow-go/tree/UlianaAndrukhiv/7073-mapBackData-generic-refactoring), and this revert commit undoes those modifications to restore the intended state of the target branch.
Reverts onflow/flow-go#7110

Revert "[Malleability] Update Backend to work with generic BackData."

---

cmd/util/cmd/read-badger/cmd/storages.go

Currently, `InitBadgerAndPebble()` can return error without closing `badger.DB`.  In this case, the opened badger.DB is not accessible to the caller so it cannot be closed.
This PR fixes this by not opening `badger.DB` before `InitBadgerAndPebble()` returns error along with `nil *badger.DB`.

[Storage] Fix InitBadgerAndPebble() not closing badger.DB on error

---

engine/execution/state/bootstrap/bootstrap_test.go
fvm/evm/evm_test.go
fvm/evm/impl/impl.go
fvm/evm/stdlib/contract.cdc
fvm/evm/stdlib/contract.go
fvm/evm/stdlib/contract_test.go
utils/unittest/execution_state.go

Closes https://github.com/onflow/flow-go/issues/6800
This new method can be used instead of `COA.call`, in a Cadence transaction, when the user wants to execute a contract call, without committing any state changes. This is useful for reading a contract's state.

Introduce the `dryCall` method under `EVM` contract & `CadenceOwnedAccount` resource

---

module/mempool/common.go
module/mempool/stdmap/backDataHeapBenchmark_test.go
module/mempool/stdmap/backend.go
module/mempool/stdmap/backend_test.go
module/mempool/stdmap/eject.go
module/mempool/stdmap/eject_test.go
module/mempool/stdmap/options.go

Note: This is copy of PR https://github.com/onflow/flow-go/pull/7110 as it was unintentionally merged and reverted than.
In this PR [Backend](https://github.com/onflow/flow-go/blob/feature/malleability/module/mempool/stdmap/backend.go) was refactored to work with the generic `Backdata` interface introduced in this PR https://github.com/onflow/flow-go/pull/7089.  
The [Backend](https://github.com/onflow/flow-go/blob/feature/malleability/module/mempool/stdmap/backend.go) now uses generic type parameters:
- Key (K) is constrained with comparable, ensuring that it supports equality checks.
- Value (V) is defined as any, allowing flexibility.
Also, tests and some parts that are being used by [Backend](https://github.com/onflow/flow-go/blob/feature/malleability/module/mempool/stdmap/backend.go) …

[Malleability] Update Backend to work with generic BackData.

---

cmd/scaffold.go
cmd/scaffold/pebble_db.go
cmd/util/cmd/read-badger/cmd/root.go
cmd/util/cmd/read-badger/cmd/storages.go

`v0.39.0` is using `--pebble-dir` already, let's keep using this flag.

Update pebble dir path

---

cmd/util/cmd/read-badger/cmd/transaction_results.go
fvm/fvm_bench_test.go
model/flow/transaction_result.go

https://github.com/onflow/flow-go/issues/6723
This PR resolves malleability of `flow.TransactionResult` by removing `ID` and fixing usages to depend on data fields instead of `flow.IDEntity` interface.

[Malleability] `flow.TransactionResult` 

---

cmd/access/node_builder/access_node_builder.go
cmd/consensus/main.go
cmd/observer/node_builder/observer_builder.go
consensus/integration/nodes_test.go
engine/access/access_test.go
engine/access/ingestion/engine_test.go
engine/testutil/nodes.go
module/chunks/chunk_assigner.go
module/mempool/stdmap/assignments.go
module/mempool/stdmap/guarantees.go
module/mempool/stdmap/guarantees_test.go
module/mempool/stdmap/identifier_map.go
module/mempool/stdmap/identifier_map_test.go
module/mempool/stdmap/receipts.go
module/mempool/stdmap/receipts_test.go
module/mempool/stdmap/times.go
module/mempool/stdmap/times_test.go
module/mempool/stdmap/transaction_timings.go
module/mempool/stdmap/transaction_timings_test.go
module/metrics/example/verification/main.go
module/state_synchronization/indexer/indexer_core_test.go

Closes: #7166
This PR updates the constructors for various memory pools (`Assignments`, `Guarantees`, `IdentifierMap`, `Receipts`, `Times`, `TransactionTimings`) by removing the second return value (`error`). These constructors cannot fail, making the error return unnecessary. Removing it simplifies function signatures and improves readability by cleaning up the calling code.

[Malleability] Follow up for fixing root interface implementations in the stdmap package

---

cmd/util/cmd/run-script/cmd.go
engine/access/rest/router/router.go
engine/access/rest/server.go
engine/access/rest/websockets/handler.go
engine/access/rpc/engine.go

Pass irrecoverable context to ws handler

---

model/flow/resultApproval.go
model/flow/resultApproval_test.go

Closes: #6652 
In this PR `ID` method of the `ResultApproval` was fixed by hashing all fields of the struct. Malleability checker test was added as well.

[Malleability] ResultApproval 

---

engine/execution/block_result.go
engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/computer/result_collector.go
engine/execution/computation/manager.go
engine/execution/ingestion/block_queue/queue.go
engine/execution/ingestion/core.go
engine/execution/ingestion/core_test.go
engine/execution/ingestion/mocks/block_store.go
engine/execution/ingestion/uploader/file_uploader.go
engine/execution/ingestion/uploader/gcp_uploader.go
engine/execution/ingestion/uploader/uploader.go
engine/execution/state/state_storehouse_test.go
engine/execution/state/unittest/fixtures.go
fvm/fvm_bench_test.go
module/mempool/entity/executableblock.go
storage/badger/computation_result_test.go
storage/badger/operation/computation_result_test.go
utils/unittest/fixtures.go

Close: #6672
The `ExecutableBlock` type implemented `Entity`, but its` ID()` method was misused in various places.
- Renamed `ID()` to `BlockID()` to clarify its purpose and refactored its usages.  
**NOTE**: **The only valid use** of `ExecutableBlock` as an `Entity` was in `enqueueBlock`(`engine/execution/ingestion/core.go`) for `flow.Deduplicate`. However, based on the `HandleBlock` implementation, if an error is returned, both `missingColls` and `executables` are always `nil`, making the deduplication step (`flow.Deduplicate(append(...))`) likely redundant.

[Malleability] Fix ID misuse in ExecutableBlock type

---

model/flow/incorporated_result_seal.go
module/builder/consensus/builder_test.go
module/mempool/consensus/exec_fork_suppressor.go
module/mempool/consensus/exec_fork_suppressor_test.go
module/mempool/stdmap/incorporated_result_seals_test.go

Close:  #6705
The `IncorporatedResultSeal` type previously implemented `Entity`, but its `ID()` method was misused in several places. This PR corrects those usages.  
- `ExecForkSuppressor` (`module/mempool/consensus/exec_fork_suppressor.go`)
Since`mempool.IncorporatedResultSeals` stores seals by the `ID` of the incorporated result. `ExecForkSuppressor` also stores a set of seals indexed by `incorporated result ID`.  
- Updated usages in unit tests

[Malleability] Fix ID misuse in IncorporatedResultSeal type

---

model/flow/incorporated_result.go
module/mempool/herocache/backdata/cache_test.go
module/mempool/herocache/backdata/heropool/pool_test.go
module/mempool/queue/heroQueue_test.go
module/mempool/stdmap/backDataHeapBenchmark_test.go
module/mempool/stdmap/backdata/mapBackData_test.go
module/mempool/stdmap/backend_test.go
module/mempool/stdmap/eject_test.go
utils/unittest/entity.go
utils/unittest/util.go

Closes: #6675, #6680.
The `IncorporatedResult` and `MockEntity` structs previously implemented the `Entity` interface, but their `ID()` method was misused. This PR corrects that issue.
- The `Checksum` method was removed from `IncorporatedResult`, and its `ID()` method is now used solely to identify the struct, rather than to implement the `Entity` interface.
- `MockEntity` has been refactored to serve as a standalone struct for testing mempool functionality.
- Updated unit tests to reflect these changes.

[Malleability] Fixed misuse of ID for IncorporatedResult and MockEntity

---

model/flow/incorporated_result.go
model/flow/incorporated_result_test.go

Closes: #6675.
The `IncorporatedResult` previously implemented the `Entity` interface without any need. This PR corrects that issue and fixed implementation of the `ID` method.
- The `Checksum` method was removed from `IncorporatedResult`, and its `ID()` method is now used solely to identify the struct.
- Added unit test with the Malleability checker to reflect these changes.

[Malleability] Fix ID implementation of IncorporatedResult type

---

model/flow/chunk.go
model/flow/chunk_test.go

Close: #6659
This PR resolves the malleability of `flow.Chunk` by updating the `ID()` method based on all the data (`Index` and `EndState` were not included in `ID()` previously). It also ensures the correct `EncodeRLP` implementation for `flow.Chunk` and `flow.ChunkBody`.  
- Added a unit test to verify that `flow.Chunk` is not malleable.  
- Updated unit tests to reflect the changes. 
- Removed `ByChecksum` as it was unused.  
- Removed `TestDistinctChunkIDs_EmptyChunks` and `TestDistinctChunkIDs_FullChunks`, as they are both checking that changing a field in the `ChunkBody` changes the `ID`, which is already be covered by the new `TestChunkMalleability`.

[Malleability] Chunk

---

storage/badger/init.go

Currently, the `InitPublic()` and `InitSecrets()` functions can successfully open BadgerDB and then return an error without allowing the caller to close the database.
This PR updates `InitPublic()` and `InitSecrets()` to close the opened database before they return an error.

[Storage] Close BadgerDB before db init functions return error

---

cmd/scaffold.go

Currently, `initProtocolDB()` sets `ProtocolDB` to either BadgerDB or PebbleDB depending on `dbops`. But there is still some old code that sets `ProtocolDB` to BadgerDB in `initBadgerDB()`.
This PR removes the old code in `initBadgerDB()`.

[Storage] Remove old code in `initBadgerDB()`

---

model/flow/epoch_test.go
utils/unittest/entity.go
utils/unittest/entity_test.go

This PR extends the malleability checker to work with types that do not implement `IDEntity` (for example, a hash of all fields excluding a signature field, used as the digest for a signature).

Extend Malleability Checker to non-Entity types

---

storage/badger/receipts.go

This PR optimizes storing execution receipts in BadgerDB by removing extra `receipt.ID()`.
Also, remove the unused `ExecutionReceipts.results` field variable.
This was found while getting familiar with BadgerDB and Pebble storage code base.

[Storage] Optimize storing execution receipts in BadgerDB

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
integration/tests/access/cohort4/websocket_subscriptions_test.go

Closes: #7251
Updates the CLI flag used to control the websockets API to use the final naming, and enable by default.

[Access] update websockets cli flag

---

engine/access/rest/common/models/block.go
model/flow/ledger.go

Closes #7193 
while building the block model for the rest api, we shouldn't manually call marshalJSON, as that will actually double encode this particular value. Instead, just add string function to the type and call that instead

Add string function to StateCommitment type, use in place of marshalJSON

---

engine/common/version/version_control.go
engine/common/version/version_control_test.go

Currently, we log a message each time a version beacon event is ignored in the `VersionControl`. This check happens for each block, so we end up logging the same line once per second at info level. Since the message is really only useful one time, add logic to only log it once.

[Access] Only log version control overrides once

---

engine/execution/ingestion/block_queue/queue.go
model/flow/protocol_state.go
model/flow/resultApproval.go
model/flow/timeout_certificate.go

Closes: #7226
Reviewed `ID` implementations for all types and refactored the following structs to use the standard `flow.MakeID(struct)` method:
-  `ResultApproval`
-  `EpochStateContainer`
-  `MissingCollection`
-  `TimeoutCertificate`
`ExecutionReceiptMeta` type is not included in this PR, as it is currently under review and its `ID` implementation will be handled in PR #7208.

[Malleability] Review structs with stub ID implementation

---

.golangci.yml

This PR extends https://github.com/onflow/flow-go/pull/7322. It un-comments out the custom linter config to enable the custom linter. 
This exists as a separate PR only so that each merge to `master` passes CI, because CI uses the version of the workflow definition defined on `master`.

Enable custom `structwrite` linter in CI

---

state/protocol/badger/state_test.go

This was flakey. If a consensus node was constructed as the duplicate in the test case, it would result in an invalid dkg id mapping representation, which would cause the test to eventually panic.
Closes https://github.com/onflow/flow-go/issues/7332
```
% go test -run=TestBootstrap_InvalidIdentities/duplicate_node_ID -count=100 ./state/protocol/badger
ok  	github.com/onflow/flow-go/state/protocol/badger	5.231s
```

Fix bug in bootstrapping duplicate node ID test

---

.github/workflows/image_builds.yml
actions/promote-images/action.yml

The following PR creates a new workflow that will centralize the process for building and releasing Flow docker images.
* [Public Build](https://github.com/onflow/flow-go/actions/runs/14605211390)
* [Secure Build](https://github.com/onflow/flow-go/actions/runs/14605685087)
This workflow is designed to **build, tag, and publish Docker images** for the `flow-go` project using GitHub Actions. It supports **both public and secure builds**, and provides a mechanism to **promote successfully built images from a private registry to a public registry**.
---
- **Build and push Docker images** for various `flow-go` roles (e.g., access, collection, consensus, etc.) based on a specified Git tag.
- **Support two build modes**:
- **Public Build** (`secure-build: false`): Pulls from the public flow-go …

Create pipeline to handle image promotion from private registry to public

---

cmd/consensus/main.go
consensus/integration/nodes_test.go
module/builder/consensus/builder.go
module/builder/consensus/builder_test.go

The RootHeight can be retrieved from protocol state, this allows us to remove the dependency of database for the builder., and also saves one db query.

Remove database dependency from consensus builder

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
cmd/scaffold.go
follower/follower_builder.go
network/p2p/cache/node_disallow_list_wrapper.go
network/p2p/cache/node_disallow_list_wrapper_test.go
storage/node_disallow_list.go
storage/operation/node_disallow_list.go
storage/operation/node_disallow_list_test.go
storage/store/node_disallow_list.go
storage/store/node_disallow_list_test.go

Updates #7242 (completes subtask "Libp2p Blocklist")
Currently, `NodeDisallowListWrapper` receives BadgerDB handle and we need to transition it to use `storage.DB` when we migrate backend database from BadgerDB to Pebble.
This PR supports disallow list.  Changes include:
- Add storage operations in storage/operation/node_disallow_test.go
- Add storage store in storage/store/node_disallow_list.go
- Add storage interface in storage/node_disallow_list.go
This PR also modifies `NodeDisallowListWrapper` to:
- Receive `storage.DB` as input parameter
- Use `storage.NodeDisallowList` to retrieve and store disallow list
The word "blocklist" and "disallowlist" are used interchangeably in the existing code, file name, error messages, etc.  We briefly discussed replacing both with "denylist" but …

[Storage] Support NodeDisallowList for db migration

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
cmd/scaffold.go
follower/follower_builder.go
network/p2p/cache/node_disallow_list_wrapper.go
network/p2p/cache/node_disallow_list_wrapper_test.go
storage/badger/operation/bft.go
storage/badger/operation/prefix.go
storage/operation/node_disallow_list.go
storage/operation/prefix.go

This addresses old tech debt encountered while working on PR #7361.  For consistency, this PR renames "blocklist" to "disallowlist" and also renames db prefix code `blockedNodeIDs` to `disallowedNodeIDs`.
For more info, see "Caveats" at PR #7361.

Refactor to rename blocklist to disallowlist for consistency

---

module/mempool/herocache/backdata/cache.go
module/mempool/herocache/backdata/cache_test.go
module/mempool/herocache/backdata/heropool/pool.go

Closes: #7171 
In this PR implementation of the `Adjust`  function is changed in a way where we find the value by the key and adjust it without re-inserting it with the same key.

[Malleability] Review implementation of Adjust in the heropool cache.

---

fvm/evm/emulator/config.go

moving Petra update timestamp to month ahead to avoid accidentally enabling it in case of emergency HCU - will update it to the actual upgrade date once we set the upgrade timeline.

set Pectra upgrade timestamp to Jun 3rd 2025

---

cmd/bootstrap/run/cluster_qc_test.go
cmd/util/cmd/read-light-block/read_light_block.go
cmd/util/cmd/read-light-block/read_light_block_test.go
engine/collection/compliance/core_test.go
engine/collection/compliance/engine_test.go
engine/collection/message_hub/message_hub_test.go
engine/collection/synchronization/engine_test.go
integration/tests/collection/suite.go
model/cluster/block.go
model/messages/collection.go
model/messages/convert_test.go
module/builder/collection/builder_test.go
module/finalizer/collection/finalizer.go
module/finalizer/collection/finalizer_test.go
state/cluster/badger/mutator.go
state/cluster/badger/mutator_test.go
state/cluster/badger/snapshot_test.go
state/cluster/badger/state.go
state/cluster/root_block.go
storage/badger/cluster_blocks_test.go
storage/badger/procedure/cluster.go
storage/badger/procedure/cluster_test.go
utils/unittest/fixtures.go

Related PR: #7334
This PR builds on the work in [#7334](https://github.com/onflow/flow-go/pull/7334) and applies a similar approach as for `UntrustedClusterBlock` to `UntrustedClusterProposal` ([comment](https://github.com/onflow/flow-go/pull/7334#discussion_r2064197494)).
Given the widespread usage of `cluster.BlockProposal` and `UntrustedClusterProposal` these changes are isolated into a separate PR for clarity and ease of review.
- Replaced fields for `cluster.BlockProposal` with non-pointers.
- Replaced the `UntrustedClusterProposal` type with:
`type UntrustedClusterProposal cluster.BlockProposal`
- Updated constructor for `cluster.Block` to return non-pointer as it mostly uses in creating `cluster.BlockProposal`.
Additionally:
- Simplified some helper fixture functions.
- Updated …

[Malleability] UntrustedClusterProposal, BlockProposal refactoring

---

integration/localnet/builder/bootstrap.go
integration/localnet/conf/grafana-loader.json
integration/localnet/conf/prometheus.yaml
integration/localnet/docker-compose.metrics.yml

Having a named and attachable network allows for running additional containers on the same network. 
This makes it easy to start a TPS loader on the same network. This also allows the loaders metrics to be collected by the local grafana if the loader is started.

Localnet hooks for TPS loader

---

engine/execution/state/bootstrap/bootstrap_test.go

Added additional test for safety. So we don't accidentally change something in the bookkeeping parts of the transactions.

Add additional test to check for state commitment changes

---

cmd/util/cmd/atree_inlined_status/cmd.go
cmd/util/cmd/check-storage/cmd.go
cmd/util/cmd/diff-states/cmd.go
cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/export-evm-state/cmd.go
cmd/util/cmd/generate-authorization-fixes/cmd.go
cmd/util/cmd/run-script/cmd.go
cmd/util/ledger/util/state.go

Closes #7368
This PR can reduce state extraction duration by ~29 minutes:
- before: about ~49 minutes
- after:  about ~20 minutes
When state is extracted without migration, trie was needlessly rebuilt, which took about 29 minutes.
This PR avoids rebuilding trie (for this case) by creating checkpoint file from loaded trie.
Thanks @zhangchiqing for identifying this and opening issue #7368. :+1:

Reduce state extraction w/o migration by ~29 minutes (~2.5x speedup)

---

engine/access/subscription/tracker/execution_data_tracker.go

Closes: #7338 
Currently, the grpc and websockets streams will verify that the requested start height is within the range of indexed blocks on the node. When using endpoints that start from the latest sealed block, this frequently fails with an error because the sealed block has not finished indexing.
```
Error: Failed to subscribe to topic events: internal error: subscription finished with error: rpc error: code = InvalidArgument desc = could not get start height from block height: start height 110896543 is higher than highest indexed height 110896542
```
This PR relaxes this check to allow a small difference between the start height and the indexed height. If a request comes in for a start height that is less than 30 blocks ahead of the latest indexed height, the stream will be allowed. …

[Access] Allow small gap between streaming start and indexed height

---

model/flow/collection.go
model/flow/collection_test.go
model/flow/entity.go

This PR implements a cache for entity IDs, using a lazy strategy of caching the ID when it is first requested, and using an atomic so the entity remains safe for concurrent use.
This approach has the outstanding problem that entities created from unmarshalling (from the database or network) do not generally use the constructor and consequently will not populate the `idCache` field 🤔. In this PR I have addressed this by over-riding un-marshalling to instantiate the cache field. Alternatively we could:
- change unmarshal points to use the constructor (this would be another per-type task to do as part of https://github.com/onflow/flow-go/issues/7269
- make `ID` safe if `idCache` is not initialized (just re-compute the hash every time, like it currently works on `master`)
---
There is another …

Cache ID on hash strategy

---

engine/common/version/version_control.go

Backports: https://github.com/onflow/flow-go/pull/7420
This PR adds some missing compatible version overrides, and removes 2 that were unused. See issue for details.

[Access] Fix version compatibility list - v0.41

---

engine/common/version/version_control.go

v0.41 has a backwards incompatible change for scripts. Queries for account data for blocks before the account was migrated in Feb 2025 will return empty results instead of the expected data.

[Access] Remove v0.41 compatibility override

---

storage/operation/badgerimpl/writer.go
storage/operation/badgerimpl/writer_test.go
storage/operation/writes_test.go

Updates #7242
Currently, docs for `ReaderBatchWriter.Set()` promises it is safe to modify the key and value after `Set()` returns.  However, BadgerDB's docs for `WriteBatch.Set()` says users must not modify key and value until the end of transaction.
This PR clones arguments in badgerimpl's `ReaderBatchWriter.Set()` and `ReaderBatchWriter.Delete()` to allow the caller to modify the key and value as promised by our docs.
This bug hasn't surfaced yet because of the way the functions are currently used and leaving it as-is risks future problems.
The corresponding functions for Pebble don't need this fix because Pebble clones the same arguments under-the-hood.
I found this while getting familiar with storage code related to BadgerDB and Pebble (not looking for bugs).

[Storage] Fix Writer.Set() & Writer.Delete() args not being safe to modify (BadgerDB)

---

cmd/execution_builder.go

Remove the badger to pebble halfway data migration for execution node.
"halfway" means, it only migrate a subset of data from badger to pebble, such as last executed block. This was suppose to allow EN to switch to pebble storage after a restart without a complete badger -> pebble data migration. However, as the [protocol data refactor is close to complete](https://github.com/onflow/flow-go/pulls/zhangchiqing), as well as [the migration util ](https://github.com/onflow/flow-go/pull/7413) , we can probably either do a dynamic bootstrapping or data migration to switch the storage from badger to pebble for EN's protocol database. This simply the logic, since the data is only stored in one place - either badger or pebble, therefore, we don't need the chained storage which queries both …

[Execution] Disable halfway data migration from badger to pebble

---

storage/operation/badgerimpl/writer.go
storage/operation/pebbleimpl/writer.go
storage/operations.go

This PR removes the call to `Close` from the `Commit` method of `ReaderBatchWriter`. The reason is that:
- `WithReaderBatchWriter` defers `batch.Close` https://github.com/onflow/flow-go/blob/3701d49e46af01d11d43d1a94a7f91bb556d3808/storage/operation/pebbleimpl/writer.go#L95
- `WithReaderBatchWriter` also calls `batch.Commit` https://github.com/onflow/flow-go/blob/3701d49e46af01d11d43d1a94a7f91bb556d3808/storage/operation/pebbleimpl/writer.go#L108
So currently (prior to this PR) we were closing each `Batch` _twice_ when using `WithReaderBatchWriter` in the happy path. 
We have seen some crashes originating from Pebble indicating unset fields (see [Notion document](https://www.notion.so/flowfoundation/EN-Pebble-Fatal-Errors-2025Q2-2091aee123248050abbce0f0da1e8b66?source=copy_link) for …

[v0.42] Remove double-close of pebble batch

---

module/block_iterator/executor/executor.go
module/state_synchronization/indexer/indexer_core.go
storage/operation/dbtest/helper.go

This PR builds on https://github.com/onflow/flow-go/pull/7489, which fixed `batch.Close` being called more than once. 
This PR is to ensure `batch.Close` is **always** called, and is called **exactly once**. This is only necessary when the `batch` object is created outside of `db.WithReaderBatchWriter` helper function, which handles Commit and Close internally.

[Storage] Ensure batch.Close is called exactly once.

---

.golangci.yml
engine/verification/assigner/engine.go
engine/verification/fetcher/engine.go
engine/verification/fetcher/engine_test.go
engine/verification/fetcher/execution_fork_test.go
engine/verification/requester/requester_test.go
engine/verification/utils/unittest/helper.go
model/chunks/chunkLocator.go
model/chunks/chunkLocator_test.go
model/verification/chunkStatus.go
module/mempool/stdmap/chunk_requests_test.go
utils/unittest/fixtures.go

Closes: #7276
This PR targets `feature/malleability` because `Locator` had many usages in a struct on master (`inMemChunkStatus`) that is already removed in `feature/malleability` during the `mempool` refactoring.
-  Added constructor `Locator` type.
-  Removed non-constructor mutations.
-  Removed `ChunkLocatorID` util function and replaced usages to `constructor` and `ID()` method.
-  Added `UntrustedLocator` model.
-  Added unit tests for constructor.

[Malleability Immutable] Removed non-constructor mutations for Locator

---

cmd/util/cmd/rollback-executed-height/cmd/rollback_executed_height_test.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/execution_verification_test.go
engine/execution/ingestion/core_test.go
engine/execution/messages.go
engine/verification/utils/unittest/fixture.go

Closes: #7274
This change is targeted at the `feature/malleability` branch, where `ExecutableBlock.ID` has already been renamed to `ExecutableBlock.BlockID`.
This pull request is made following the suggestion in this [comment](https://github.com/onflow/flow-go/pull/7433#discussion_r2146114855) regarding `ComputationResult` malleability.
Immutability issue #7274 for this type should not have been made, since `ComputationResult` does not have a canonical `ID` (after renaming for `ExecutableBlock.ID` to `ExecutableBlock.BlockID`) and is not sent over the network.
This pull request implements the second part of the suggested changes from the comment:
> Make `ComputationResult.ExecutionReceipt `a non-embedded field

[Malleability Immutable] ComputationResult refactoring

---

.github/workflows/ci.yml

This changes the cache key to include the SHA, and allows fallback to equivalent cache keys from other SHAs (branches). This ensures different branches have distinct cache keys, which prevents potential contention if GH Actions Cache uses a shared namespace (not fully clear from documentation).

Update cache key definition for linter binary

---

engine/access/ingestion/engine_test.go
engine/access/rest/http/routes/collections_test.go
engine/access/rpc/backend/backend_stream_transactions_test.go
engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions_test.go
engine/access/rpc/backend/retry_test.go
engine/common/rpc/convert/collections.go
integration/internal/emulator/memstore.go
integration/internal/emulator/tests/store_test.go
model/flow/collection.go
model/flow/collection_test.go
module/state_synchronization/indexer/indexer_core.go
state/cluster/badger/mutator_test.go
storage/badger/collections.go
storage/badger/collections_test.go
storage/badger/operation/collections_test.go
storage/badger/procedure/cluster.go
storage/operation/collections_test.go
storage/store/collections.go
storage/store/collections_test.go

This PR adds:
- `LightCollection` immutability
- Using pointer type by default for `LightCollection` (match other types)

Remove non-constructor mutations of LightCollection

---

cmd/access/node_builder/access_node_builder.go
cmd/execution_builder.go
cmd/execution_config.go
cmd/util/cmd/read-badger/cmd/commits.go
engine/execution/state/state.go
module/executiondatasync/storage/datastore_factory.go

Work towards https://github.com/onflow/flow-go/issues/7265
This PR:
- Updates execution node to support pebble based execution data. 
- Storage engine can be chosen by flag `--execution-data-db=pebble`, default is `--execution-data-db=badger`.
- Refactor access node to reuse the same logic for determine the storage engine for execution data.

[Storage] execution node support pebble based execution data store

---

.github/workflows/image_builds.yml
actions/promote-images/action.yml

This pull request introduces a new job to the GitHub Actions workflow for promoting container images from the private registry to the partner registry. The promotion process is designed to ensure that only approved images are deployed to the partner registry.
- **New Job: `promote-to-partner-registry`**
- Promotes container images for the `access` role from the private registry to the partner registry.
- Utilizes a matrix strategy to handle promotion tasks in parallel for different roles (currently only `access`).
- Includes gating mechanisms to ensure promotion only occurs if at least one of the `public-build` or `secure-build` jobs succeeds.
- Defines an environment for each role to manage the promotion process.
- **Steps in the Job:**
- Checks out the repository using …

Add support for promoting images to partner registry

---

storage/operation/computation_result.go
storage/operation/events.go
storage/operation/reads.go
storage/operation/reads_test.go
storage/operation/receipts.go
storage/operation/transaction_results.go

Refactored the iteration mechanism in storage/operation to improve developer experience and prevent common bugs.
The previous IterationFunc required the caller to manage key copying, which could lead to subtle bugs if a key was appended to a slice without being copied first. The iteration control was also less intuitive, relying on sentinel errors to
exit early.
This commit introduces the following changes:
- The IterationFunc signature is changed to func(keyCopy []byte, getValue func(destVal any) error) (bail bool, err error).
- Key copying is now handled internally within the IterateKeys function, hiding this implementation detail from the caller and preventing misuse.
- Callers can now exit an iteration early by returning (bail=true, err=nil), which is more explicit than the previous …

[Storage] Optimize the IterFunction

---

storage/badger/guarantees.go
storage/badger/guarantees_test.go
storage/guarantees.go

Differing consensus forks can contain the same collection guarantee, which caused indexing from CollectionID -> GuaranteeID to fail with an irrecoverable error. However, this situation is expected, so needs to be handled. We now simply skip duplicates, since we know there is a 1:1 relationship between collections and guarantees.

[Malleability] fix CollectionGuarantee ID indexing

---

.github/workflows/ci.yml

The following PR updates our CI workflow to leverage environments for accessing the Docker secrets. This will enable us to properly use the secrets with PRs from forks. The condition that is used to set the environment name enables us to leverage an `internal ci` for PRs from members associated with the org. The `external ci` environment will be used for non team members, and this will require a secondary approval by the protocol team before the environment can be accessed.

Update CI workflow to leverage environments

---

state/protocol/protocol_state/state/mutable_protocol_state_test.go
storage/collections.go
storage/operation/collections.go
storage/store/collections.go
storage/store/epoch_commits_test.go
storage/store/epoch_protocol_state_test.go
storage/store/epoch_setups_test.go
storage/store/payloads_test.go
storage/store/seals_test.go

[PR 7262](https://github.com/onflow/flow-go/pull/7262) introduces a subtle but potentially important change to the test [`state/protocol/protocol_state/state/mutable_protocol_state_test.go`](https://github.com/onflow/flow-go/blob/53f2fcff62158a4c913c0646ce069eaf095d91fa/state/protocol/protocol_state/state/mutable_protocol_state_test.go), which I think overall weakens the test. Hence, this PR reverts the questionable portion of the changes.
[PR 7262](https://github.com/onflow/flow-go/pull/7262) changes the [**variables holding mocks** from **value types** to **pointer types**](https://github.com/onflow/flow-go/blob/53f2fcff62158a4c913c0646ce069eaf095d91fa/state/protocol/protocol_state/state/mutable_protocol_state_test.go#L37-L38):
* When you instantiate a new Mock with the provided …

Reverting portions of `mutable_protocol_state_test.go` to avoid weakening the tests

---

fvm/evm/emulator/emulator.go
fvm/evm/emulator/emulator_test.go
fvm/evm/emulator/tracker.go
fvm/evm/precompiles/arch.go
fvm/evm/precompiles/precompile.go
fvm/evm/precompiles/replayer.go
fvm/evm/testutils/handler.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Work Towards: https://github.com/onflow/flow-go/issues/7816
Release notes: https://github.com/ethereum/go-ethereum/releases/tag/v1.16.3

Bump `ethereum/go-ethereum` dependency to `v1.16.3`

---

engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/transactions/provider/execution_node.go
engine/access/rpc/backend/transactions/provider/local.go
engine/access/rpc/backend/transactions/retrier/retrier.go
engine/access/rpc/backend/transactions/status/deriver.go
engine/access/rpc/backend/transactions/status/deriver_test.go
engine/access/rpc/backend/transactions/stream/transaction_metadata.go
engine/access/rpc/backend/transactions/transactions.go
engine/access/testutil/fixture.go
engine/access/testutil/state.go
module/mempool/herocache/transactions_test.go
utils/unittest/fixtures.go

- Improve documentation for `TxStatusDeriver`
- Add tests
- Cleanup outdated error handling (methods no longer return `state.ErrUnknownSnapshotReference`)

[DataAvailability] Improve derived tx status handling and documentation

---

module/metrics/compliance.go
module/metrics/labels.go

This PR adds a resource label to existing block finalization metrics to count seals which don't include verifier signatures.
[Testing on Benchnet](https://flowfoundation.grafana.net/d/PkvVJj4Mz/mainnet-general?orgId=1&from=2025-09-10T16:03:01.045Z&to=2025-09-10T16:30:30.606Z&timezone=America%2FVancouver&var-network=seal-metrics&refresh=10s)
From Benchnet testing, the first spike is from enabling emergency sealing on SN1 and shutting off VN1 (only VN). Second spike is from setting `--required-construction-seal-approvals=0` on SN1. This plots the number of emergency seals as a percentage of total seals. 
```
100 *
sum(increase(consensus_compliance_finalized_payload_total{resource="emergency_seal",network="seal-metrics"}[5m]))
/
sum(increase(consensus_compliance_finalized_payload_total{resour …
```

Metric for emergency seals

---

engine/access/access_test.go
engine/access/ingestion/collection_syncer.go
engine/access/ingestion/engine_test.go

Closes: #7929
Currently, Access nodes will batch collection requests within the requester engine, and allow the requester to decide when to send them. In the worst case, this could end up taking 2x the batch interval, which defaults to 1 second. We've observed that ANs tend to get collections 1-3 seconds after the block is finalized.
This PR updates ANs to send the collections request immediately after the block is finalized.

[Access] Request collections immediately

---

cmd/util/cmd/checkpoint-collect-stats/cmd.go

Closes #7924 
Updates #7573
The checkpoint-collect-stats subcommand reports unknown payload key if the payload is using the new data format using account status format v4.
The new data format was introduced by the migration PR https://github.com/onflow/flow-go/pull/7738 and testnet was migrated on Sept. 17, 2025.

Support account status v4 in checkpoint-collect-stats util

---

.github/workflows/stale.yml

Closes #7935
This PR prevents `actions/stale` from closing pull requests with "Preserve" label.
Changes to stale.yml:
- added `exempt-pr-labels: 'Preserve'`
- bumped `actions/stale` from v9 to v10

Prevent actions/stale from closing pull requests with "Preserve" label

---

cmd/util/cmd/compare-cadence-vm/cmd.go
cmd/util/cmd/debug-script/cmd.go
cmd/util/cmd/debug-tx/cmd.go
utils/debug/remoteClient.go
utils/debug/remoteView.go

Improve the remote debugging commands (`debug-tx`, `debug-script`, `compare-cadence-vm`).
The AN rejects register value requests for invalid addresses. Handle this gracefully and assume the register is empty.

[Cadence VM] Handle invalid addresses

---

module/executiondatasync/execution_data/downloader.go

I don't believe this is causing actually issues today because `edCids` are currently unused and each goroutine only accesses their index into `chunkExecutionDatas`.

[Access] Fix unsynchronized concurrent access in downloader

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/computer/result_collector.go
engine/execution/computation/computer/transaction_coordinator_test.go
module/metrics.go
utils/unittest/fvm.go

After changes from https://github.com/onflow/flow-go/pull/7944 the logs have the problem logs contain `"critical_error":true` even if the transaction was successfully executed.
I changed the semantics a little bit with the code and the logging. The `process` and the "old" system transaction are now considered to be system transactions, but the scheduled transactions are not.
Full log after https://github.com/onflow/flow-go/pull/7944.
```
{
"level": "info",
"node_role": "execution",
"node_id": "5f6c73a22445d7d958c6a37c1f3be99c72cacd39894a3e46d6647a9adb007b4d",
"module": "FVM",
"block_id": "d2dbaa58604f13d1c3ec16654612cda6eeddc36a8d9cb8fb0ee321d3ef5eef16",
"height": 282459901,
"system_chunk": true,
"system_transaction": true,
"critical_error": true,
"num_collections": 0,
"num_txs": 2, …
```

Change system chunk logging
