onflow/flow-go

crypto/README.md

(It would be great to merge this PR before open sourcing)
- update the new github path
- include the latest changes in the lib

Crypto: update readme

---

README.md

ref: https://github.com/dapperlabs/flow-go/pull/4838

Fix bad readme change

---

README.md
ledger/common/hash.go
ledger/common/hash_test.go
ledger/common/pathfinder/pathfinder.go
ledger/common/pathfinder/pathfinder_test.go
ledger/complete/mtrie/forest.go
ledger/partial/ledger.go
ledger/partial/ledger_test.go

this PR adds the remaining tests to the ledger package.

Adding missing tests to the ledger package

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Adds release drafter action, copied from https://github.com/onflow/cadence/blob/master/.github/release-drafter.yml

Add release drafter action

---

integration/localnet/bootstrap.go

Set chunk-alpha=1 in consensus and verification nodes in local docker network.

Change default chunk-alpha in integration localnet

---

go.mod
go.sum
integration/go.sum

The previously pinned commit was on a branch that was deleted. This pins the corresponding on the main branch

Update core-contracts dependency

---

cmd/bootstrap/cmd/final_list.go

Before:
```
<nil> INF reading staking contract node information: /Users/leo/flow-mgmt/proposed.pub.json
<nil> ERR staked node count does not match flow and parnter node count nodes=11 staked nodes=6
<nil> WRN matching staked node not found for collected node collected-node-id=26044bbeea6d33d37e6d67a125dabd432f4e9d7260723c28fefedb28f749acf4
<nil> WRN matching staked node not found for collected node collected-node-id=42656e6a616d696e2056616e204d6574657200ed3315cbccd3bf137b61251d17
<nil> WRN matching staked node not found for collected node collected-node-id=436173657920417272696e67746f6e000d3a668638d42f7b85eaa9cb7ecedc53
<nil> WRN matching staked node not found for collected node collected-node-id=44696574657220536869726c65790012c6dfe7f9952efde6a871d2d118c14391
<nil> WRN matching staked …
```

improve bootstrapping logging

---

module/mempool/stdmap/approvals_test.go
module/mempool/stdmap/incorporated_results_test.go

* fixed flakey test for Approvals Mempool 
* minor cleanup of unittest for IncorporatedResults mempool

fixed flakey test for Approvals Mempool

---

cmd/consensus/main.go
module/builder/consensus/builder.go
module/builder/consensus/config.go

closes [4883](https://github.com/dapperlabs/flow-go/issues/4883)

Adding a limit of max 100 collection guarantees per block

---

model/flow/seal.go
model/flow/seal_test.go

simplest possible solution for https://github.com/dapperlabs/flow-go/issues/5075

included sigs in seal ID

---

access/api.go
cmd/access/main.go
engine/access/access_test.go
engine/access/ingestion/engine_test.go
engine/access/rpc/backend/backend.go
engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions.go
engine/access/rpc/backend/historical_access_test.go
engine/access/rpc/backend/retry_test.go
engine/access/rpc/engine.go

Fix tests
go sum
Add test for GetTransaction
No more pending from historical

Allow querying older access nodes for tx results

---

cmd/bootstrap/cmd/copy.go
cmd/bootstrap/cmd/finalize.go

Bring changes from https://github.com/onflow/flow-go/pull/189/files to `v0.12`

Copy changes for updating private keys during finalize

---

engine/verification/match/engine.go

The metrics shows even if the execution node is not broadcasting result for sealed block, the verification are still sending back chunk data pack requests.
I guess the reason is because the execution node was behind and didn't know the block was actually sealed, and still broadcast the result, which causes the verification node sends back the chunk data pack again, and further slows down the execution node to catch up.
This PR add the logic to not drop the result if it's for a block that has already been sealed.

[Verification] not to verify sealed results

---

engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/execution/state_sync_test.go
integration/tests/execution/state_sync_test.go

disable state syncing

---

consensus/hotstuff/blockproducer/block_producer.go
model/flow/index.go
module/builder/consensus/builder.go
storage/badger/blocks_test.go
storage/badger/operation/prefix.go
storage/badger/operation/seals.go
storage/badger/procedure/index.go
storage/badger/procedure/index_test.go
utils/unittest/fixtures.go

- Fixing https://github.com/dapperlabs/flow-go/issues/5181 (see explanation in the comments)
- Added unit tests

Fix payload Indexing

---

go.mod
go.sum
integration/go.mod
integration/go.sum

This release contains the bugfix for testnet: https://github.com/onflow/cadence/pull/586

Update to Cadence v0.12.10

---

engine/consensus/matching/core.go
engine/consensus/matching/engine.go

* some revisions and updates of goDoc and comments;
* renamed receiver variables for `matching.Core` to `c` and for `matching.Engine` to `e`

minor goDoc and stylistic revisions for #5263

---

cmd/verification/main.go
engine/consensus/compliance/engine.go
engine/consensus/matching/engine.go
engine/consensus/matching/engine_test.go
engine/consensus/matching/next_unsealed_results.go
engine/testutil/mock/nodes.go
engine/testutil/nodes.go
engine/verification/match/engine.go
engine/verification/utils/fixtures.go
utils/unittest/chain_suite.go

Brings changes from the following PR to 0.14
https://github.com/onflow/flow-go/pull/365
https://github.com/onflow/flow-go/pull/363

0.14 Patchs 

---

go.mod
go.sum
integration/go.mod
integration/go.sum

Includes https://github.com/onflow/cadence/pull/587
Changes: https://github.com/onflow/cadence/compare/v0.12.10...v0.12.11

Update to Cadence v0.12.11

---

engine/consensus/matching/core.go
engine/consensus/matching/engine.go
utils/fifoqueue/fifoqueue.go

suggested add-on to PR https://github.com/onflow/flow-go/pull/355
* `FifoQueue`: 
-  extended goDoc 
- couple API micro-revisions 
* On errors which `matching.Core` escalates to `matching.Engine`:
- extended logging:   `matching.Core` now logs a full json serialization of the message which was processed when the fatal error occurred
- `matching.Core` now also specifies in its returned error, in which context the error occurred (on processing receipt, approval, or sealing check)
- added error return to `Core.CheckSealing` (thereby, surrounding engine uniformly handles unexpected internal errors)

minor extensions to logging and godoc

---

engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions.go

Cherry Picking 390 to v0.14 branch

---

.github/workflows/ci.yml

Small change to run tests on the v0.14 branch as well

Enable CI on v0.14 branch

---

cmd/execution/main.go
engine/access/rpc/backend/backend.go
engine/execution/ingestion/engine_test.go
engine/execution/state/bootstrap/bootstrap_test.go
fvm/context.go
fvm/extralog/extralog.go
fvm/state/accounts.go
fvm/transaction.go
fvm/transaction_test.go
module/mempool/mock/pending_receipts.go
utils/unittest/execution_state.go

This PR, adds the retry logic to some of the failed transactions. (the ones that fails on checking)

[Execution] Retry logic on transaction with failed checks

---

engine/consensus/matching/indexer.go
fvm/state/accounts.go

- Remove debug log
- Remove [fatal error](https://github.com/onflow/flow-go/pull/422/files)

Remove debug logs

---

storage/badger/collections.go
storage/badger/collections_test.go
storage/collections.go

Same as https://github.com/onflow/flow-go/pull/448

Cherry-pick #448 to v0.14

---

cmd/bootstrap/transit/main.go
engine/common/rpc/convert/convert.go
utils/unittest/equals.go

Resolves https://github.com/dapperlabs/flow-go/issues/5288.

[Transit] Pull and Push Root Snapshot

---

go.mod
go.sum
integration/go.mod
integration/go.sum

Apply bugfix onflow/cadence#666
- Code diff: https://github.com/onflow/cadence/compare/v0.13.1-no-contract-update-validation...v0.13.1-untyped-capability-fix

Update to Cadence v0.13.1-untyped-capability-fix

---

engine/execution/computation/manager.go
engine/execution/computation/manager_test.go
engine/execution/state/bootstrap/bootstrap_test.go
go.mod
go.sum
integration/go.mod
integration/go.sum
utils/unittest/execution_state.go

Add ExecuteScript panic fix
Bump Cadence to v0.13.5

Kan/cherry pick mainnet hotfixes to v0.14

---

cmd/collection/main.go
engine/collection/ingest/config.go

Jordan/cherry pick #476 to 0.14

---

engine/verification/match/engine.go
engine/verification/verifier/engine.go
model/flow/chunk.go
model/flow/chunk_test.go
utils/unittest/fixtures.go

This PR is basically a [cherrypicked set](https://github.com/onflow/flow-go/commit/46e63af24dd67fb6cadaa9446711605f9c902043) of logging improvements for verification node from the master.

[Verification] Yahya/v0.14-improve-verification-logging

---

Makefile
cmd/util/cmd/read-badger/cmd/root.go
cmd/util/cmd/read-protocol-state/cmd/root.go
cmd/util/cmd/root.go

Finish https://github.com/dapperlabs/flow-go/issues/5327

Move read-badger and read-protocol-state to utils

---

engine/verification/assigner/engine.go

* updated Verifier's assigner.Engine to skip receipts whose result is not incorporated in the block

suggested revisions for PR 462

---

cmd/bootstrap/cmd/finalize.go
cmd/bootstrap/run/execution_state.go
cmd/bootstrap/run/execution_state_test.go
cmd/scaffold.go
engine/execution/state/bootstrap/bootstrap.go
engine/execution/state/bootstrap/bootstrap_test.go
engine/testutil/nodes.go
engine/verification/utils/fixtures.go
integration/testnet/network.go
integration/tests/common/mvp_test.go

Added a flag to enable storage limiting.

Storage limit flag

---

module/validation/seal_validator.go
state/protocol/badger/snapshot.go
state/traverse.go
state/traverse_test.go

This PR contains changes that were requested here: https://github.com/onflow/flow-go/pull/521
This PR targets master and old one will be discarded.

[Refactoring] Chain traversing refactoring 2nd attempt 

---

access/api.go
engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions.go
engine/access/rpc/backend/retry.go
go.mod
go.sum
integration/go.mod
integration/go.sum

`git cherry-pick 1cfa5ef5c3b75131d2fb88f1ca781b3d020f5cbe`
https://github.com/onflow/flow-go/commit/1cfa5ef5c3b75131d2fb88f1ca781b3d020f5cbe
PR on master was: https://github.com/onflow/flow-go/pull/533

porting the change to add block ID to GetTransactionResult to v0.14 from master

---

ledger/common/hash.go
ledger/common/utils/split.go
ledger/complete/ledger_benchmark_test.go
ledger/complete/mtrie/forest.go
ledger/complete/mtrie/node/node.go
ledger/complete/mtrie/trie/trie.go

* extended goDoc 
* removed pointers to slices and used slices directly 
* fixed unhandled edge case for non-inclusion proofs 
* ~split out logic for trie updates into dedicated path depending on conditions~

suggestions for PR 505

---

go.mod
go.sum
integration/go.mod
integration/go.sum

https://github.com/onflow/cadence/releases/tag/v0.14.4

Update Cadence to v0.14.4

---

cmd/bootstrap/cmd/finalize.go

Fix a bootstrap process to be compatible with storage fees.

Fix loader

---

cmd/scaffold.go

Limit storage on all networks

---

network/queue/queueWorker.go

- Setting inbound message queue workers to 50 from 5

[Network] Increasing number of network inbound message queue workers

---

module/metrics.go
module/metrics/cache.go
module/metrics/noop.go
module/mock/cache_metrics.go
storage/badger/cache.go

Fix cache missing metrics

---

go.mod
go.sum
integration/go.mod
integration/go.sum

port the cadence version change to master

switch cadence on master

---

cmd/util/ledger/migrations/storage_reporter.go
cmd/util/ledger/migrations/storage_v4.go
cmd/util/ledger/migrations/storage_v4_test.go

During the last Canary spork we identified several problems with the state migration, this PR fixes those issues.

Fix storage format v4 migration

---

cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/migrations/accounts.go
cmd/util/ledger/migrations/broken_contract_migration.go
cmd/util/ledger/migrations/broken_contract_migration_test.go
cmd/util/ledger/migrations/contract_reporter.go
cmd/util/ledger/migrations/storage_reporter.go
cmd/util/ledger/migrations/storage_v4.go
fvm/transactionFeeDeductor.go
module/trace/constants.go

This PR adds a migration which fixes the broken contracts.

[cmd] Broken contract migration

---

engine/consensus/approvals/approval_collector.go

ApprovalCollector: reducing number of locks

Concurrent result approval processing: suggestions pt1

---

engine/consensus/approvals/approval_collector.go
engine/consensus/approvals/assignment_collector.go
model/flow/identifierList.go

* extended some sanity checks;
* added functionality for creating lookup to IdentifierList

Concurrent result approval processing: suggestions pt2

---

engine/execution/ingestion/engine_test.go

Skip for now, as I'm working on the fix

skip flakey tests

---

engine/consensus/sealing/core.go
engine/execution/computation/committer/committer.go
engine/execution/ingestion/engine.go
integration/testnet/network.go
integration/tests/common/msg_state.go
integration/tests/common/receipt_state.go
integration/tests/consensus/sealing_test.go
integration/tests/execution/chunk_data_pack_test.go
integration/tests/execution/state_sync_test.go
integration/tests/verification/system_chunk_test.go
ledger/common/hash/hash.go
ledger/common/proof/proof.go
ledger/complete/ledger_benchmark_test.go
ledger/complete/ledger_test.go
ledger/complete/mtrie/forest_test.go
ledger/complete/mtrie/node/node.go
ledger/complete/mtrie/node/node_test.go
ledger/complete/mtrie/trie/trie.go
ledger/complete/mtrie/trie/trie_test.go
ledger/complete/wal/checkpointer_test.go
ledger/complete/wal/encoding.go
ledger/partial/ledger.go
ledger/partial/ptrie/node.go
ledger/partial/ptrie/partialTrie.go
ledger/partial/ptrie/partialTrie_test.go
model/flow/execution_result.go
module/mempool/consensus/exec_fork_suppressor_test.go
module/validation/receipt_validator.go
storage/ledger.go

implemented will all suggestions from [my PR review](https://github.com/onflow/flow-go/pull/514#pullrequestreview-648664467)

suggestions for PR #514: [Ledger] switch hash slices to arrays 

---

storage/badger/collections.go
storage/badger/my_receipts.go
storage/badger/operation/common.go
storage/errors.go

Simplify the not found error. See comments.

Fix not found error

---

engine/verification/match/engine.go
engine/verification/match/engine_test.go

Add missing verification metrics

---

engine/common/fifoqueue/fifoqueue.go
engine/consensus/compliance/engine.go
engine/enqueue.go
engine/enqueue_test.go
engine/fifoqueue.go

* updated some goDoc
* removed `MessageStore.Filter` method
* removed FifoQueue's Put and Get methods

Suggestions for PR 646

---

cmd/util/ledger/migrations/storage_reporter.go
cmd/util/ledger/migrations/storage_v4.go
engine/execution/computation/computer/computer_test.go
fvm/accounts_test.go
fvm/context.go
fvm/crypto.go
fvm/env.go
fvm/fvm_test.go
fvm/transactionInvocator.go
fvm/transactionInvocator_test.go
go.mod
go.sum
integration/go.mod
integration/go.sum

ref: https://github.com/dapperlabs/flow-internal/issues/1515
ref: https://github.com/dapperlabs/flow-go/issues/5542
This is part 1. where `ValidatePublicKey` will be a stub (always return true).
Cadence reference should be replaced with a tag before merging.

Cadence version upgrade

---

storage/badger/dkg_keys.go

Update `storage.DKGKeys` (only on the epochs feature branch) to use new `transaction` package after merge to master.

Update DKGKeys storage module for new transaction 

---

engine/execution/ingestion/engine.go

Revert [the double execution fix](https://github.com/onflow/flow-go/pull/635/files) as we saw some issue on canary net

revert double execution fix

---

cmd/scaffold.go

https://github.com/onflow/flow-go/pull/599 was never merged to master.

Turn on storage limiting for mainnet

---

cmd/scaffold.go

https://github.com/onflow/flow-go/pull/750 but for v0.17

Turn on storage limiting for mainnet v0.17

---

module/builder/consensus/builder.go
module/mempool/execution_tree.go
storage/badger/receipts.go

* includes suggested revisions for `consensus.Builder`
* does _not_ include requested revision for `badger.Snapshot` (see [comment](https://github.com/onflow/flow-go/pull/660#discussion_r640355405))

implementing most revisions suggested in my comment for PR 660

---

go.mod
go.sum
integration/go.mod
integration/go.sum

Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.16.1..v0.16.1-patch.1

Update to Cadence v0.16.1-patch.1

---

engine/execution/rpc/engine.go

Porting changes from this [PR](https://github.com/onflow/flow-go/pull/773) back to master
Description [here](https://github.com/onflow/flow-go/pull/773#issue-659469992)

convert non UTF-8 cadence error to a UTF-8 error

---

fvm/crypto/crypto.go
fvm/fvm_test.go
fvm/transactionVerifier.go

closes: https://github.com/dapperlabs/flow-go/issues/5544

BLS signature verification

---

crypto/types.go
fvm/accounts_test.go
fvm/crypto/crypto.go
fvm/crypto/crypto_test.go
fvm/env.go

ref: https://github.com/dapperlabs/flow-go/issues/5541

Implement FVM ValidatePublicKey

---

go.mod
go.sum
integration/go.mod
integration/go.sum

References: https://github.com/onflow/cadence/pull/988

Auto Cadence Update: Remove italics from auto flow-go PR

---

go.mod
go.sum
integration/go.mod
integration/go.sum

References: https://github.com/onflow/cadence/pull/987

Auto Cadence Update: _Improve sync flow_go action_

---

go.mod
go.sum
integration/go.mod
integration/go.sum

References: https://github.com/onflow/cadence/pull/991

Auto Cadence Update: Disable the wasmtime VM for now

---

go.mod
go.sum
integration/go.mod
integration/go.sum

References: https://github.com/onflow/cadence/pull/962

Auto Cadence Update: Update for changes in Flowkit API

---

go.mod
integration/go.mod

Update the crypto package version used in `flow-go` to the newly tagged version.

Update the crypto lib version

---

go.mod
go.sum
integration/go.mod
integration/go.sum

References: https://github.com/onflow/cadence/pull/995

Auto Cadence Update: Make `PublicKey` type importable

---

go.mod
go.sum
integration/go.mod
integration/go.sum

References: https://github.com/onflow/cadence/pull/1001

Auto Cadence Update: Remove the result declaration kind

---

engine/execution/state/bootstrap/bootstrap_test.go
go.mod
go.sum
integration/go.sum
utils/unittest/execution_state.go

flow-core-contracts version bump.
The main reason being that the current reference was not referencing a tag.

Upgrade `flow-core-contracts` version

---

go.mod
go.sum
integration/go.mod
integration/go.sum

References: https://github.com/onflow/cadence/pull/1003

Auto Cadence Update: Add documentation for the Cadence documentation generator

---

Makefile
cmd/Dockerfile
go.mod
go.sum
integration/go.mod
integration/go.sum

Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.18.0..v0.18.0-patch.1

Update to Cadence v0.18.0-patch.1

---

engine/verification/fetcher/engine.go
engine/verification/fetcher/engine_test.go

Refactors notifier id based on chunk locator in the fetcher engine.

[Verification] Fixes notifier id at fetcher engine

---

engine/verification/assigner/engine.go
engine/verification/fetcher/engine.go
model/verification/chunkStatus.go

This PR adds block height to the logs on the processing pipeline of chunks in the verification node.

[Verification] Logging block height on chunk processing pipeline

---

cmd/execution/main.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/testutil/nodes.go

https://github.com/onflow/flow-go/pull/857

[Execution] Cherry-pick "add pause execution flag" to 0.17

---

cmd/execution/main.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/testutil/nodes.go
fvm/fvm_test.go
utils/unittest/generator/events.go

https://github.com/onflow/flow-go/pull/857

[Execution] cherrypick "add pause execution flag" to v0.18

---

engine/consensus/approvals/assignment_collector.go
engine/consensus/sealing/core.go
module/chunks/chunk_assigner.go

Specifically, sealing config we're intending to run on mainnet 10

Update sealing config

---

access/errors.go
access/validator.go
fvm/transactionVerifier.go
fvm/transactionVerifier_test.go
model/flow/transaction.go

Reject duplicated signatures

---

fvm/fvm_test.go
go.mod
go.sum
utils/unittest/generator/events.go

This commit has support for Cadence v0.18.0-patch.3

update to Flow Go SDK 533a95abf0714f43d547a10b7afdf1f452f44780

---

fvm/env.go

addresses #5632 for now till we get a chance to separate the environments for tx and scripts.

[FVM] Enable getAccountKeys for scripts

---

.github/workflows/ci.yml
crypto/build_dependency.sh

[crypto, chore, easy] Lint our scripts

---

cmd/bootstrap/cmd/finalize.go
cmd/util/cmd/epoch-recovery/cmd/reset.go
fvm/bootstrap.go
go.sum
integration/dkg/dkg_emulator_suite.go
integration/epochs/cluster_epoch_test.go
integration/testnet/network.go
integration/tests/verification/suite.go
module/dkg/client.go
module/dkg/client_test.go
module/epochs/epoch_config.go
module/epochs/qc_client.go

This PR incorporates changes required after the latest merge from `master` beyond merge conflicts. In particular:
* Update usages of `cadence.NewString` to handle new error return
* Update new VN integration test with a long epoch to avoid encountering epoch transition during the test

Additional Changes from merge `master->feature/epochs`

---

network/p2p/libp2pNode_test.go
network/p2p/pubsub_test.go
network/queue/queueWorker_test.go
network/test/echoengine.go
network/test/echoengine_test.go

Removes a potential few data races in network tests

[network, test-only] Network testing races

---

cmd/bootstrap/cmd/keys.go

Export func to generate machine account file

export machine account file func

---

cmd/access/main.go
cmd/scaffold.go
engine/access/rate_limit_test.go
engine/access/rpc/engine.go
engine/access/secure_grpcr_test.go
go.mod
network/p2p/keyTranslator.go
network/p2p/keyTranslator_test.go
network/p2p/libp2pNode.go
network/p2p/libp2pNode_test.go
network/p2p/libp2pUtils.go
network/p2p/libp2pUtils_test.go
utils/grpc/grpc.go
utils/grpc/grpc_test.go

git cherry-pick [4ec3bd0379712abc580971cb031fff76ce0768cb](https://github.com/onflow/flow-go/commit/4ec3bd0379712abc580971cb031fff76ce0768cb)
git cherry-pick [e090bf5971590d8dcc674c9f153c236f9eb86ba5](https://github.com/onflow/flow-go/commit/e090bf5971590d8dcc674c9f153c236f9eb86ba5)

cherr-picking secure gRPC commits from master to v0.19

---

consensus/hotstuff/block_producer.go
consensus/hotstuff/event_handler.go
consensus/hotstuff/vote_aggregator.go
consensus/hotstuff/vote_collector.go
consensus/hotstuff/vote_collector_factory.go
consensus/hotstuff/voter.go
model/flow/header.go
model/flow/quorum_certificate.go

The `feature/consensus-voting` branch is the latest master.
This PR adds the discussed interfaces for consensus voting.
Since it changes the interface, a lot of modules is broken. Fixes and tests will be introduced in other PRs.
We will turn on CI as soon as all modules and tests have been fixed (or commented).

[Consensus] add interfaces for consensus voting

---

consensus/hotstuff/verification/bls_wrapper.go
consensus/hotstuff/verification/bls_wrapper_non_relic.go
consensus/hotstuff/verification/common.go
engine/execution/utils/hasher.go
module/mocks/network.go
module/signature/threshold_non_relic.go
storage/mocks/storage.go

port https://github.com/onflow/flow-go/pull/1074 to v0.20

Non relic build fix v0.20

---

engine/execution/computation/computer/computer.go

Return the system chunk transaction execution error so that it can be logged.

Return transaction error to be checked for system chunk transaction

---

model/flow/identifierList.go
network/p2p/network.go

Cleanup some filtering code in identifier and network. Will use this later for IdentityProvider.

[flow] Cleanup identifier filter code

---

cmd/execution/main.go
engine/execution/computation/computer/uploader/uploader_test.go

Turns out we cannot use single variable.
Fix propagating the module

Fix uploader module

---

integration/go.mod
network/test/testUtil.go

Creates a "fixed table" identity translator for testing

[network] Identity provider fixes

---

cmd/access/node_builder/upstream_connector.go
network/test/testUtil.go

Fixes compilation of testUtils & others

[network] Fix the compilation of a bunch of remaining tests

---

fvm/state/state.go
fvm/transactionStorageLimiter.go

original: https://github.com/onflow/flow-go/pull/1156

Fix checking storage over randomly ordered list - backport

---

consensus/hotstuff/committees/consensus_committee.go
model/flow/epoch.go
module/epochs/epoch_lookup.go
state/protocol/badger/mutator.go
state/protocol/inmem/epoch.go

suggestions for PR https://github.com/onflow/flow-go/pull/1250
* tried to consolidate the EECC logic a bit 
* added, updated, polished goDoc

EECC suggestions

---

cmd/util/cmd/execution-state-extract/cmd.go
network/mocknetwork/overlay.go

The previous condition helped pass the tests, but did not properly account for the

Hotfix state extract

---

engine/common/synchronization/engine_test.go
engine/common/synchronization/request_handler.go

[testnet, UAN, consensus follower] Backport of Server-side clamping

---

consensus/hotstuff/vote_collectors.go
consensus/hotstuff/voteaggregator/vote_aggregator_v2.go
consensus/hotstuff/voteaggregator/vote_collectors.go
consensus/hotstuff/voteaggregator/vote_collectors_test.go
consensus/hotstuff/votecollector/statemachine.go

https://github.com/dapperlabs/flow-go/issues/5787
`VoteCollectors` main purpose is to index collectors by view, create and provide access to them in concurrent safe way.
This PR implements core logic for `VoteCollectors` as well as unit tests. 
Same related refactoring and changes were done to `VoteAggregator` in scope of this PR.

[Consensus Voting] Vote collectors implementation

---

engine/consensus/matching/core.go

Apply [the fix](https://github.com/onflow/flow-go/pull/1294) to v0.21

Fix matching engine

---

engine/consensus/approvals/veryfing_assignment_collector.go

Backport https://github.com/onflow/flow-go/pull/1301

lower emergency sealing threshold

---

go.mod
go.sum
integration/go.mod
integration/go.sum

References: https://github.com/onflow/cadence/pull/1134

Auto Cadence Update: Add PublicAccount conversion during InvokeContractFunction

---

engine/consensus/approvals/veryfing_assignment_collector.go

Lower the sealing threshold to around 5 mins

[Consensus] lower emergency sealing threshold

---

consensus/hotstuff/signature.go
consensus/hotstuff/votecollector/combined_vote_processor.go
consensus/hotstuff/votecollector/combined_vote_processor_test.go
consensus/hotstuff/votecollector/staking_vote_processor.go

For https://github.com/dapperlabs/flow-go/issues/5785
This PR implemented building QC with the aggregators and the packer.
Test cases are listed for now and will be implemented when we add the missing dependencies to CombinedVoteProcessorFactory

[Consensus Voting] Add QC Builder

---

consensus/hotstuff/consumer.go
consensus/hotstuff/mocks/consumer.go
consensus/hotstuff/mocks/vote_collector.go
consensus/hotstuff/mocks/vote_collectors.go
consensus/hotstuff/notifications/log_consumer.go
consensus/hotstuff/notifications/noop_consumer.go
consensus/hotstuff/notifications/pubsub/distributor.go
consensus/hotstuff/notifications/pubsub/finalization_distributor.go
consensus/hotstuff/notifications/slashing_violation_consumer.go
consensus/hotstuff/vote_collector.go
consensus/hotstuff/voteaggregator/vote_aggregator_v2.go
consensus/hotstuff/votecollector/statemachine.go
consensus/hotstuff/votecollector/statemachine_test.go
consensus/hotstuff/votecollector/vote_cache.go
network/mocknetwork/overlay.go

https://github.com/dapperlabs/flow-go/issues/5848
This PR implements several features:
- Extends `hotstuff.Notifier` with new callback which can be used to report votes for invalid proposal
- Updated implementors of notifier interface
- Added handling of invalid votes into `VoteAggregatorV2`.

[Consensus voting] Handling of invalid votes

---

consensus/hotstuff/signature.go
consensus/hotstuff/signature/weighted_signature_aggregator.go
consensus/hotstuff/votecollector/combined_vote_processor.go

This PR includes attempt to fix linter error and some optional suggestions. 
Linter error seems like a false positive which is hard to explain, the best solution seems just to ignore it. It definitely has to do something with `signature.SignatureAggregatorSameMessage` since removing it resolves linting errors. 
WARNING: this is not production ready so please review it, especially documentation wise.

[Consensus Voting] Attempt to fix linter error + suggestions 

---

engine/consensus/approvals/tracker/record.go
engine/consensus/approvals/tracker/tracker.go

Porting https://github.com/onflow/flow-go/pull/1324 to v0.21

[Consensus] v0.21 log verifier

---

engine/consensus/dkg/reactor_engine_test.go
go.mod
integration/go.mod
module/dkg.go
module/dkg_broker.go

https://github.com/onflow/flow-go/pull/1333

M4ksio/backport 1333 to 0.22

---

cmd/bootstrap/cmd/constraints.go
cmd/bootstrap/cmd/dkg.go
cmd/bootstrap/cmd/final_list.go
cmd/bootstrap/cmd/finalize.go
cmd/bootstrap/cmd/finalize_test.go
cmd/bootstrap/cmd/qc.go
cmd/bootstrap/cmd/rootblock.go
cmd/bootstrap/cmd/rootblock_test.go
cmd/bootstrap/cmd/seal.go
cmd/bootstrap/run/qc.go
cmd/bootstrap/run/qc_test.go
cmd/bootstrap/utils/file.go
cmd/flags.go
integration/testnet/network.go
model/bootstrap/filenames.go
state/protocol/inmem/encodable.go

1 additional change compared to #1371 : 
* adding `MarkFlagRequired` from `master`

Porting  #1371 to `v0.21_consensus_test`

---

cmd/util/ledger/migrations/accounts.go
cmd/util/ledger/migrations/storage_v5.go
fvm/bootstrap.go
fvm/handler/accountKey.go
fvm/handler/accountKey_test.go
fvm/handler/contract.go
fvm/scriptEnv.go
fvm/state/accounts.go
fvm/transactionEnv.go
fvm/transactionVerifier.go

Backports 
https://github.com/onflow/flow-go/pull/1376/ and https://github.com/onflow/flow-go/pull/1338/

[0.21] Backport 1376

---

.github/workflows/ci.yml
Makefile
crypto/Makefile

- moves ADX detection to crypto Makefile
- de-quarantine BLST tests

[crypto] Test infra maintenance

---

engine/collection/pusher/engine.go
engine/collection/pusher/engine_test.go
engine/consensus/ingestion/engine.go
engine/consensus/ingestion/engine_test.go

backports https://github.com/onflow/flow-go/pull/1406 to v0.21

[v0.21] Fixes guarantee dissemination

---

module/synchronization/core.go

ports https://github.com/onflow/flow-go/pull/1387

port sync engine fix

---

module/synchronization/core.go
module/synchronization/core_rapid_test.go
module/synchronization/status.go

[v0.21] sync engine Bugfix backport

---

consensus/hotstuff/randombeacon_follower.go
consensus/hotstuff/signature/randombeacon_follower.go
consensus/hotstuff/signature/randombeacon_follower_test.go
crypto/bls_thresholdsign.go
crypto/dkg_jointfeldman.go
crypto/thresholdsign.go

* largely goDoc revisions and polishing 
* Personally, I find go already very verbose. The less code I get on one screen, the more I have to scroll, which complicates code reviews _slightly_. Therefore, I prefer to remove unnecessary white spaces (just a few)
* I noticed that in some cases, error messages were very brief, and there were additional code comments for clarification. In these cases, I would prefer to make the error messages more self-explanatory. Thereby, it helps when debugging and removes the need for additional comments (which also extend the code length). 
Feel free to select the changes you like.

Suggestions for PR #1404

---

consensus/recovery/recover.go

backport https://github.com/onflow/flow-go/pull/1564

continue recover block when hitting invalid block

---

network/p2p/network.go

cherry-picking from https://github.com/onflow/flow-go/pull/1529/commits/5ebd9e9eb8ceda37978815566542ad9a350d3332

refactors network cache size

---

consensus/recovery/recover.go
ledger/complete/ledger.go
ledger/complete/mtrie/README.md
ledger/complete/mtrie/flattener/forest.go
ledger/complete/mtrie/flattener/iterator_test.go
ledger/complete/mtrie/flattener/trie_test.go
ledger/complete/mtrie/forest.go
ledger/complete/mtrie/forest_test.go
ledger/complete/mtrie/node/node.go
ledger/complete/mtrie/node/node_test.go
ledger/complete/mtrie/trie/trie.go
ledger/complete/mtrie/trie/trie_test.go

1. Cherry pick PR https://github.com/onflow/flow-go/pull/1578
> git cherry-pick d451dba9720ed3cf2d7cfa512e6aeffc2cca4836
> git cherry-pick ba837303d59165b457c4d0ab83defa9c7730fd4e
> git cherry-pick 8b9416b3107d8509dde8338e36b2de6386c5f9fb
> git cherry-pick 24e27682b6d967e552f857f0fbbddfc7b8f9d2b8
2. Cherrypick Leo's commit from master - https://github.com/onflow/flow-go/pull/1565
> git cherry-pick 74ef899f4648301503d1ae52a21ad0bd2465f845

cherry picking commits for today's denvet31 spork

---

consensus/hotstuff/signature/packer_test.go

This PR implements extra tests for `Packer` to make sure that current packer implementation satisfies requirements of consensus voting v2 and v3, provides expected serialization and can be safely used in vote processor and verifier.

[Consensus Voting] `Packer` extra v2 tests

---

fvm/fvm.go
fvm/transaction.go

Recover Ledger interaction limit panics

Recover ledger interaction error

---

fvm/crypto/crypto.go

While looking at script issues with the FCL team, I noticed the crypto error messages were messy. This PR cleans up the errors by using the error constructor properly.

[FVM] fix error messages

---

engine/access/rest/handler.go
engine/access/rest/middleware/common_query_params.go
engine/access/rest/middleware/common_query_params_test.go
engine/access/rest/request_decorator.go
engine/access/rest/select_filter.go
engine/access/rest/select_filter_test.go
engine/access/rest_api_test.go

Have not yet plugged it in the server.

adding a select filter to filter out elements from the json response

---

engine/access/rest/blocks.go
engine/access/rest/converter.go
engine/access/rest/middleware/common_query_params.go

https://github.com/dapperlabs/flow-go/issues/6035

adding base64 conversions to script arg, script text & signatures

---

cmd/consensus/main.go
consensus/aggregator.go
consensus/config.go
consensus/participant.go
engine/collection/epochmgr/factories/hotstuff.go

see my comment here for more details on the suggested change

Restructured dependency encapsulation for HotStuff Participant

---

.dockerignore
integration/localnet/.dockerignore
integration/localnet/Makefile

https://github.com/dapperlabs/flow-go/issues/6045

Fix localnet docker build caching

---

engine/access/rest/accounts.go
engine/access/rest/collections.go
engine/access/rest/converter.go
engine/access/rest/execution_result.go
engine/access/rest/execution_result_test.go
engine/access/rest/handler.go
engine/access/rest/scripts.go
engine/access/rest/transactions.go

Added execution tests and more comments

REST execution tests

---

engine/execution/computation/computer/computer.go
fvm/errors/execution.go
fvm/fvm_test.go
fvm/state/accounts.go
fvm/state/state.go
fvm/state/state_holder.go
fvm/state/state_test.go
fvm/transaction.go
fvm/transactionInvoker.go

[V0.23]  patch1 - Relaxing the ledger limit

---

model/flow/identity.go

I think this allocation is not necessary: https://github.com/onflow/flow-go/blob/b10a0bb63f9acca82eab7d1a7871778e0fb3fbd3/model/flow/identity.go#L531
Added a suggestion in this PR how to optimize this code further and remove the allocation.

Suggestion for PR 1513: removed memory allocation for IdentityList.Union

---

integration/utils/batchLoadGenerator.go
integration/utils/contLoadGenerator.go
integration/utils/scripts.go

The bug was that the amount was not replaced correctly. I switched replacements to arguments.

Fix bug in transfer tokens transaction in integration load tests

---

model/flow/identifier.go
storage/merkle/node.go
storage/merkle/tree.go

Revert "Suggested refactorings for Merkle Patricia Tree"

---

engine/execution/computation/computer/computer.go
fvm/transactionInvoker.go

Backport to master:
- https://github.com/onflow/flow-go/pull/1836
- https://github.com/onflow/flow-go/pull/1837

Backport: Ledger interaction error

---

ledger/complete/wal/checkpointer.go
ledger/complete/wal/compactor.go
ledger/complete/wal/wal.go

Cherry-picked from PR https://github.com/onflow/flow-go/pull/1894 to apply to v0.23 so we can see more logs for checkpoint creation.

Update v0.23 to add more checkpoint logging

---

engine/execution/computation/manager.go

git cherry-pick 44c45fc794f90c454db7f1c5754091a47f8e2e02
git cherry-pick 11397c6f43f9ff67a27057fe1f32fa0b58093ffd
git cherry-pick 465e0c6dc3f605ede5ef65dd94e749c6a0249798

v0.24 plus the commits from PR 1952

---

go.mod
go.sum
integration/go.mod
integration/go.sum

https://github.com/dapperlabs/cadence-internal/pull/58
Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.21.1-patch.1...v0.21.1-patch.2

Update to Cadence v0.21.1-patch.2

---

cmd/bootstrap/cmd/clusters.go
cmd/bootstrap/run/cluster_qc.go
cmd/bootstrap/run/cluster_qc_test.go
engine/collection/test/cluster_switchover_test.go
integration/testnet/network.go

backport https://github.com/onflow/flow-go/pull/1976

fix cluster qc generation

---

cmd/util/ledger/reporters/account_reporter.go

Fix https://github.com/dapperlabs/flow-go/issues/6140
Was running into a crash.

Fix account reporter

---

README.md
engine/common/synchronization/engine.go
module/synchronization/core.go

https://github.com/onflow/flow-go/pull/1947

Port of #1947

---

engine/execution/computation/manager.go

This PR fix the sealing halt issue on devnet33

Devnet33 sealing fix

---

fvm/transactionContractFunctionInvocator.go

Reduced the severity of the log, as it is sometimes expected that this might happen.
Also added some extra information to the log.

Fix TransactionContractFunctionInvoker error log

---

cmd/access/main.go
cmd/access/node_builder/access_node_builder.go
cmd/access/node_builder/unstaked_access_node_builder.go

Port of https://github.com/onflow/flow-go/pull/2037

[Observer] Support running observer standalone using standard AN image

---

module/metrics.go
module/metrics/network.go
module/metrics/noop.go
module/mock/network_metrics.go
network/p2p/middleware.go

cherry pick https://github.com/onflow/flow-go/pull/2077

V0.24 unicast metric

---

admin/commands/helper.go
admin/commands/state_synchronization/read_execution_data.go
admin/commands/storage/helper.go
admin/commands/storage/read_blocks.go
admin/commands/storage/read_results.go
admin/commands/storage/read_seals.go
admin/commands/storage/read_seals_test.go
cmd/execution/main.go
cmd/scaffold.go
engine/execution/computation/manager.go

This [PR](https://github.com/onflow/flow-go/pull/1998) but against v0.24
git checkout v0.24
git pull origin v0.24
git cherry-pick cbfb6ea22ba5bd50c56ad5dd4c85140cc79cb79d

implement read execution data admin command

---

go.mod
go.sum
integration/go.mod
integration/go.sum

Update the flow-go/crypto dependency to use the new tag.

Update flow-go/crypto dependency

---

Makefile

Partially implements https://github.com/onflow/flow-go/issues/2066

Add observer as a separate docker image

---

cmd/consensus/main.go
consensus/hotstuff/notifications/pubsub/finalization_distributor.go
consensus/hotstuff/voteaggregator/vote_aggregator.go
consensus/hotstuff/voteaggregator/vote_aggregator_test.go
consensus/vote_aggregator.go
engine/collection/compliance/core.go
engine/collection/compliance/core_test.go
engine/collection/compliance/engine.go
engine/collection/compliance/engine_test.go
engine/collection/epochmgr/factories/hotstuff.go
engine/common/follower/engine.go
engine/common/follower/engine_test.go
engine/common/synchronization/finalized_snapshot.go
engine/consensus/compliance/core.go
engine/consensus/compliance/core_test.go
engine/consensus/compliance/engine.go
engine/consensus/compliance/engine_test.go
engine/consensus/matching/engine.go
engine/consensus/matching/engine_test.go
engine/consensus/sealing/engine.go
engine/consensus/sealing/engine_test.go
follower/consensus_follower.go
module/buffer.go
module/buffer/backend.go
module/buffer/backend_test.go
module/buffer/pending_blocks.go
module/buffer/pending_cluster_blocks.go
module/mock/pending_block_buffer.go
module/mock/pending_cluster_block_buffer.go

This PR implements requested changes for pruning `VoteAggregator` and handling of finalization events for compliance engine.

[Consensus] `VoteAggregator` pruning revision

---

access/api.go
access/handler.go
access/mock/api.go
engine/access/access_test.go
engine/access/mock/access_api_client.go
engine/access/mock/access_api_server.go
engine/access/mock/execution_api_client.go
engine/access/mock/execution_api_server.go
engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions.go
engine/common/rpc/convert/convert.go
engine/execution/rpc/engine.go
engine/execution/rpc/engine_test.go
engine/execution/state/state.go
go.mod
go.sum
integration/go.mod
integration/go.sum
module/metrics/labels.go
storage/badger/events.go
storage/badger/events_test.go
storage/badger/operation/prefix.go
storage/badger/operation/transaction_results.go
storage/badger/transaction_results.go
storage/badger/transaction_results_test.go
storage/events.go
storage/mock/events.go
storage/mock/transaction_results.go
storage/mocks/storage.go
storage/transaction_results.go

cheery picked commits from: https://github.com/onflow/flow-go/pull/2166/files

Create GetTransactionResultByIndex AN/EN API

---

engine/execution/computation/manager.go

closes https://github.com/dapperlabs/flow-go/issues/6210

Log execution data ID

---

Makefile

Adds docker labels with git pointers

Docker labels

---

cmd/access/node_builder/access_node_builder.go
cmd/collection/main.go
cmd/consensus/main.go
cmd/execution/main.go
cmd/node_builder.go
cmd/scaffold.go
cmd/verification/main.go
engine/common/synchronization/config.go
engine/common/synchronization/request_handler.go
follower/consensus_follower.go
module/synchronization/core.go

Update request size limit for sync engine

---

network/p2p/middleware.go

Backporting https://github.com/onflow/flow-go/pull/2267

[Networking] Fixes unicast timeout value for chunk data packs

---

cmd/util/ledger/reporters/account_reporter.go
fvm/errors/accounts.go
fvm/errors/codes.go
fvm/state/accounts.go
go.mod
go.sum
integration/go.mod
integration/go.sum

Now that the Mainnet spork is complete, merge the changes from `v0.25` back to `master`.

Merge v0.25 to master

---

engine/access/rpc/backend/backend.go
engine/access/rpc/backend/backend_scripts.go

corresponding deploy PR for: https://github.com/onflow/flow-go/pull/2282/

Add mutex around script tracking map

---

engine/access/ingestion/engine.go

Fix https://github.com/onflow/flow-go/pull/2287 to master

Use block ID from seal

---

engine/execution/computation/computer/computer.go

Add memory allocation metering and logging for transactions, if debug logging is enabled.

Secure Cadence - add memory alloc metering

---

fvm/transactionInvoker.go

Skip transaction  https://testnet.flowscan.org/transaction/51be45d5d298403e7798e5c8048102529acae4b05e16f795220f2ac1034ccf64

[devnet34] Skip a specific transaction because of OOO

---

insecure/wintermute/attackOrchestrator_test.go
ledger/complete/wal/fadvise.go
ledger/complete/wal/fadvise_linux.go

Fix linting error

---

.github/workflows/cd.yml

Exclude daily tags that will be created on a schedule. We do not want these to kickoff new container builds using this workflow.

Update cd.yml to ignore daily tags created through automation

---

engine/collection/compliance/engine.go
engine/consensus/compliance/core.go
engine/consensus/compliance/engine.go

No logic change, only adding logs

improve signer indices logging

---

fvm/transactionVerifier.go

@tarakby This is just the fix to let us continue testing the secure-cadence branch.

[FVM] Signing errors swapped fix

---

go.mod
go.sum
integration/go.mod
integration/go.sum
utils/unittest/generator/events.go

upgrade to secure-cadence-m7 tag of cadence

Secure Cadence upgrade to m7

---

consensus/hotstuff/committee.go
consensus/hotstuff/signature/packer.go
model/flow/quorum_certificate.go
module/signature/checksum.go
module/signature/checksum_test.go
module/signature/errors.go
module/signature/signer_indices.go

fixed typos and minor extension of error handling

Suggestion for PR #2414

---

engine/execution/computation/manager_test.go
fvm/fvm_test.go

Closes https://github.com/onflow/flow-go/issues/2464
See linked issue for context as to why these tests are necessary.

Add tests to ensure mutations in scripts are discarded

---

go.mod
go.sum
integration/go.mod
integration/go.sum

Diff: https://github.com/dapperlabs/cadence-internal/compare/v0.23.3-patch.2...v0.23.3-patch.3

Update to Cadence v0.23.3-patch.3

---

go.mod
go.sum
integration/go.mod
integration/go.sum

This is just a re-tag, no code changes

Update to Cadence v0.23.3-patch.4

---

go.mod
go.sum
integration/go.mod
integration/go.sum

Upgrade flow-go to use secure cadence milestone 9 release candidate

upgrade cadence to secure-cadence-m9

---

engine/access/rpc/backend/backend_transactions.go

Port https://github.com/onflow/flow-go/pull/2329

system chunk tx port

---

cmd/execution_builder.go
integration/localnet/Makefile
integration/localnet/bootstrap.go

While here, also fix the profiler flags.

feat(localnet): pass through tracing, extensive tracing, and cadence tracing flags

---

access/validator.go
cmd/collection/main.go
engine/collection/ingest/config.go
engine/collection/ingest/engine.go
engine/collection/ingest/engine_test.go
model/flow/constants.go

https://github.com/onflow/flow-go/pull/2552 against `v0.26`

[v0.26] Remove max account index

---

access/validator.go
cmd/collection/main.go
engine/collection/ingest/config.go
engine/collection/ingest/engine.go
engine/collection/ingest/engine_test.go
model/flow/constants.go

Remove maximum account index from transaction validation. [Additional context in TPM discussion](https://www.notion.so/dapperlabs/Technical-Product-Meeting-with-Dete-054824f0be334392806e1e39641afe48#5d04b106e12e436f8c9d27a98b5919b6)

Remove max account index

---

consensus/hotstuff/safetyrules/safety_rules_test.go

Following comments in https://github.com/onflow/flow-go/pull/2444, I have extended test cases for `ProduceVote` and `ProduceTimeout` to cover every possible edge case.

[Consensus] `SafetyRules` extra test cases 

---

cmd/util/cmd/checkpoint-list-tries/cmd.go

fix encoding in checkpoint-list-trie cmd

---

model/convert/fixtures/fixture.go
model/convert/service_event_test.go
module/chunks/chunkVerifier_test.go

This PR resolves a potential cycle import issue. Explained in comments.

Moving convert fixtures to a namespace for test cases

---

admin/commands/storage/read_seals.go
cmd/util/cmd/read-badger/cmd/seals.go
engine/consensus/sealing/core.go
engine/consensus/sealing/core_test.go
engine/execution/checker/engine.go
model/flow/sealing_segment.go
module/builder/consensus/builder.go
module/builder/consensus/builder_test.go
module/validation/receipt_validator.go
module/validation/seal_validator.go
state/protocol/badger/mutator.go
state/protocol/badger/mutator_test.go
state/protocol/badger/params.go
state/protocol/badger/snapshot.go
state/protocol/badger/state.go
state/protocol/util/testing.go
storage/badger/operation/prefix.go
storage/badger/operation/seals.go
storage/badger/seals.go
storage/badger/seals_test.go
storage/mock/seals.go
storage/seals.go
utils/unittest/chain_suite.go
utils/unittest/epoch_builder.go

This pulls in https://github.com/onflow/flow-go/pull/2551 from master

[Protocol State] Index seal by sealed block id (backport v0.26)

---

go.mod
go.sum
integration/go.mod
integration/go.sum

Downgrading to further investigate the panic issue in https://github.com/dapperlabs/flow-go/issues/6279

Downgrades libp2p pubsub version

---

integration/utils/contLoadGenerator.go

This removes extra formatting calls to Msgf and reduces amount of copy-paste in the code.

chore(loader): cleanup logging

---

engine/execution/computation/manager.go

Script encoding may fail with an implementation error (panic). 
Gracefully handle the panic and treat script execution as failed.

Gracefully handle script result encoding panics 

---

cmd/bootstrap/transit/cmd/generate_root_block_vote.go

Adding log for debugging purpose

log node id and block id when signing root block

---

engine/execution/computation/manager.go

Move script execution log to debug

---

engine/common/synchronization/request_handler.go

These changes have already been merged into master: https://github.com/onflow/flow-go/pull/2671
Adding them to v0.26

V0.26 add warning logs

---

engine/execution/computation/computer/computer.go
engine/execution/computation/manager.go

backport https://github.com/onflow/flow-go/pull/2710/files

En logging backport

---

consensus/hotstuff/forks.go
consensus/hotstuff/forks/finalizer/finalizer.go
consensus/hotstuff/timeoutcollector/timeout_processor.go
consensus/hotstuff/validator/validator.go
module/forest/vertex.go

follow-up suggestion on top of PR https://github.com/onflow/flow-go/pull/2685
* mostly extended goDoc
* added nil-pointer check for validating TCs

follow-up suggestion on top of PR #2685

---

ledger/complete/wal/wal.go

I suspect this is related to the recently execution slowdown.

remove disk size metrics

---

engine/execution/computation/manager.go

global random uses a global `lockedSource` that has implicit global synchronization.  Hence, introduce explicit locking and hide it behind the `e.log.Debug().Enabled()`.

[Exec] Remove global lock from script execution

---

.github/workflows/bench.yml
fvm/fvm_bench_test.go

1. Increased the number of bench runs to 10 (from 7) since other CI take longer so we have extra time to get some more accuracy on the benchmarks.
2. Disabled running regular tests during the benchmarks
3. There was a bug in one of the benchmarks causing it to error out
4. Added memstats to the benchmarking output

[FVM] Benchstat CI improvements

---

model/flow/factory/cluster_list.go
state/protocol/badger/mutator.go
state/protocol/badger/validity.go
state/protocol/errors.go

* minor consolidation of logic
* some extensions of goDoc

suggested amendment for PR #2625

---

integration/loader/main.go
integration/utils/accounts.go
integration/utils/contLoadGenerator.go
integration/utils/follower.go
integration/utils/follower_test.go

chore(loader): switch from Client to Access API

---

engine/access/rpc/backend/connection_factory.go

* trigger eviction logic for overwriting an entry
* comment with reasoning
Co-authored-by: Vishal <1117327+vishalchangrani@users.noreply.github.com>

[AN] - Trigger Cache Eviction on Overwrite (#2760)

---

README.md

- Update note about setting up the crypto module locally for every new version.
- Replace outdated note.

Update crypto note in README

---

CODEOWNERS

Adding myself to the performance stream as suggested by @SaveTheRbtz

Add Andrew Meyer to performance stream

---

fvm/contractFunctionInvocations.go
fvm/scriptEnv.go
fvm/transactionEnv.go
fvm/transactionInvoker.go

the closures cost cpu/memory and doesn't provide any benefit

Invoke contracts directly instead of via currying

---

consensus/hotstuff/eventhandler/event_handler.go
consensus/hotstuff/model/errors.go
consensus/hotstuff/timeout_collectors.go
consensus/hotstuff/timeoutaggregator/timeout_aggregator.go
consensus/hotstuff/timeoutaggregator/timeout_collectors.go
consensus/hotstuff/timeoutaggregator/timeout_collectors_test.go
consensus/hotstuff/vote_aggregator.go
consensus/hotstuff/vote_collectors.go
consensus/hotstuff/voteaggregator/vote_aggregator.go
consensus/hotstuff/voteaggregator/vote_collectors.go
consensus/hotstuff/voteaggregator/vote_collectors_test.go
engine/consensus/approvals/request_tracker.go
engine/consensus/approvals/request_tracker_test.go
engine/consensus/approvals/verifying_assignment_collector.go
engine/consensus/sealing/core.go
module/mempool/errors.go
module/mempool/incorporated_result_seals.go
module/mempool/pending_receipts.go
module/mempool/stdmap/incorporated_result_seals.go
module/mempool/stdmap/pending_receipts.go

https://github.com/dapperlabs/flow-go/issues/6318

[Consensus] Replace `DecreasingPruningHeightError` with `BelowPrunedThresholdError`

---

integration/utils/scripts.go
integration/utils/scripts/addKeyToAccountTransaction.cdc
integration/utils/scripts/compHeavyTransaction.cdc
integration/utils/scripts/createAccountsTransaction.cdc
integration/utils/scripts/deployingMyFavContractTransaction.cdc
integration/utils/scripts/eventHeavyTransaction.cdc
integration/utils/scripts/ledgerHeavyTransaction.cdc
integration/utils/scripts/myFavContract.cdc
integration/utils/scripts/tokenTransferTransaction.cdc

Moving out all inlined Cadence source from .go file into separate files.

[Integration] Splitting Cadence files from go source

---

cmd/bootstrap/cmd/block.go
cmd/bootstrap/cmd/keygen.go
cmd/bootstrap/cmd/machine_account.go
cmd/scaffold.go
engine/common/rpc/convert/convert.go
flips/component-interface.md
fvm/systemcontracts/system_contracts.go
fvm/systemcontracts/system_contracts_test.go
k8s/local/flow-collection-node-deployment.yml
k8s/local/flow-consensus-node-deployment.yml
k8s/local/flow-execution-node-deployment.yml
k8s/local/flow-verification-node-deployment.yml
k8s/staging/flow-collection-node-deployment.yml
k8s/staging/flow-consensus-node-deployment.yml
k8s/staging/flow-execution-node-deployment.yml
k8s/staging/flow-verification-node-deployment.yml
model/flow/address.go
model/flow/address_test.go
model/flow/chain.go
module/component/component.go

We are considering re-branding canary net. This updates all instances of Canary to Stagingnet

Add staging net

---

model/flow/identifier.go

In future I'll likely rewrite that in terms of percents or percentage points so it is more intuitive.

chore(comment): fix IsSampled description

---

cmd/util/ledger/reporters/account_reporter.go
engine/execution/computation/manager_test.go
fvm/account.go
fvm/accounts_test.go
fvm/script.go
fvm/scriptEnv.go

In particular, don't silently ignore errors.  I'll dedup in a followup PR.

Backport setExecutionParameters from TransactionEnv to ScriptEnv

---

cmd/util/cmd/read-execution-state/list-accounts/cmd.go
cmd/util/ledger/reporters/account_reporter.go
cmd/util/ledger/reporters/fungible_token_tracker.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/manager_test.go
fvm/bootstrap.go
fvm/executionParameters.go
fvm/executionParameters_test.go
fvm/fvm.go
fvm/fvm_test.go
fvm/handler/contract_test.go
fvm/handler/programs_test.go
fvm/meter/weighted_meter.go
fvm/meter/weighted_meter_test.go
fvm/programs/programs_test.go
fvm/scriptEnv.go
fvm/state/accounts_test.go
fvm/state/address_generator_test.go
fvm/state/state_test.go
fvm/state/uuids_test.go
fvm/transactionEnv.go
fvm/transactionInvoker_test.go
fvm/transactionSequenceNum_test.go
fvm/transactionVerifier_test.go
fvm/transaction_test.go

1. Move weighted.Meter into meter package
2. Renamed weighted.Meter to meter.WeightedMeter
This is a followup/cleanup PR for #2882

Move weighted Meter into meter package

---

cmd/util/cmd/hotstuff-view/cmd/getter.go
cmd/util/cmd/hotstuff-view/cmd/reader.go
cmd/util/cmd/hotstuff-view/cmd/root.go
cmd/util/cmd/hotstuff-view/cmd/setter.go
cmd/util/cmd/hotstuff-view/main.go
cmd/util/cmd/read-badger/cmd/storages.go

close https://github.com/dapperlabs/flow-go/issues/6346
This PR add the following command
```
./util hotstuff-view get --datadir ./protocol
./util hotstuff-view set 100 --datadir ./protocol
```

[Util] set/get hotstuff view

---

fvm/scriptEnv.go
fvm/state/state_holder.go
fvm/transactionEnv.go

We never switch on/off the limits independently.

Simplify meter limits control

---

cmd/access/node_builder/unstaked_access_node_builder.go
cmd/dynamic_startup.go
cmd/node_builder.go
cmd/scaffold.go

Port https://github.com/onflow/flow-go/pull/2944 to v0.26

Port 2944 to master

---

integration/testnet/network.go
integration/tests/epochs/epoch_static_transition_test.go
integration/tests/epochs/suite.go

* make epoch safety threshold configurable in integration test config

Suggestions for PR #2935

---

module/profiler/profiler.go

`SetProfilerEnabled` can be called from a different goroutine via the admin command creating a minor race condition.

[Profiler] fix race in SetProfilerEnabled

---

CODEOWNERS

While here, also sort our part.

[CODEOWNERS] actualize performance team's ownership

---

cmd/observer/node_builder/observer_builder.go

Backport PR for https://github.com/onflow/flow-go/pull/2973

Added rpc metrics flag to Observer Node Builder

---

fvm/env.go
fvm/environment/program_logger.go
fvm/environment/tracer.go
fvm/environment/unsafe_random_generator.go
fvm/scriptEnv.go
fvm/transactionEnv.go

Eventually, all environment code (including the stuff in the current handler
subpackage) will live in this subpackage.

Move fully refactored code into new environment subpackage

---

integration/benchmark/tx_per_second_test.go
integration/epochs/cluster_epoch_test.go
integration/tests/access/access_test.go
integration/tests/access/observer_test.go
integration/tests/collection/ingress_test.go
integration/tests/collection/proposal_test.go
integration/tests/collection/suite.go
integration/tests/consensus/inclusion_test.go
integration/tests/consensus/sealing_test.go
integration/tests/execution/chunk_data_pack_test.go
integration/tests/execution/failing_tx_reverted_test.go
integration/tests/execution/state_sync_test.go
integration/tests/ghost/ghost_node_example_test.go
integration/tests/lib/util.go
integration/tests/mvp/mvp_test.go
integration/tests/network/network_test.go
integration/utils/scripts.go
integration/utils/worker_test.go

This is a first step towards enabling `golangci-lint`.

[Testing] Format all files in the integration directory

---

network/p2p/compressed/compressedStream.go

https://github.com/onflow/flow-go/pull/2988/commits/ae7ccdaebbcfa5850eb387e12f1fae7bf3b2ea23#r948527814

[Networking] Checks returned error of gzip writer upon closing. 

---

cmd/util/ledger/reporters/export_reporter.go

backport https://github.com/onflow/flow-go/pull/3018

Remove epoch counter

---

cmd/scaffold.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/execution_verification_test.go
engine/testutil/nodes.go
fvm/blocks.go
fvm/bootstrap.go
fvm/context.go
fvm/env.go
fvm/environment/blocks.go
fvm/environment/blocks_test.go

also renamed some variables for better searchability.

move blocks.go into environment subpackage

---

admin/commands/execution/checkpoint_trigger.go
cmd/bootstrap/run/execution_state.go
cmd/execution_builder.go
cmd/util/cmd/exec-data-json-export/ledger_exporter.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
engine/testutil/nodes.go
ledger/complete/compactor.go
ledger/complete/compactor_test.go
ledger/complete/ledger_benchmark_test.go
ledger/complete/ledger_test.go
ledger/complete/wal/checkpointer_test.go
utils/unittest/logging.go

Backport https://github.com/onflow/flow-go/pull/3010

add admintool for triggering checkpoint

---

integration/benchmark/cmd/ci/main.go
integration/benchmark/cmd/manual/main.go
integration/benchmark/prometheus.go

[Testing] De-duplicate metric pusher code

---

integration/tests/lib/receipt_state.go

[Testing] Fix race in WaitForReceiptFromAny

---

admin/commands/execution/checkpoint_trigger.go
cmd/execution_builder.go
ledger/complete/wal/compactor.go
ledger/complete/wal/compactor_test.go

Add admin tool to trigger checkpoint manually for v0.26.

add admintool for triggering checkpoint for v0.26

---

network/p2p/protocolPeerCache.go

[Networking] Make protocolPeerCache threadsafe

---

cmd/scaffold.go

Temp disable storage check so the core contracts can be upgraded.

[FVM] TEMP Disable sandboxnet storage check

---

integration/tests/access/execution_state_sync_test.go
integration/tests/common/sealing_and_verification.go
integration/tests/execution/chunk_data_pack_test.go
integration/tests/execution/failing_tx_reverted_test.go
integration/tests/execution/state_sync_test.go
integration/tests/lib/block_state.go
integration/tests/verification/verification_stream_negotiation_test.go
integration/tests/verification/verify_system_chunk_test.go

[Testing] Fix races in BlockState

---

consensus/hotstuff/forks/block_builder_test.go
consensus/hotstuff/forks/blockcontainer.go
consensus/hotstuff/forks/forks.go
module/forest/leveled_forest.go
module/forest/leveled_forest_test.go

suggested amendments for PR https://github.com/onflow/flow-go/pull/2954
• extension of goDoc
• fixed edge case is LevelledForest `VerifyVertex` method and added unit test

suggested amendments for PR 2954

---

cmd/execution_builder.go

Port of https://github.com/onflow/flow-go/pull/3070

Fix error logging in script execution - port to master

---

consensus/hotstuff/integration/connect_test.go
consensus/hotstuff/integration/filters_test.go
consensus/hotstuff/integration/instance_test.go

• minor doDoc revisions
• added absent lock to consensus integration test

suggested amendments for PR #2935

---

module/jobqueue/component_consumer_test.go

Fix job queue test races

---

integration/tests/access/execution_state_sync_test.go

This PR quarantines flakey integration-access execution state sync test.

Quarantine execution state sync test

---

consensus/hotstuff/eventhandler/event_handler.go
consensus/integration/slow_test.go
engine/collection/compliance/engine.go
engine/consensus/compliance/engine.go

• added lock to in-line implementation of `BlockOrDelayFunc`
• extended, polished goDoc for tests
• polishing of `EventHandler`: stylistic, logging and documentation changes only (no functional changes)

suggested amendments for PR #2935 (round 3)

---

integration/benchmark/follower.go

This addresses Patrick's comments from #2838.  As a side effect this diff also fixes the `txsTotalUnknown` counter.

[Benchmark] Simplify follower inner loop

---

cmd/util/ledger/reporters/account_reporter.go

port of https://github.com/onflow/flow-go/pull/3082 to master

[FVM] Fix account reporter memory limit - master

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
engine/access/access_test.go
engine/access/ingestion/engine_test.go
engine/access/rest_api_test.go
engine/access/rpc/engine_builder.go
engine/access/rpc/rate_limit_test.go
engine/access/secure_grpcr_test.go

implements hotfix for https://github.com/onflow/flow-go/issues/3115
confirmed working via localnet

[mainnet 19] Hotfix for signer indices decoding

---

.github/workflows/ci.yml

This will unblock landing the test speed up: #3087

[Testing] Disable race detecor while we fix reamining flakes

---

crypto/bls.go
crypto/bls_multisig.go
crypto/bls_thresholdsign.go
crypto/dkg_feldmanvss.go
crypto/dkg_feldmanvssq.go
crypto/dkg_jointfeldman.go
crypto/dkg_test.go
crypto/hash/kmac.go

No functional changes.
Automatic commit with:
```bash
$ golangci-lint run --fix --build-tags relic ./...
```

[Crypto] Reformat using go 1.19 fmt

---

cmd/execution_builder.go

Note that I've left the provider engine unmodified since it will conflict with #3132

Convert component/module initialization closures into methods

---

fvm/env.go
fvm/environment/contract_reader.go
fvm/handler/contract.go
fvm/handler/contract_test.go
fvm/scriptEnv.go
fvm/state/state_holder.go
fvm/transactionEnv.go

NOTE: handler.ContractHandler now only handles contract updates

Refactor contract reader into environment

---

.github/workflows/bench.yml
.github/workflows/bft-tests.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/flaky-test-debug.yml
.github/workflows/flaky-test-monitor-integration.yml
.github/workflows/flaky-test-monitor.yml
.github/workflows/performance-ci.yml
.github/workflows/skipped-test-tracker-integration.yml
.github/workflows/skipped-test-tracker.yml
cmd/Dockerfile
cmd/testclient/go.mod
crypto/Dockerfile
crypto/go.mod
go.mod
integration/benchmark/cmd/manual/Dockerfile
integration/go.mod

Aside from the [new features in 1.19](https://tip.golang.org/doc/go1.19) it will also give us 3-5% performance boost.
(FVM benchmark does not capture this because it is using the same go version on both checkouts.)
Interesting features for us are:
* `GOMEMLIMIT` so that we can run GC more rare than once in two minutes.
* New runtime metrics including: `/cgo/go-to-c-calls:calls` and `/gc/*`.
* Race detector is 2-3x faster.  Also `-asan` is available on Linux.
Depends on: #3136 #3137 #3140 #3141 #2988

[All] Go 1.19

---

fvm/bootstrap.go
fvm/contractFunctionInvocations.go
fvm/contractFunctionInvoker.go
fvm/contractFunctionInvoker_test.go
fvm/env.go
fvm/mock/environment.go
fvm/scriptEnv.go
fvm/transactionEnv.go
fvm/transactionInvoker.go
fvm/transactionStorageLimiter.go
fvm/transactionStorageLimiter_test.go

1. Renamed ContractFunctionInvoker to SystemContracts
2. Converted functions in contractFunctionInvocations.go into SystemContracts
methods
3. Add AddressFromChain to ContractionFunctionSpec
4. Add SystemContracts to environment object
Note: I'll rename and concat the files when I move them into the environment
package.

Refactor system contracts

---

cmd/execution_builder.go

Finish migrating execution node initialization closure to method

---

fvm/fvm_test.go
fvm/transactionInvoker.go

Move of the internal PR: https://github.com/dapperlabs/flow-go/pull/6380
Should be merged as is, as this is whats currently deployed.

[FVM] Interaction limit error fix

---

cmd/util/ledger/reporters/account_reporter.go
engine/execution/computation/manager_test.go
fvm/bootstrap.go
fvm/executionParameters.go
fvm/fvm.go
fvm/mock/procedure.go
fvm/mock/script_processor.go
fvm/mock/transaction_processor.go
fvm/script.go
fvm/scriptEnv.go
fvm/transaction.go
fvm/transactionEnv.go
fvm/transactionInvoker.go
fvm/transactionInvoker_test.go
fvm/transactionSequenceNum.go
fvm/transactionSequenceNum_test.go
fvm/transactionVerifier.go
fvm/transactionVerifier_test.go
fvm/transaction_test.go

Drop vm argument + skip creating programs in tests.

Simplify Process, Processor, Environment initialization

---

fvm/transactionVerifier.go

just a small change with less repeating code.

[FVM] Refactor checkAccountsAreNotFrozen

---

engine/consensus/compliance/core.go
engine/consensus/compliance/engine.go
engine/consensus/compliance/engine_test.go
engine/consensus/provider/engine.go
engine/consensus/provider/engine_test.go

* documented expected error returns in compliance.Core and compliance.Engine
* compactified code by removing unnecessary line breaks

suggested amendments to PR #3121

---

fvm/env.go
fvm/handler/programs.go

With this change, the only cadence runtime.Interface method remaining in facadeEnvironment is ResourceOwnerChanged (I don't really know where to group this).
1. Removed nonAddressPrograms (TransactionPrograms can also handle non-address location)
2. Renamed `(h *ProgramsHandler)` to `(programs *Programs)`
3. Renamed `masterState` to `stateTranaction`
4. Renamed `Programs TransactionPrograms` to `transactionPrograms TransactionPrograms)`
5. Renamed Get/Set to get/set
6. Move GetProgram/SetProgram/DecodeArgument from facadeEnvironment to Programs
7. Also reordered the fields within facadeEnvironment

Refactor environment Programs

---

engine/execution/computation/computer/uploader/retryable_uploader_wrapper.go

[Execution] Porting the fix to wrong WaitGroup usage in goroutine

---

fvm/fvm_bench_test.go

... In order to get a better(more realistic) performance picture from bench tests.

[FVM] Set ReusableCadenceRuntimePoolSize in bench tests

---

engine/execution/computation/computer/uploader/gcp_uploader.go

Back port of: https://github.com/onflow/flow-go/pull/3290
---
Execution nodes have an option to upload block computation results to a GCS bucket. The upload has a retry feature, but does not check the error returned from flushing/closing the connection when deciding if the upload succeeded. Occasionally, the close operation fails with a 50x error from the GCS API, resulting in miss block uploads.
This PR also checks the response from closing the stream and returns an error encountered.

[Execution] Return error when closing gcp connection fails

---

cmd/util/cmd/checkpoint-list-tries/cmd.go
ledger/complete/wal/checkpointer.go
ledger/complete/wal/checkpointer_test.go
ledger/complete/wal/checkpointer_versioning_test.go
utils/unittest/unittest.go

Extracting changes to LoadCheckpoint for checkpointing v4
[Addressing comments](https://github.com/onflow/flow-go/pull/3273/files#r983940431)

Refactor load checkpoint

---

cmd/util/ledger/reporters/account_reporter.go
cmd/util/ledger/reporters/fungible_token_tracker_test.go
cmd/verification_builder.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/execution_verification_test.go
engine/execution/computation/manager.go
engine/execution/computation/manager_benchmark_test.go
engine/execution/computation/manager_test.go
engine/execution/computation/programs_test.go
engine/execution/state/bootstrap/bootstrap.go
engine/testutil/nodes.go
engine/verification/utils/unittest/fixture.go
fvm/environment/programs_test.go
fvm/fvm.go
fvm/fvm_bench_test.go
fvm/fvm_test.go
fvm/state/transaction_state.go
fvm/transactionEnv.go
fvm/transactionInvoker.go
fvm/transaction_test.go
integration/go.mod
integration/go.sum
utils/debug/remoteDebugger.go

uses https://github.com/onflow/flow-emulator/pull/212

[FVM] Remove old FVM constructors

---

engine/common/requester/engine.go
engine/execution/ingestion/engine.go

[Exec] Add logging to collection fetch and handling (v27 backport)

---

integration/benchmark/follower.go

Adds timeout to block/collection fetching.

[Benchmark] Add timeout to tx follower to avoid stalls during high load

---

fvm/fvm.go

It is not safe to ignore txnPrograms' commit error for transactions that trigger programs invalidation.
Note: commit never returns error under sequential execution (except with bad test setup).

Fix TransactionPrograms Commit error handling.

---

engine/collection/compliance/core.go
engine/common/follower/engine.go
engine/consensus/compliance/core.go

• removed white-spaces
• removed unnecessary, duplicated ID computations
• minor extensions of godoc

Suggested amendments for PR #3294

---

fvm/fvm_bench_test.go

Block programs were not behaving properly in the tests.

[FVM] Bench test fixes

---

engine/collection/synchronization/engine_test.go
engine/collection/synchronization/request_handler.go
engine/common/synchronization/engine_test.go

Align message processing between common and collection sync engines

Align request handlers between common and collection sync engines

---

cmd/execution_builder.go

Fix module init

---

cmd/bootstrap/cmd/block.go
cmd/bootstrap/cmd/keygen.go
cmd/bootstrap/cmd/machine_account.go
cmd/bootstrap/cmd/rootblock.go
cmd/scaffold.go
engine/common/rpc/convert/convert.go
flips/component-interface.md
fvm/systemcontracts/system_contracts.go
fvm/systemcontracts/system_contracts_test.go
model/flow/address.go
model/flow/address_test.go
model/flow/chain.go
module/component/component.go

The update of the Stagingnet chain name was added to the `v0.27` branch, but it was never merged to master. We need to reconcile the changes and get these merged to the `v0.28` branch.

Reconcile ChainID changes for Sandboxnet

---

engine/collection/epochmgr/engine.go

* minor polishing of `epochmgr.Engine`: goDoc and removing duplicated `Final()` data base call

suggested amendments to [PR #2994](https://github.com/onflow/flow-go/pull/2994)

---

cmd/execution_builder.go

This reverts commit 749291c46b11d08e0d95bc1fcaa34f2419aa9287.
This performs fine on localnet benchmarks causes issues on EN1 by overflowing its network queue (due to collection node communication issues.)
Ref: https://github.com/onflow/flow-go/pull/3406.
Ref: https://github.com/onflow/flow-go/pull/3442

Revert "[Execution] Backport collection retries" (v27 backport)

---

fvm/errors/errors_collector_test.go

Forgot to add test for this during the refactoring.

Test ErrorsCollector against SplitError

---

ledger/complete/ledger.go

This PR made an optimization in state extraction that it will not rebuild the trie if there is no migration. This could save about 22 mins during spork.

[State Extraction] no migration optimization

---

network/codec.go
network/codec/cbor/codec.go
network/codec/cbor/codec_test.go
network/codec/cbor/decoder.go
network/codec/cbor/decoder_test.go
network/codec/cbor/encoder.go
network/codec/codes.go
network/codec/errors.go
network/p2p/middleware/middleware.go
network/validator/pubsub/topic_validator.go

Fixes data validation for cbor encoding and adds unit test coverage

[Network] Fix cbor decoder validation

---

cmd/execution_builder.go

Blobservice is required by both the gcp uploader and the provider component

Break blobservice out to own component in en builder

---

cmd/scaffold.go

Previously, it started last. This moves it to start before node specific components

Start auto profiler first

---

cmd/execution_builder.go

Reverts onflow/flow-go#3497
Reverting this so we can narrow down the issue occurring on EN1. Will likely add it back later

Revert "Break blobservice out to own component in en builder"

---

engine/common/requester/engine.go

Fix a bug that causing EN to stuck on execution from time to time. 
See [comments ](https://github.com/onflow/flow-go/pull/3515/files#r1014327314) for reasoning and [solution](https://github.com/onflow/flow-go/pull/3515/files#r1014329994).

[Requester] Fix blocking call in requester

---

admin/command_runner.go
admin/command_runner_test.go

This is a backport of #3508 to v0.28

[Profiler] Add selected /debug/pprof/ endpoints to admin interface (v28 backport)

---

fvm/bootstrap.go

The remaining fields in BootstrapProcedure will get refactor into an executor object.
The also simplified default value parsing a bit.

Split bootstrap parameters into a separate struct.

---

engine/common/requester/engine.go

Backport https://github.com/onflow/flow-go/pull/3515 to master

Backport: make requester's Force method non-blocking

---

engine/execution/ingestion/engine.go

This PR fixes a bug that some collections were not requested by ingestion

Fix ingestion engine

---

engine/common/requester/engine.go

backporting https://github.com/onflow/flow-go/pull/3517 to v0.28

make requester's Force method non-blocking

---

CODEOWNERS

In this diff:
* cherry-pick 7d1b1bf170f18d477d5f1c95bef77d4107095382 from the active-pacemaker branch,
* Add @gomisha as a reviewers for `/integration/benchmark`,
* Add "Dev Tools Stream",
* Remove @zhangchiqing from `localnet` to reduce spam,
* Remove @Kay-Zee to reduce spam,
* Remove ex-team members,
* Remove `/utils/binstat` since it is unsupported.

[CODEOWNERS] Update ownership

---

admin/README.md
admin/commands/common/set_golog_level.go
cmd/scaffold.go
go.mod
network/p2p/dht/dht_test.go

This is a backport of https://github.com/onflow/flow-go/pull/3526 to v0.28
Ref: https://github.com/onflow/flow-go/issues/3455

[Networking] Add ability to change libp2p's logging level on the fly (v28 backport)

---

network/p2p/scoring/score_option.go

https://github.com/onflow/flow-go/pull/3506/files

Backports 3506 changes

---

integration/benchmark/cmd/ci/main.go
integration/localnet/Makefile

We'll be replacing cmd flags with a gRPC interface.

[Benchmark] Remove unused flags from CI

---

model/flow/identity.go

A followup for: https://github.com/onflow/flow-go/pull/3542

[Model] Fix race condition in DeterministicSample

---

engine/common/provider/engine.go
engine/common/requester/engine.go

For debugging https://github.com/onflow/flow-go/issues/3455#issuecomment-1315713131

log entity ids in debug level log

---

fvm/executionParameters.go
fvm/fvm.go

1. make meter parameter overrides cache-able.
2. move all meter parameter setup logic into a function
gh: #3102

Refactor meter parameter setup logic.

---

integration/benchmark/cmd/ci/main.go
integration/benchmark/cmd/ci/main_test.go
integration/benchmark/contLoadGenerator.go
integration/benchmark/worker_stats_tracker.go

Each time we encounter a timeout we want to throttle unconditionally.

[Benchmark] Throttle on timeout

---

engine/execution/ingestion/engine.go
network/p2p/middleware/middleware.go
network/p2p/network.go

This PR fixes a bug that when ingestion engine can't load unexecuted blocks

[Execution] Fix ingestion loading unexecuted blocks

---

engine/execution/computation/computer/computer.go

executeCollection and executeSystemCollection have identical logic, with only minor tracing and logging differences.
gh: #3547

dedup executeCollection logic

---

engine/execution/computation/computer/computer.go
engine/execution/messages.go

All the necessary transaction result info are in TransactionProcedure. There's no need to set the ComputationResult's fields using individual calls.
gh: #3547

Simplify adding transaction result to ComputationResult

---

.github/workflows/bench.yml

Trade some benchstat accuracy for some time.
Also make benchstat optional since its only informative anyway.

Shorten bench and make it optional

---

engine/execution/computation/computer/computer.go

Asides from error string formating, there's no difference in how regular and system collections should be processed.
gh: #3547

Stop special casing system collection execution

---

admin/command_runner.go

This PR builds on https://github.com/onflow/flow-go/pull/3649 and also sets a max receive size.

[Access] Also set max receive size in admin server

---

cmd/execution_builder.go
engine/execution/state/state.go
state/protocol/badger/state.go
state/protocol/badger/state_test.go
storage/badger/procedure/executed.go
storage/badger/procedure/executed_test.go

Backport of https://github.com/onflow/flow-go/pull/3596

report finalized sealed height on startup

---

fvm/bootstrap.go
fvm/fvm.go
fvm/script.go
fvm/transaction.go
fvm/transactionInvoker.go
fvm/transactionInvoker_test.go
fvm/transactionVerifier_test.go
fvm/transaction_test.go

Replace Procedure's Run method with NewExecutor

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/result_collector.go

Improve result collector to return error instead of panic

---

cmd/access/node_builder/access_node_builder.go

This was added to [all other nodes](https://github.com/onflow/flow-go/blob/master/cmd/scaffold.go#L952-L956), but was missing on ANs.

[Access] Add support for blocklist in admin server

---

fvm/fvm_bench_test.go

One of the bench tests had a problem with the interaction limit.

[FVM] Fix bench test

---

integration/benchmark/contLoadGenerator.go
integration/benchmark/follower.go

Quality of life improvements to logging.

[Benchmark] Improve logging output

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/result_collector.go

Prep work for flattening the executeCollection loop.
gh: #3547

Refactor execute transaction input into a struct

---

fvm/utils/view.go

The bootstrap util's reporter crashed during the last canary spork with the stacktrace below. 
This PR adds locking to the `MapLedger` to prevent concurrent access
```
7:49PM INF starting reporter ledger_mod=complete name="Account Reporter"
fatal error: concurrent map writes
goroutine 535 [running]:
github.com/onflow/flow-go/fvm/utils.(*MapLedger).Get(...)
/app/fvm/utils/view.go:160
github.com/onflow/flow-go/fvm/utils.(*SimpleView).Get(0xc00c438000, {0xc0b74240f8, 0x8}, {0xc0b74240f0, 0x7})
/app/fvm/utils/view.go:64 +0x69
github.com/onflow/flow-go/fvm/utils.(*SimpleView).Get(0xc0b6efa020, {0xc0b74240f8, 0x8}, {0xc0b74240f0, 0x7})
/app/fvm/utils/view.go:73 +0xe8
github.com/onflow/flow-go/fvm/utils.(*SimpleView).Get(0xc0000e44c0, {0xc0b74240f8, 0x8}, {0xc0b74240f0, 0x7}) …
```

[Bootstrap] Fix concurrent read/write in reporter

---

module/metrics.go
module/metrics/example/collection/main.go
module/metrics/example/consensus/main.go
module/metrics/labels.go
module/metrics/network.go
module/metrics/noop.go
module/mock/network_core_metrics.go
module/mock/network_metrics.go
network/message_scope.go
network/p2p/network.go

Backports https://github.com/onflow/flow-go/pull/3761

[Network] Add protocol metrics label - v0.29 backport

---

network/message_scope.go

Backport of https://github.com/onflow/flow-go/pull/3767

[Network] Fix inbound message metrics label v0.29-no-pacemaker backport

---

insecure/corruptlibp2p/pubsub_adapter_config.go

https://github.com/onflow/flow-go/pull/3564

[BFT Testing] fixes CI failure on PR 3564

---

cmd/access/node_builder/access_node_builder.go
cmd/node_builder.go
cmd/observer/node_builder/observer_builder.go
cmd/scaffold.go
follower/follower_builder.go
network/p2p/cache/node_blocklist_distributor.go
network/p2p/cache/node_blocklist_wrapper.go
network/p2p/cache/node_blocklist_wrapper_test.go
network/p2p/middleware/middleware.go

This PR implements my suggested revisions for PR https://github.com/onflow/flow-go/pull/3762

suggested revisions for PR #3762

---

engine/access/rest/blocks.go
engine/access/rest/blocks_test.go
engine/access/rest/models/block.go
engine/access/rest/models/model_block.go

Closes https://github.com/onflow/flow-go/issues/3622

[Access] Add BlockStatus to GetBlock REST API

---

cmd/util/cmd/common/flow_client.go

backport of https://github.com/onflow/flow-go/pull/3857

[Access Client] Set message received limits - v0.29 backport

---

cmd/util/cmd/common/flow_client.go

backport of https://github.com/onflow/flow-go/pull/3857

[Access Client] Set message received limits - v0.29-no-pacemaker backport

---

engine/common/rpc/convert/convert.go
engine/common/rpc/convert/convert_test.go
module/blobs/blob_store.go
module/executiondatasync/execution_data/util.go
storage/badger/seals.go

Backports https://github.com/onflow/flow-go/pull/3887

[Access] Fix panic converting execution data to protobuf messages 

---

cmd/bootstrap/cmd/access_keygen.go
cmd/bootstrap/cmd/access_keygen_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
utils/grpcutils/grpc.go
utils/grpcutils/grpc_test.go

This new command allows generating Access API TLS keys

[Tools] Add bootstrap command to generate grpc TLS keys

---

engine/access/rest/middleware/metrics.go
engine/access/rest/router.go
engine/access/rpc/backend/backend_accounts.go
engine/access/rpc/backend/backend_events.go
engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/backend_transactions.go
engine/common/rpc/convert/convert.go
engine/common/rpc/errors.go
engine/common/rpc/errors_test.go
engine/execution/rpc/engine.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
module/metrics/noop.go
module/metrics/rest_api.go

Backports the following changes:
* https://github.com/onflow/flow-go/pull/3691
* https://github.com/onflow/flow-go/pull/3915
* https://github.com/onflow/flow-go/pull/3897

[Access] Backport error reporting and rest metrics - v0.29

---

cmd/bootstrap/cmd/qc.go
cmd/bootstrap/run/qc.go
cmd/bootstrap/run/qc_test.go
consensus/integration/nodes_test.go
integration/testnet/network.go

See comments.
If we fail to construct QC, we will log the error and also log invalid votes if there is any.
If we succeeded to construct a QC, we will also log invalid votes if there is any.

Log invalid vote in bootstrap finalize

---

cmd/bootstrap/cmd/qc.go
cmd/bootstrap/run/qc.go
cmd/bootstrap/run/qc_test.go
consensus/integration/nodes_test.go
integration/testnet/network.go

Backport of https://github.com/onflow/flow-go/pull/3832#issuecomment-1432163770

0.29 log invalid vote in bootstrap finalize

---

fvm/environment/program_logger.go

closes: https://github.com/onflow/flow-go/issues/3878

[FVM] Debug log cadence logs

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/computer/mock/block_computer.go
engine/execution/computation/computer/result_collector.go
engine/execution/computation/execution_verification_test.go
engine/execution/computation/manager.go
engine/execution/computation/manager_benchmark_test.go
engine/execution/computation/manager_test.go
engine/execution/computation/mock/computation_manager.go
engine/execution/computation/programs_test.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/execution/ingestion/uploader/manager_test.go
engine/execution/ingestion/uploader/uploader_test.go
engine/execution/messages.go
engine/execution/state/unittest/fixtures.go
engine/testutil/mock/nodes.go
engine/verification/utils/unittest/fixture.go
fvm/fvm_bench_test.go
module/trace/constants.go

Also removed handleComputationResult since it does nothing

Generate execution result as part of block computation

---

network/p2p/p2pbuilder/libp2pNodeBuilder.go
network/p2p/p2pbuilder/utils.go

Backports: https://github.com/onflow/flow-go/pull/3904

[Networking] Logging of libp2p Resource Limits at Node Startup

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to Cadence v0.31.5

---

fvm/derived/table.go
fvm/derived/table_test.go

We only need to check for missing / out-of-ordered transactions when committing the transaction.  Moving the commit range check from unsafeValidate() to commit() enables us to validate transactions in any order.

Fix derived transaction to support out-of-ordered validation

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
fvm/derived/derived_block_data.go
fvm/derived/derived_chain_data_test.go
fvm/derived/invalidator.go
fvm/environment/contract_updater.go
fvm/environment/contract_updater_test.go
fvm/environment/derived_data_invalidator.go
fvm/environment/derived_data_invalidator_test.go
fvm/environment/facade_env.go
fvm/environment/mock/derived_transaction_data.go
fvm/environment/mock/metrics_reporter.go
fvm/environment/program_logger.go
fvm/environment/programs.go
fvm/environment/programs_test.go
fvm/programs/programs.go
module/metrics.go
module/metrics/execution.go
module/metrics/noop.go
module/mock/execution_metrics.go
module/mock/runtime_metrics.go

Port of:
- https://github.com/onflow/flow-go/pull/3706
- https://github.com/onflow/flow-go/pull/3888
- https://github.com/onflow/flow-go/pull/3896

Port programs cache changes and metrics

---

cmd/util/cmd/rollback-executed-height/cmd/rollback_executed_height_test.go
engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/computer/result_collector.go
engine/execution/computation/execution_verification_test.go
engine/execution/computation/manager_test.go
engine/execution/computation/programs_test.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/execution/messages.go
engine/execution/state/mock/execution_state.go
engine/execution/state/state.go
engine/execution/state/unittest/fixtures.go
engine/verification/utils/unittest/fixture.go
insecure/corruptnet/network.go
model/flow/execution_receipt.go

Also remove a bunch of fields from computation result

Generate execution receipt as part of block computation

---

utils/debug/remoteDebugger.go
utils/debug/remoteView.go

There's no need to duplicate the view logic.  We only need a custom Get method

Replace RemoteView with delta.View

---

engine/execution/computation/manager.go
fvm/bootstrap.go
fvm/fvm.go
fvm/script.go
fvm/transaction.go
fvm/transactionInvoker.go
fvm/transactionInvoker_test.go
fvm/transactionVerifier_test.go

prep work to make fvm procedure idempotent

Refactor fvm procedure output into a struct

---

engine/execution/computation/computer/computer_test.go
engine/execution/state/bootstrap/bootstrap_test.go
fvm/bootstrap.go
fvm/environment/contract_updater.go
fvm/environment/contract_updater_test.go
fvm/environment/mock/contract_updater_stubs.go
fvm/environment/system_contracts.go
fvm/fvm_blockcontext_test.go
fvm/systemcontracts/system_contracts.go
utils/unittest/execution_state.go

ref: https://github.com/onflow/flow-core-contracts/pull/356
ref: https://github.com/onflow/flow-go/issues/2635

Remove audit vouchers

---

engine/common/follower/cache/cache.go

suggested revisions for follower cache

suggested revisions for follower cache

---

fvm/derived/derived_block_data.go
fvm/environment/facade_env.go
fvm/environment/programs.go

up next: 
- remove individual get and set methods
- remove the nil location check

Use GetOrCompute for programs

---

fvm/fvm_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
integration/tests/epochs/epoch_join_and_leave_an_test.go

See https://github.com/onflow/cadence/pull/2380

Update to Cadence v0.31.5-account-linking-improved-pragma

---

engine/execution/computation/computer/result_collector.go
engine/execution/ingestion/engine_test.go
engine/execution/ingestion/uploader/model.go
engine/execution/ingestion/uploader/model_test.go
engine/execution/ingestion/uploader/retryable_uploader_wrapper.go
engine/execution/ingestion/uploader/retryable_uploader_wrapper_test.go
engine/execution/messages.go
engine/execution/state/unittest/fixtures.go
engine/verification/utils/unittest/fixture.go
storage/badger/computation_result_test.go
storage/badger/operation/computation_result_test.go

The identical data is available in chunks

Remove StateCommitments from ComputationResult

---

engine/execution/computation/computer/computer_test.go
fvm/derived/derived_block_data.go
fvm/derived/derived_chain_data_test.go
fvm/derived/table.go
fvm/derived/table_test.go
fvm/environment/meter.go
fvm/environment/programs.go
module/trace/constants.go

ref: https://github.com/onflow/cadence/issues/1684

Remove unused/usafe Get/Set on Derived data

---

fvm/environment/contract_reader.go
fvm/environment/contract_updater.go
fvm/environment/mock/contract_updater.go
fvm/environment/mock/environment.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

to https://github.com/onflow/cadence/commit/ba9bfc7b2551b1e76b67af40c9d0e62e6746200a

Upgrade Cadence

---

CODEOWNERS

Remove so outdated entries, add myself to access/execution sync streams

Cleanup codeowners

---

fvm/derived/dependencies.go
fvm/derived/dependencies_test.go
fvm/derived/derived_block_data.go
fvm/environment/contract_updater.go
fvm/environment/contract_updater_test.go
fvm/environment/derived_data_invalidator.go
fvm/environment/derived_data_invalidator_test.go
fvm/environment/env.go
fvm/environment/facade_env.go
fvm/environment/mock/contract_updater.go
fvm/environment/mock/environment.go
fvm/environment/programs.go
fvm/environment/programs_test.go
fvm/transactionInvoker.go

ref: https://github.com/onflow/cadence/issues/1684
This is now possible that account freezing is removed, and will be needed to remove double counting of imports.

Change program dependencies to cadence location

---

fvm/accounts_test.go

Note that I will be replace the views with proper (SnapshotTree) storage snapshots in a future PR.

Update accounts test to use vm.RunV2

---

cmd/util/ledger/reporters/account_reporter.go
engine/execution/computation/manager_test.go

Also updated account reporter to access accounts via env

Switch non-fvm use cases to NewScriptEnvironmentFromStorageSnapshot

---

engine/common/follower/pending_tree/pending_tree.go

This PR aims to extend and polish the documentation of `PendingTree`. Particularly, I am trying to add more details to address this comment in a related PR: https://github.com/onflow/flow-go/pull/4094#discussion_r1150737746
**GoDoc revisions only; no algorithmic changes**

extend documentation of pending tree

---

ledger/complete/wal/checkpoint_v6_leaf_reader.go
ledger/complete/wal/checkpoint_v6_reader.go
ledger/complete/wal/checkpoint_v6_test.go

Cherry-picked commits for `v0.29`
Fixes #3990

Add read leaf nodes from checkpoint file for Archive node use (#4040)

---

engine/execution/computation/computer/computer_test.go
model/convert/service_event_test.go
module/chunks/chunkVerifier_test.go
utils/unittest/service_events_fixtures.go

Extracting pieces from https://github.com/onflow/flow-go/pull/3736 so its easier to digest and merge.

Move test fixtures closer to usage

---

state/protocol/badger/mutator.go
state/protocol/badger/mutator_test.go

Updating docs to account for change to service event processing.

Suggestions for PR #4149

---

fvm/environment/contract_updater.go
fvm/environment/derived_data_invalidator_test.go
fvm/environment/programs_test.go

Note that we still need initialize TransactionState using delta view in various places for now

Clean up delta view usage in fvm/environment

---

cmd/access/node_builder/access_node_builder.go
cmd/collection/main.go
cmd/execution_builder.go
cmd/observer/node_builder/observer_builder.go
cmd/verification_builder.go
engine/common/follower/integration_test.go
engine/testutil/nodes.go
follower/follower_builder.go

This PR connects finalization events for all node types, this was missed before.

[Hotfix] Follower engine finalization events

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update Cadence to v0.31.5-account-linking-improved-pragma-patch.2

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

[v0.30] Update to Cadence v0.38.1

---

ledger/complete/wal/checkpoint_v6_leaf_reader.go
ledger/complete/wal/checkpoint_v6_test.go

Backporting https://github.com/onflow/flow-go/pull/4137/files to v0.30

v0.30 fix read leaf nodes

---

cmd/util/cmd/read-execution-state/list-accounts/cmd.go
cmd/util/ledger/reporters/account_reporter.go
cmd/util/ledger/reporters/fungible_token_tracker.go
cmd/util/ledger/reporters/fungible_token_tracker_test.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/computer/result_collector.go
engine/execution/state/delta/view.go
fvm/environment/derived_data_invalidator_test.go
fvm/environment/event_emitter_test.go
fvm/environment/facade_env.go
fvm/environment/programs_test.go
fvm/environment/uuids_test.go
fvm/fvm.go
fvm/state/execution_snapshot.go
fvm/state/execution_state.go
fvm/state/execution_state_test.go
fvm/state/spock_state.go
fvm/state/spock_state_test.go
fvm/state/transaction_state.go
fvm/state/transaction_state_test.go
fvm/storage/derived/derived_chain_data_test.go
fvm/storage/derived/table_test.go
fvm/storage/testutils/utils.go
module/chunks/chunkVerifier.go

This also internalizes spockState

Change execution state to use storage snapshot as input

---

fvm/storage/primary/intersect.go
fvm/storage/primary/intersect_test.go

To be used for transaction validation

Add register id sets intersection function

---

cmd/access/node_builder/access_node_builder.go
engine/access/rpc/backend/backend_scripts.go

Backport https://github.com/onflow/flow-go/pull/4239 to master

Backport fix scripts

---

engine/execution/computation/computer/computer_test.go
engine/execution/computation/execution_verification_test.go
engine/verification/utils/unittest/fixture.go
fvm/bootstrap.go
fvm/environment/derived_data_invalidator_test.go
fvm/environment/facade_env.go
fvm/environment/programs_test.go
fvm/fvm.go
fvm/storage/derived/derived_block_data.go
fvm/storage/derived/derived_chain_data.go
fvm/storage/derived/table.go
fvm/storage/derived/table_test.go
fvm/storage/testutils/utils.go
module/chunks/chunkVerifier.go

The initializer has been updated to match primary block data's initializer.

Simplify derived block data initializer

---

engine/execution/computation/computer/computer_test.go

Extra test to ensure ExecuteBlock terminates / returns error when we start supporting parallel execution.

Add computer test to check for internal error

---

cmd/access/node_builder/access_node_builder.go
cmd/collection/main.go
cmd/execution_builder.go
cmd/observer/node_builder/observer_builder.go
cmd/verification_builder.go
follower/follower_builder.go

This PR backports changes from PR to tagged branch: https://github.com/onflow/flow-go/pull/4173/files

[Hotfix] Connected finalization events to follower engines

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

https://github.com/dapperlabs/cadence-internal/compare/v0.31.5-account-linking-improved-pragma-patch.2...v0.31.6-patch.1

Update to Cadence v0.31.6-patch.1

---

.github/workflows/builds.yml
Makefile
cmd/Dockerfile

Backports https://github.com/onflow/flow-go/pull/4223 which added a GHA secret mount for authenticating to GH during builds

[CI] Add GHA secret mount - v0.29 backport

---

fvm/systemcontracts/system_contracts.go

We already fixed this one, but we forgot to port it to master from v0.30

Fix system transaction imports

---

fvm/systemcontracts/system_contracts.go

port - Fix system transaction imports (#4443)

---

engine/access/rpc/backend/backend_transactions.go

…dexed (#4454)
* [Access] Do not return not found for tx result when collection not indexed
* address review feedback

fix get tx

---

cmd/execution_builder.go

port - Transaction logging fix 

---

engine/access/rpc/backend/backend_transactions.go

We will need to apply the same fix as #4462 to the system tx events as well

Include fix for system tx as well

---

engine/execution/ingestion/engine.go
module/mempool/queue/queue.go
module/mempool/queue/queue_test.go

Backport https://github.com/onflow/flow-go/pull/4464

[Execution] Backport - panic when on executed block error

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

https://github.com/dapperlabs/cadence-internal/compare/v0.31.6-patch.2...v0.31.6-patch.3

Update to Cadence v0.31.6-patch.3

---

admin/commands/storage/helper.go
admin/commands/storage/read_blocks.go
admin/commands/storage/read_range_blocks.go
admin/commands/storage/read_range_cluster_blocks.go
admin/commands/storage/read_transactions.go
admin/commands/storage/read_transactions_test.go

Backport https://github.com/onflow/flow-go/pull/4476

Backport to v0.31 increase range limit

---

engine/execution/computation/manager_benchmark_test.go

Prep work for benchmarking concurrent execution

Refactor manager banchmark test

---

engine/execution/computation/computer/computer.go

I'll expose the concurrent execution option in a follow up PR.
Issue: #3547

Concurrent transaction execution skeleton

---

engine/execution/computation/computer/computer.go
engine/execution/computation/computer/computer_test.go
engine/execution/computation/computer/mock/transaction_write_behind_logger.go
engine/execution/computation/computer/result_collector.go
engine/execution/computation/computer/transaction_coordinator.go
engine/execution/computation/computer/transaction_coordinator_test.go
module/metrics.go
module/metrics/execution.go
module/metrics/noop.go
module/mock/execution_metrics.go

Add transaction conflict retry metrics

---

admin/commands/execution/stop_at_height_test.go
cmd/execution_builder.go
cmd/execution_config.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/execution/ingestion/stop/stop_control.go
engine/execution/ingestion/stop/stop_control_test.go
engine/testutil/nodes.go

Allow ingestion engine to gracefully stop before crashing.

Add graceful stop to stop control

---

Makefile

backport of https://github.com/onflow/flow-go/pull/4484

backport of CI fix of intermittent failures of verify-mocks

---

cmd/execution_builder.go
cmd/execution_config.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/testutil/nodes.go

backports: https://github.com/onflow/flow-go/pull/3860/files

Backport Temporary workaround for LN networking issue v0.31

---

engine/execution/ingestion/uploader/model.go
engine/execution/ingestion/uploader/model_test.go

Port https://github.com/onflow/flow-go/pull/4562 to v0.31 branch

port PR4562 to v0.31 branch

---

cmd/execution_builder.go
cmd/execution_config.go
cmd/util/cmd/truncate-database/cmd.go
engine/execution/state/state.go
integration/localnet/builder/bootstrap.go
integration/testnet/network.go
module/mempool/queue/queue_test.go
storage/badger/chunkDataPacks.go
storage/badger/chunk_data_pack_test.go
storage/chunkDataPacks.go
storage/mock/chunk_data_packs.go

back port https://github.com/onflow/flow-go/pull/4618

[backport] v0.31 store chunk data separate dir

---

network/p2p/middleware/middleware.go

Backports https://github.com/onflow/flow-go/pull/4623

[Network] Fix chunk datapack size and timeout limits

---

cmd/verification_builder.go

This is a quick fix for version v0.31.
It only changes the behaviour of verification nodes.
Do not port directly! this logic should be extracted not duplicated.

Fix verification cadende runtime settings

---

engine/execution/scripts/engine.go
engine/execution/state/state.go

This PR is a follow up on the #4668 as it was prematurely automatically merged.

Script execution engine interface changes refactor

---

engine/execution/computation/computer/computer.go
engine/execution/ingestion/engine.go

backporting https://github.com/onflow/flow-go/pull/4716

v0.31 log num txs cols

---

Makefile

[CI] Rename without_netgo tag to without-netgo - port

---

Makefile
crypto/bls.go
crypto/bls12381_utils.c
crypto/bls12381_utils.go
crypto/bls12381_utils.h
crypto/bls_core.c
crypto/bls_thresholdsign.go
crypto/bls_thresholdsign_core.c
crypto/blst_include.h
crypto/dkg_core.c
crypto/dkg_feldmanvss.go
crypto/dkg_include.h

Minor cleanups (clearer names, formatting, typos, use `E2` descriptive instead of `G2`)

[Crypto] minor clean up

---

module/mempool/herocache/backdata/cache.go
network/p2p/connection/connection_gater.go
network/p2p/connection/internal/loggerNotifiee.go
network/p2p/p2pnode/libp2pNode.go
network/p2p/tracer/gossipSubMeshTracer.go
network/p2p/tracer/gossipSubMeshTracer_test.go
network/p2p/tracer/gossipSubScoreTracer.go
network/p2p/tracer/gossipSubScoreTracer_test.go

Backport https://github.com/onflow/flow-go/pull/4736 to v0.31

v0.31 move to debug log

---

cmd/util/ledger/reporters/fungible_token_tracker.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

https://github.com/onflow/cadence/releases/tag/v0.39.15

[v0.31] Update to Cadence v0.39.15

---

engine/execution/ingestion/engine_test.go
engine/execution/ingestion/mocks/block_store.go
engine/execution/ingestion/mocks/collection_store.go
engine/execution/ingestion/mocks/fetcher.go
engine/execution/state/state.go
model/flow/chunk_test.go

Refactor the ingestion engine tests.

Refactor ingestion test cases

---

fvm/flex/blockstore.go
fvm/flex/evm/config.go
fvm/flex/evm/emulator.go
fvm/flex/evm/emulator_test.go
fvm/flex/evm/signer.go
fvm/flex/flex_test.go
fvm/flex/handler.go
fvm/flex/handler_test.go
fvm/flex/models/block.go
fvm/flex/models/blockchain.go
fvm/flex/models/emulator.go
fvm/flex/models/events.go
fvm/flex/models/result.go
fvm/flex/storage/database.go
fvm/flex/testutils/accounts.go
fvm/flex/testutils/contract.go
fvm/flex/testutils/emulator.go
fvm/script.go
fvm/transactionInvoker.go

- improve interfaces for results 
- fix block height injection issue
- leave room for future multi-procedure blocks 
- separate out block storage from the database

[Flex] improve structure

---

consensus/hotstuff/committees/cluster_committee.go
state/protocol/cluster.go

minor suggestions for [PR #4726](https://github.com/onflow/flow-go/pull/4726/)
• extending documentation around cluster committee
• compactifying code

minor suggestions for PR #4726

---

ledger/complete/ledger.go
ledger/complete/ledger_test.go
ledger/partial/ledger.go
ledger/partial/ledger_test.go

[Ledger] update ledger.Set to remove empty update case

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Port of https://github.com/dapperlabs/flow-go/pull/6891

[v0.32] Update cadence to v0.42.2

---

cmd/execution_config.go
cmd/node_builder.go

Backport for https://github.com/onflow/flow-go/pull/4885

[Backport] Make path configs to be usable by container by default

---

access/api.go
access/handler.go
access/legacy/handler.go
access/mock/api.go
engine/access/rest/apiproxy/rest_proxy_handler.go
engine/access/rest/routes/events.go
engine/access/rest/routes/events_test.go
engine/access/rest/routes/transactions.go
engine/access/rest/routes/transactions_test.go
engine/access/rpc/backend/backend_events.go
engine/access/rpc/backend/backend_test.go
engine/access/rpc/backend/backend_transactions.go
engine/access/rpc/backend/backend_transactions_test.go
engine/access/rpc/backend/historical_access_test.go
engine/access/rpc/backend/retry_test.go
engine/access/state_stream/backend/handler.go
engine/access/state_stream/backend/handler_test.go
engine/common/rpc/convert/events.go
engine/common/rpc/convert/events_test.go
engine/common/rpc/convert/execution_data.go
engine/common/rpc/convert/execution_data_test.go
engine/execution/rpc/engine.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
utils/unittest/generator/events.go

Backports: https://github.com/onflow/flow-go/pull/4809

[Access] Make CCF encoded events optional via request parameter - backport v0.32

---

network/p2p/p2pbuilder/libp2pNodeBuilder.go

This PR slightly refactors applying the limit on inbound connections. With changes in this PR, the limit is only applied when the corresponding flag is set. Otherwise, the libp2p default limit is applied.

[Networking] Refactors inbound connection limit application

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Port of https://github.com/dapperlabs/flow-go/pull/6890

[v0.31] Update cadence to v0.39.17

---

access/handler.go
cmd/access/node_builder/access_node_builder.go
engine/access/rpc/backend/backend_scripts.go
engine/execution/computation/query/executor.go
engine/execution/rpc/engine.go
engine/execution/rpc/engine_test.go
engine/execution/scripts/engine.go
integration/testnet/client.go
integration/tests/access/access_api_test.go
integration/utils/transactions.go
module/execution/scripts.go
module/execution/scripts_test.go
module/metrics.go
module/metrics/noop.go
module/metrics/transaction.go
module/mock/access_metrics.go
module/mock/backend_scripts_metrics.go
module/state_synchronization/indexer/indexer_core.go
module/state_synchronization/indexer/indexer_core_test.go
storage/pebble/testutil.go

Backports the following PRs:
* https://github.com/onflow/flow-go/pull/4902
* https://github.com/onflow/flow-go/pull/4895
* https://github.com/onflow/flow-go/pull/4894
* https://github.com/onflow/flow-go/pull/4862
* https://github.com/onflow/flow-go/pull/4920
* https://github.com/onflow/flow-go/pull/4907
* https://github.com/onflow/flow-go/pull/4917

Backport Access related fixes to v0.32

---

network/p2p/inspector/validation/control_message_validation_inspector.go

https://github.com/onflow/flow-go/pull/4968

[Networking] Backport 4968 updating rpc inspector log

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update cadence to [v0.42.4](https://github.com/onflow/cadence/releases/tag/v0.42.4)

Update cadence to v0.42.4

---

.github/workflows/ci.yml
.github/workflows/flaky-test-monitor.yml
integration/Makefile
integration/tests/access/cohort1/access_api_test.go
integration/tests/access/cohort2/observer_test.go
integration/tests/access/cohort3/access_circuit_breaker_test.go
integration/tests/access/cohort3/access_test.go
integration/tests/access/cohort3/consensus_follower_test.go
integration/tests/access/cohort3/execution_state_sync_test.go
integration/tests/access/cohort3/grpc_compression_test.go
integration/tests/access/cohort3/rest_state_stream_test.go
integration/tests/bft/framework/passthrough_test.go
integration/tests/epochs/cohort2/epoch_join_and_leave_vn_test.go
network/p2p/p2pnode/resourceManager_test.go
network/test/cohort1/meshengine_test.go
network/test/cohort1/network_test.go
network/test/cohort2/blob_service_test.go
network/test/cohort2/echoengine.go
network/test/cohort2/echoengine_test.go
network/test/cohort2/epochtransition_test.go
network/test/cohort2/unicast_authorization_test.go
utils/test_matrix/test_matrix.go
utils/test_matrix/test_matrix_test.go

Sync with `master` to get CI improvements

---

engine/execution/mock/executed_finalized_wal.go
engine/execution/mock/in_memory_register_store.go
engine/execution/mock/register_store.go
engine/execution/mock/wal_reader.go
engine/execution/storehouse.go
engine/execution/storehouse/in_memory_register_store.go
engine/execution/storehouse/in_memory_register_store_test.go
utils/unittest/fixtures.go

This PR implemented the [in memory register store](https://github.com/onflow/flow-go/pull/4836)

[Storehouse] Storehouse in memory regsiter store

---

engine/access/rest/request/address.go
engine/access/rest/request/address_test.go
engine/access/rest/request/get_account.go
engine/access/rest/request/get_account_key.go
engine/access/rest/request/get_account_key_test.go
engine/access/rest/request/get_account_test.go
engine/access/rest/request/proposal_key.go
engine/access/rest/request/signature_test.go
engine/access/rest/request/signatures.go
engine/access/rest/request/transaction.go
engine/access/rest/routes/subscribe_events_test.go
engine/access/rest/routes/websocket_handler.go
engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/script_comparer.go
engine/access/rpc/backend/script_comparer_test.go
engine/common/rpc/convert/validate.go
ledger/common/convert/convert_test.go
model/flow/ledger.go
model/flow/ledger_test.go
storage/pebble/registers_test.go

Backports:
* https://github.com/onflow/flow-go/pull/4930
* https://github.com/onflow/flow-go/pull/4936
* https://github.com/onflow/flow-go/pull/4954
* https://github.com/onflow/flow-go/pull/4942
* https://github.com/onflow/flow-go/pull/4956

[Access] Backport AN changes to v0.32

---

cmd/access/node_builder/access_node_builder.go
cmd/execution_config.go
engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/backend_scripts_test.go
engine/execution/computation/query/executor.go
fvm/errors/codes.go
module/execution/scripts.go
module/execution/scripts_test.go

Backports:
* https://github.com/onflow/flow-go/pull/5036
* https://github.com/onflow/flow-go/pull/5037

[Access] Backport script execution improvements

---

engine/access/rest/routes/subscribe_events_test.go
engine/access/rest/routes/websocket_handler.go

Backport: https://github.com/onflow/flow-go/pull/5048

[Access] Update websockets event streaming to return JSON-CDC encoded events - v0.32

---

cmd/execution_builder.go
cmd/execution_config.go
cmd/util/cmd/rollback-executed-height/cmd/rollback_executed_height_test.go
engine/execution/block_result.go
engine/execution/state/bootstrap/bootstrap.go
engine/execution/state/mock/execution_state.go
engine/execution/state/mock/read_only_execution_state.go
engine/execution/state/mock/script_execution_state.go
engine/execution/state/state.go
engine/execution/state/state_test.go
engine/testutil/nodes.go
fvm/storage/state/execution_state_test.go
module/finalizedreader/finalizedreader.go
storage/badger/headers.go

Close https://github.com/onflow/flow-go/issues/5002

[Storehouse] Adding flag to enable storehouse

---

cmd/execution_builder.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/engine_test.go
engine/testutil/nodes.go

Remove unused dependency for execution ingestion engine

[Execution] Remove module.Local from ingestion engine

---

fvm/evm/types/events.go

Closes: #5219 
Fixed wrong order of event fields.

[EVM] Fix order of fields in the event

---

.github/workflows/builds.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
Makefile
cmd/Dockerfile

This reconciles the build changes that were made to support SSH key injection for downloading dependencies. 
The following workflow was run as a test
* [Build Images](https://github.com/onflow/flow-go/actions/runs/6880694054)
* [CI](https://github.com/onflow/flow-go/actions/runs/7615068865/job/20738733863?pr=5258)
* [Build Images in separate repo](https://github.com/dapperlabs/flow-go/actions/runs/7616320450)

Reconcile build changes in Makefile & Dockerfile

---

cmd/util/ledger/migrations/change_contract_code_migration.go
engine/execution/computation/manager.go
fvm/bootstrap.go
fvm/evm/evm.go
fvm/evm/evm_test.go
fvm/evm/stdlib/abiOnlyContract.cdc
fvm/evm/stdlib/contract.go
fvm/evm/stdlib/contract_test.go
fvm/fvm_bench_test.go
fvm/fvm_test.go
fvm/systemcontracts/system_contracts.go
fvm/transactionStorageLimiter.go
fvm/transactionStorageLimiter_test.go

This is a port of both https://github.com/onflow/flow-go/pull/5255 and https://github.com/onflow/flow-go/pull/5230

Add feature flag for deploying EVM contract only with ABI functionality - Port

---

cmd/util/ledger/migrations/change_contract_code_migration.go
cmd/util/ledger/util/util.go

Required for https://github.com/onflow/cadence/issues/3063

Support emulator in migrations

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

https://github.com/onflow/cadence/releases/tag/v0.42.9

[v0.33] Update to Cadence v0.42.9

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to Cadence v0.42.9

---

cmd/access/node_builder/access_node_builder.go
engine/access/integration_unsecure_grpc_server_test.go
engine/access/rpc/backend/backend.go
engine/access/rpc/backend/backend_accounts_test.go
engine/access/rpc/backend/backend_events.go
engine/access/rpc/backend/backend_events_test.go
engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/backend_scripts_test.go
engine/access/rpc/backend/events_index.go
engine/access/rpc/backend/script_executor.go
engine/access/state_stream/backend/backend.go
engine/access/state_stream/backend/backend_events.go
engine/access/state_stream/backend/backend_events_test.go
engine/access/state_stream/backend/backend_executiondata_test.go
engine/access/state_stream/backend/streamer.go
integration/localnet/Makefile
integration/localnet/builder/bootstrap.go
integration/tests/access/cohort3/grpc_state_stream_test.go
module/execution/registers_async.go
module/execution/registers_async_test.go
module/execution/scripts.go
module/state_synchronization/index_reporter.go
module/state_synchronization/indexer/indexer.go
module/state_synchronization/mock/index_reporter.go
module/state_synchronization/requester/distributer.go
storage/badger/events.go

Backports: https://github.com/onflow/flow-go/pull/5321

 [Access] Fix event index bounds checking in Access APIs - v0.33 backport

---

cmd/execution_builder.go
module/executiondatasync/provider/provider.go
module/executiondatasync/tracker/noop.go

Close https://github.com/onflow/flow-go/issues/5457

Disable execution data pruner

---

cmd/execution_builder.go
module/executiondatasync/provider/provider.go
module/executiondatasync/tracker/noop.go

Backporting https://github.com/onflow/flow-go/pull/5463 to v0.33

Backport v0.33 disable execution data pruner

---

cmd/util/ledger/migrations/atree_register_migration.go
cmd/util/ledger/migrations/cadence_value_validation_test.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/migrator_runtime.go
cmd/util/ledger/migrations/staged_contracts_migration.go

Required for https://github.com/onflow/flow-emulator/pull/584

Export migrator runtime constructor

---

cmd/access/node_builder/access_node_builder.go
cmd/observer/node_builder/observer_builder.go
integration/localnet/builder/bootstrap.go
integration/testnet/network.go
integration/tests/access/cohort3/execution_state_sync_test.go
network/channels/channels.go
network/network.go

Backport 2 PRs in order to allow access node to support execution data on the public network
- https://github.com/onflow/flow-go/pull/5253
- https://github.com/onflow/flow-go/pull/5375

Backport v0.33 public execution state sync merge

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/staged_contracts_migration.go
cmd/util/ledger/migrations/staged_contracts_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Improvements:
- Added type update rule to change from `MetadataViews.Resolver` to `ViewResolver.Resolver`
- Improved error logging to include error details.
Also update dependencies to:
- [onflow/flow-go-sdk v1.0.0-preview.14](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.14)
- [onflow/cadence v1.0.0-preview.16](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.16)

Improve cadence migrations

---

integration/benchnet2/Makefile

Port a change from master that fixes BN2 create network action

Fix BN2 action

---

cmd/util/ledger/migrations/atree_register_migration.go
cmd/util/ledger/migrations/cadence_value_diff.go
cmd/util/ledger/migrations/cadence_value_validation.go
cmd/util/ledger/migrations/migrator_runtime.go
cmd/util/ledger/reporters/fungible_token_tracker.go
cmd/util/ledger/util/util.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.17](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.17)
- [onflow/cadence v1.0.0-preview.19](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.19)

Update to Cadence v1.0.0-preview.19

---

engine/common/unit/unit.go
engine/common/unit/unit_test.go
engine/unit.go

Addressing review comments https://github.com/onflow/flow-go/pull/5643#discussion_r1556665271

move PreReady and PreDone to constructor and add test cases

---

ledger/complete/wal/checkpoint_v6_reader.go
ledger/complete/wal/checkpoint_v6_test.go

Close https://github.com/onflow/flow-go/issues/5623

Add validation to checkpoint head file

---

state/fork/traversal.go

Backport https://github.com/onflow/flow-go/pull/5661

Backport v0.33 fix traversal error handling

---

fvm/evm/evm.go
fvm/evm/stdlib/contract.go
fvm/evm/stdlib/contract_test.go
fvm/script.go
fvm/transactionInvoker.go

Improve naming and remove unused parameter

Clean up EVM environment setup

---

admin/commands/storage/read_protocol_snapshot.go
cmd/util/cmd/read-protocol-state/cmd/snapshot.go
cmd/util/common/checkpoint.go

Backport https://github.com/onflow/flow-go/pull/5679

[Backport] Log the checkpoint file when using generating protocol snapshot from

---

integration/benchmark/load/load_type_test.go

Not sure if this is correct, but it makes the test work. Copied from other similar test cases

Fix EVM load test

---

engine/execution/rpc/engine.go
engine/execution/rpc/engine_test.go
model/flow/chunk.go
model/flow/event_test.go

Backport https://github.com/onflow/flow-go/pull/5611

Backport check events hash when block has no events

---

cmd/util/cmd/root.go

Add profiler capability to util.

add profiler to util

---

fvm/evm/emulator/emulator.go

Add transaction index to the transaction run result.

[EVM] Add transaction index to result

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

See https://discord.com/channels/613813861610684416/1108479699732152503/1235322871060893758

Update to tagged atree version

---

engine/execution/ingestion/core.go

Backport: https://github.com/onflow/flow-go/pull/5838

Backport v0.33: [Execution] Check local collection exists before fetching

---

engine/execution/ingestion/core.go

This PR fixes an issue that the new ingestion engine should load the collection from local if exists instead of requesting it from other nodes.

[Execution] Check local collection exists before fetching

---

engine/execution/ingestion/core.go
engine/execution/ingestion/engine.go
engine/execution/ingestion/machine.go
engine/execution/ingestion/stop/stop_control.go
engine/execution/ingestion/stop/stop_control_test.go
engine/execution/ingestion/throttle.go
engine/execution/ingestion/throttle_test.go
storage/badger/procedure/index.go
utils/unittest/mocks/protocol_state.go

Backport https://github.com/onflow/flow-go/pull/5863

Backport v0.33 [Execution] Fix throttle

---

fvm/environment/block_info.go
fvm/environment/block_info_test.go
utils/unittest/fixtures.go

Backport https://github.com/onflow/flow-go/pull/5853

Backport v0.33 fix getblock

---

model/flow/protocol_state.go

This is a **suggested amendment to PR https://github.com/onflow/flow-go/pull/5773**.
* added consistency checks to constructor for `RichProtocolStateEntry`, which enforce that setup / commit events are nil in case no respective epoch is specified

consistency checks for `RichProtocolStateEntry` constructor

---

insecure/integration/functional/test/gossipsub/scoring/ihave_spam_test.go
insecure/integration/functional/test/gossipsub/scoring/scoring_test.go
network/p2p/builder/libp2pNodeBuilder.go

fixes bug in DHT initialization that resulted in always disabling the DHT

[Access] Fix conditional in DHT setup

---

engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/backend_scripts_test.go

[Access] Failover when script exceeds computation or memory limit

---

cmd/util/cmd/find-inconsistent-result/cmd.go
cmd/util/cmd/root.go

Backport https://github.com/onflow/flow-go/pull/5883

Backport: [Util] add util cmd to find mismatch result

---

cmd/util/cmd/find-inconsistent-result/cmd.go
cmd/util/cmd/root.go

This PR adds a util to find the first result that mismatch with the sealed result.

[Util] add util cmd to find mismatch result

---

engine/access/rpc/backend/backend_transactions.go
engine/access/rpc/backend/backend_transactions_test.go

Cache system tx result. Add test for it.
Issue: https://github.com/onflow/flow-go/issues/5757

[Access] Support fetching system tx result from cache

---

fvm/environment/block_info.go
fvm/environment/block_info_test.go

This PR temporarily revert [the fix](https://github.com/onflow/flow-go/pull/5878/files), and will re-enable it once we do another HCU for mainnet24.

v0.33 revert get block fix

---

cmd/util/cmd/find-inconsistent-result/cmd.go

Backport https://github.com/onflow/flow-go/pull/5890

v0.33 Fix find mismatch result util 

---

cmd/util/cmd/find-inconsistent-result/cmd.go

This PR fixes a bug in the find inconsistent result util cmd.

Fix find mismatch result util

---

engine/execution/ingestion/core.go
engine/execution/ingestion/core_test.go
engine/execution/ingestion/machine.go

Backport: https://github.com/onflow/flow-go/pull/5871

Backport: v0.33 add ingestion metrics

---

engine/common/requester/engine.go
engine/execution/ingestion/fetcher/fetcher.go

This PR fixes an issue in the requester engine that could cause EN not able to fetch collection.

Fix requester engine's optimization

---

engine/common/requester/engine.go
engine/execution/ingestion/fetcher/fetcher.go

Backport https://github.com/onflow/flow-go/pull/5941

[Backport] Fix request collection

---

cmd/util/ledger/migrations/change_contract_code_migration.go
go.mod
go.sum

Stage contract update for NFTStorefrontV2 on Testnet

---

cmd/util/ledger/migrations/migrator_runtime.go
fvm/evm/evm.go
fvm/evm/evm_test.go
fvm/script.go
fvm/transactionInvoker.go

Small cleanup on the setup evm API.

[EVM] EVM setup cleanup

---

access/api.go
access/handler.go
access/mock/api.go
engine/access/apiproxy/access_api_proxy.go
engine/access/mock/access_api_client.go
engine/access/mock/access_api_server.go
engine/access/rpc/backend/backend.go
engine/common/rpc/convert/collections.go
engine/common/rpc/convert/collections_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Working towards  https://github.com/onflow/flow-go/issues/5782
This PR adds a new GRPC endpoint `GetFullCollectionByID` to the access node.

Add get full collection by id api

---

cmd/util/ledger/migrations/account_based_migration.go

While investigating onflow/cadence#3366, I refactored the concurrent account migration to use [errgroup](https://pkg.go.dev/golang.org/x/sync/errgroup). 
While it turned out that the existing implementation is not problematic, it still maybe makes sense to get the refactored version in, as it is IMHO more readable. For example, errors can be returned from the goroutines as usually done in normal functions.
This PR is best viewed with whitespace changed disabled.

Use errgroup for concurrent account migration

---

engine/execution/ingestion/fetcher/access_fetcher.go

Backport https://github.com/onflow/flow-go/pull/6011

Backport v0.33 [Execution] increase guarantee buffer

---

cmd/collection/main.go

https://github.com/dapperlabs/flow-go/issues/6964

Disable script checking by default

---

fvm/environment/block_info.go
fvm/environment/block_info_test.go

Re-enable https://github.com/onflow/flow-go/pull/5896

Backport v0.33 fix get block API

---

cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/migration_metrics_collector.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.34](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.34)
- [onflow/cadence v1.0.0-preview.32](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.32)

Update to Cadence v1.0.0-preview.32

---

ledger/complete/wal/checkpoint_v6_leaf_reader.go
ledger/complete/wal/checkpoint_v6_reader.go
ledger/complete/wal/checkpoint_v6_test.go
storage/pebble/bootstrap.go

Backporting https://github.com/onflow/flow-go/pull/6032

[Backport v0.33] check checkpoint has only 1 trie before importing

---

cmd/util/cmd/update-commitment/cmd.go
storage/pebble/bootstrap_test.go

Fix a test cases that was failing in this PR https://github.com/onflow/flow-go/pull/6033

Fixing test case

---

ledger/complete/wal/checkpoint_v6_leaf_reader.go
ledger/complete/wal/checkpoint_v6_reader.go
ledger/complete/wal/checkpoint_v6_test.go
storage/pebble/bootstrap.go
storage/pebble/bootstrap_test.go
utils/grpcutils/grpc.go

Close https://github.com/onflow/flow-go/issues/6030

Check checkpoint has only 1 trie before importing

---

cmd/util/ledger/migrations/atree_register_migration.go

Closes https://github.com/onflow/cadence/issues/3408 https://github.com/onflow/cadence/issues/3409
Currently, empty storage map isn't migrated during atree migration because migration is done by migrating storage map elements which in turn migrate modified storage map.
This PR migrates empty storage map by resetting type of its underlying atree map, so underlying atree map is modified and migrated when re-encoded.
The fix can be confirmed by running `atree-inlined-status` command added by
- https://github.com/onflow/flow-go/pull/6063
cc: @j1010001

Migrate empty storage map in atree migration

---

cmd/util/ledger/migrations/cadence_values_migration_test.go
cmd/util/ledger/migrations/migration_matrics_collector_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.36](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.36)
- [onflow/cadence v1.0.0-preview.34](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.34)

Update to Cadence v1.0.0-preview.34

---

cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/migrations/atree_register_migration_test.go
cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
cmd/util/ledger/migrations/fix_broken_data_migration_test.go
cmd/util/ledger/util/registers/registers.go

Optimize atree migration by porting and modifying PR 5914 to feature/atree-inlining-cadence-v0.42

---

cmd/util/ledger/migrations/atree_register_migrator_runtime.go
fvm/storage/state/execution_state.go
fvm/storage/state/spock_state.go
fvm/storage/state/spock_state_test.go
fvm/storage/state/transaction_state.go

Optimize atree migration by porting and modifying PR 5920 to feature/atree-inlining-cadence-v0.42

---

cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/util/payload_grouping.go
cmd/util/ledger/util/payload_grouping_test.go
ledger/common/convert/convert.go
ledger/common/convert/convert_test.go

Optimize atree migration by porting and modifying PR 5929 to feature/atree-inlining-cadence-v0.42

---

cmd/util/ledger/util/payload_grouping.go
ledger/common/convert/convert.go
ledger/common/convert/convert_test.go
ledger/trie.go
ledger/trie_encoder.go
ledger/trie_test.go
module/state_synchronization/indexer/indexer_core_test.go
storage/pebble/bootstrap_test.go

Optimize atree migration by porting and modifying PR 5948 to feature/atree-inlining-cadence-v0.42

---

cmd/util/cmd/execution-state-extract/execution_state_extract.go
cmd/util/ledger/util/payload_grouping.go
cmd/util/ledger/util/registers/registers.go

Optimize atree migration by porting and modifying PR 5942 to feature/atree-inlining-cadence-v0.42

---

.github/workflows/stale.yml

This has been failing since it was [moved](https://github.com/onflow/flow-go/pull/4116) to the workflows directory. Update the format to use standard GHA job, and run daily.

[CI] Fix stale issue workflow

---

cmd/util/cmd/execution-state-extract/cmd.go
cmd/util/cmd/execution-state-extract/execution_state_extract.go

Work towards onflow/cadence#3303
A full profile is useful for e.g. profile-guided optimization

Profile whole state extraction, not just migration

---

fvm/evm/emulator/emulator.go
fvm/evm/emulator/state/stateDB.go
fvm/evm/types/errors.go

Adding extra checks for negative amounts in transactions.

[Flow EVM] add extra checks for EVM state balance changes

---

cmd/util/cmd/find-trie-root/cmd.go
cmd/util/cmd/root.go
ledger/complete/wal/encoding.go
ledger/complete/wal/encoding_test.go

Porting https://github.com/onflow/flow-go/pull/6094 to master

[Util] find trie root hash

---

cmd/util/ledger/migrations/contract_checking_migration.go

Include the code of the checked contracts in the report, for both successes and failures.
Best viewed with whitespace disabled.
This is in general useful so developers know exactly what staged code was included in the migration. 
It also helps with debugging, e.g. https://github.com/onflow/cadence/issues/3436

Report checked code

---

fvm/fvm_signature_test.go
fvm/transactionPayerBalanceChecker.go
fvm/transactionPayerBalanceChecker_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum
module/state_synchronization/indexer/util_test.go
utils/unittest/generator/events.go
utils/unittest/service_events_fixtures.go

- [onflow/flow-go-sdk v1.0.0-preview.37](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.37)
- [onflow/cadence v1.0.0-preview.35](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.35)

Update to Cadence v1.0.0-preview.35

---

engine/execution/state/bootstrap/bootstrap_test.go
fvm/evm/evm_test.go
fvm/evm/stdlib/contract.cdc
fvm/evm/stdlib/contract_test.go
fvm/evm/types/balance.go
fvm/evm/types/events.go
utils/unittest/execution_state.go

[Flow EVM] Adding balance after to deposit and withdraw events

---

engine/access/rpc/backend/backend_scripts.go
engine/access/rpc/backend/script_comparer.go
engine/access/rpc/backend/script_comparer_test.go

Backports: https://github.com/onflow/flow-go/pull/5959

[Access] Reduce logging for script executions

---

fvm/evm/emulator/emulator.go

This PR fixes nil pointer problems in case of tx tracing is tracing a invalid transaction.

[Flow EVM] fix the issue with the new Geth tracing

---

cmd/util/ledger/migrations/cadence_values_migration.go

Just like for `MissingTarget` calls with `linkMissingTargetEntry`, and for `MissingCapabilityID` calls with `capabilityMissingCapabilityIDEntry`, report a dedicated entry type for cyclic link migration errors (`CyclicLink` calls).
The custom entry has an added kind, which can be used when querying the report.

[Cadence 1.0 migration] Improve reporting of cyclic link migration errors

---

cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.45](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.45)
- [onflow/cadence v1.0.0-preview.42](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.42)

Update to Cadence v1.0.0-preview.42

---

fvm/evm/types/block.go
fvm/evm/types/block_test.go

This PR patches the broken block loading (v6).

[Flow EVM] patch backoff block loading

---

cmd/util/cmd/diff-states/cmd.go
cmd/util/cmd/diff-states/diff_states_test.go
go.mod

Work towards #6132
Add support for detecting if accounts differ, without reporting actual byte or value differences

[Util] Add support for detecting differing accounts

---

cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go

Fixes https://flow-foundation.slack.com/archives/C074F78ECNL/p1723052086114979

Set capability issue handler in capability value migration

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Depends on https://github.com/onflow/cadence/pull/3514

Report and skip storage caps with no borrow type

---

fvm/evm/debug/tracer.go

Some tracing changes seems to have dropped during the porting to the previewnet

[Flow EVM] port missing tracing updates to previewnet

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Incorporate changes from:
- https://github.com/onflow/cadence/pull/3516
- https://github.com/onflow/cadence/pull/3517

Improve storage capability migration

---

cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/cadence_values_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.49](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.49)
- [onflow/cadence v1.0.0-preview.47](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.47)

Update to Cadence v1.0.0-preview.47

---

fvm/evm/evm.go
fvm/evm/handler/blockstore.go
fvm/evm/handler/blockstore_benchmark_test.go
fvm/evm/handler/blockstore_test.go
fvm/evm/handler/handler_test.go
fvm/evm/types/block.go
fvm/evm/types/block_test.go

Populate all fields for the Genesis block, it changes the genesis block hash to be flow chain ID dependent.

[Flow EVM] Populate all fields for the genesis block

---

engine/access/rpc/backend/backend.go
engine/access/rpc/backend/backend_test.go

Backports: https://github.com/onflow/flow-go/pull/5969

[Access] Backport fix for preferred execution node selection

---

cmd/execution_builder.go
cmd/execution_config.go
fvm/evm/debug/tracer_test.go
fvm/evm/debug/uploader.go

This PR disables the bucket upload step of debug tracer if the bucket name is set to empty

[Flow EVM] skip debug trace uploading step if bucket name is empty

---

model/events/parse.go
model/events/parse_test.go

Closes: https://github.com/onflow/flow-go/issues/6355

[Access] Update event parsing validator to support ResourceDestroyed events

---

engine/access/rpc/backend/backend_network.go

Closes: https://github.com/onflow/flow-go/issues/6365
This is needed for flow wallet testing

[Access] Hardcode network parameters chainID to flow-migrationnet

---

cmd/util/ledger/migrations/cadence_values_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Updating to https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.49

Update to cadence v1.0.0-preview.49

---

cmd/util/ledger/migrations/cadence_values_migration_test.go

Depends on https://github.com/onflow/flow-go/pull/6383

Add test for storage capability migration determinism

---

cmd/util/cmd/check-storage/cmd.go

This PR skips EVM storage account (testnet & mainnet) during atree storage health check because EVM registers require a different decoder.  Cadence-Atree decoder cannot decode EVM registers.
Support for storage health check of EVM registers can be added later in separate PR(s).

Skip EVM storage account in `check-storage` command

---

cmd/util/ledger/migrations/contract_checking_migration_test.go
fvm/environment/program_recovery.go

Work towards https://github.com/onflow/cadence/issues/3480
Add support for recovering pre-Cadence 1.0 NFT Collections.
Simplify tests

[FVM] Recover NFT Collections

---

cmd/util/ledger/migrations/contract_checking_migration.go
cmd/util/ledger/migrations/type_requirements_extractor.go

needed by e.g. CLI, see https://github.com/onflow/flow-cli/pull/1704

[Cadence 1.0 migration] Export type requirement extraction

---

Makefile
README.md
cmd/util/cmd/check-storage/cmd.go
cmd/util/ledger/migrations/account_storage_migration.go
cmd/util/ledger/migrations/cadence.go
cmd/util/ledger/migrations/cadence_values_migration.go
cmd/util/ledger/migrations/contract_checking_migration.go
cmd/util/ledger/migrations/contract_checking_migration_test.go
cmd/util/ledger/migrations/fix_broken_data_migration.go
cmd/util/ledger/migrations/migrator_runtime.go
cmd/util/ledger/migrations/type_requirements_extractor.go
cmd/util/ledger/util/migration_runtime_interface.go
fvm/environment/facade_env.go
fvm/environment/mock/environment.go
fvm/environment/program_recovery.go
fvm/evm/evm.go
fvm/evm/evm_test.go
fvm/evm/impl/abi.go
fvm/evm/impl/impl.go
fvm/evm/stdlib/contract.go
fvm/evm/stdlib/contract_test.go
fvm/evm/stdlib/type_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Merge `master` into `v0.37`. It consists mostly of Cadence-related improvements 
See https://flow-foundation.slack.com/archives/C074F78ECNL/p1724686543836929

Update v0.37 with master

---

cmd/util/cmd/debug-tx/cmd.go
cmd/util/cmd/root.go
utils/debug/remoteDebugger.go

Heavily inspired by @janezpodhostnik's previous work in [`janez/debug-migration-mainnet?expand=1`#diff-485f7944e6](https://github.com/onflow/flow-go/compare/janez/debug-migration-mainnet?expand=1#diff-485f7944e6bc35f9ae2f4bb703ec25479b43987300f7c8a128f630b3f297b407R12) 👌

[Util] Add command to debug transaction

---

cmd/bootstrap/cmd/pull.go
cmd/bootstrap/gcs/gcs.go
cmd/bootstrap/transit/cmd/flags.go
cmd/bootstrap/transit/cmd/pull.go
cmd/bootstrap/utils/md5.go

Backporting https://github.com/onflow/flow-go/pull/6353/files

Backport v0.37 pull improvements

---

cmd/util/ledger/migrations/cadence_values_migration_test.go
go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

- [onflow/flow-go-sdk v1.0.0-preview.55](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.55)
- [onflow/cadence v1.0.0-preview.52](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.52)

Update to Cadence v1.0.0-preview.52

---

network/p2p/inspector/validation/control_message_validation_inspector.go

Backport https://github.com/onflow/flow-go/pull/6441

Backport: Change sample size log from warn to debug

---

fvm/evm/debug/tracer.go
fvm/evm/emulator/emulator_test.go

[EVM] port #6467 - patch evm tracer

---

fvm/evm/impl/abi.go
fvm/evm/stdlib/contract_test.go

[EVM] backport of 6480 - handle UInt,Int types for ABI encoding/decoding

---

fvm/evm/impl/abi.go
fvm/evm/stdlib/contract_test.go

Follow-up on PR: https://github.com/onflow/flow-go/pull/6480

[Flow EVM] Add boundary checks for ABI encoding values of type `UInt` & `Int`

---

fvm/evm/impl/abi.go
fvm/evm/stdlib/contract_test.go

[EVM] port 6486 - Add boundary checks for ABI encoding values of type UInt & Int

---

cmd/bootstrap/cmd/final_list.go
cmd/bootstrap/cmd/finalize.go
cmd/bootstrap/cmd/finalize_test.go
cmd/bootstrap/cmd/rootblock.go

Fix the duplication detection logic in root block finalization.

[Bootstrap] Fix duplication detection in root block finalization

---

fvm/environment/program_recovery.go

$git cherry-pick [25ef9f0614049829369c3a6c1b0754f24031333c](https://github.com/onflow/flow-go/pull/6513/commits/25ef9f0614049829369c3a6c1b0754f24031333c)
$git cherry-pick [76678dc63afce88ea8a0317f5ec5e129b4a82c84](https://github.com/onflow/flow-go/pull/6513/commits/76678dc63afce88ea8a0317f5ec5e129b4a82c84)

cherrypick commits from PR: https://github.com/onflow/flow-go/pull/6513

---

.github/workflows/cd.yml

Some issues with CD file mirroring changes from master

Remove input

---

cmd/bootstrap/cmd/block.go
cmd/bootstrap/cmd/dkg.go
cmd/bootstrap/cmd/finalize.go
cmd/bootstrap/cmd/qc.go
cmd/bootstrap/cmd/rootblock.go
cmd/bootstrap/dkg/dkg.go
cmd/bootstrap/run/qc.go
integration/testnet/network.go
model/dkg/dkg.go
state/protocol/inmem/encodable.go

https://github.com/onflow/flow-go/issues/6726
Refactored encoding structures to correctly represent available data, previously it was missing information about participants. Also grouped it by participant to avoid relying on indexing for 3 structures, now instead of 3 different slices we have 1.

[EFM] Refactored encoding and decoding of DKG data during bootstrapping

---

module/metrics/server.go

Change the metrics server to be a proper component.

Metrics server as component

---

Makefile

This PR is getting the following change https://github.com/onflow/flow-go/pull/6790 into v0.37. I did have to fix conflicts on the branch.

Update Makefile to support private util builds

---

engine/execution/computation/manager.go
fvm/blueprints/system_test.go

Added an enable for the v2 storage for all networks besides mainnet

enable storage format v2 for all but mainnet

---

cmd/util/cmd/read-protocol-state/cmd/blocks.go

Backport https://github.com/onflow/flow-go/pull/6857

Backport v0.37 add query last executed sealed block

---

.github/workflows/builds.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/flaky-test-monitor.yml
.github/workflows/tools.yml
README.md
cmd/Dockerfile
cmd/testclient/go.mod
crypto/go.mod
go.mod
insecure/go.mod
integration/benchmark/cmd/manual/Dockerfile
integration/go.mod
integration/localnet/client/Dockerfile

Upgrade repo to use [go1.23](https://tip.golang.org/doc/go1.23)

Upgrade to go 1.23

---

CODEOWNERS

v0.37 branch codeowners blocking merge of https://github.com/onflow/flow-go/pull/6937

add FVM codeowners

---

module/pruner/pruners/chunk_data_pack.go
module/pruner/pruners/chunk_data_pack_test.go
utils/unittest/fixtures.go

This PR adds chunk data pack pruning functions.

[Chunk Data Pack Pruner] Add chunk data pack pruner

---

engine/access/subscription/streamer.go
engine/common/rpc/logging_interceptor.go
module/grpcserver/server_builder.go

Stop logging when stream context is canceled
Reduce log level for common API error codes

[Access] Tuning API logging

---

go.mod
go.sum
insecure/go.mod
insecure/go.sum
integration/go.mod
integration/go.sum

Update to [Cadence v1.3.3](https://github.com/onflow/cadence/releases/tag/v1.3.3)

[v0.38] Update to Cadence v1.3.3

---

engine/execution/pruner/core.go
engine/execution/pruner/core_test.go
module/block_iterator.go
module/block_iterator/executor/executor.go
module/block_iterator/executor/executor_test.go
module/block_iterator/iterator.go
module/metrics.go
module/metrics/execution.go
module/metrics/noop.go
module/mock/block_iterator.go
module/mock/execution_metrics.go

Working towards https://github.com/onflow/flow-go/issues/6516
This PR improves the logging and metrics of chunk data pack pruning.

[Execution] Improve chunk data pack pruner logging and metrics

---

cmd/consensus/README.md

Fix minor typos

---

cmd/scaffold.go
consensus/integration/nodes_test.go
engine/testutil/nodes.go
integration/testnet/container.go
state/protocol/badger/mutator_test.go
storage/badger/all.go
storage/operation/version_beacon.go
storage/operation/version_beacon_test.go
storage/store/version_beacon.go

Working towards: https://github.com/onflow/flow-go/issues/6939
Refactor storage version beacon

[Storage] Refactor storage version beacon

---

tools/test_matrix_generator/matrix.go
utils/unittest/unittest_test.go

make function comments match function names

chore: make function comments match function names

---

cmd/bootstrap/cmd/rootblock_test.go
cmd/bootstrap/run/epochs.go
cmd/util/cmd/epochs/cmd/recover.go

Backport of https://github.com/onflow/flow-go/pull/7127

[v0.39] Add sanity checks and logging to EFM recovery tool

---

storage/operation/pebbleimpl/writer.go

Currently, Pebble's `Batch` isn't closed after `Commit()` is called.  This PR closes `Batch` to release resources by calling pebble's `Batch.Close()`.
Internally in Pebble, `Batch.Close()` resets `Batch` resources and returns it to `sync.Pool` for recycling.
This PR assumes `Storage.Batch` isn't used after `Batch.Commit()` is called.  Otherwise, instead of closing `Batch`, we need to explicitly reset batch (which wasn't being done before this PR).

[Storage] Release Pebble batch resource to reduce memory use

---

module/profiler/profiler.go
module/profiler/profiler_test.go

Backport https://github.com/onflow/flow-go/pull/7215

Backport: v0.39 disable block profiler

---

module/profiler/profiler.go
module/profiler/profiler_test.go

The block profiler is causing some issue. Disable it for now.

Disable block profiler

---

module/profiler/profiler.go
module/profiler/profiler_test.go

Backport https://github.com/onflow/flow-go/pull/7215/ to v0.40

v0.40 disable block profiler

---

storage/operation/badgerimpl/iterator.go

Currently, `badger.Txn` is created when BadgerDB iterator is created in `newBadgerIterator()`, but the created transaction is never discarded.
According to BadgerDB's docs for v2, `Txn.Discard()` is very important and must be called.
This PR updates `badgerIterator.Close()` to call `badger.Txn.Discard()` after the iterator is closed.
This was found while getting familiar with storage code related to BadgerDB and Pebble.

[Storage] Discard BadgerDB transaction when iterator is closed

---

consensus/hotstuff/eventloop/event_loop.go
consensus/hotstuff/timeoutaggregator/timeout_aggregator.go
consensus/hotstuff/voteaggregator/vote_aggregator.go
engine/collection/compliance/core.go
engine/collection/message_hub/message_hub.go
engine/common/follower/compliance_core.go
engine/consensus/compliance/core.go
engine/consensus/matching/core.go
engine/consensus/message_hub/message_hub.go
engine/verification/assigner/engine.go
module/jobqueue/consumer.go
network/underlay/network.go

This PR reduces the log level from INFO to DEBUG for some high-volume and relatively low-value log lines. It is based on [this audit of log volume](https://www.notion.so/flowfoundation/Log-Volume-Investigation-2025-03-21-1bd1aee123248046a79ddb4042d658d5?pvs=4). It also fixes a few instances where logger were not scoped properly.
As is this will reduce info-level log volume by about 20-40%.

Logging level adjustments

---

consensus/hotstuff/eventloop/event_loop.go
consensus/hotstuff/timeoutaggregator/timeout_aggregator.go
consensus/hotstuff/voteaggregator/vote_aggregator.go
engine/collection/compliance/core.go
engine/collection/message_hub/message_hub.go
engine/common/follower/compliance_core.go
engine/consensus/compliance/core.go
engine/consensus/matching/core.go
engine/consensus/message_hub/message_hub.go
engine/verification/assigner/engine.go
module/jobqueue/consumer.go
network/underlay/network.go

Backport https://github.com/onflow/flow-go/pull/7174

[v0.40] Logging level adjustments

---

cmd/util/cmd/debug-tx/cmd.go

- Allow executing multiple transactions
- Dump read and updated registers to CSV files

Improve remote debugger

---

engine/access/subscription/tracker/execution_data_tracker.go

Backports: https://github.com/onflow/flow-go/pull/7340

[Access] Allow small gap between streaming start and indexed height - v0.40

---

engine/common/version/version_control.go

Also adding v0.39 and v0.40 missing in master branch

adding compatibility for v0.41 

---

engine/access/rest/websockets/data_providers/account_statuses_provider.go
engine/access/rest/websockets/data_providers/account_statuses_provider_test.go
engine/access/rest/websockets/data_providers/events_provider.go
engine/access/rest/websockets/data_providers/events_provider_test.go

Backports: https://github.com/onflow/flow-go/pull/7339

[Access] Update websockets events and account status reponses to use json-cdc

---

engine/access/rest/websockets/data_providers/account_statuses_provider.go
engine/access/rest/websockets/data_providers/account_statuses_provider_test.go
engine/access/rest/websockets/data_providers/events_provider.go
engine/access/rest/websockets/data_providers/events_provider_test.go

Closes: #7337 
Currently, the endpoints return the default CCF encoded events, but should return JSON-CDC encoded events similar to the REST APIs.

[Access] Update websockets events and account status reponses to use json-cdc encoding

---

engine/access/rest/websockets/data_providers/account_statuses_provider.go
engine/access/rest/websockets/data_providers/account_statuses_provider_test.go
engine/access/rest/websockets/data_providers/events_provider.go
engine/access/rest/websockets/data_providers/events_provider_test.go
engine/access/subscription/tracker/execution_data_tracker.go

Backports: https://github.com/onflow/flow-go/pull/7339, https://github.com/onflow/flow-go/pull/7340

Backport websockets API fixes to v0.41

---

engine/common/version/version_control.go

Closes: #7414 
This PR adds some missing compatible version overrides, and removes 2 that were unused. See issue for details.

[Access] Fix version compatibility list

---

model/bootstrap/node_info.go

Add a warning comment following this discussion: https://github.com/onflow/flow-go/pull/2803#discussion_r2110382657

Add warning note for `NodeInfo`

---

module/block_iterator/executor/executor.go
module/state_synchronization/indexer/indexer_core.go
storage/operation/dbtest/helper.go

Backport https://github.com/onflow/flow-go/pull/7490 to v0.42

[Backport v0.42] [Storage] Ensure batch.Close is called exactly once.

---

.gitignore

cursor stores project rules under `./cursor/rules`

Ignore .cursor/

---

fvm/evm/emulator/state/delta.go
fvm/evm/emulator/state/delta_test.go
fvm/evm/emulator/state/stateDB.go

Backport https://github.com/onflow/flow-go/pull/7405 to `v0.42` .

[Backport v0.42] Fix high CPU usage related to EVM `DeltaView.AddressInAccessList`

---

engine/common/version/version_control.go

adding access node compatibility for new version

---

.cursor/rules/godocs.mdc

Add a cursor rule to help AI generate consistent godocs.

[Tooling] Add cursor rule for godocs

---

engine/execution/state/state.go
engine/execution/state/state_storehouse_test.go
engine/verification/verifier/engine.go
engine/verification/verifier/engine_test.go
state/protocol/badger/state.go
state/protocol/protocol_state/kvstore/kvstore_storage.go
state/protocol/protocol_state/kvstore/kvstore_storage_test.go
state/protocol/protocol_state/kvstore/set_value_statemachine_test.go
state/protocol/protocol_state/kvstore/upgrade_statemachine_test.go
state/protocol/protocol_state/kvstore_storage.go
state/protocol/protocol_state/mock/protocol_kv_store.go
state/protocol/protocol_state/state/protocol_state.go
storage/approvals.go
storage/locks.go
storage/mock/my_execution_receipts.go
storage/mock/protocol_kv_store.go
storage/mock/result_approvals.go
storage/operation/approvals.go
storage/operation/writes.go
storage/protocol_kv_store.go
storage/receipts.go
storage/store/approvals.go
storage/store/approvals_test.go
storage/store/my_receipts.go
storage/store/my_receipts_test.go
storage/store/protocol_kv_store.go
storage/store/protocol_kv_store_test.go

This PR replace the storage locking with lockctx manager in the following modules:
- approvals
- my own receipts
- protocol kv store

[Storage] Replace with lockctx Manager

---

cmd/access/node_builder/access_node_builder.go
cmd/bootstrap/cmd/key.go
cmd/execution_builder.go
cmd/execution_config.go
cmd/observer/node_builder/observer_builder.go
cmd/util/cmd/compare-cadence-vm/cmd.go
cmd/util/cmd/debug-script/cmd.go
cmd/util/cmd/debug-tx/cmd.go
integration/tests/access/cohort3/execution_state_sync_test.go
integration/tests/access/cohort3/pebble_execution_state_sync_test.go
module/executiondatasync/storage/datastore_factory.go
utils/debug/remoteClient.go
utils/debug/remoteView.go

Merge `feature/v0.42-cadence-vm` and `master` into `feature/cadence-vm`

[Cadence VM] Sync feature branch
